new icon: Vuetify (original, line, plane)
devicons/devicon pull request #1033
Opened 2022-02-01 08:39 UTC by vikash2806

# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date
https://vuetifyjs.com/en/

2022-02-01 13:58 UTC, Panquesito7 requested changes
Hey there! Thanks for submitting a PR! 😄 Please revert the changes in the `package-lock.json`. Let us know if you need any help. Thanks. :)

2022-02-01 13:58 UTC, Panquesito7 commented on devicon.min.css
> +﻿@font-face{font-family:"devicon";src:url("fonts/devicon.eot?rgb6be");src:url("fonts/devicon.eot?rgb6be#iefix") format("embedded-opentype"),url("fonts/devicon.ttf?rgb6be") format("truetype"),url("fon
Please add the endline back. Without this endline, there can be issues with some IDEs and configurations.

2022-02-01 13:58 UTC, Panquesito7 commented on icons/vuetify/vuetify-line.svg
> +</svg>
Missing an endline.
```suggestion
</svg>

```

2022-02-01 13:58 UTC, Panquesito7 commented on icons/vuetify/vuetify-original.svg
> +</svg>
Missing an endline.
```suggestion
</svg>

```

2022-02-01 13:58 UTC, Panquesito7 commented on icons/vuetify/vuetify-plain.svg
> +</svg>
Missing an endline.
```suggestion
</svg>

```

2022-02-01 13:58 UTC, Panquesito7 commented on devicon.json
> +
```suggestion
```

2022-02-01 14:28 UTC, Panquesito7 requested changes
Could you please add the changes back in the `devicon.json` file? Thanks.

2022-02-02 05:29 UTC, Panquesito7 approved these changes
LGTM 🚀 Thank you for your contribution! 😄👍

2022-02-02 06:11 UTC, Thomas-Boi approved these changes
Great job @vikash2806! Just fyi, we will have a release within this month so you'll see your icon soon.

2022-02-02 06:11 UTC, merged

2022-02-02 06:31 UTC, vikash2806 commented
> Great job @vikash2806! Just fyi, we will have a release within this month so you'll see your icon soon.

Thank you , That's awesome. I'am looking forward to contribute more to Devicon.