update icon: bitbucket
devicons/devicon pull request #1044
Opened 2022-02-14 05:45 UTC by jusuchin85

# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date
https://atlassian.design/resources/logo-library/

2022-02-14 15:15 UTC, Panquesito7 commented
@Thomas-Boi, any idea why it looks like that? 👀 Thanks.

2022-03-13 23:18 UTC, jusuchin85 commented
@Thomas-Boi @Panquesito7 - updated PR with new commits. Hopefully, this will fix the icon text appropriately. 😃

2022-03-14 04:24 UTC, Thomas-Boi requested changes
Just need to change the viewBox. Everything else looks good to me.

2022-03-14 04:24 UTC, Thomas-Boi commented on icons/bitbucket/bitbucket-original-wordmark.svg
> +   viewBox="0 0 32 32"
```suggestion
   viewBox="0 0 128 128"
```

2022-03-14 04:24 UTC, Thomas-Boi commented on icons/bitbucket/bitbucket-original.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
```suggestion
<svg viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg">
```

2022-03-14 04:32 UTC, jusuchin85 commented on icons/bitbucket/bitbucket-original.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Updated!

2022-03-14 04:32 UTC, jusuchin85 commented on icons/bitbucket/bitbucket-original-wordmark.svg
> +   viewBox="0 0 32 32"
Updated!

2022-03-14 04:43 UTC, Thomas-Boi commented
@jusuchin85 everything looks good to me. Thank you very much for the PR. I'll leave this PR open temporary to test a script upgrade. Once that's tested and no other errors show up, I'll merge the PR 👍.

@Panquesito7 please review and merge [this PR](https://github.com/devicons/devicon/pull/1060) first 😄. Forgot to do something so this PR will fix it.

2022-03-14 04:45 UTC, jusuchin85 commented
Thanks @Thomas-Boi ! 😄

2022-03-14 17:33 UTC, Thomas-Boi requested changes
Hi @jusuchin85,

I'm sorry but I made a mistake. When resizing an SVG, you'd have to use a resizer, not just changing the viewBox.

For each of the icon, please change your viewBox back to `0 0 32 32` and resize it using this [website](https://www.iloveimg.com/resize-image/resize-svg#resize-options,pixels). Thank you for your patience and I'm sorry for the inconvenience.

2022-03-14 23:10 UTC, jusuchin85 commented
Icons resized accordingly using [iloveimg](https://www.iloveimg.com/resize-image/resize-svg#resize-options,pixels). Thanks for pointing this out, @Thomas-Boi !

2022-03-15 17:03 UTC, Thomas-Boi submitted a review, later dismissed
Just need to change the values here. You can just press the Commit Suggestion button for quick fixes like this. No need to open your editor, change the files etc.

2022-03-15 17:03 UTC, Thomas-Boi commented on icons/bitbucket/bitbucket-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128px" height="px" viewBox="0 0 128 128" version="1.1">
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128px" height="128px" viewBox="0 0 128 128" version="1.1">
```

2022-03-15 17:12 UTC, Thomas-Boi commented on icons/bitbucket/bitbucket-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128px" height="px" viewBox="0 0 128 128" version="1.1">
No worries Pan. The `height` attr will be removed by our SVG optimizer later.

2022-03-15 17:18 UTC, Thomas-Boi approved these changes
Looks good now! Thanks for your work and patience @jusuchin85

2022-03-15 17:18 UTC, merged

2022-03-15 21:02 UTC, jusuchin85 commented
No worries! Happy to help!