new icon: k3os (original, original-wordmark)
devicons/devicon pull request #1121
Opened 2022-03-29 20:44 UTC by thehedgefrog

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.
[k3os website](https://k3os.io/)

2022-03-30 02:13 UTC, Panquesito7 requested changes

2022-03-30 02:13 UTC, Panquesito7 commented on devicon.json
> +            "operating system",
```suggestion
            "operating-system",
```

2022-04-08 07:58 UTC, amacado approved these changes
🥳

2022-04-08 07:58 UTC, amacado commented
@Panquesito7 merge is blocked because of your change request :)
![image](https://user-images.githubusercontent.com/8781699/162391840-9d6a00c3-bb94-43af-9fe4-2b5e8b87db14.png)

2022-04-08 15:48 UTC, merged