New icon: YAML
devicons/devicon pull request #1142
Opened 2022-04-16 13:52 UTC by daczarne

### Adding a New Icon? 
- Add `?quick_pull=1&template=new_icon.md` to the end of your current URL and press `Enter`

### Adding a New Feature or fixing a bug? 
- Add `?quick_pull=1&template=new_feature.md` to the end of your current URL and press `Enter`.

2022-04-17 21:36 UTC, amacado requested changes
hi! :) Thank you for picking up `yaml`. While looking through the files I noticed some things you might want to apply/fix before this pr is ready:

- You introduced many new whitespaces in the `devicon.json`, while this is probably auto-added by a style in your idea: Please remove the whitespaces to follow our previous style
- As our bot noticed there's also no `font` definition in the `devicon.json` for `yaml` and "SVG" must be be written lowercase :)
- The icon itself looks non-centered. It seems like there is some space bellow but non above.
- Also it looks like there is a small fine square around the logo (which is non intended). This might be a error in the github preview as well

You might take an additional look at https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons and/or https://github.com/devicons/devicon/wiki/Example-of-Submitting-Icons-to-the-Repository


![image](https://user-images.githubusercontent.com/8781699/163732936-d9dbbac4-afe8-4872-a902-f7a0583b313a.png)

greetings and happy easter! 🐰

2022-04-17 22:05 UTC, daczarne commented
> * You introduced many new whitespaces in the `devicon.json`, while this is probably auto-added by a style in your idea: Please remove the whitespaces to follow our previous style

Yes, looks like the VSCode JSON formatter linted the file. Can you tell me which lintter are you guys using?

> * As our bot noticed there's also no `font` definition in the `devicon.json` for `yaml` and "SVG" must be be written lowercase :)

I think I now understood what the `font` key there is for. I'll add it.

> * The icon itself looks non-centered. It seems like there is some space bellow but non above.

I understand. But to my (extremely limited) knowledge of SVG that is a consequence of using `viewBox="0 0 128 128"`. I should change the `x` and `y` coordinates in order to center it. Could you point to another way of doing it, @amacado?

> * Also it looks like there is a small fine square around the logo (which is non intended). This might be a error in the github preview as well

I don't see that square thb. Could you point to it in the SVG code, please?

2022-04-19 14:51 UTC, Panquesito7 approved these changes

2022-04-19 20:33 UTC, amacado requested changes
I'm not an expert in svg either. All I can see is that the icon is not centered and should either cover the whole space or be centered. Currently there's space at the bottom. You can see that clearly in the icon preview:

![image](https://user-images.githubusercontent.com/8781699/164090844-72a94ddc-2ce2-42a7-988b-52477f30a85a.png)

2022-04-19 22:16 UTC, closed without merging