new icon: streamlit (original, plain, original-wordmark, plain-wordmark)
devicons/devicon pull request #1207
Opened 2022-06-07 17:26 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1202**

## Link to prove your SVG is correct and up-to-date.

https://streamlit.io/brand

2022-06-08 17:50 UTC, Panquesito7 submitted a review, later dismissed
LGTM 🚀 Thank you for your contribution! 😄👍

2022-06-11 13:23 UTC, amacado requested changes
Hey! We just added a new property in `devicon.json` called `altnames`. Would you mind adding this (even empty) to your contribution?
https://github.com/devicons/devicon/wiki/Updating-the-%60devicon.json%60

2022-06-11 15:38 UTC, canaleal commented
Okay, sounds good. I'll add altnames.

2022-06-12 00:36 UTC, Panquesito7 approved these changes

2022-06-12 11:48 UTC, amacado approved these changes

2022-06-12 11:48 UTC, merged