new icon: hibernate (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1227
Opened 2022-06-23 20:33 UTC by kilian-paquier

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://hibernate.org/

2022-07-14 02:18 UTC, Snailedlt approved these changes
LGTM!

2022-07-14 02:19 UTC, Snailedlt requested changes
Nvm, this PR has merge conflicts which need to be solved before merging

2022-07-17 14:49 UTC, Snailedlt reviewed
As far as I can tell this is a brand, and not a technology. So it doesn't meet the requirements for devicons
![Screenshot_20220717_164630](https://user-images.githubusercontent.com/43886029/179403856-ebee1dc9-e046-421d-a161-2b035e762f2a.jpg)

2022-07-17 15:05 UTC, kilian-paquier commented
https://www.jmdoudoux.fr/java/dej/chap-hibernate.htm
https://www.tutorialspoint.com/hibernate/orm_overview.htm
https://en.wikipedia.org/wiki/Hibernate_(framework)

The only difference between nhibernate and hibernate is the target language.

2022-07-17 21:54 UTC, Snailedlt commented
@kilian-paquier 
The wikipedia link you sent calls it Hibernate ORM.

Okey, so hibernate is the company/organization name, and hibernate ORM is the product name. But then the product is also called hibernate (quite confusing if you ask me).

So then, shouldn't the name be `hibernateorm`? We can have `hibernate` as an alt name too

2022-07-18 06:17 UTC, kilian-paquier commented
Hibernate is a framework, it seems to be owned by Red Hat, but it's open source. Hibernate provides functionalities/libraries/tools, such as the hibernate ORM, validator, etc.

All the functionalities come with the same logo.

Here's the GitHub link of hibernate : https://github.com/hibernate

2022-07-18 11:53 UTC, Snailedlt commented
Yeah, looking at their twitter account it says something like "...hibernate is a suite of open-source projects..."

@Panquesito7 Looks like this is a suite of products (not a single one), do you think it qualifies for devicons?

2022-07-18 15:48 UTC, Snailedlt approved these changes
Approved by me, but will wait for other maintainers to see if they think it's an icon that should be accepted or not.

@devicons/maintainer Please take a look at the comments on this PR

2022-08-06 00:26 UTC, Snailedlt requested changes

2022-08-06 00:26 UTC, Snailedlt commented on devicon.json
> +        "name": "hibernate",
The object needs to be moved so it's in alphabetical order in relation to the other icons

2022-08-06 11:04 UTC, Snailedlt submitted a review, later dismissed
Thanks for your contribution! :bow:

2022-08-16 16:30 UTC, Panquesito7 commented on devicon.json
> +            "framework"
Isn't this Java related, too?
```suggestion
            "framework",
            "java"
```


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

2022-08-16 16:50 UTC, Panquesito7 approved these changes
Awesome! Thanks for contributing! 🚀 


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-21 08:10 UTC, Snailedlt approved these changes

2022-08-21 08:10 UTC, merged