new icon: envoy (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1228
Opened 2022-06-23 20:52 UTC by kilian-paquier

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://www.envoyproxy.io/
https://www.envoyproxy.io/docs/envoy/latest/start/start

2022-06-24 02:56 UTC, Panquesito7 approved these changes
Hey there! Could you please resolve the merge conflicts?
Let us know if you need any help with this! 🙂


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

2022-06-24 05:58 UTC, kilian-paquier commented
Rebase done 🙂

2022-07-28 19:50 UTC, Snailedlt requested changes
Imo the icon should be renamed to envoy, since the website and logo calls it that. Please tell me if I'm wrong though.

Other than that, there's just one comment on a tag.

**PS:** When renaming the icon, remember to rename the files, folders and PR title too

2022-07-28 19:50 UTC, Snailedlt commented on devicon.json
> +        ],
imo these should switch places. The website calls it envoy, and the logo says envoy, so I would think the icon name should be envoy too
```suggestion
        "name": "envoy",
        "altnames": [
            "envoyproxy"
        ],
```

2022-07-28 19:50 UTC, Snailedlt commented on devicon.json
> +    {
Remember to move this so it fits alphabetically with the rest of the icons

2022-07-28 19:50 UTC, Snailedlt commented on devicon.json
> +            "middle proxy",
Never heard of middle proxy before. Did you mean `proxy`?
```suggestion
            "proxy",
```

2022-07-28 21:31 UTC, Snailedlt commented
@Panquesito7 one of the checks is failing because the PR title was changed after the PR was made. I've re-ran the job, but it didn't work. Any ideas on how to fix it?
![image](https://user-images.githubusercontent.com/43886029/181641163-f55ad95c-687e-45c7-bdd9-e359aad5a178.png)

![image](https://user-images.githubusercontent.com/43886029/181641217-ae1e743d-51fb-4167-a143-32e1edf84b65.png)

2022-07-29 06:31 UTC, kilian-paquier commented
> @Panquesito7 one of the checks is failing because the PR title was changed after the PR was made. I've re-ran the job, but it didn't work. Any ideas on how to fix it? ![image](https://user-images.githubusercontent.com/43886029/181641163-f55ad95c-687e-45c7-bdd9-e359aad5a178.png)
> 
> ![image](https://user-images.githubusercontent.com/43886029/181641217-ae1e743d-51fb-4167-a143-32e1edf84b65.png)

The first commit needed to be renamed too

2022-07-29 08:10 UTC, Snailedlt approved these changes
LGTM! :heavy-checkmark:

2022-07-29 20:10 UTC, Panquesito7 approved these changes
Nice! Thank you. 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient, Maintainable

2022-07-29 20:10 UTC, merged