new icon: poetry (original, plain)
devicons/devicon pull request #1243
Opened 2022-06-28 20:12 UTC by kilian-paquier

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1222**

## Link to prove your SVG is correct and up-to-date.

https://python-poetry.org/

2022-06-28 20:15 UTC, kilian-paquier commented
Feel free to suggest another plain icon, I find this one ugly 😒

2022-07-02 19:58 UTC, Snailedlt requested changes

2022-07-02 20:08 UTC, kilian-paquier commented
@Snailedlt Accepted your suggestions 🙂

2022-07-02 22:31 UTC, Snailedlt submitted a review, later dismissed

2022-07-24 11:18 UTC, Snailedlt approved these changes
LGTM :heavy_check_mark:

2022-07-25 14:57 UTC, merged