new icon: vitejs (original, original wordmark)
devicons/devicon pull request #1252
Opened 2022-07-03 03:04 UTC by AcmeGamers

## Double check these details before you open a PR

- [ ✔ ] PR does not match another non-stale PR currently opened
- [ ✔ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ✔ ] PR's base is the `develop` branch.
- [ ✔ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ✔ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ✔ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**
This PR closes #1053

## Link to prove your SVG is correct and up-to-date.
https://vitejs.dev/

2022-07-03 10:28 UTC, kilian-paquier commented
Hello @AcmeGamers, I reviewed your PR https://github.com/devicons/devicon/pull/1253, can you follow the recommandations and standards for this PR too ?

2022-07-05 06:42 UTC, AcmeGamers commented
> Hello @AcmeGamers, I reviewed your PR #1253, can you follow the recommandations and standards for this PR too ?

Onto it :D, and really thanks for helping out with the previous ones

2022-07-25 22:00 UTC, Snailedlt requested changes
In addition to all the changes suggested below, you can also remove the `.eps` files.
A good start, but needs a bit of work before it's ready to be merged :)

Let us know if you need any more help

2022-07-25 22:00 UTC, Snailedlt commented on icons/vitejs/vite-original-wordmark.svg
> +	 viewBox="0 0 271.6 113.8" style="enable-background:new 0 0 271.6 113.8;" xml:space="preserve">
Make sure the viewbox is `0 0 128 128` as explained in the [SVG Standards](https://github.com/devicons/devicon/wiki/SVG-Standards)

2022-07-25 22:00 UTC, Snailedlt commented on icons/vitejs/vite-original.svg
> +	 viewBox="0 0 121.4 119.8" style="enable-background:new 0 0 121.4 119.8;" xml:space="preserve">
make sure the viewbox is `0 0 128 128` as explained in the [SVG Standards](https://github.com/devicons/devicon/wiki/SVG-Standards)

2022-07-25 22:00 UTC, Snailedlt commented on devicon.json
> +    "tags": ["react", "compiler", "esbuild"],
Those aren't really relevant for vite, so here's some other suggestions
```suggestion
    "tags": [
        "tooling",
        "buildtool",
        "bundler",
        "javascript",
        "js",
    ],
```

2022-07-25 22:00 UTC, Snailedlt commented on devicon.json
> +        "base": "original"
You need to also add an alias here.
```suggestion
        "base": "original"
        "alias": "plain"
```

I suggest you take a look at [Example-of-Submitting-Icons-to-the-Repository](https://github.com/devicons/devicon/wiki/Example-of-Submitting-Icons-to-the-Repository) and [Updating the `devicon.json`](https://github.com/devicons/devicon/wiki/Updating-the-%60devicon.json%60) to see why it should be like this.

2022-07-25 22:00 UTC, Snailedlt commented on package.json
> +  "version": "2.15.1",
You should reverse all the changes in `package.json` since they are not relevant for icon requests

2022-07-25 22:00 UTC, Snailedlt commented on package-lock.json
> +  "version": "2.15.1",
You should reverse all the changes in `package-lock.json` since they are not relevant for icon requests

2022-07-25 22:08 UTC, Snailedlt commented on devicon.json
> +      "font": ["original"]
```suggestion
      "font": [
          "original"
      ]
```

2022-07-25 22:11 UTC, Snailedlt commented on devicon.json
> +    "name": "vitejs",
```suggestion
    "name": "vitejs",
    "altnames": []
```

2022-07-28 20:21 UTC, Snailedlt commented
@AcmeGamers Please read and implement the changes listed above when you have time

2022-08-06 11:47 UTC, Snailedlt commented
Let us know if you need any help with the PR :)

2022-10-26 09:04 UTC, Snailedlt commented
Stale and replaced by #1473

2022-10-26 09:04 UTC, closed without merging