new icon: eclipse (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1258
Opened 2022-07-03 14:46 UTC by kilian-paquier

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1215**

## Link to prove your SVG is correct and up-to-date.

https://www.eclipse.org/ide/

2022-07-06 12:20 UTC, Snailedlt requested changes
Add alias and tags then we're good :)

Logos look fine

2022-07-06 12:20 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": [
            "Eclipse IDE"
        ],
```

2022-07-06 15:35 UTC, kilian-paquier commented
> Add alias and tags then we're good :)
> 
> Logos look fine

Hello @Snailedlt,

An alias between which version and which other version ? Because I made SVG's for the plain and SVG's for the original. Maybe the line then ?

2022-07-06 16:03 UTC, Snailedlt commented
Ahh, no I meant altname, not alias. Sorry my bad :)

2022-07-06 16:39 UTC, kilian-paquier commented
@Snailedlt Suggestions applied

2022-07-07 22:09 UTC, Snailedlt approved these changes

2022-07-09 22:21 UTC, Snailedlt commented
@Panquesito7 Looks good to me

2022-07-14 11:42 UTC, Snailedlt approved these changes
LGTM!

2022-07-14 11:42 UTC, merged