new icon: azure-devops (original, plain)
devicons/devicon pull request #1289
Opened 2022-07-24 09:17 UTC by kilian-paquier

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1281**

## Link to prove your SVG is correct and up-to-date.

See #1281.

2022-07-25 21:02 UTC, Snailedlt requested changes
The folder, icons and PR title should be renamed to `azuredevops`. See the [Naming-Conventions](https://github.com/devicons/devicon/wiki/Naming-Conventions) wiki for more info

2022-07-26 21:42 UTC, Snailedlt requested changes
There's also some conflicts that need to be solved before we can merge this

2022-07-26 21:42 UTC, Snailedlt commented on devicon.json
> +            "devops"
```suggestion
            "devops",
            "cloud",
            "version control",
            "vcs"
```

2022-07-27 20:36 UTC, Snailedlt approved these changes
LGTM! :heavy_check_mark:

2022-07-27 20:37 UTC, merged

2022-07-28 11:10 UTC, BenSouchet commented
@kilian-paquier
Please, make sure, when you add a new entry in the `devicon.json` file that you add it at the correct position in the file.
Elements order need to reflect the `icons/` folder, in this PR you added `azuredevops` between `clojurescript` and `cloudflare`.

It hard to keep track of everything and this can lead to mistake when new elements are not added at the correct alphabetic position.

I think this isn't the first time you added a new element to `devicon.json` at "random" possition, I have seen `lumen` placed between `ceylon` and `chrome`.

Because of these misplacements I had an had time fixing merge conflicts in my own PRs.

So if you can ensure for your future contributions that you place new entries at the right alphabetic place in the `devicon.json` file, thanks.

@Snailedlt Maybe It will be another element to add to the checklist when reviewers look at PRs, and maybe a good element to add to documentation for new contributors.

Have a good day guys ☀️

2022-07-28 12:08 UTC, Snailedlt commented
@BenSouchet Ohh yeah, didn't notice that. My bad for merging.

On the note of adding this to the reviewing process, I agree. I think we can even do one better, and automatically sort the devicon.js file with some type of linter. Should be possible to do before merge, so we avoid merge conflicts in the future.

I'll make an issue on this once I get back home, so we can discuss it further :)

Thanks for letting me know

2022-07-28 12:17 UTC, BenSouchet commented
@Snailedlt I already created this Feature Request #1327 , so everyone can comment / add elements or feedback on the idea.

And yes, automatically sort the JSON file would be great since some entries are already misplaced.
So we could iterate on a proper ordered file for future contributions, and avoid continuing to misplace entries.