new icon: datagrip (original, plain)
devicons/devicon pull request #1292
Opened 2022-07-24 10:02 UTC by kilian-paquier

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR contributes to #1125**

## Link to prove your SVG is correct and up-to-date.

https://www.jetbrains.com/fr-fr/datagrip/

2022-07-25 21:10 UTC, Snailedlt requested changes
Suggested some more tags

2022-07-25 21:10 UTC, Snailedlt commented on devicon.json
> +            "ide"
```suggestion
            "ide",
            "sql",
            "database"
```

2022-07-28 20:47 UTC, Snailedlt requested changes

2022-07-28 20:47 UTC, Snailedlt commented on devicon.json
> +    {
The new icon needs to be in the correct alphabetical order compared to the other icons

2022-07-28 21:08 UTC, Snailedlt approved these changes
LGTM! ✔️ 

Perfection is not attainable, but if we chase perfection we can catch excellence.
\- [Vince Lombardi](https://www.brainyquote.com/authors/vince-lombardi-quotes)

2022-07-29 05:58 UTC, merged

2022-08-18 21:35 UTC, kilian-paquier commented
@Snailedlt Here too