new icon: moleculer (original, plain)
devicons/devicon pull request #1296
Opened 2022-07-24 17:36 UTC by kilian-paquier

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://moleculer.services/

2022-07-25 20:16 UTC, Snailedlt requested changes
Some small changes. I also noticed that they have a few more logos, I'll make an issue so we can discuss further there

2022-07-25 20:16 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": [
             "moleculerjs"
             "moleculer.js"
         ],
```

2022-07-25 20:16 UTC, Snailedlt commented on devicon.json
> +            "nodejs",
```suggestion
            "nodejs",
            "javascript",
            "js",
```

2022-07-25 20:34 UTC, kilian-paquier commented on devicon.json
> +             "moleculerjs"
```suggestion
             "moleculerjs",
```

2022-07-28 18:03 UTC, Snailedlt requested changes

2022-07-28 18:03 UTC, Snailedlt commented on devicon.json
> +        "name": "moleculer",
Please move this to the correct place so it's in alphabetical order. See [this relevant comment](https://github.com/devicons/devicon/pull/1289#issuecomment-1198001547) and [this issue](https://github.com/devicons/devicon/issues/1327) for more info

2022-07-28 20:41 UTC, kilian-paquier commented
@Snailedlt Done. I also updated all my PRs to replace the new object at the right place 🙂

2022-07-28 20:48 UTC, Snailedlt commented
> @Snailedlt Done. I also updated all my PRs to replace the new object at the right place 🙂

Great, you are so damn fast, lol!

2022-07-28 20:50 UTC, Snailedlt approved these changes
LGTM! ✔️ 
Thanks for your contribution! 🚀

2022-07-29 05:59 UTC, merged