update icon: webstorm (original, plain, plain-wordmark)
devicons/devicon pull request #1317
Opened 2022-07-26 20:23 UTC by kilian-paquier

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *update icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)

**This PR contributes to #1125**

## Link to prove your SVG is correct and up-to-date.

https://www.jetbrains.com/fr-fr/webstorm/

2022-08-03 01:29 UTC, Panquesito7 submitted a review, later dismissed
Thanks for contributing! 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient

2022-08-03 05:54 UTC, Snailedlt commented on icons/webstorm/webstorm-plain-wordmark.svg
> +  <path d="M55.75 50.965v14.73h3.063v-1.422a4.158 4.158 0 0 0 3.37 1.614c2.559 0 4.919-1.976 4.919-5.586v-.04c0-3.61-2.398-5.585-4.918-5.585-1.593 0-2.626.746-3.371 1.754v-5.465H55.75zm16.984.406c-2.
Missing fill?

2022-08-06 09:53 UTC, kilian-paquier commented on icons/webstorm/webstorm-plain-wordmark.svg
> +  <path d="M55.75 50.965v14.73h3.063v-1.422a4.158 4.158 0 0 0 3.37 1.614c2.559 0 4.919-1.976 4.919-5.586v-.04c0-3.61-2.398-5.585-4.918-5.585-1.593 0-2.626.746-3.371 1.754v-5.465H55.75zm16.984.406c-2.
Related to the #1291 thread

2022-08-06 11:53 UTC, Snailedlt requested changes
Marking as request changes until #1291 is solved

2022-08-19 08:50 UTC, Snailedlt approved these changes
LGTM! :heavy_check_mark:

2022-08-19 08:51 UTC, merged