Feature/sort devicon json and add sort check
devicons/devicon pull request #1405
Opened 2022-10-02 00:18 UTC by Snailedlt

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

1. Sort and re-indent `devicon.json`
2. Add check to `check_icon_pr.py` to see if devicon.json is still sorted

**This PR closes NONE**

This PR closes #1337
## Notes

Please check both if the functionality looks sound, and if the error messages can be improved

2022-11-19 13:45 UTC, Snailedlt commented
The sorting of devicon.json in this PR needs to be redone because devicon.json has been updated since it was last sorted

2022-12-07 11:47 UTC, lunatic-fox commented
Code used to sort `devicon.json`
```python
import json
path = 'devicon.json'

with open(path) as file:
  file: list[dict] = json.load(file)
  file.sort(key=lambda e: e['name'])
  file = json.dumps(file, indent=4) + '\n'

with open(path, 'w') as output_file:
  output_file.write(file)
```

2022-12-07 14:25 UTC, Snailedlt commented
@lunatic-fox did you check if the check-icon script deemed it as sorted?

2022-12-07 14:27 UTC, Snailedlt commented on .github/scripts/check_icon_pr.py
> +            err_msg += devicon_err_msg
Whoopsie. This should probably use .append like the others :)

2022-12-07 14:45 UTC, lunatic-fox commented
> @lunatic-fox did you check if the check-icon script deemed it as sorted?

Not yet, I'll do later some tests in a private repo.

2022-12-07 15:39 UTC, Snailedlt commented on .github/scripts/check_icon_pr.py
>          if devicon_err_msg != "":
```suggestion
        if devicon_err_msg != []:
```

2022-12-07 15:39 UTC, Snailedlt commented on .github/scripts/check_icon_pr.py
> +            err_msg += devicon_err_msg
nvm, .append is for strings only, so we can use `+=` or `.extend`, of which I prefer `.extend`
```suggestion
            err_ms.extend(devicon_err_msg)
```

2022-12-11 14:28 UTC, lunatic-fox requested changes
It'll work properly after fixing the reference error.
### Preview
![preview](https://user-images.githubusercontent.com/76992016/206909468-c76c8840-92c1-47d2-b686-dbc7c9ca1216.png)

2022-12-11 14:28 UTC, lunatic-fox commented on .github/scripts/check_icon_pr.py
> +            err_ms.extend(devicon_err_msg)
Fix a reference error.
```suggestion
            err_msg.extend(devicon_err_msg)
```

2022-12-11 14:28 UTC, lunatic-fox commented on .github/scripts/check_icon_pr.py
> +            devicon_err_msg.append("devicon.json is not sorted correctly. Please make sure that your icon is added in the `devicon.json` file at the correct alphabetic position as seen [here](https:/
Restructure the error message for better visualization.
```suggestion
            devicon_err_msg.append(f"devicon.json is not sorted correctly.\nPlease make sure that your icon is added in the `devicon.json` file at the correct alphabetic position\nas seen here: https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60")
```

### Preview
![preview](https://user-images.githubusercontent.com/76992016/206909391-9670a57d-8a7d-431d-960a-69bf6a7314c9.png)

2022-12-11 19:30 UTC, lunatic-fox approved these changes
- `devicon.json` is up-to-date and sorted with its latest version: https://github.com/devicons/devicon/commit/eb35d73a014618970ee84759b56883bfc33182b0
- Conflicts are resolved.

Looking good! ✔
Thank you for this great feature! 🚀

2022-12-11 22:18 UTC, merged