new icon: livewire (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1415
Opened 2022-10-02 19:58 UTC by Panquesito7

## Double check these details before you open a PR

Special thanks to @Snailedlt for their tremendous help! 🚀

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #855**

## Link to prove your SVG is correct and up-to-date.

https://laravel-livewire.com/

2022-10-02 20:13 UTC, Snailedlt approved these changes
LGTM ✔️ 
Thank you for your continued contributions,! 💯 
Looking forward to the next one 🚀

2022-10-02 22:02 UTC, Snailedlt requested changes
@Panquesito7 like we discussed on Discord, it seems like icomoon isn't rendering the icon fonts correctly with the masks. Notice in the images below how the screenshots from icomoon don't have the eye cutout, while the SVG versions uploaded here do.

## Comparison

### How they should look
![image](https://user-images.githubusercontent.com/43886029/193478218-c907cda4-d388-4be9-87c5-2ad396f2385d.png)

## How they look on icomoon

![image](https://user-images.githubusercontent.com/43886029/193478178-03f8dc94-c1a0-4137-8f1e-5aac828c648b.png)

![image](https://user-images.githubusercontent.com/43886029/193478235-5557d917-9fc4-479f-b70d-6a3fc60f9979.png)

2022-10-03 04:53 UTC, Panquesito7 commented
What should we do about it, then? 🤔

2022-10-03 06:34 UTC, Snailedlt commented
> What should we do about it, then? 🤔
> 

Either remove the plain icons or find another way to clip out the shapes.

I suggest trying to do it with inkscape like so: https://graphicdesign.stackexchange.com/a/42590

2022-10-05 21:11 UTC, Panquesito7 commented
Nice! It finally looks good. 🙂

2022-10-06 08:48 UTC, Snailedlt approved these changes
Looks good! ✔️ 
Kinda sad you force pushed so I can't see the diff easily, but as long as it works I guess it's okey :)

2022-10-07 23:24 UTC, merged