new icon: llvm (original, plain)
devicons/devicon pull request #1428
Opened 2022-10-04 12:56 UTC by weh

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

closes #688

## Link to prove your SVG is correct and up-to-date.

https://llvm.org/Logo.html

2022-10-06 03:30 UTC, Panquesito7 requested changes

2022-10-06 03:30 UTC, Panquesito7 commented on devicon.json
> +        "color": "#000000",
```suggestion
        "color": "#5A90B6",
```

2022-10-06 03:30 UTC, Panquesito7 commented on devicon.json
> +            "framework"
```suggestion
            "framework",
            "c++",
            "open-source"
```

2022-10-06 03:30 UTC, Panquesito7 commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": ["Low Level Virtual Machine"],
```

2022-10-06 08:44 UTC, Snailedlt commented on icons/llvm/llvm-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M82.039 103.988c-.402-.086-1.238-.164-1.859-.168-1.215-.012-3.527-.727-5.363-1.664-2.664-1.352-5.715-4.
Also noticed there's a bit of a white outline around the whole SVG
![image](https://user-images.githubusercontent.com/43886029/194265075-3a5789b6-e609-4422-9430-fdad8fbf0564.png)
![image](https://user-images.githubusercontent.com/43886029/194265630-1cda627f-6c6f-4613-a600-a46c609e0e82.png)

2022-10-06 11:27 UTC, weh commented on icons/llvm/llvm-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M82.039 103.988c-.402-.086-1.238-.164-1.859-.168-1.215-.012-3.527-.727-5.363-1.664-2.664-1.352-5.715-4.
yeah, i saw that while converting it. My first idea was, that it is not so important, when the svg is used as icon, in relative small sizes. But you may scale it up as well, an then it gets more noticeable. I can try converting it again with other params, and maybe try to improve the quality.

2022-10-06 13:12 UTC, Snailedlt commented on icons/llvm/llvm-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M82.039 103.988c-.402-.086-1.238-.164-1.859-.168-1.215-.012-3.527-.727-5.363-1.664-2.664-1.352-5.715-4.
Yeah exactly. Assuming people use it in small sizes it's okey, but if they scale it up not so much.

Dw about the colors when converting, those can be changed afterwards by editing the colorcodes, I'm more interested in removing that white outline, and also adding in those black outlines

2022-10-07 07:45 UTC, weh commented
i think this version is better now

![image](https://user-images.githubusercontent.com/482423/194500049-72f8766e-90e0-44bc-adfd-eea2f5798889.png)

2022-10-07 09:58 UTC, Snailedlt requested changes
This looks much better already!
Great work! 💯 

Now there are only two very small things left:
1. The black outlines look like they are slightly thicker than the ones on the original .png logo. The difference is so small so it's barely noticeable. Imo this doesn't need fixing, but it's there if you (or anyone else) wants to fix it.
2. The colors are slightly different from what they should be, I made a suggestion with the correct color values. The diff doesn't look right in the GitHub UI, but if you diff it locally you'll see that only the color values changed :)

In summary:
Great work, almost there! Just implement the suggestion and everything else should be good enough to merge :)

2022-10-07 09:58 UTC, Snailedlt commented on icons/llvm/llvm-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M82.625 103.785c-1.48-.203-3.551-.723-5.164-1.301a22.87 22.87 0 0 1-1.992-.875c-3.031-1.496-4.984-3.203
Changed the color codes so they are the same as those in the .png.

#### New version
<img title="new version (new color codes)"  alt="new version (new color codes)" src="https://user-images.githubusercontent.com/43886029/194524137-876c8d7c-a236-485b-a8aa-e9b7c8eb539d.svg" width="500px"></img> 

#### Original PNG Version
<img  title="original PNG version"  alt="original PNG version" src="https://llvm.org/img/LLVMWyvernSmall.png" width="500px"></img> 

#### Old Version
<img  title="old version"  alt="old version" src="https://user-images.githubusercontent.com/43886029/194524577-2addf9fe-aac0-43db-9ad7-45b4bbb76977.svg" width="500px"></img>


```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M82.625 103.785c-1.48-.203-3.551-.723-5.164-1.301a22.87 22.87 0 0 1-1.992-.875c-3.031-1.496-4.984-3.203-8.324-7.281-.609-.746-1.066-1.254-1.141-1.266s-.531.18-1.027.418c-1.711.824-5.727 2.488-7.871 3.262-6.113 2.203-10.492 3.074-14.324 2.848-2.918-.172-5.246-.676-6.93-1.5-1.246-.609-2-1.258-2.605-2.242-.375-.609-.684-1.402-.582-1.5.074-.074.168-.016 1.047.668.754.59 1.383.973 1.969 1.207.91.363 2.332.688 3.906.887.883.109 3.887.109 4.637-.004 2.254-.336 6.117-1.441 8.777-2.512 1.09-.441 4.414-2.039 7.375-3.547 2.387-1.219 3.113-1.617 3.383-1.859.191-.168.191-.176.117-.457-.043-.16-.367-1.023-.727-1.922-.691-1.746-1.523-4.035-2.324-6.391-1.023-3.008-1.309-3.734-1.465-3.734-.172 0-.734.738-2.133 2.797-1.051 1.543-1.227 1.746-1.543 1.746-.324 0-.758-.184-1.355-.574-.859-.559-1.625-1.234-3.234-2.859-.973-.98-1.578-1.547-1.656-1.547-.359 0-.582.699-.625 1.945-.027.836.008 1.199.145 1.563.023.063.008.102-.039.102-.141 0-.852-.5-1.109-.777-.324-.352-.73-1.215-.91-1.934-.078-.316-.16-.609-.184-.645-.086-.141-.281-.055-.551.246-.52.574-.852 1.66-.852 2.766 0 .688-.047.73-.41.367-.508-.508-.965-1.457-1.09-2.27-.191-1.215-.27-1.309-.687-.855-.387.418-.789 1.285-.902 1.949-.051.309-.117.586-.148.617-.062.066-.402-.391-.594-.801-.5-1.074-.445-2.586.141-3.727.496-.973.57-1.148.699-1.625.32-1.18.895-1.785 2.117-2.23.293-.105.547-.129 1.645-.152 1.992-.047 3.23.109 4.012.508.363.184 1.055.898 2.371 2.453 1.402 1.66 1.738 2.012 1.898 1.988.152-.02.621-.777.914-1.48.168-.395.207-.59.25-1.246.031-.426.098-.93.152-1.117.266-.914.906-1.676 1.914-2.27l.602-.355-.027-.227a18.65 18.65 0 0 1-.066-.75c-.051-.75-.141-1.109-.309-1.242-.109-.086-.348-.133-.973-.187a19.47 19.47 0 0 1-3.414-.676c-1.93-.582-5.559-2.359-10.211-5-3.344-1.898-4.945-2.59-6.902-2.984-1.305-.266-2.648-.328-3.559-.164-.922.164-2.328.836-2.895 1.383-.359.348-.445.539-.57 1.266-.109.652-.203.813-.203.359 0-.145-.027-.445-.062-.668-.055-.363-.09-.43-.324-.645-.402-.367-1.285-.766-1.941-.879-.719-.125-2.703-.129-3.273-.008-1.656.355-4.082 2.102-5.82 4.195-.582.695-.641.793-.68 1.09-.117.902-.242 1.598-.293 1.598-.027 0-.055-.387-.055-.859 0-1 .055-.902-.809-1.461-2.102-1.355-4.074-1.59-5.789-.691-2.684 1.406-4.75 5.344-6.223 11.855-.633 2.805-.652 4.008-.09 6.465l.246 1.047c.016.043.004.078-.02.078-.105 0-.754-1.965-1.293-3.922C1.66 74.691.719 69.727.348 66.164c-.25-2.371-.285-7.445-.07-9.336.352-3.094.676-4.531 1.719-7.672 1.184-3.574 2.297-5.937 4.027-8.574 2.074-3.164 4.801-6.199 7.898-8.789a61.3 61.3 0 0 1 1.988-1.547c.723-.543 1.348-1.031 1.387-1.082s.07-.156.059-.234c-.02-.125-.07-.148-.426-.195-.422-.051-3.945-.008-4.996.063-.402.027-.605.02-.605-.023 0-.082.145-.109 1.398-.266 1.656-.203 2.512-.254 4.918-.293 3.125-.047 5.746.094 7.875.426 1.328.207 1.742.215 2.148.051.281-.113.402-.129.699-.094.387.051 3.801.895 6.238 1.551 1.813.484 2.707.688 2.836.637.219-.082.051-.543-.512-1.426-.648-1.016-1.199-1.652-2.941-3.418-.699-.711-1.25-1.312-1.223-1.34.059-.059 1.121.5 1.84.965 1.574 1.016 2.914 2.395 3.707 3.813.652 1.16.797 1.391 1.184 1.848.602.727.734 1.289.441 1.918-.145.309-.254.422-.895.906-.281.211-.371.34-.637.883-.777 1.609-2.16 6.383-3.047 10.512-.176.809-.316 1.52-.316 1.578s.113.234.258.395c.332.375.785 1.309.859 1.773.035.203.09.402.129.449s.215.113.391.152c.512.109 7.863 1.309 8.035 1.309.125 0 .195-.074.379-.398.121-.219.262-.434.309-.473s1.047-.191 2.223-.344c2.867-.371 5.738-.816 9.266-1.437 1.664-.297 1.988-.336 2.16-.277.16.059.234.055.402-.031.238-.121 3.094-2.977 4.594-4.594 1.215-1.312 1.625-1.84 2.043-2.645.625-1.211.848-2.105.805-3.273-.031-.937-.172-1.348-.609-1.785-.418-.422-.598-.461-2.082-.457-1.391.004-2.047.082-3.531.43-1.285.301-1.406.363-1.762.898-.344.527-.59.746-1.285 1.152-.812.477-1.316.883-2.473 1.977-1.277 1.211-1.875 1.715-2.227 1.867-.25.113-.266.113-.652-.008-.457-.145-.801-.336-.801-.453 0-.105.258-.344.996-.93 1.027-.816 1.875-1.746 2.336-2.57.34-.613.465-1.07.465-1.715 0-.52-.012-.574-.16-.723-.141-.141-.187-.152-.445-.117-.387.059-1.281.387-1.477.543-.215.168-.199.316.066.609.121.137.215.273.203.305s-.219.004-.457-.059c-.602-.16-1.09-.156-1.301.008-.09.07-.164.184-.164.246s.141.301.313.523.313.426.313.445c0 .086-.582-.039-1.035-.223-.715-.285-1.02-.242-1.02.141 0 .238.086.398.387.707.156.164.223.273.176.301-.09.059-.66-.113-1.34-.402-.309-.133-.754-.273-.988-.309s-.512-.113-.613-.164c-.32-.164-.711-.609-.93-1.059-.187-.387-.207-.48-.207-.977 0-.523.008-.559.168-.695.098-.086.32-.176.527-.215 1.461-.273 2.098-.543 2.723-1.145.227-.219.418-.461.445-.562s.008-.371-.039-.602c-.109-.582-.051-1.094.168-1.504.922-1.727 5.48-4.035 9.613-4.871.773-.156 1.609-.211 1.609-.105 0 .031-.227.203-.508.387-1.492.969-3.535 3.113-3.535 3.711 0 .137.035.223.102.25.219.082 2.469-.461 3.109-.754.18-.082.543-.359.84-.637.809-.762 1.371-1.105 2.328-1.414 1.219-.395 3.473-.633 3.297-.348-.02.031-.406.238-.859.453-1.352.645-2.098 1.113-2.098 1.32 0 .156.191.211 1.063.301 1.969.203 2 .203 2.891-.09.855-.277 1.469-.367 2.559-.367.816-.004 1.77.066 1.77.125 0 .051-.434.223-1.543.609-.879.309-1.023.398-1 .621.016.129.172.277.707.68a8.24 8.24 0 0 0 2.195 1.223c1.129.434 2.469 1.215 2.328 1.355-.039.043-.316.031-.832-.039a8.54 8.54 0 0 0-1.141-.086l-.375.02-.02.262c-.008.145.039.492.105.777s.141.66.164.828.055.395.074.496c.023.125.352.504 1.086 1.258.914.941 1.172 1.266 1.008 1.266-.023 0-.387-.109-.805-.246-.836-.273-.969-.293-1.078-.164-.082.102-.211.801-.32 1.762l-.078.695.344.578c.395.668.609 1.078.609 1.172 0 .117-.121.066-.547-.219-.461-.309-.539-.328-.625-.168-.082.148-1.094 3.766-1.32 4.711-.219.918-.227 1.066-.059 1.152.426.23 6.484 1.313 10.082 1.805l2.086.289c.832.113 1.098.227 1.164.504.027.109.129.258.223.332.152.125.219.133.73.102.566-.031 4.191-.594 4.961-.766.68-.152.777-.254 1.047-1.062.266-.797.379-1 .773-1.387.152-.152.281-.316.281-.363 0-.164-.93-4.187-1.305-5.645-.434-1.68-.93-3.375-1.359-4.637-.687-2.02-.871-2.332-1.805-3.102-.414-.34-.594-.68-.598-1.133-.008-.477.168-.883.578-1.336.195-.215.531-.711.754-1.117 1.188-2.141 2.359-3.422 4.195-4.578.742-.465 1.828-1.031 1.883-.977.02.02-.281.34-.668.707-.914.871-1.789 1.777-2.375 2.465-.953 1.113-1.805 2.465-1.773 2.816.027.344.211.316 3.293-.504 2.484-.66 5.074-1.301 5.664-1.402.426-.07.477-.066.762.059.383.172.797.172 1.832.012 2.117-.328 4.672-.5 7.488-.5 2.637 0 5.074.16 6.68.441.645.109.508.207-.234.16-1.207-.074-4.309-.121-4.855-.074-.395.031-.559.07-.586.137-.055.145.348.516 1.57 1.441 4.609 3.5 7.984 7.176 10.637 11.582 1.563 2.598 2.676 5.32 3.863 9.434.547 1.895.82 3.367 1.07 5.758.137 1.309.16 6.234.035 7.688-.359 4.141-.984 7.84-2.043 12.074-.684 2.734-1.691 5.914-1.703 5.375 0-.059.195-.961.438-2.008l.438-1.902-.223-1.262c-.547-3.086-1.375-6.18-2.254-8.418-1.215-3.082-3.094-5.434-4.902-6.137-.637-.246-1.184-.324-2.02-.289-.844.035-1.324.176-2.402.699-.828.402-1.418.777-1.559.992-.082.125-.113.359-.141 1-.016.465-.051.84-.078.84s-.066-.145-.09-.324c-.098-.777-.297-1.59-.449-1.852-.34-.582-2.469-2.629-3.512-3.375-.668-.477-2.113-1.195-2.664-1.32-.523-.121-2.855-.141-3.379-.031-.418.09-1.484.555-1.773.777s-.434.57-.484 1.191c-.023.285-.066.516-.098.516s-.07-.133-.094-.297c-.117-.863-.215-1.125-.535-1.477-.617-.676-1.613-1.191-2.789-1.441-.734-.156-2.539-.156-3.332 0-2. [...]

2022-10-07 13:46 UTC, Snailedlt approved these changes
Greeat work @weh! ✔️ The icons look stunning! ✨ 
I'm interested in knowing what tool(s) you used to convert the PNG into SVG, would you be willing to share your knowledge? 🧠

2022-10-07 14:53 UTC, weh commented
Sure @Snailedlt 

Basically my Workflow is using the Tools mentioned on the Wiki Page https://github.com/devicons/devicon/wiki/Recommended-resources-and-tools
- Inkscape
- Iloveimage
- vecta.io

1. Open PNG image in Inkscape
2. Use the "Trace Bitmap" function to convert the Image
![image](https://user-images.githubusercontent.com/482423/194578122-fa978f07-dfbf-46fc-986f-fb7e05ce706e.png)
3. Change the Image aspect ratio to be square (size does not matter)
4. Save image in Inkscape format (with all the "bloated" svg stuff)
5. Resize the Image to 128x128 with https://www.iloveimg.com/resize-image/resize-svg
6. Optimize image Size with https://vecta.io/nano
7. Re-add the viewBox="0 0 128 128" (that gets removed by Vecta)

You may need to test the results with Trace Bitmap and tweak the params. In this Case the tricky part was the White Background. It got removed, in every variant. So i Gimp to create a "white only" version of the Image and combined both Inkscape converted Images in my IDE (or any text Editor you want).

Inkscape writes pretty good editable svg xml files. Many times i do tweak colors and similar things in the text editor.

2022-10-07 14:59 UTC, Snailedlt commented
@weh neat! 
I didn't know that Inkscape was that good at converting bitmap images to vector images.

Would be nice to have that step by step guide in the wiki somewhere. Maybe a separate section for `How to convert PNG to SVG`, or alternatively `How to convert bitmap images (PNG, JPG,...) to vector images (SVG...)`.

Would you want to add that yourself, or should I do it?

2022-10-11 02:06 UTC, Panquesito7 approved these changes
Thanks! 🚀

2022-10-11 02:12 UTC, merged