new icon: qwik (original, plain, original-wordmark, plain-wordmark)
devicons/devicon pull request #1435
Opened 2022-10-08 20:09 UTC by AmreshSinha

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1409**

## Link to prove your SVG is correct and up-to-date.

https://qwik.builder.io/media/

2022-10-09 02:14 UTC, Snailedlt requested changes
The icons look good, so just a few standards that need to be followed, and we're good :)

2022-10-09 02:14 UTC, Snailedlt commented on devicon.json
> +        "name": "qwik",
The altnames attribute is missing here. If there are no altnames you can just have it be an empty array
```suggestion
        "name": "qwik",
        "altnames": [],
```

2022-10-09 02:14 UTC, Snailedlt commented on icons/qwik/qwik-plain-wordmark.svg
> +        <path style=" stroke:none;fill-rule:nonzero;fill:rgb(9.411765%,71.372549%,96.470588%);fill-opacity:1;" d="M 33.09375 64.832031 C 33.929688 63.113281 34.226562 61.609375 33.402344 60.097656 L
Plain icons should only have a single path. So please combine the paths if possible, :)

2022-10-09 02:14 UTC, Snailedlt commented on icons/qwik/qwik-plain.svg
> +        <path style=" stroke:none;fill-rule:nonzero;fill:rgb(9.411765%,71.372549%,96.470588%);fill-opacity:1;" d="M 95.671875 112.554688 L 78.242188 95.214844 L 77.996094 95.257812 L 77.996094 95.074
Plain icons should only have a single path. So please combine the paths if possible, :)

2022-10-09 02:14 UTC, Snailedlt commented on devicon.json
> +        "name": "qwik",
The altnames attribute is missing.
If there are no alternative names, you can just have an empty array (see suggestion 👇)

```suggestion
        "name": "qwik",
        "altnames": [],
```

2022-10-09 11:02 UTC, AmreshSinha commented
> The icons look good, so just a few standards that need to be followed, and we're good :)

Yep done! Have a look. Also, this is my time contributing to Devicons. 😃

2022-10-09 12:12 UTC, Snailedlt commented
> > The icons look good, so just a few standards that need to be followed, and we're good :)
> 
> Yep done! Have a look. Also, this is my time contributing to Devicons. smiley Also, should I remove the grouping or keep it there?

@AmreshSinha 
Nice!
Very well done for your first contribution!
Also, what do you mean by grouping?

2022-10-09 12:14 UTC, AmreshSinha commented
> > > The icons look good, so just a few standards that need to be followed, and we're good :)
> > 
> > 
> > Yep done! Have a look. Also, this is my time contributing to Devicons. smiley Also, should I remove the grouping or keep it there?
> 
> @AmreshSinha Nice! Very well done for your first contribution! Also, what do you mean by grouping?

by grouping, I mean that `g` element inside svg

2022-10-09 12:19 UTC, Snailedlt commented
@AmreshSinha 
Ahh, okey :)
I guess the `g` elements can be removed

2022-10-09 12:30 UTC, AmreshSinha commented
Done, Removed `g` element. 👍 
Can you test it again and check if it's fine or has any breaking changes?

2022-10-09 18:18 UTC, Snailedlt commented
Looks good, ship it! 😁

2022-10-09 18:19 UTC, Snailedlt submitted a review, later dismissed
LGTM! :heavy_check_mark: 
Thanks for another great contribution! :100:

2022-10-11 04:08 UTC, Panquesito7 commented on devicon.json
> +            "framework"
```suggestion
            "framework",
            "open-source"
```

2022-10-11 04:09 UTC, Panquesito7 approved these changes
Great! Thanks. 🚀

2022-10-11 04:11 UTC, merged