new icon: tex (plain-wordmark)
devicons/devicon pull request #1449
Opened 2022-10-12 14:22 UTC by lunatic-fox

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1444**

## Link to prove your SVG is correct and up-to-date.
https://commons.wikimedia.org/wiki/File:TeX_logo.svg

2022-10-14 17:29 UTC, Snailedlt requested changes

2022-10-14 17:29 UTC, Snailedlt commented on devicon.json
> +        ]
Same here as with the [YAML](https://github.com/devicons/devicon/pull/1448) PR, the icon should be changed to `original`, and the aliases should be changed as follows:
```suggestion
        "versions": {
            "svg": [
                "original"
            ],
            "font": [
                "original"
            ]
        },
        "color": "#000000",
        "aliases": [
            {
                "base": "original",
                "alias": "original-wordmark"
            },
            {
                "base": "original",
                "alias": "plain"
            },
            {
                "base": "original",
                "alias": "plain-wordmark"
            }
        ]
```

2022-10-14 18:27 UTC, Snailedlt approved these changes
LGTM! ✔️

2022-10-15 03:49 UTC, KayleeDavisGitHub commented
Thank you all <3

2022-12-10 11:01 UTC, merged