new icon: bun (original)
devicons/devicon pull request #1462
Opened 2022-10-15 19:18 UTC by AmreshSinha

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://github.com/oven-sh/bun/blob/main/packages/bun-landing/public/logo.svg

2022-10-27 07:53 UTC, AmreshSinha commented
Bump.

2022-10-29 22:25 UTC, Snailedlt requested changes
The icon itself looks good, but since it's multi-colored it can't be used as a font. So either remove `original` from the font array, or add a new mono-colored (plain or line) icon which can be used as a font :)

2022-10-29 22:25 UTC, Snailedlt commented on devicon.json
> +            ]
We only allow mono-colored icons as fonts. 
For more info check out [SVG-Standards](https://github.com/devicons/devicon/wiki/SVG-Standards) and [SVG-Versions](https://github.com/devicons/devicon/wiki/SVG-Versions) in our wiki :)
```suggestion
            "font": []
```

2022-11-07 23:42 UTC, Snailedlt commented
@AmreshSinha Do you want to make a plain or line version of this icon?
You can follow this guide for making a line icon: https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294

If you don't want to, that's okey too :) We can ask someone else

2022-11-08 07:55 UTC, AmreshSinha commented
> @AmreshSinha Do you want to make a plain or line version of this icon?
> 
> You can follow this guide for making a line icon: https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294
> 
> 
> 
> If you don't want to, that's okey too :) We can ask someone else 

I can't think of the main color in this main logo for the plain one. :/ It would be very helpful if anyone can co-author this pr with a plain or line version.

2022-11-08 08:15 UTC, Snailedlt commented
@lunatic-fox or @kilianpaquier
Any of you wanna make some plain and line versions of this icon?

2022-11-08 09:50 UTC, kilianpaquier commented
> @lunatic-fox or @kilianpaquier
> Any of you wanna make some plain and line versions of this icon?

Hello, I can take a look next Saturday

2022-11-24 21:30 UTC, kilianpaquier commented
> > @lunatic-fox or @kilianpaquier
> > Any of you wanna make some plain and line versions of this icon?
> 
> Hello, I can take a look next Saturday

Hello, here's a proposition for the bun original icon.

![bun-original (1)](https://user-images.githubusercontent.com/107955904/203865398-93496dcb-1ec8-4ae3-92da-1e53df45aba6.svg)

2022-11-25 03:39 UTC, lunatic-fox commented
Hi @kilianpaquier!
The version you're making actually is the `plain` one. 🙂
I thought in something that way:
> *It's not a SVG*
<img width="256" src="https://user-images.githubusercontent.com/76992016/203894503-cacadea0-5ae5-4273-8b82-e6ebefdf8d3b.png"/>
Like preserving the mouth contour and no fill.

---

> *PS: I don't know why, probably a bug from my side since it works fine in other programs, but when I try to visualize from browser this happens:*
<img width="256" src="https://user-images.githubusercontent.com/76992016/203896066-c031808e-2716-4ea1-af04-f82fb5ad89e0.png"/>

> *This is just a thing that I want to share. Don't need to worry about it.* 😀

2022-11-25 07:18 UTC, kilianpaquier commented
> Hi @kilianpaquier! The version you're making actually is the `plain` one. 🙂 I thought in something that way:
> 
> > _It's not a SVG_
> 
> <img alt="" width="256" src="https://user-images.githubusercontent.com/76992016/203894503-cacadea0-5ae5-4273-8b82-e6ebefdf8d3b.png">
> 
> Like preserving the mouth contour and no fill.
> > _PS: I don't know why, probably a bug from my side since it works fine in other programs, but when I try to visualize from browser this happens:_
> 
> <img alt="" width="256" src="https://user-images.githubusercontent.com/76992016/203896066-c031808e-2716-4ea1-af04-f82fb5ad89e0.png">
> 
> > _This is just a thing that I want to share. Don't need to worry about it._ 😀

Hello ! Yes obviously I didn’t right the correct word 😂.

Thanks for the feedback, I see it with the right color on my phone, but I’m gonna take a look at the attributes just to be sure.

Great idea for the line icon, I shouldn’t take me long tonight to draft it.

2022-11-25 19:06 UTC, kilianpaquier commented
Hello,

I fixed the plain with the fill attribute instead of style. Plus here's also the line icon.

![bun-plain](https://user-images.githubusercontent.com/107955904/204043013-2c7e2954-7dc3-4652-9532-936241930648.svg)
![bun-line](https://user-images.githubusercontent.com/107955904/204043016-7665c8ab-269d-477c-8d83-7d23616ae1fc.svg)

2022-11-25 22:17 UTC, lunatic-fox commented
Pretty good! 🤩
I think the only thing that's needed is to keep the little tongue contour on `plain` version.

2022-12-10 14:56 UTC, Snailedlt commented
@lunatic-fox feel free to add the plain and line icons to the PR. Like you said, the plain version needs the tongue added back in :)

2022-12-12 00:06 UTC, lunatic-fox approved these changes
Approved! ✔
Thank you for this contribution! 🚀

2022-12-12 07:12 UTC, Snailedlt approved these changes

2022-12-12 07:13 UTC, merged