new icon: Jira Align (original,plain)
devicons/devicon pull request #1468
Opened 2022-10-19 07:52 UTC by yeyeto2788

## Double check these details before you open a PR

- [X] PR does not match another non-stale PR currently opened
- [X] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [X] PR's base is the `develop` branch.
- [X] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [X] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [X] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #789 **

## Link to prove your SVG is correct and up-to-date.

2022-10-19 13:18 UTC, Snailedlt requested changes
Those don't look like the official logos 🙊 
Please change to the official ones (I linked to them in issue #789)

2022-10-20 07:17 UTC, yeyeto2788 commented
That is really weird cuz I do see it correctly in Inkscape
![image](https://user-images.githubusercontent.com/6363686/196881648-fe2ffe3f-c686-4032-b219-37e084b372d0.png)

Any suggestions on how to fix it? Maybe exporting it differently?

2022-10-20 07:19 UTC, yeyeto2788 commented
I'll grouping them to see if that fixes the issue.

2022-10-20 07:25 UTC, yeyeto2788 commented
I had to use the ones you provided on the issue itself as the grouping didn't work. Thanks for that!

2022-10-22 22:48 UTC, lunatic-fox commented
Hello there!
@yeyeto2788 you're doing great!
I just have some recommendations to the icons.
First, I think you'll need to change the icons name and add two more icons:
* `original` to `original-wordmark`
* `plain` to `plain-wordmark`

And add the `original` and `plain` icons based on the square-like icon recommended by @Snailedlt on #789 issue.

To `original-wordmark` icon you can ungroup all and unify just "Jira Align" characters in one path.
To `plain-wordmark` icon, you can ungroup all and unify all in just one path.
All icons need to be an 128×128px square.

Wish for the best!

2022-10-24 08:41 UTC, yeyeto2788 commented
Hey @lunatic-fox!

I think I have covered everything you asked me for but if you see there is something missing just let me know.

Best.

2022-10-24 17:02 UTC, lunatic-fox commented
The icons look great now @yeyeto2788! 🤩

However there are some issues yet:
* `plain` and `plain-wordmark` paths need to be united in just one path, to keep them as simple as possible. 
**Source doc:** https://github.com/devicons/devicon/wiki/SVG-Standards

* In `devicon.json` the icon color is `#F04E98`, I suggest `#2684FF` since is the main color of the `original` version.

* You can add `plain-wordmark` to `font` array of `versions` object of `devicon.json`.

* A recommendation is to ungroup all since you already fixed the invisible paths issue in your last icons.

Keep rocking! 🚀

2022-10-25 08:31 UTC, yeyeto2788 commented
Hey @lunatic-fox! 

I hope this time is correct. So for uniting the path I followed these steps:

1. Ungroup the objects `Ctrl Shift G`
2. Select all `Ctrl A`
3. Path > Union `Ctrl + +` 

I guess that could be added into the documentation. I really helped me a lot the example with the box creation and this might as well help others.

2022-10-25 14:59 UTC, lunatic-fox commented
Hello @yeyeto2788!
In short:
* `original` ✔
* `original-wordmark` ✔
* `plain` ✔

But `plain-wordmark` is grouped. The key command to ungroup is `Shift+Ctrl+G`, otherwise it'll probably group instead. However, you can also follow that way bellow.

<details>
<summary>Checking layers</summary>

* Go to `Layers and Objects`. If it's not opened you can open it by `Object > Layers and Objects...` or `Shift+Ctrl+L`
* If you see some layer with ![folder-icon](https://user-images.githubusercontent.com/76992016/197802364-d1c356ee-2b0c-4b57-8368-e6eb83d8e5a5.png), that means this layer is a group of layers.
* You can ungroup this layer by right clicking on the layer ![folder-icon](https://user-images.githubusercontent.com/76992016/197802364-d1c356ee-2b0c-4b57-8368-e6eb83d8e5a5.png) and selecting `Ungroup`.
* To be sure that everything is ungrouped, all layers should be with this icon ![path-icon](https://user-images.githubusercontent.com/76992016/197803632-aaa515e9-1da3-4624-8a06-334b47c208fd.png)
* Once all layers are paths ![path-icon](https://user-images.githubusercontent.com/76992016/197803632-aaa515e9-1da3-4624-8a06-334b47c208fd.png), them select all and `Unify` by `Path > Union` or `Ctrl++`
* Lastly you should see just one ![path-icon](https://user-images.githubusercontent.com/76992016/197803632-aaa515e9-1da3-4624-8a06-334b47c208fd.png) path layer.
</details>

Hope everything works fine! 👍🏼

2022-10-26 09:32 UTC, yeyeto2788 commented
Hopefully this one is the last one. Once again sorry for the inconveniences.

Best.

2022-10-26 21:28 UTC, lunatic-fox commented
No worries! There is no inconvenience at all. 🙂
Like the other PR, I haven't seen before just two things: the `altnames` and `tags` properties are missing after `name` property.

*Suggestions of tags*
```json
"tags": [
    "development",
    "integration",
    "software"
]
```

The icons are great now! 🎉

Like I said before you can also contact us on [**Discord server**](https://discord.gg/hScy8KWACQ).

2022-10-29 23:04 UTC, Snailedlt requested changes
Almost there! 🚀 

Just need to add the name with whitespaces as an altname and minimize all of the icons. You can minimize the icons like I explained here: https://github.com/devicons/devicon/pull/1465/files#r1008766362

2022-10-29 23:04 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": [
            "Jira Align"
        ],
```

2022-10-29 23:06 UTC, Snailedlt commented
@yeyeto2788 
> Hey @lunatic-fox!
> 
> I hope this time is correct. So for uniting the path I followed these steps:
> 
> 1. Ungroup the objects `Ctrl Shift G`
> 2. Select all `Ctrl A`
> 3. Path > Union `Ctrl + +`
> 
> I guess that could be added into the documentation. I really helped me a lot the example with the box creation and this might as well help others.

Yes, this could be added to the wiki as a part of this issue: #1306

2022-10-29 23:17 UTC, lunatic-fox commented
> @yeyeto2788
> 
> > Hey @lunatic-fox!
> > I hope this time is correct. So for uniting the path I followed these steps:
> > 
> > 1. Ungroup the objects `Ctrl Shift G`
> > 2. Select all `Ctrl A`
> > 3. Path > Union `Ctrl + +`
> > 
> > I guess that could be added into the documentation. I really helped me a lot the example with the box creation and this might as well help others.
> 
> Yes, this could be added to the wiki as a part of this issue: #1306

I'll be adding this later [Instructions to resize to square](https://github.com/devicons/devicon/pull/1465#issuecomment-1287950577) and [Checking layers](https://github.com/devicons/devicon/pull/1468#issuecomment-1290702218).

2022-10-29 23:19 UTC, Snailedlt commented
@lunatic-fox Nice! Please add links to those as comments with the same format I used in the issue I created: #1306

2022-10-31 16:22 UTC, Snailedlt commented
> Hi!
> 
> I'm the `check-bot` and we have some issues with your PR:
> 
> ```
> SVG Error in 'jiraalign-plain.svg':
> - 'viewBox' is not '0 0 128 128' -> Set it or scale the file using https://www.iloveimg.com/resize-image/resize-svg.
> ```
> 
> Check our [CONTRIBUTING guide](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards) for more details regarding these errors.
> 
> Please address these issues. When you update this PR, I will check your SVGs again.
> 
> Thanks for your help, SVG-Checker Bot 😄

@yeyeto2788 Please resize the viewbox as explained above. I recommend using [iloveimg](https://www.iloveimg.com/resize-image/resize-svg) to make it fast and easy :)

2022-10-31 22:42 UTC, Snailedlt requested changes
Looks good now, but the icons are still quite big. Could you please optimize them using this method? https://github.com/devicons/devicon/issues/1306#issuecomment-1296015861

2022-11-02 12:15 UTC, yeyeto2788 commented
> Looks good now, but the icons are still quite big. Could you please optimize them using this method? [#1306 (comment)](https://github.com/devicons/devicon/issues/1306#issuecomment-1296015861)

I did that step before my last commit but I have done again hoping it does not screw anything as the last time.

Best.

2022-11-03 00:48 UTC, Snailedlt approved these changes
Looking good! ✔️ 
Thank you for your contribution! 💯

2022-11-08 18:56 UTC, lunatic-fox approved these changes
Approved! ✔
Great contribution! 🚀

2022-11-09 08:43 UTC, merged