Add VS Code Intellisense to `devicon.json`
devicons/devicon pull request #1487
Opened 2022-10-30 01:04 UTC by lunatic-fox

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

VS Code Intellisense to `devicon.json` provides these features:
- A snippet to create a new input object by typing `new`
- Validates
    - `name` structure
    - `color` structure
    - `version.svg[]`, `version.font[]`, `aliases.?base` and `aliases.?alias` completion
- Provides some description for the properties based on the documentation

**This PR closes #1481**

## Notes

2022-10-31 21:06 UTC, Snailedlt requested changes
Looking great!
One of the features I'm most looking forwards too, since this will boost productivity so much!

As always, there's a few suggestions I'd like you to look at before we're ready for merging this. Great general structure though, definitely good work! 💯

2022-10-31 23:37 UTC, lunatic-fox commented on .vscode/devicon.code-snippets
> +    "scope": "json",
Yeah, I was wishing just the same, too bad that's not possible. But I think your suggested feature #1484 solves that issue.

2022-11-07 15:47 UTC, Snailedlt approved these changes
Looking good! ✔️
Can't wait to get this into master, well done with the changes :)

2022-11-18 22:16 UTC, lunatic-fox commented
@Panquesito7, please review this request. 🙂
Here's another reason: #1514

2022-12-10 10:58 UTC, merged