update icon: tailwindcss (plain)
devicons/devicon pull request #1493
Opened 2022-11-01 07:05 UTC by theabhayprajapati

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

This PR closes #1489
## Link to prove your SVG is correct and up-to-date.

https://tailwindcss.com/

2022-11-02 22:02 UTC, Snailedlt requested changes
In addition to the suggestions you should do the following:
- Update tailwindcss in `devicon.json` (See [updating devicon.json](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)). 
More precisely you should change the color to the same as the new icons, and add [aliases](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60#aliases-and-aliasobj) between original and plain, as well as between original-wordmark and plain-wordmark.
- Remove [Tailwindcss-wordmark-01.eps](https://github.com/devicons/devicon/blob/develop/icons/tailwindcss/Tailwindcss-wordmark-01.eps)

2022-11-06 03:38 UTC, theabhayprajapati commented on icons/tailwindcss/tailwindcss-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M64.004 25.602c-17.067 0-27.73 8.53-32 25.597 6.398-8.531 13.867-11.73 22.398-9.597 4.871 1.214 8.352 4.746 12.207 8.66C72.883 5
Almost I used it but then i thought lets not change the whole and so I just updated the color of the both the icons.,

2022-11-06 19:07 UTC, Snailedlt commented on icons/tailwindcss/tailwindcss-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M64.004 25.602c-17.067 0-27.73 8.53-32 25.597 6.398-8.531 13.867-11.73 22.398-9.597 4.871 1.214 8.352 4.746 12.207 8.66C72.883 5
Imo it's better to use that one, since it's the official logo

2022-11-06 19:30 UTC, theabhayprajapati commented on icons/tailwindcss/tailwindcss-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M64.004 25.602c-17.067 0-27.73 8.53-32 25.597 6.398-8.531 13.867-11.73 22.398-9.597 4.871 1.214 8.352 4.746 12.207 8.66C72.883 5
Right I will update the new one soon.

2022-12-17 15:23 UTC, lunatic-fox submitted a review, later dismissed
- `devicon.json` up-to-date with `develop` branch.
  Here's `tailwindcss` object: [***lines 8477 - 8497***](https://github.com/devicons/devicon/pull/1493/files#diff-8fb0089a81b777eae04d6ac8f37becd0a07c41dd808f17e9e90eafb7411a8f60R8477-R8497)
- Fixed icons.

Thank you for this contribution! 🚀

2022-12-17 15:28 UTC, Snailedlt requested changes
Something went wrong with the devicon.json update, so the file has been changed in a lot of places. Please merge or rebase on develop, and make sure only tailwind is added/edited

2023-01-09 18:58 UTC, Snailedlt approved these changes
Looks good ✔️ 
Thank you for your contribution 💯

2023-01-18 10:42 UTC, merged