new icon: photonengine (original)
devicons/devicon pull request #1499
Opened 2022-11-04 11:02 UTC by yeyeto2788

## Double check these details before you open a PR

- [X] PR does not match another non-stale PR currently opened
- [X] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [X] PR's base is the `develop` branch.
- [X] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [X] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [X] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1469 **

## Link to prove your SVG is correct and up-to-date.

2022-11-07 17:23 UTC, Snailedlt commented
I made some changes:
- Added plain icon
- Edited `font` and `alias` in devicon.json
- Moved the devicon.json entry up, so that it's alphabetically sorted

2022-11-07 17:27 UTC, Snailedlt submitted a review, later dismissed
LGTM! ✔️
Thank you for your contribution! 🙇

2022-11-08 20:44 UTC, lunatic-fox commented on devicon.json
> +        },
```suggestion
        "versions": {
            "svg": [
                "original"
            ],
            "font": [
                "plain"
            ]
        },
```

2022-11-09 08:41 UTC, Snailedlt approved these changes

2022-11-09 17:47 UTC, lunatic-fox requested changes

2022-11-09 17:47 UTC, lunatic-fox commented on devicon.json
> +        },
```suggestion
        "versions": {
            "svg": [
                "original",
                "plain"
            ],
            "font": [
                "plain"
            ]
        },
```
Adds `plain` version in `svg[]`.

2022-11-09 17:59 UTC, lunatic-fox commented
`plain` version added to `versions.svg[]`

2022-11-09 18:04 UTC, lunatic-fox approved these changes
Approved! ✔
Great contribution! 🚀

2022-11-10 15:29 UTC, Snailedlt approved these changes

2022-11-29 20:14 UTC, merged