new icon: stackoverflow (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1511
Opened 2022-11-17 20:16 UTC by Panquesito7

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/wiki/Organizing-SVGs)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/wiki/Updating-the-%60devicon.json%60)

**This PR closes #1223**

## Link to prove your SVG is correct and up-to-date.

https://stackoverflow.design/brand/logo/

2022-11-19 05:01 UTC, lunatic-fox requested changes
Hello there!
You'll need to do a few things to the icons:

***To all icons***
- Release clip paths
  - In Inkscape:
    - In `Layers and Objects` tab
      - Right click the grouped paths ![clip-path-icon](https://user-images.githubusercontent.com/76992016/202834724-77264272-2616-4856-b7a6-e365e44d9ca6.png)
      - Select: `Release Clip`
    - This action will open two paths
      - Remove the clip path.


***To `plain` and `plain-wordmark` versions***
- Ungroup all layers and unify them into one.
  > ***[Info of how to ungroup all and unify in Inkscape](https://github.com/devicons/devicon/issues/1306#issuecomment-1296052892)***

2023-02-09 08:02 UTC, Snailedlt commented on icons/stackoverflow/stackoverflow-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M.07 1H1v1H.07m0 0"/><path style="fill-rule:evenodd;fill:#bbb;fill-opacity:1" d="M98.125 82.582h11.36V1
Can you remove the `width` and `height` attributes for all icons? Iirc it will allow end-users to more easily change the size of the icon

2023-02-09 08:06 UTC, Snailedlt requested changes
Things to fix:
- Paths need to be unified for `plain` icons
- `width` and `height` attributes should be removed

Optional
- Consider adding a `line` version

2023-02-09 08:06 UTC, Snailedlt commented on icons/stackoverflow/stackoverflow-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M.07 1H1v1H.07m0 0"/><path style="fill-rule:evenodd;fill:#bbb;fill-opacity:1" d="M98.125 82.582h11.36V1
Can you remove the `width` and `height` attributes for all icons? Iirc it will allow end-users to more easily change the size of the icon

2023-02-09 08:06 UTC, Snailedlt commented on icons/stackoverflow/stackoverflow-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><path d="M0,6 h1 V7 H0 m0,0"/><path d="M0.278,1 H1 v1 H0.278 m0,0"/><path style="fill-rule:nonzero;fill:#1e1b1d;
The paths need to be unified here since it's a plain icon. So you should end up with just one `<path ... />` element

2023-02-16 06:57 UTC, lunatic-fox approved these changes
Great! ✔
Thank you for this contribution! 🚀

2023-02-17 20:29 UTC, Panquesito7 commented
> Great! ✔ Thank you for this contribution! 🚀

Thanks for your help and reviews. :)

2023-02-17 23:33 UTC, Snailedlt approved these changes

2023-02-17 23:36 UTC, merged