new icon: solidjs (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1557
Opened 2022-11-27 09:48 UTC by AbdelrahmanDwedar

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://www.solidjs.com/media

2022-11-28 07:08 UTC, Snailedlt requested changes
Wordmark icons aren't centered and resized correctly. Look at the file previews

2022-11-29 19:41 UTC, lunatic-fox commented
**This PR closes #1253 (staled PR)**

2022-12-02 17:51 UTC, AbdelrahmanDwedar commented
Oh I didn't see it. Sorry.

2022-12-02 17:52 UTC, AbdelrahmanDwedar commented
> Wordmark icons aren't centered and resized correctly. Look at the file previews

I'll check them out, maybe I forgot to do something.

2022-12-02 18:00 UTC, AbdelrahmanDwedar commented
I don't know what happened in the plain wordmark version the colors seem to disappear in the image.

2022-12-03 06:39 UTC, lunatic-fox commented
> Oh I didn't see it. Sorry.

No problem! 🙂

2022-12-03 07:46 UTC, lunatic-fox requested changes

2022-12-03 07:46 UTC, lunatic-fox commented on icons/solidjs/solidjs-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><g fill="#518ac8"><path d="M75.81 15.35S50.86-3.49 31.5.91l-1.7.47A12.35 12.35 0 0 0 23.22 6a11.18 11.18 0 0 0-.71 1.18l-7.15 12.15 12.35
It seems that the bottom path of the "s" is missing.
Here's some suggestion of fixing made with Inkscape CLI from `original-wordmark` version.

### Preview
<img alt="preview" width="256" src="https://user-images.githubusercontent.com/76992016/205429295-ee70a4f2-8fc1-4025-9ca9-b8e01a4408e0.svg"/>

> Note: even it's black, actually the path has no fill color, so it'll be filled by `color` property of `devicon.json` entry.

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M40.25 67.017a4.374 4.374 0 0 0 2.952 1.24c1.239 0 2.26-.73 2.26-1.969 0-2.843-5.65-2.15-5.65-5.65 0-1.64 1.458-3.024 3.535-3.024a4.374 4.374 0 0 1 3.026 1.093l-.55.948a3.783 3.783 0 0 0-2.48-.984c-1.457 0-2.368.947-2.405 1.931 0 2.697 5.65 1.932 5.65 5.65 0 1.676-1.313 3.061-3.427 3.061a4.87 4.87 0 0 1-3.571-1.458zm17.895-9.33a5.733 5.733 0 0 1 5.759 5.795 5.832 5.832 0 0 1-5.759 5.904h-.036a5.832 5.832 0 0 1-5.76-5.904v-.037a5.733 5.733 0 0 1 5.796-5.758zm-.036 10.679a4.738 4.738 0 0 0 4.628-4.844v-.04c0-2.697-2.04-4.775-4.592-4.775a4.636 4.636 0 0 0-4.629 4.738c0 2.77 2.041 4.884 4.593 4.92zm12.355-10.46h1.094L71.52 68.22h5.249v.984H70.39zm12.356.036h1.094l-.037 11.335h-1.093zm8.456 0h3.645c3.39 0 5.685 2.077 5.685 5.686 0 3.608-2.296 5.649-5.685 5.649h-3.645zm3.499 10.35c2.77 0 4.629-1.64 4.665-4.664.037-3.026-1.859-4.666-4.629-4.666H92.37l-.036 9.33zm15.37.985a3.743 3.743 0 0 0 2.573-.919 3.28 3.28 0 0 0 1.042-2.587v-7.694h-2.278v7.526a1.53 1.53 0 0 1-.364 1.093 1.316 1.316 0 0 1-1.01.39q-1.071 0-1.563-1.257l-1.928 1.075q.944 2.373 3.528 2.373zm13.653.025c1.265 0 2.256-.313 2.967-.944a3.138 3.138 0 0 0 1.064-2.474 2.584 2.584 0 0 0-.911-2.067c-.612-.525-1.593-.977-2.941-1.363a4.286 4.286 0 0 1-1.37-.572.937.937 0 0 1-.402-.784.984.984 0 0 1 .401-.82 1.677 1.677 0 0 1 1.06-.31 2.067 2.067 0 0 1 2.082 1.356l1.884-1.031a3.663 3.663 0 0 0-1.483-1.765 4.436 4.436 0 0 0-2.38-.623 4.05 4.05 0 0 0-2.715.948 2.956 2.956 0 0 0-1.127 2.387 2.734 2.734 0 0 0 .846 2.045q.758.765 2.686 1.345a6.018 6.018 0 0 1 1.648.663.85.85 0 0 1 .433.762.999.999 0 0 1-.47.842 2.056 2.056 0 0 1-1.203.332 2.551 2.551 0 0 1-2.405-1.542l-1.968 1.017a3.955 3.955 0 0 0 1.636 1.906 5.008 5.008 0 0 0 2.668.692zm-104.36.609a7.705 7.705 0 0 0-8.212-2.606L.46 70.789s9.111 6.867 16.15 5.263l.62-.17c2.882-.916 3.866-3.61 2.208-5.97zm3.382-6.021a7.694 7.694 0 0 0-8.23-2.606L3.842 64.768.46 70.79l19.255 3.28 3.451-6.14c.69-1.178.62-2.661-.346-4.04zM8.646 56.123l-.624.175c-2.879.93-3.863 3.623-2.208 5.985a7.698 7.698 0 0 0 8.215 2.587l10.76-3.502s-9.076-6.849-16.143-5.245zm19.248.087s-9.094-6.866-16.15-5.263l-.62.172a4.501 4.501 0 0 0-2.398 1.684 4.075 4.075 0 0 0-.259.43L5.861 57.66l4.501.878a8.018 8.018 0 0 0 6.419 1.262l8.018 1.567z"/></svg>

```

2022-12-03 07:46 UTC, lunatic-fox commented on icons/solidjs/solidjs-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><defs><linearGradient id="a" x1="27.5" x2="152" y1="3" y2="63.5" gradientTransform="matrix(.8 0 0 .8 -3.16485 5.81808)" gradientUnits="us
Seems that this icon is not well aligned to the center. 🤔

2022-12-03 07:46 UTC, lunatic-fox commented on icons/solidjs/solidjs-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><defs><linearGradient id="a" x1="27.5" x2="152" y1="3" y2="63.5" gradientTransform="matrix(.8 0 0 .8 -2.97213 2.26858)" gradientUnits="us
Seems that this icon also is not well aligned to the center and the paths are not unified into one.
If you need some help in unifying the paths on Inkscape, take a look at this [comment](https://github.com/devicons/devicon/issues/1306#issuecomment-1296052892).
And if you want some help about alignment on Inkscape, just keep reading.

### Align to the center of the page
> **Steps to follow if you're editing some `original` or `original-wordmark` version that has more than one path will be marked with `*`**
- Open the "Align and Distribute" tab by going to `Object > Align and Distribute...` or by key command `Shift + Ctrl + A`
- \* Select all `Ctrl + A` and group it `Ctrl + G`
- On `Align`, select `Relative to: Page`
- Select to center to the vertical and horizontal axis
- \* Select all `Ctrl + A` and ungroup it `Shift + Ctrl + G`

2022-12-03 07:46 UTC, lunatic-fox commented on devicon.json
> +	},
Fix alignment and remove unnecessary aliases. 🙂
```suggestion
    {
        "name": "solidjs",
        "altnames": [],
        "tags": [
            "javascript",
            "framework",
            "frontend"
        ],
        "versions": {
          "svg": [
              "original",
              "original-wordmark",
              "plain",
              "plain-wordmark"
          ],
          "font": [
              "plain",
              "plain-wordmark"
          ]
        },
        "color": "#518ac8",
        "aliases": []
    },
```

2022-12-17 14:46 UTC, lunatic-fox submitted a review, later dismissed
Icons are ok now and conflicts are resolved in `devicon.json`
Thank you for this contribution! 🚀

2022-12-17 15:24 UTC, Snailedlt requested changes

2022-12-17 15:24 UTC, Snailedlt commented on devicon.json
> +        "color": "#518ac8",
Accord to https://www.solidjs.com/media the primary color should be `#2c4f7c`
```suggestion
        "color": "#2c4f7c",
```

2022-12-17 15:24 UTC, Snailedlt commented on icons/solidjs/solidjs-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><defs><linearGradient id="a" x1="27.5" x2="152" y1="3" y2="63.5" gradientTransform="translate(-.394 50.573) scale(.17312)" gradientUnits=
This should be replaced with the version from their media assets page: https://www.solidjs.com/media

2023-01-09 18:40 UTC, Snailedlt approved these changes
Looking good! Thank you for your contribution! ✔️

2023-01-30 20:27 UTC, merged