new icon: <i>Iswagger</i> (<i>original, plain</i>)
devicons/devicon pull request #1561
Opened 2022-12-01 06:31 UTC by yeyeto2788

## Double check these details before you open a PR

- [X] PR does not match another non-stale PR currently opened
- [X] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [X] PR's base is the `develop` branch.
- [X] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [X] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [X] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #903**

## Link to prove your SVG is correct and up-to-date.

2022-12-01 07:18 UTC, PantheraRed commented on devicon.json
> +    },
I'd suggest some changes.

```suggestion
    {
       "name": "swagger",
       "altnames": [],
       "tags": [
           "development",
           "api",
           "documentation",
           "tool"
       ],
       "versions": {
           "svg": [
               "original",
               "plain"
           ],
           "font": [
               "original",
               "plain"
           ]
       },
       "color": "#173647",
       "aliases": [
           {
               "base": "original",
               "alias": "original-wordmark"
           },
           {
               "base": "plain",
               "alias": "plain-wordmark"
           }
       ]
    },
```

2022-12-01 12:16 UTC, PantheraRed commented
@yeyeto2788, I think it would be a good idea to separate icon from its wordmark version and call it the `original` version. Also fonts made out of `original` and `plain` versions are very small and multi-colored. I have made a few changes and new versions. Please have a look and give your opinion on them.

# swagger-original

![swagger-original](https://user-images.githubusercontent.com/41539361/205050300-adea49b1-24ec-4c78-81fa-7063b88dfd44.svg)

# swagger-original-wordmark

![swagger-original-wordmark](https://user-images.githubusercontent.com/41539361/205050304-c231eff0-1ffb-4c7e-930f-fb5276af2736.svg)

# swagger-plain

![swagger-plain](https://user-images.githubusercontent.com/41539361/205050309-f9c2ee94-95bb-4961-be7b-d7083ca54264.svg)

# swagger-plain-wordmark

![swagger-plain-wordmark](https://user-images.githubusercontent.com/41539361/205050287-3234bbac-36cb-4655-803f-02111591dba7.svg)

2022-12-01 12:32 UTC, yeyeto2788 commented
@PantheraRed that is fine for me but then the original wouldn't be the original as the real one has the wording on it.

I regards of your versions, they do look great considering that I was using the blueish color as the predominant one but definitely the green one pops a lot.

@Snailedlt, if you still want me to change and agree with @PantheraRed it just let me know. 

Best.

2022-12-03 06:30 UTC, lunatic-fox commented
Hello there!

The main color of this icon is `#173647` and I agree with @PantheraRed in `original` and `original-wordmark` versions.

`plain` and `plain-wordmark` versions can be done from the current `plain` version, but I prefer the idea of @PantheraRed since variations of this color `#85ea2d` are more frequent than variations of `#173647` on their [website](https://swagger.io/), suggesting that it should be the main theme color related to this technology.

The `original` version is fine since they're using it as [favicon](https://static1.smartbear.co/swagger/media/assets/swagger_fav.png) and if you look at the bottom of their [website](https://swagger.io/) they're also using this version of the icon. And `original-wordmark` is similar to `original` version, but with the technology name.

If you choose the icons with `#85ea2d` color, remember to change `color` property before make the new commit. We also have to remove the `<clipPath>` from `plain` and `plain-wordmark*`.
> *\* To be done.*

---
> ### 💡 General tip
> `plain`, `plain-wordmark`, `line` and `line-versions` don't really need a fill color, as long as those versions receive the fill color from `devicon.json` `color` property. The only exception happens when some version is an alias from `original` or `original-wordmark` versions.

2022-12-03 12:43 UTC, Snailedlt commented
@yeyeto2788 I agree with what @PantheraRed and @lunatic-fox suggested, so go ahead 😊

2022-12-03 15:54 UTC, PantheraRed commented
@lunatic-fox,
> If you choose the icons with `#85ea2d` color, remember to change `color` property before make the new commit. We also have to remove the `<clipPath>` from `plain` and `plain-wordmark*`.

All the SVGs in this https://github.com/devicons/devicon/pull/1561#issuecomment-1333681625 are already optimized and don't have `<clipPath>` attributes.

2022-12-03 16:09 UTC, lunatic-fox commented
> @lunatic-fox,
> 
> > If you choose the icons with `#85ea2d` color, remember to change `color` property before make the new commit. We also have to remove the `<clipPath>` from `plain` and `plain-wordmark*`.
> 
> All the SVGs in this [#1561 (comment)](https://github.com/devicons/devicon/pull/1561#issuecomment-1333681625) are already optimized and don't have `<clipPath>` attributes.

I was talking based on @yeyeto2788 icons, but that's great, since the icons that you made are just ready-to-go. 🤩

2022-12-05 07:57 UTC, yeyeto2788 commented
Hey guys! Sorry for the delay.

Changes applied, thanks @PantheraRed for providing the icons and @Snailedlt and @lunatic-fox for your quick reply.

2022-12-05 10:42 UTC, lunatic-fox requested changes
Made some commits to fix the `devicon.json` structure and a little resize to the icons.

@yeyeto2788, I think you should check out for some linter on the IDE that you're using to edit `devicon.json`

2022-12-05 10:42 UTC, lunatic-fox commented on devicon.json
> +        ],
Some suggestions of tag.
```suggestion
        "tags": [
            "development",
            "software",
            "tool"
        ],
```

2022-12-06 08:52 UTC, lunatic-fox approved these changes
Approved! ✔
Thank you for this contribution! 🚀

2022-12-06 10:06 UTC, Snailedlt approved these changes

2022-12-06 10:06 UTC, merged