update icon: jenkins (original, plain, line)
devicons/devicon pull request #1590
Opened 2022-12-20 20:08 UTC by lunatic-fox

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features
|old|new|
|:-:|:-:|
|![0003](https://user-images.githubusercontent.com/76992016/208752689-4fe38d32-9e6f-47ff-81e3-29d64882f1ca.png)|![0002](https://user-images.githubusercontent.com/76992016/208752693-7763ded3-ac40-4ddf-a544-d38aad76212f.png)|

**This PR closes NONE**

## Notes

2023-01-30 20:22 UTC, Snailedlt requested changes

2023-01-30 20:22 UTC, Snailedlt commented on icons/jenkins/jenkins-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#201d1e" d="M63.625 127.825c-1.475-.175-3.775-.6-5.025-.95l-1.3-.375-.7-1.925c-.4-1.075-1.35-4.025-2.1-6.575l-1.4-4.625-1.975
Both the new and the old versions here are missing some shadows on the eyelids. Here's the official logo: https://www.jenkins.io/images/logos/jenkins/jenkins.svg
![](https://www.jenkins.io/images/logos/jenkins/jenkins.svg)

Which can be found here: https://www.jenkins.io/artwork/

2023-02-15 09:38 UTC, Snailedlt approved these changes
Looks good now! ✔️

2023-02-16 03:06 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-02-16 03:08 UTC, merged