new icon: consul (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1604
Opened 2023-01-02 23:54 UTC by luizcarloscf

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1603**

## Link to prove your SVG is correct and up-to-date.

[Project Homepage](https://www.consul.io/)
[HashiCorp Brand Guidelines](https://www.hashicorp.com/brand)
[Logo](https://drive.google.com/uc?export=download&id=17tlD38R-KQmAN1NnQ0RL6ROeXOEwiWRx)

2023-01-08 02:24 UTC, lunatic-fox requested changes
Hello there!
Since `original` version is already a monochromatic icon I took the liberty to remove `plain` version and aliased `original` as `plain` in `devicon.json`. Hope that's ok! 😁

I also suggesting two more tags `security` and `tool`.

You've made a great pull request! 🚀

2023-01-08 02:24 UTC, lunatic-fox commented on devicon.json
> +        ],
Two more tags.
```suggestion
        "tags": [
            "networking",
            "infrastructure",
            "security",
            "tool"
        ],
```

2023-01-08 12:45 UTC, luizcarloscf commented
Hey @lunatic-fox, I think I added all the requested changes. Also, the suggestions you made about original version being already a monochromatic icon and making alias of original as plain in devicon.json apply to another PR that I made #1609.

I've dedicated myself to contributing good quality icons, is there anything that could be better?

2023-01-08 18:10 UTC, lunatic-fox submitted a review, later dismissed
Hello @luizcarloscf, perfect catch on your other PR.

Well, I think you're already doing a great job. If you want to get more specific info you can take a look at [**SVG Versions**](https://github.com/devicons/devicon/wiki/SVG-Versions) and [**Updating `devicon.json`**](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60) wiki topics.

There's also the [**Devicon Discord server**](https://discord.gg/hScy8KWACQ).

A little thing about GitHub is that is possible to commit someone's suggestion this way:
- [Docs GitHub - Incorporating feedback in your pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request).

Thank you for this contribution! ✔🚀

2023-01-09 19:42 UTC, Snailedlt requested changes

2023-01-09 19:42 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": ["HashiCorp Consul"],
```

2023-01-09 19:45 UTC, Snailedlt commented
> Hey @lunatic-fox, I think I added all the requested changes. Also, the suggestions you made about original version being already a monochromatic icon and making alias of original as plain in devicon.json apply to another PR that I made #1609.
> 
> I've dedicated myself to contributing good quality icons, is there anything that could be better?

The icons are excellent! 💯 

I think the only thing to make them better is to add a new line at the end of each file, since it's needed for some older text editors and IDE's.
See this warning: 
![image](https://user-images.githubusercontent.com/43886029/211394470-f3d0591c-9369-40a9-8b5f-f61eb6812f7c.png)

2023-01-09 23:35 UTC, Snailedlt requested changes
Resizing looks good, however there are now two newlines instead of one at the end of each file. It's a bit confusing since GitHub automatically hides the last newline, but if you edit the file, you'll see that there are 2 empty lines at the end.

So make sure there's only one newline at the end of each file :)

2023-01-09 23:43 UTC, lunatic-fox commented on devicon.json
> +        "altnames": ["HashiCorp Consul"],
```suggestion
        "altnames": [
            "HashiCorp Consul"
        ],
```

2023-01-09 23:46 UTC, luizcarloscf commented
That's kind odd, I opened with a text editor and I saw only two lines in the SVG files

2023-01-10 01:16 UTC, luizcarloscf commented
I opened the icon files with `vim` and use the command `:set list` to display tabs and newline characters.
I hope that everything is fine now :smiley:

2023-01-27 04:10 UTC, lunatic-fox approved these changes
Approved! ✔
Thank you for this great contribution! 🚀

2023-01-27 14:15 UTC, Snailedlt approved these changes
LGTM! ✔️

2023-01-27 14:16 UTC, Snailedlt commented
Thanks for another great PR, and thank you for making our review process easy by having high quality PR's!

2023-01-27 14:16 UTC, merged