new icon: vault (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1609
Opened 2023-01-04 10:15 UTC by luizcarloscf

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1206**

## Link to prove your SVG is correct and up-to-date.

https://www.hashicorp.com/brand
https://www.vaultproject.io/

2023-01-09 19:55 UTC, Snailedlt requested changes
Just an alias I want to get in. Once that's added I'll approve ✔️

2023-01-09 19:55 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": ["HashiCorp Vault"],
```

2023-01-09 23:36 UTC, Snailedlt requested changes
Same here as with #1604 :)

2023-01-09 23:43 UTC, lunatic-fox commented on devicon.json
> +        "altnames": ["HashiCorp Vault"],
```suggestion
        "altnames": [
            "HashiCorp Vault"
        ],
```

2023-01-27 04:12 UTC, lunatic-fox approved these changes
Approved! ✔
Thank you for this great contribution! 🚀

2023-01-27 14:17 UTC, Snailedlt approved these changes
Excellent PR as always! 🎉 
Approved! ✔️

2023-01-27 14:17 UTC, merged