Update nano icon
devicons/devicon pull request #1619
Opened 2023-01-08 21:02 UTC by ConX

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

 - Fixes issue mentioned in #1613 where Icomoon does not generate a font.

**This PR closes NONE**

## Notes

2023-01-09 19:22 UTC, Snailedlt requested changes
`nano-original-wordmark.svg` looks good, just need to be minified. 

In the original issue you also mentioned that `nano-original.svg` has the same issue with icomoon, if that's the case, then that should be updated here too, right?

> I am not sure what was wrong with the previous version. After exporting with Adobe Illustrator, it worked.

Hmm, odd. Great that it was easily fixable though! :D

2023-01-09 19:22 UTC, Snailedlt commented on icons/nano/nano-original-wordmark.svg
> -<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#C8F" d="M32.535 31.532c0-.08.028-.145.084-.196s.128-.077.217-.077c.091 0 .164.025.219.075.055.05.083.116.083.198s-.028.148-.
Should be minified using [SVGOMG](https://jakearchibald.github.io/svgomg/)
I went ahead and did it for you, so all you have to do is click apply:)

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 128 128">
  <path fill="#c8f" d="M32.5 31.5c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1c.1 0 .1.1.1.2s0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1-.1-.1-.1-.2zm0 .9c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1-.1-.1-.1-.2zm1.9-.9c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1-.1-.1-.1-.2zm0 .9c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1-.1-.1-.1-.2zm1.9-.9c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1c.1 0 .1.1.1.2s0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1c-.1 0-.1-.1-.1-.2zm0 .9c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1c-.1-.1-.1-.1-.1-.2zM6.6 36.2h.6v.2H5.8v-.2h.6v-1H6V35h.6v1.2zm-.3-1.7v-.2h.2v.4c0 .1-.1 0-.1 0h-.1v-.2zm2.6 1.3v-.1h.2V36.5H7.5v-.2H7.8v-1.4h-.2v-.2h1v.2h-.5v1.4h.8v-.5zm.7.6h-.2v-.2H9.7v-1.4h-.2v-.2H11v.6h-.2v-.4h-.9v.5h.4v-.2h.2v.5h-.2v-.2h-.4v.7h.8v-.4h.2v.6h-.1l-1.2.1zm2.2-1c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.2.1-.3.2-.4s.3-.2.4-.2c.2 0 .3.1.4.2s.2.2.2.4c0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4s-.3.2-.5.2-.3-.1-.5-.2-.2-.2-.2-.4c.2-.2.3-.4.5-.5zm-.1.5c0 .1 0 .2.1.3s.2.1.3.1.2 0 .3-.1.1-.2.1-.3c0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .1-.1.2-.1.3zm.1-.9c0 .1 0 .2.1.2s.2.1.3.1c.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1-.1.1-.2.2-.1.3zm1.9.4c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.1.1-.3.2-.4.1-.1.3-.2.4-.2.2 0 .3.1.4.2s.2.2.2.4c0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4s-.3.2-.5.2-.3-.1-.5-.2-.2-.2-.2-.4c.2-.2.3-.4.5-.5zm-.1.5c0 .1 0 .2.1.3.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .1-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2s.2.1.3.1c.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1s-.2 0-.3.1c0 .1-.1.2-.1.3zm1.9 1.4h-.4v-.2h.1v-1.4h-.1v-.2h.7c.3 0 .5.1.6.2.2.2.2.4.2.7 0 .1 0 .3-.1.4 0 .1-.1.2-.2.3-.1.1-.2.1-.3.2-.1 0-.3.1-.4.1h-.1c.1-.1 0-.1 0-.1zm0-.2h.2c.3 0 .4-.1.6-.2.1-.1.2-.3.2-.5s-.1-.4-.2-.5c-.1-.1-.3-.2-.6-.2h-.2v1.4zm2.7.1v.3c0 .1 0 .1-.1.2l-.2.2c-.1 0-.2.1-.4.1h-.3c-.1 0-.1-.1-.1-.1v-.1H17.4c.1 0 .3 0 .3-.1.1-.1.1-.2.1-.4v-1.1H17v-.2h1l.2 1.2zm-.4-1.8v-.2h.2v.4h-.2v-.2zm1.5 1.6c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1c0 0-.1-.1-.1-.2zm5.7-.8c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1c-.1-.1-.1-.1-.1-.2zm0 .8c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1c-.1 0-.1-.1-.1-.2zm2.7.2v.3c0 .1 0 .1-.1.2l-.2.2c-.1 0-.2.1-.4.1h-.3c-.1 0-.1-.1-.1-.1v-.1H26.9c.1 0 .3 0 .3-.1.1-.1.1-.2.1-.4v-1.1h-.8v-.2h1c.2-.1.2 1.2.2 1.2zm-.5-1.8v-.2h.2v.4h-.2v-.2zm1.5 1.9h-.4v-.2h.1v-1.4h-.1v-.2h.7c.3 0 .5.1.6.2.2.2.2.4.2.7 0 .1 0 .3-.1.4 0 .1-.1.2-.2.3-.1.1-.2.1-.3.2-.1 0-.3.1-.4.1h-.1c.1-.1 0-.1 0-.1zm0-.2h.2c.3 0 .4-.1.6-.2.1-.1.2-.3.2-.5s-.1-.4-.2-.5c-.1-.1-.3-.2-.6-.2h-.2v1.4zm1.9-.8c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.2.1-.3.2-.4s.3-.2.4-.2c.2 0 .3.1.4.2.1.1.2.2.2.4 0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4-.1.1-.3.2-.5.2s-.3-.1-.5-.2c-.1-.1-.2-.3-.2-.4l.5-.5zm0 .5c0 .1 0 .2.1.3.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1-.1.1-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1-.1.1-.1.2-.1.3zm1.9.4c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.2.1-.3.2-.4s.3-.2.4-.2c.2 0 .3.1.4.2.1.1.2.2.2.4 0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4-.1.1-.3.2-.5.2s-.3-.1-.5-.2c-.1-.1-.2-.3-.2-.4.2-.2.3-.4.5-.5zm0 .5c0 .1 0 .2.1.3.1.1.2.1.3.1.1 0 .2 0 .3-.1s.1-.2.1-.3c0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1-.1.1-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2s.2.1.3.1c.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1-.1.1-.1.2-.1.3zm1.9.4c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.1.1-.3.2-.4.1-.1.3-.2.4-.2.2 0 .3.1.4.2s.2.2.2.4c0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4-.1.1-.3.2-.5.2s-.3-.1-.5-.2c-.1-.1-.2-.3-.2-.4.2-.2.3-.4.5-.5zm-.1.5c0 .1 0 .2.1.3s.2.1.3.1.2 0 .3-.1.1-.2.1-.3c0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .1-.1.2-.1.3zm.1-.9c0 .1 0 .2.1.2.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1s-.2 0-.3.1c-.1.1-.1.2-.1.3zm1.9.4c-.1 0-.2-.1-.2-.2-.1-.1-.1-.1-.1-.2s.1-.3.2-.4c.1-.1.3-.2.4-.2.2 0 .3.1.4.2.1.1.2.2.2.4 0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4s-.3.2-.5.2-.3-.1-.5-.2 0-.4 0-.5c0-.2.1-.4.3-.5zm-.1.5c0 .1 0 .2.1.3.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .1-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2s.2.1.3.1c.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .1-.1.2-.1.3zm2 .4c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.2.1-.3.2-.4s.3-.2.4-.2c.2 0 .3.1.4.2.1.1.2.2.2.4 0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4-.1.1-.3.2-.5.2s-.3-.1-.5-.2c-.1-.1-.2-.3-.2-.4.2-.2.3-.4.5-.5zm-.1.5c0 .1 0 .2.1.3.1.1.2.1.3.1.1 0 .2 0 .3-.1s.1-.2.1-.3c0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .1-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .1-.1.2-.1.3zm1.9 1.4h-.4v-.2h.1v-1.4h-.1v-.2h.7c.3 0 .5.1.6.2.2.2.2.4.2.7 0 .1 0 .3-.1.4 0 .1-.1.2-.2.3-.1.1-.2.1-.3.2-.1 0-.3.1-.4.1H40c.1-.1 0-.1 0-.1zm0-.2h.2c.3 0 .4-.1.6-.2.1-.1.2-.3.2-.5s-.1-.4-.2-.5c-.1-.1-.3-.2-.6-.2H40v1.4zm2.7.1v.3c0 .1 0 .1-.1.2l-.2.2h-.7c-.1 0-.1-.1-.1-.1v-.1H41.9c.1 0 .3 0 .3-.1.1-.1.1-.2.1-.4v-1.1h-.8V35h1v1.3zm-.4-1.8v-.2h.2v.4h-.2v-.2zm1.5.8c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1-.1-.1-.1-.2zm0 .8c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2-.1.1-.2.1-.2 0-.2-.1-.1-.1-.1-.2zM2.4 39.9c0-.1 0-.1.1-.2s.1-.1.2-.1.2 0 .2.1.1.1.1.2 0 .1-.1.2c-.1 0-.1.1-.2.1s-.2 0-.2-.1-.1-.1-.1-.2zm2.7-.4v-.1h.2V40.2H3.7V40H4v-1.4h-.2v-.2h1v.2h-.5V40h.8v-.5zm1.8.4v-.4h-.4v-.2H7.4c.1 0 0 0 0 .1v.1h-.1v.6c-.1 0-.2.1-.3.1h-.3c-.3 0-.5-.1-.7-.3s-.3-.4-.3-.7c0-.3.1-.5.2-.7.2-.2.4-.3.6-.3h.2c.1 0 .1 0 .2.1v-.1h.2v.5H7c-.1 0-.1 0-.1-.1-.1-.2-.2-.3-.4-.3s-.3.1-.4.2c-.1.3-.2.5-.2.7 0 .2.1.4.2.6.1.1.3.2.5.2h.2l.1-.1zm1.6.1h.6v.2H7.7V40h.6v-1h-.5v-.2h.6c.1 0 .1 1.2.1 1.2zm-.3-1.7v-.2h.2v.4c0 .1-.1 0-.1 0h-.1v-.2zm2.4.5h.1v.2H10v.5c0 .2 0 .3.1.3s.1.1.2.1.2 0 .3-.1c.1 0 .2-.1.2-.1h.1v.2s-.1 0-.1.1c-.1 0-.2.1-.3.1h-.2c-.1 0-.2 0-.3-.1 0 .1-.1 0-.1 0v-.9h-.5v-.2h.4v-.5h.2v.5l.6-.1zm.9 1.4h-.2c-.1 0 0 0 0-.1V40H11.6v-1.4h-.2v-.2H12.9v.6h-.2v-.4h-.8v.5h.4v-.2h.2v.5h-.2v-.2h-.4v.7h.8v-.4h.2v.6h-.1l-1.3.1zm2.2-1c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.1.1-.3.2-.4.1-.1.3-.2.4-.2.2 0 .3.1.4.2.1.1.2.2.2.4 0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4s-.3.2-.5.2-.3-.1-.5-.2-.2-.2-.2-.4c.2-.3.3-.5.5-.5zm-.1.4c0 .1 0 .2.1.3.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1 0 .2-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2s.2.1.3.1c.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2s-.2-.1-.3-.1-.2 0-.3.1-.1.2-.1.3zm2 .5c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.1.1-.3.2-.4.1-.1.3-.2.4-.2.2 0 .3.1.4.2.1.1.2.2.2.4 0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4-.1.1-.3.2-.5.2s-.3-.1-.5-.2-.2-.2-.2-.4c.1-.3.3-.5.5-.5zm-.1.4c0 .1 0 .2.1.3s.2.1.3.1c.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.3-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1-.1.2-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2s.2.1.3.1c.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.2-.1-.1-.2-.1-.3-.1-.1 0-.2 0-.3.1s-.1.2-.1.3zm2 .5c-.1 0-.2-.1-.2-.2-.1-.1-.1-.2-.1-.3 0-.1.1-.3.2-.4.1-.1.3-.2.4-.2.2 0 .3.1.4.2.1.1.2.2.2.4 0 .1 0 .2-.1.3l-.2.2c.1 0 .2.1.2.2.1.1.1.2.1.3 0 .2-.1.3-.2.4-.1.1-.3.2-.5.2s-.3-.1-.5-.2c-.1-.1-.2-.3-.2-.4.1-.3.3-.5.5-.5zm-.1.4c0 .1 0 .2.1.3.1.1.2.1.3.1.1 0 .2 0 .3-.1.1-.1.1-.2.1-.3 0-.1 0-.2-.1-.3s-.2-.1-.3-.1c-.1 0-.2 0-.3.1s-.1.2-.1.3zm0-.9c0 .1 0 .2.1.2. [...]

2023-01-09 23:39 UTC, lunatic-fox commented
Hello there!

I think we can preserve the `original` and `original-wordmark` as it is and create a `plain` and `plain-wordmark` to use them as font.

My idea is to do a filled `η` like their favicon as `plain` version and `η GNU nano` as the `plain-wordmark` the same way.
![](https://nano-editor.org/favicon.ico)

Some topics:
- `original` work as a font character, but it's size is 126kB.
- Old `original-wordmark` "blocks" the font build, making all icons unable to be displayed.
- New `original-wordmark` doesn't show up, but the font build runs fine.

Some smoothing happened in the new `original-wordmark`, but the file yet to big (181kB) to be rendered properly as a font character.

I'll be very busy this month, so if this idea is ok, it'll be really great if you can make it. Otherwise, I'll be doing that as soon as possible. 🤩

2023-01-27 14:33 UTC, Snailedlt commented
@lunatic-fox I think the idea is good. Not ideal, but it's better than a crashing fontset.
Looks like you'll be the one to implement this, so let me know if you need any help with it, and ofc set me up as reviewer when the time comes :)

2023-01-27 23:25 UTC, lunatic-fox commented
Hello there!
Here are some options.

|Solid|Solid wordmark|
|:-:|:-:|
|<img width="256" src="https://user-images.githubusercontent.com/76992016/215223832-25a83a1e-d6db-4cff-b66f-4412cf4c7a4c.svg"/>|<img width="256" src="https://user-images.githubusercontent.com/76992016/215223837-f95d4d3c-e150-40a4-8ce2-6badd20df810.svg"/>|

|Striped|Striped wordmark|
|:-:|:-:|
|<img width="256" src="https://user-images.githubusercontent.com/76992016/215223841-feb8319c-8a8f-4dd5-94dc-d3faf85b8987.svg"/>|<img width="256" src="https://user-images.githubusercontent.com/76992016/215223844-7c0e13c1-d5ae-40db-9812-e4fe952163e5.svg"/>|

2023-01-29 15:40 UTC, Snailedlt commented
@lunatic-fox Both look good! I think the striped ones look better, but feel free to choose the one you like best here :)

2023-02-03 11:20 UTC, lunatic-fox approved these changes

2023-02-03 17:39 UTC, Snailedlt approved these changes
LGTM! ✔️ 
Thank you for making the issue and PR @ConX and thank you for updating the plain icons @lunatic-fox

2023-02-03 17:41 UTC, merged