new icon: windows11 (original, original-wordmark)
devicons/devicon pull request #1621
Opened 2023-01-09 07:42 UTC by PantheraRed

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes https://github.com/devicons/devicon/issues/800**

## Link to prove your SVG is correct and up-to-date.

https://en.wikipedia.org/wiki/Windows_11#/media/File:Windows_11_logo.svg

2023-01-09 07:44 UTC, PantheraRed commented
Opening a new pr in reference to https://github.com/devicons/devicon/pull/822.

2023-02-08 21:50 UTC, Panquesito7 requested changes
Please fix the issues mentioned by the `check-bot` workflow.
Let us know if you need any help with that. 🙂

2023-02-08 21:58 UTC, PantheraRed commented
Sorry @Panquesito7. I completely missed this and placed windows11 after windows8.
![image](https://user-images.githubusercontent.com/41539361/217660548-62a5b608-e894-436e-9ac1-f87f09e747d8.png)

2023-02-09 00:52 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            },
            {
                "base": "original-wordmark",
                "alias": "plain-wordmark"
            }
        ]
```

2023-02-09 20:17 UTC, Panquesito7 approved these changes
Awesome. Thanks! 🚀

2023-02-09 22:09 UTC, Snailedlt approved these changes
LGTM! :heavy_check_mark: 
Thank you for another great contribution @PantheraRed :rocket:

2023-02-09 22:10 UTC, merged