new icon: pnpm (original, plain)
devicons/devicon pull request #1666
Opened 2023-02-04 15:15 UTC by felipesuri

## Double-check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1068**

## Link to prove your SVG is correct and up-to-date.

[PNPM Logos](https://pnpm.io/logos)

Note: I just added the original without a wordmark because the width of 128 cannot work perfectly and it is my first PR, so I don't know how to do that. If someone can help me, I can add the wordmark.

2023-02-07 07:09 UTC, Panquesito7 commented
Hmm. I'm not sure if there's a way to use the official wordmark logo with 128x128 size.
@devicons/supporter, thoughts on this?

2023-02-07 18:15 UTC, Snailedlt commented
@Panquesito7 Can't we just remove the height and width attributes and resize it using the tools explained in our "[Recommended resources and tools](https://github.com/devicons/devicon/wiki/Recommended-resources-and-tools)" wiki page?

2023-03-06 10:17 UTC, Snailedlt requested changes

2023-03-06 10:17 UTC, Snailedlt commented on icons/pnpm/pnpm-plain.svg
> +<svg width="128" height="128" viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg">
Remove height and width attributes 
```suggestion
<svg viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg">
```

2023-03-06 10:17 UTC, Snailedlt commented on icons/pnpm/pnpm-plain-wordmark.svg
> +<svg width="128" height="366" viewBox="0 0 128 366" fill="none" xmlns="http://www.w3.org/2000/svg">
Remove height and width attributes, and fix viewbox
```suggestion
<svg viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg">
```

2023-03-06 10:17 UTC, Snailedlt commented on icons/pnpm/pnpm-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128px" height="128px" viewBox="0 0 128 128" version="1.1">
Remove height and width attributes
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 128 128" version="1.1">
```

2023-03-06 10:17 UTC, Snailedlt commented on icons/pnpm/pnpm-original-wordmark.svg
> +<svg width="128" height="366" viewBox="0 0 128 366" fill="none" xmlns="http://www.w3.org/2000/svg">
Remove height and width attributes
```suggestion
<svg viewBox="0 0 128 366" fill="none" xmlns="http://www.w3.org/2000/svg">
```

2023-03-06 10:17 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": [
            "performant npm"
        ],
```

2023-03-06 10:18 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
https://pnpm.io/faq#what-does-pnpm-stand-for

2023-03-15 20:51 UTC, Snailedlt requested changes
We're getting there 🚀 
Now we just need to: 
- [ ] resize and center `pnpm-original-wordmark.svg`
- [ ] center and unite paths for `pnpm-plain-wordmark.svg`
- [ ] unite paths for `pnpm-plain.svg`

2023-03-15 20:51 UTC, Snailedlt commented on icons/pnpm/pnpm-plain-wordmark.svg
Whoopsie, where is the icon?
![image](https://user-images.githubusercontent.com/43886029/225437079-81bae939-ab66-42f5-8f77-1d86fcd44eee.png)

Remember that you need to re-center the icon after resizing. You can do it in Inkscape by following this guide: https://github.com/devicons/devicon/issues/1306#issuecomment-1296051881

Once you've done that you'll need to unite the paths, since this is a plain icon. To do that see this guide for how to unite paths: https://github.com/devicons/devicon/issues/1306#issuecomment-1296014473

2023-03-15 20:51 UTC, Snailedlt commented on icons/pnpm/pnpm-original.svg
Looks good ✔️

2023-03-15 20:51 UTC, Snailedlt commented on icons/pnpm/pnpm-plain.svg
> +</svg>
Looks good visually, but the paths need to be unified for plain and line icons.
See this guide for how to unite paths: https://github.com/devicons/devicon/issues/1306#issuecomment-1296014473

2023-03-15 20:51 UTC, Snailedlt commented on icons/pnpm/pnpm-original-wordmark.svg
This icon still needs to be resized and centered
![image](https://user-images.githubusercontent.com/43886029/225438675-6f901995-958b-4922-9a99-7dc481028901.png)
You can do it in Inkscape by following this guide: https://github.com/devicons/devicon/issues/1306#issuecomment-1296051881

2023-04-09 19:09 UTC, Panquesito7 approved these changes
Looks good! Thanks. 🚀

2023-04-21 15:40 UTC, Snailedlt requested changes
Great job so far. Only thing left to fix now is the unrelated changes in devicon.json (see comments below) :)

2023-04-21 15:40 UTC, Snailedlt commented on devicon.json
> +            ]
These lines should be changed in a separate PR, since they have nothing to do with the pnpm icon

2023-04-21 15:40 UTC, Snailedlt commented on devicon.json
> +            }
Same with these lines

2023-04-21 18:10 UTC, lunatic-fox commented on devicon.json
> +            ]
Right! Let's try this.
```suggestion
          "svg": [
              "original",
              "original-wordmark",
              "plain",
              "plain-wordmark"
          ],
          "font": [
              "plain",
              "plain-wordmark"
          ]
```

2023-04-21 18:12 UTC, lunatic-fox commented on devicon.json
> +            }
And this.
```suggestion
          {
            "base": "original",
            "alias": "plain"
          }
```

2023-04-22 13:18 UTC, Snailedlt approved these changes
Looks good now! :heavy_check_mark: 
Thank you @felipesuri for the contribution, and thank you @lunatic-fox for the quick fix :100:

2023-04-24 17:59 UTC, lunatic-fox approved these changes

2023-04-24 20:00 UTC, merged