new icon: Pypi (original,original-wordmark)
devicons/devicon pull request #1697
Opened 2023-03-07 09:20 UTC by yeyeto2788

## Double check these details before you open a PR

- [X] PR does not match another non-stale PR currently opened
- [X] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [X] PR's base is the `develop` branch.
- [X] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [X] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [X] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #922**

## Link to prove your SVG is correct and up-to-date.

2023-03-07 09:21 UTC, yeyeto2788 commented
Sorry for the delay on this one guys! My bad. If there is anything I need to change or add let me know.

2023-03-07 11:08 UTC, Snailedlt requested changes
There's a few things that need to be changed, so I'll give a brief overview here. 
Read each comment for more info.

Some things that need to be fixed:
1. Move `devicon.json` object to correct line, so that the file is alphabetically sorted
1. Add altnames in `devicon.json`
1. Change to correct color in `devicon.json`
1. Remove *TM* from original-wordmark
1. Resize both icons to `viewbox="0 0 128 128"`

Optional (recommended):
1. Add `plain` and `plain-wordmark` versions
1. Add `line` and `line-wordmark` versions

2023-03-07 11:38 UTC, yeyeto2788 commented on icons/pypi/pypi-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 112"><path fill="#e9e9ff" stroke="#ccc" stroke-linejoin="bevel" stroke-width=".073" d="m-186.329 59.726 3.185 1.16v3.743l-3.185-1.16Zm0 0" tra
The icon is not squared so the viewbox should be different right? I mean, the lead should be in the `width` having something like `0 0 128 112` or something similar right?

2023-03-07 11:56 UTC, Snailedlt commented on icons/pypi/pypi-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 112"><path fill="#e9e9ff" stroke="#ccc" stroke-linejoin="bevel" stroke-width=".073" d="m-186.329 59.726 3.185 1.16v3.743l-3.185-1.16Zm0 0" tra
No the viewbox should be the same, the icon just won't fill the entire viewbox :)

2023-03-07 11:58 UTC, Snailedlt commented on icons/pypi/pypi-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 112"><path fill="#e9e9ff" stroke="#ccc" stroke-linejoin="bevel" stroke-width=".073" d="m-186.329 59.726 3.185 1.16v3.743l-3.185-1.16Zm0 0" tra
Just make sure the icon is centered in the viewbox

2023-03-07 12:10 UTC, yeyeto2788 commented on icons/pypi/pypi-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 112"><path fill="#e9e9ff" stroke="#ccc" stroke-linejoin="bevel" stroke-width=".073" d="m-186.329 59.726 3.185 1.16v3.743l-3.185-1.16Zm0 0" tra
Ohhhh got it then. I thought that was the actual dimensions of the icons. Changed applied.

2023-03-07 12:45 UTC, Snailedlt commented on icons/pypi/pypi-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 112"><path fill="#e9e9ff" stroke="#ccc" stroke-linejoin="bevel" stroke-width=".073" d="m-186.329 59.726 3.185 1.16v3.743l-3.185-1.16Zm0 0" tra
Nice, now you just need to center them vertically, and remove the horizontal padding
![image](https://user-images.githubusercontent.com/43886029/223425800-1700b878-b404-4cf3-851f-3f55d7b2040e.png)

2023-03-07 12:49 UTC, Snailedlt commented on devicon.json
> +            ]
@yeyeto2788 Seems like you need to have plain icons. To make them, just duplicate the original versions then do the following:
1. Unify paths
2. Remove the `fill` attribute

I also recommend making a line icon. See this guide for how to make one: https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294

2023-04-09 19:06 UTC, Panquesito7 commented on devicon.json
> +            "python"
```suggestion
            "python",
            "package",
            "programming"
```

2023-04-09 19:07 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-04-21 15:22 UTC, Snailedlt approved these changes
Great work fixing all of the issues in one go 💯
Thank you for the contribution! ✔️

2023-04-28 16:28 UTC, merged