new icon: thymeleaf (original)
devicons/devicon pull request #1705
Opened 2023-03-16 23:11 UTC by ruubytes

## Double check these details before you open a PR

- [X] PR does not match another non-stale PR currently opened
- [X] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [X] PR's base is the `develop` branch.
- [X] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [X] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [X] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1657**

## Link to prove your SVG is correct and up-to-date.

<a href="https://www.thymeleaf.org/">
<img src="https://www.thymeleaf.org/images/thymeleaf.png" width="128" height="128" />
</a

2023-03-17 14:19 UTC, Snailedlt requested changes
Looks good to me, but a plain or line icon is needed since `thymeleaf-original.svg` can not be used as a font, due to multiple paths and fill colors.

If you want to make a line icon, you can follow this guide: https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294

Regardless if you choose plain or line, make sure it meets our [SVG Standards](https://github.com/devicons/devicon/wiki/SVG-Standards). 

If you want more info on the different SVG versions we use (e.g.) original, plain, line), you can read our [SVG Versions](https://github.com/devicons/devicon/wiki/SVG-Versions) wiki page.

2023-03-17 14:21 UTC, ruubytes commented
aye aye captain

2023-03-17 15:46 UTC, Snailedlt submitted a review, later dismissed
Wow, that was fast. Looks like "font" is the only thing missing

2023-03-17 15:46 UTC, Snailedlt commented on devicon.json
> +            ]
```suggestion
            ],
            "font": [
                "plain"
            ]
```

2023-03-17 16:25 UTC, ruubytes commented
It didn't stop at the svgo-action, but the git auto commit action, what happened?

2023-03-20 18:53 UTC, Snailedlt commented
@ruubytes Yeah, it's a known issue with the workflow -> #1715. Hopefully we can get around to fixing it soon, until the, you can safely ignore the Optimize Icons workflow entirely

2023-03-23 06:44 UTC, lunatic-fox approved these changes
Great work! ✔
Thank you for this contribution! 🚀

2023-04-06 03:31 UTC, Panquesito7 submitted a review, later dismissed
Looks like there's a wordmark version for this logo (found it in their [downloads](https://www.thymeleaf.org/download.html) page). It'd be great if you could add those as well. 🙂
The other icons look great by the way. Thanks! 🚀

2023-04-06 08:50 UTC, Snailedlt commented
Here's all the official svg logos: https://github.com/thymeleaf/thymeleaf-org/blob/main/artwork/thymeleaf%202016/thymeleaf.svg

2023-11-05 16:58 UTC, lunatic-fox approved these changes
I think that everything is ok right now. ✔️
Thank you by this contribution! 🚀
![image](https://github.com/devicons/devicon/assets/76992016/1d8ef243-100d-4bf3-95a1-6d8d175bdb3f)
![image](https://github.com/devicons/devicon/assets/76992016/3b7c5aa5-6b74-468e-b642-295cf5b97f48)

2023-11-05 16:59 UTC, lunatic-fox approved these changes

2024-05-05 23:42 UTC, canaleal approved these changes

2024-05-06 00:01 UTC, merged