new icon: vitess (original, plain)
devicons/devicon pull request #1720
Opened 2023-04-02 05:15 UTC by AbdelrahmanDwedar

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

[the image used in their website source code](https://github.com/vitessio/website/blob/1a3cb3f8ac33568da8742e40d8354fa0e7daef65/wip-docs/images/vitess_logo.svg)

2023-04-02 05:27 UTC, AbdelrahmanDwedar commented
I forgot what are the options to use in SVGO. When someone check this PR can you tell me the needed options?

2023-04-03 15:23 UTC, AbdelrahmanDwedar commented
I did the optimization with SVGO but still there's a CI error. When someone checkout this PR can you tell me what did I miss?

2023-04-03 17:44 UTC, Snailedlt commented
> I did the optimization with SVGO but still there's a CI error. When someone checkout this PR can you tell me what did I miss?

The workflow that failed is not your fault. It's because it doesn't have access to your fork, so it fails. We're looking into it :)

2023-04-04 13:28 UTC, AbdelrahmanDwedar commented
> > I did the optimization with SVGO but still there's a CI error. When someone checkout this PR can you tell me what did I miss?
> 
> The workflow that failed is not your fault. It's because it doesn't have access to your fork, so it fails. We're looking into it :)

Oh, alright no worries 👌🏼
I'll wait till you guys solve it.

2023-04-08 12:15 UTC, lunatic-fox commented on icons/vitess/vitess-plain.svg
This icon version needs to be ungrouped and with only one path. Here's a suggestion:
<img width="256" src="https://user-images.githubusercontent.com/76992016/230720253-0b371271-a407-4a42-98e7-9220011d08f1.svg">

Once this this icon will be used as `font` the colors will be added by `devicon.json` `color` property.

2023-04-28 18:53 UTC, lunatic-fox commented on devicon.json
> +	{
```suggestion
    {
```

2023-04-28 18:59 UTC, lunatic-fox commented
![vitess](https://user-images.githubusercontent.com/76992016/235231040-ab11646b-974c-40e6-b1cb-06beee7d1262.png)

2023-04-28 19:22 UTC, Panquesito7 requested changes
It appears there are also `wordmark` versions.
It'd be great if you could add those to the list as well. 🙂

https://cncf-branding.netlify.app/projects/vitess/

2023-04-28 21:52 UTC, AbdelrahmanDwedar commented
I'll try to do all that stuff tomorrow, sorry I'm in a exams time so I'll not be as active.

2023-05-16 18:52 UTC, Snailedlt commented
@AbdelrahmanDwedar Good luck with your exams if you still have some upcoming :)
Let us know if you need any help with this PR

2023-05-18 21:43 UTC, AbdelrahmanDwedar commented
> It appears there are also `wordmark` versions. It'd be great if you could add those to the list as well. slightly_smiling_face
> 
> https://cncf-branding.netlify.app/projects/vitess/

This link breaks for me, but I found another one here
https://www.vectorlogo.zone/logos/vitessio/vitessio-ar21.svg

2023-05-20 01:19 UTC, Panquesito7 requested changes
The filename for the wordmark version should be `original-wordmark`.
It'd be great if you could add `plain-wordmark` as well.

If you need any help, let us know. 🙂

2023-05-20 02:25 UTC, AbdelrahmanDwedar commented
I think this will work.

2023-05-21 20:39 UTC, Panquesito7 requested changes

2023-05-21 20:39 UTC, Panquesito7 commented on devicon.json
> +                "plain"
```suggestion
                "original",
                "original-wordmark",
                "plain",
                "plain-wordmark"
```

2023-05-21 20:39 UTC, Panquesito7 commented on devicon.json
> +                "plain"
```suggestion
                "plain",
                "plain-wordmark"
```

2023-05-21 23:01 UTC, lunatic-fox requested changes

2023-05-22 23:21 UTC, lunatic-fox commented
Color `#f16827` will be added by `color` property of `devicon.json`.
![](https://github.com/devicons/devicon/assets/76992016/df2d3667-9952-4ac4-ae2e-864e034474ea)
![](https://github.com/devicons/devicon/assets/76992016/50351783-1e90-467e-ac88-ea554c1d7b89)

2023-05-22 23:24 UTC, lunatic-fox approved these changes
Great work! ✔
Thank you for this contribution! 🚀

2023-05-23 02:47 UTC, Panquesito7 approved these changes

2023-05-23 02:52 UTC, merged