new icon: tRPC (original, original-wordmark)
devicons/devicon pull request #1742
Opened 2023-04-24 00:14 UTC by sinuheshinbr

## Double check these details before you open a PR

- [X] PR does not match another non-stale PR currently opened
- [X] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [X] PR's base is the `develop` branch.
- [X] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [X] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [X] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1732**

## Link to prove your SVG is correct and up-to-date.
https://trpc.io/

2023-04-25 17:52 UTC, lunatic-fox requested changes
Hello there! 👋🏼
The icons are pretty good, but they are different from the official logos, please consider to use the listed below to base the new icons.

`original`
<table align="center">
  <tr>
    <td>
      <img width="128" src="https://raw.githubusercontent.com/trpc/trpc/63daaab739e0eb2d330a977c50d823a66dd2038f/www/static/img/logo.svg">
    </td>
  </tr>
</table>



`original-wordmark`
<table align="center">
  <tr>
    <td>
      <img width="128" src="https://raw.githubusercontent.com/trpc/trpc/235b8d5b8f2877878aee55fab0116e9970176f49/www/static/img/logo-text-black.svg">
    </td>
    <td>
       <img width="128" src="https://raw.githubusercontent.com/trpc/trpc/235b8d5b8f2877878aee55fab0116e9970176f49/www/static/img/logo-text-white.svg">
    </td>
  </tr>
</table>

> *Remember to choose only one `original-wordmark` version.*

With this change `plain` and `plain-wordmark` will need to be new monocolor icons.

In `devicon.json` the `versions` property should be like:
```json
        "versions": {
            "svg": [
                "original",
                "original-wordmark",
                "plain",
                "plain-wordmark"
            ],
            "font": [
                "plain",
                "plain-wordmark"
            ]
        },
```

2023-04-25 19:48 UTC, lunatic-fox commented
Thank you for the fast response! 🚀

2023-04-26 17:46 UTC, Snailedlt requested changes
Almost there. Just a few suggestions :)

2023-04-26 17:46 UTC, Snailedlt commented on devicon.json
> +        "altnames": [],
```suggestion
        "altnames": [
            "Typescript Remote Procedure Call"
        ],
```

2023-04-26 17:46 UTC, Snailedlt commented on devicon.json
> +            "typescript",
```suggestion
            "typescript",
            "javascript",
```

2023-04-28 16:47 UTC, lunatic-fox commented
Sorry, I made a little mistake on icon name. Fixed!

2023-04-28 18:10 UTC, Panquesito7 commented
It appears the screenshot won't be sent due that the workflow is being taken from the `master` branch, and the workflows are still using the Ubuntu 18.04 image, which is no longer supported in GitHub Actions.
We can manually upload these icons to Icomoon and see the results, though.

https://github.com/devicons/devicon/actions/runs/4832860711

2023-04-28 18:15 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🚀

![image](https://user-images.githubusercontent.com/51391473/235222951-2ff726ce-f88b-4636-b1d1-48f0c736563c.png)
![image](https://user-images.githubusercontent.com/51391473/235223053-cf85f57d-86e1-4797-8763-a9cf35a2519a.png)

P.S.: we will need to make a release ASAP.

2023-04-28 18:16 UTC, lunatic-fox commented
> It appears the screenshot won't be sent due that the workflow is being taken from the `master` branch, and the workflows are still using the Ubuntu 18.04 image, which is no longer supported in GitHub Actions. We can manually upload these icons to Icomoon and see the results, though.
> 
> https://github.com/devicons/devicon/actions/runs/4832860711

Yes, I've make a note on #1731.

2023-04-28 18:38 UTC, lunatic-fox approved these changes
Great work! Everything looks fine! ✔
Thank you for this contribution! 🚀

2023-04-28 19:15 UTC, merged