new icon: grpc (original, plain)
devicons/devicon pull request #1751
Opened 2023-05-03 15:51 UTC by ConX

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

This PR closes #467

## Link to prove your SVG is correct and up-to-date.

https://grpc.io/img/logos/grpc-logo.png

2023-05-03 21:14 UTC, lunatic-fox requested changes
Suggestions based on: https://grpc.io/img/logos/grpc-logo.svg
|`original`|`plain`|
|:-:|:-:|
|<img alt="original" width="256" src="https://user-images.githubusercontent.com/76992016/236047464-b1481290-9be1-44f6-8d22-d2747b5cd6ac.svg"/>|<img alt="original" width="256" src="https://user-images.githubusercontent.com/76992016/236047950-411934bd-99cd-48d3-9fdc-61807aac3dc3.svg"/>|

Changes:
- `original` gradient was preserved
- `plain` based on contrast

2023-05-03 21:14 UTC, lunatic-fox commented on devicon.json
> +            "svg": [
Let's keep changes only to `grpc` entry.
```suggestion
            "svg": [ 
```

2023-05-03 21:14 UTC, lunatic-fox commented on devicon.json
> +        "aliases": []
Same thing here.
```suggestion
        "aliases": []  
```

2023-05-04 02:32 UTC, ConX commented
I updated both based on @lunatic-fox's suggestions.

2023-05-04 07:52 UTC, Snailedlt reviewed
Looks good!
Only got an alt name suggestion, otherwise it's excellent

2023-05-04 18:52 UTC, lunatic-fox requested changes

2023-05-04 18:52 UTC, lunatic-fox commented on devicon.json
> +        "color": "#5FC6C5",
I forgot to suggest this. Maybe we can change the color from `#5FC6C5` to `#00b0ad`, that's the major color of its gradient.
```suggestion
        "color": "#00b0ad",
```

2023-05-16 17:23 UTC, Panquesito7 submitted a review, later dismissed
Looks awesome. Thanks! 🚀

![image](https://github.com/devicons/devicon/assets/51391473/4a5aa7f9-769d-4cff-9000-5437e2f80ae5)
![image](https://github.com/devicons/devicon/assets/51391473/c34705e6-eb2f-432f-a434-4c9c02d4c8be)

2023-05-16 20:51 UTC, lunatic-fox approved these changes
Great! 🚀
Thank you for this contribution and @Panquesito7 for the screenshots! ✔

2023-05-17 05:06 UTC, closed without merging