new icon: reactrouter (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1765
Opened 2023-05-17 19:53 UTC by Gautam25Raj

* Add reactrouter icons

* Update devicon.json

2023-05-20 01:21 UTC, Panquesito7 requested changes

2023-05-20 01:21 UTC, Panquesito7 commented on devicon.json
> +                "original-wordmark"
The font versions should always (or in most cases) be the plain versions.
```suggestion
                "plain",
                "plain-wordmark"
```

2023-05-20 01:21 UTC, Panquesito7 commented on devicon.json
> +        ],
If the alternative name's the same as the name, it shouldn't be added.
```suggestion
        "altnames": [],
```

2023-05-21 20:41 UTC, Panquesito7 requested changes

2023-05-21 20:41 UTC, Panquesito7 commented on devicon.json
> +            "SVG": [
```suggestion
            "svg": [
```

2023-05-22 00:03 UTC, Panquesito7 submitted a review, later dismissed
Thanks! 🚀

![image](https://github.com/devicons/devicon/assets/51391473/a058f8dd-eba6-4165-b63c-863503b2a29c)

![image](https://github.com/devicons/devicon/assets/51391473/ade9fde6-f160-486c-a67e-0f8590ef88f6)

2023-05-22 23:11 UTC, lunatic-fox commented
Just to be extra sure after the modification.
Color `#f44250` will be added by `color` property of `devicon.json`.
![](https://github.com/devicons/devicon/assets/76992016/23e39477-3461-4a48-befa-8a227a54cf7b)
![](https://github.com/devicons/devicon/assets/76992016/343f3a31-0e52-47ad-b773-c4e8e007632b)

2023-05-23 01:51 UTC, Panquesito7 approved these changes

2023-05-23 02:22 UTC, merged