new icon: Kde Neon
devicons/devicon pull request #1774
Opened 2023-05-25 16:06 UTC by dotarjun

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1754 **

## Link to prove your SVG is correct and up-to-date.

https://neon.kde.org/

2023-05-26 16:25 UTC, Panquesito7 requested changes
Please create a `plain` version as well to add it to the font versions.

2023-05-26 16:25 UTC, Panquesito7 commented on devicon.json
> +            "SVG": ["original"],
```suggestion
            "svg": ["original"], 
```

2023-05-26 16:25 UTC, Panquesito7 commented on devicon.json
> +        "color": "#21769a"
```suggestion
        "color": "#21769a",
        "aliases": []
```

2023-05-28 04:36 UTC, dotarjun commented
@Panquesito7  pls check whether the plain svg is good enough

2023-05-29 14:39 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/devicons/devicon/pull/1774/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](https://discord.gg/hScy8KWACQ). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

2023-05-30 00:57 UTC, Panquesito7 requested changes

2023-05-30 00:57 UTC, Panquesito7 commented on devicon.json
> +            "svg": ["original"],
```suggestion
            "svg": [
                "original",
                "plain"
            ], 
```

2023-05-30 00:57 UTC, Panquesito7 commented on devicon.json
> +            "font": ["original"]
```suggestion
            "font": [
                "plain"
            ] 
```

2023-05-30 15:26 UTC, dotarjun reviewed
I think we're ready to merge it 🤞🏻

2023-05-30 16:29 UTC, Panquesito7 requested changes

2023-05-30 16:29 UTC, Panquesito7 commented on devicon.json
> -        "name": "phalcon",
Why was `phalcon` removed?
Or this is a Git diff error? 🤔

2023-05-31 05:41 UTC, dotarjun commented
I'm genuinely confused what happened. Closing this PR and working on this issue from a clean slate.

2023-05-31 05:41 UTC, closed without merging