new icon: framework7 (original,plain)
devicons/devicon pull request #1785
Opened 2023-06-03 05:48 UTC by dotarjun

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

#1776 
## Link to prove your SVG is correct and up-to-date.

https://framework7.io/

2023-06-03 09:14 UTC, Gautam25Raj requested changes

2023-06-03 09:14 UTC, Gautam25Raj commented on icons/framework7/framework-plain.svg
- Use **viewBox="0 0 128 128"** 
- Remove **width="128" height="128"**.

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M.454 64c0-15.383 5.391-29.496 14.367-40.536h98.36L43.017 124.429C18.232 115.699.454 91.941.454 64zm117.94-33.11c5.809 9.659 9.152 20.992 9.152 33.11 0 35.348-28.454 64-63.546 64-4.203 0-8.312-.409-12.289-1.195zM23.199 14.934C34.238 5.614 48.469 0 64 0s29.762 5.613 40.801 14.934z"/></svg>
```

2023-06-03 09:14 UTC, Gautam25Raj commented on icons/framework7/framework-original-wordmark.svg
Replace **viewBox="0 0 560 300"** with **viewBox="0 0 128 128"**  

Refer [SVG Standards](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#svg-standards) for more information.

2023-06-03 09:14 UTC, Gautam25Raj commented on icons/framework7/framework-plain-wordmark.svg
- Replace **viewBox="0 0 1911 1024"** with **viewBox="0 0 128 128"**  
- Remove **width="1911" height="1024"**
- Optimize SVG. Use [SVG Viewer](https://www.svgviewer.dev/)

Refer [SVG Standards](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#svg-standards) for more information.

2023-06-03 16:03 UTC, Gautam25Raj commented
Maybe we don't need this plain version. Both plain and original have single color. What do you think? 🤔

2023-06-03 18:43 UTC, dotarjun commented
agreed

2023-06-04 09:43 UTC, lunatic-fox approved these changes
Icons are great! ✔
Thank you for contributing! 🚀
![](https://github.com/devicons/devicon/assets/76992016/2d868767-3854-49a8-a018-874153308b39)
![](https://github.com/devicons/devicon/assets/76992016/8321a01f-98b9-4592-8b1d-f95069c1e915)

2023-06-04 09:56 UTC, dotarjun reviewed
I keep on missing these minor intricacies haha

2023-06-04 09:58 UTC, Gautam25Raj commented
> I keep on missing these minor intricacies haha

Same for me. 😆

2023-06-04 10:00 UTC, Gautam25Raj approved these changes
Great Contribution. 🚀

2023-06-04 15:12 UTC, Panquesito7 commented on devicon.json
> +            "ios"
```suggestion
            "ios",
            "open-source"
```

2023-06-05 19:00 UTC, Gautam25Raj approved these changes

2023-06-08 06:52 UTC, lunatic-fox approved these changes

2023-06-11 02:39 UTC, Panquesito7 approved these changes
Amazing. Thanks! 🚀

2023-06-11 02:40 UTC, merged