update icon: ubuntu (original, original-wordmark)
devicons/devicon pull request #1794
Opened 2023-06-16 05:35 UTC by Gautam25Raj

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features
Update Icon

**This PR closes #1740**

2023-06-16 21:09 UTC, Panquesito7 requested changes

2023-06-16 21:09 UTC, Panquesito7 commented on devicon.json
>          "aliases": []
Aliases for `plain` and `plain-wordmark` should be added.

2023-06-17 03:45 UTC, Gautam25Raj reviewed
Update devicon.json and SVGs

2023-06-20 21:30 UTC, Panquesito7 requested changes
I think we still need a `plain-wordmark` version, as the `original-wordmark` version has two different colors (black and orange), which cannot be used in font versions.

2023-06-20 21:34 UTC, Gautam25Raj commented
> I think we still need a `plain-wordmark` version, as the `original-wordmark` version has two different colors (black and orange), which cannot be used in font versions.

Okayy, will sure update them.

2023-06-23 12:53 UTC, closed without merging