new icon: miro (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1806
Opened 2023-06-23 13:22 UTC by Gautam25Raj

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1786**

## Link to prove your SVG is correct and up-to-date.

https://miro.com/

2023-07-03 22:15 UTC, Panquesito7 commented on devicon.json
> +            "project-management"
The project seems to be open-source as well (link: <https://github.com/miroapp>).}
```suggestion
            "project-management",
            "open-source"
```

2023-07-04 05:25 UTC, Gautam25Raj reviewed
I guess now everything looks okay

2023-07-04 05:32 UTC, Panquesito7 requested changes
Looks like this bug is still present. Please fix it.
If you need any help, let us know about it. 🙂

![image](https://github.com/devicons/devicon/assets/51391473/d84921d2-a173-4313-b4ef-951e5dac50c2)

2023-07-04 06:18 UTC, Gautam25Raj reviewed
Now they look perfectly fine.

![miro-plain](https://github.com/devicons/devicon/assets/63155224/2b781beb-48dd-40c5-a50c-0a7f1d1bd73d)
![miro-plain-workmark](https://github.com/devicons/devicon/assets/63155224/535819c4-e647-4329-af0f-7bf1f4be5c7d)

2023-07-21 05:29 UTC, Panquesito7 commented
It appears you're right about that. I think we'll have to close this sadly.

2023-10-21 15:29 UTC, Snailedlt commented
@Panquesito7 @lunatic-fox
Miro is mainly used by software developers and UI/UX designers (I've used it extensively myself in professional settings).. The reason we need to discuss Prototyping tools is because a lot of them are too general purpose, but since this is mainly used by developers and designers I believe this tool fits the bill for devicon.

What do you guys think?

2023-10-22 09:36 UTC, Gautam25Raj commented
> @Panquesito7 @lunatic-fox Miro is mainly used by software developers and UI/UX designers (I've used it extensively myself in professional settings).. The reason we need to discuss Prototyping tools is because a lot of them are too general purpose, but since this is mainly used by developers and designers I believe this tool fits the bill for devicon.
> 
> What do you guys think?

We already have Prototyping and designing tool like figma in Devicon and Miro itself is a Realtime Collaborative software used by many developers and designers like us to develop user flow, design and many other tasks.

2025-03-30 04:27 UTC, canaleal commented
Closing this ticket as it has been open for 1 year and 5 months. Feel free to reopen it if needed.

2025-03-30 04:27 UTC, closed without merging