new icon: tableau (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1811
Opened 2023-06-26 15:07 UTC by Gautam25Raj

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1030**

## Link to prove your SVG is correct and up-to-date.

https://www.tableau.com/about/media-download-center
https://cdnl.tblsft.com/sites/default/files/pages/tableau_cmyk_2015.png

2023-07-03 22:16 UTC, Panquesito7 commented on devicon.json
> +            "business intelligence"
Looks like the project is open-source as well: https://github.com/tableau.
```suggestion
            "business intelligence",
            "open-source"
```

2023-07-04 05:32 UTC, Gautam25Raj reviewed
Updated devicon.json

2023-07-04 05:37 UTC, Panquesito7 approved these changes
Awesome work. Thank you! 🚀

![image](https://github.com/devicons/devicon/assets/51391473/cb0c2f5b-cf5a-46ba-8234-3c6580210b4f)

![image](https://github.com/devicons/devicon/assets/51391473/1b409e19-b944-49af-8577-6722e58928e9)

2023-07-04 06:08 UTC, lunatic-fox approved these changes
Great work! ✔️
Thank you for this contribution! 🚀

2023-07-04 06:25 UTC, lunatic-fox requested changes
Should we allow this icon @Panquesito7?
I think this is a case of a CRM tool: [Wiki](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F)

2023-07-21 06:17 UTC, Panquesito7 commented
You're right. The Wiki specifically states "Salesforces", and Tableu appears to be a product from them.
I'll be closing this PR for now. We can still discuss further about the icon addition.

Thank you for your contributions. 🙂

2023-07-21 06:17 UTC, closed without merging