new icons: wolfram (original, original-watermark)
devicons/devicon pull request #1828
Opened 2023-07-13 05:53 UTC by Tarang74

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://company.wolfram.com/press-center/

2023-07-13 06:09 UTC, Tarang74 commented
Includes wolframlanugage icon also

2023-07-13 17:42 UTC, lunatic-fox requested changes
Hello there! 👋
Thank you for contributing with this project!

We need some fixes here.
Accordingly to their site Wolfram is a company and falls under a special case that we do not accept anymore: 
  - [**Wiki - What Icons Do We Accept? - Special Cases**](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F#special-cases-see-this-discussion-for-more-details)

However, Wolfram language works like a service and is allowed as an icon here.

That said you can:
- Remove `wolfram` icons and directory.
- Keep `wolframlanguage` directory and icon.
- Add `original-wordmark`, `plain` and `plain-wordmark` versions of `wolframlanguage`.

Here goes some suggestions of the icons that need to be added:
|`original-wordmark`|`plain`|`plain-wordmark`|
|:-:|:-:|:-:|
|<img width="128" src="https://github.com/devicons/devicon/assets/76992016/f17e36bb-9148-46ff-b06a-c258879afd87">|<img width="128" src="https://github.com/devicons/devicon/assets/76992016/9cdb58c5-4fda-4965-94fc-a8d75a9a9092">|<img width="128" src="https://github.com/devicons/devicon/assets/76992016/1acabd15-276a-4ab7-b5e4-0471312ad618">|

2023-08-10 19:59 UTC, lunatic-fox submitted a review, later dismissed
`wolframlanguage` icons are ok now.
Approved! ✔️
![Screenshot from 2023-08-10 16-56-54](https://github.com/devicons/devicon/assets/76992016/8bfa22a4-d164-4521-b27f-a45ce15fe3bb)
![Screenshot from 2023-08-10 16-57-29](https://github.com/devicons/devicon/assets/76992016/c4d9750d-b6f1-4e7d-8179-fec24cf9b7ca)

2023-08-20 22:35 UTC, Gautam25Raj approved these changes

2023-10-21 15:51 UTC, Snailedlt submitted a review, later dismissed
Everything looks good, but I'm wondering why this is called `wolframlanguage` instead of `wolfram` and having `wolframlanguage` as an altname. Wolfram seems to be the official name, so that is what we should use.
If there is no particular reason, please change to `wolfram`

2023-10-26 17:41 UTC, lunatic-fox commented
> Everything looks good, but I'm wondering why this is called `wolframlanguage` instead of `wolfram` and having `wolframlanguage` as an altname. Wolfram seems to be the official name, so that is what we should use. If there is no particular reason, please change to `wolfram`

Wolfram is a company and Wolfram Language is a service from that company, both share the same first name, but since it seems that are no other service that fits on the scope of Devicons I think it's ok to change it to `wolfram` instead and keep `wolframlanguage` as an altname. 👍🏼

2023-10-30 22:28 UTC, Snailedlt commented
@Tarang74 Let us know if you need any help :)

2023-11-05 17:33 UTC, lunatic-fox submitted a review, later dismissed

2024-05-06 00:59 UTC, canaleal submitted a review, later dismissed

2025-02-16 07:02 UTC, canaleal approved these changes

2025-02-16 07:04 UTC, merged