new icon: ory (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #1885
Opened 2023-10-05 08:41 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1818**

## Link to prove your SVG is correct and up-to-date.

The Ory website uses a darker purple for their icon. I went with the light purple as shown in their github documentation. 

Main Website: https://www.ory.sh/
Github: https://github.com/ory
Assets: https://github.com/ory/docs/tree/master/src/static/img/logos

2023-10-21 14:16 UTC, Snailedlt requested changes
As far as I can see the only thing missing is unifying the paths for both icons

2023-10-21 14:16 UTC, Snailedlt commented on icons/ory/ory-original-wordmark.svg
> +<svg fill="#5528ff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M 15.734375 37.949219 C 10.660156 40.65625 5.390625 43.074219 0.238281 45.65625 C 0.21875 45.664062 0.195312 45.6
Since this is an alias to plain-wordmark it needs to have a unified path

2023-10-21 14:16 UTC, Snailedlt commented on icons/ory/ory-original.svg
> +<svg fill="#5528ff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M 63.984375 13.164062 L 33.75 28.148438 C 33.71875 28.164062 33.679688 28.160156 33.648438 28.140625 C 33.617188
Same goes here. A unified path is needed for all plain icons. Learn more here: https://github.com/devicons/devicon/wiki/SVG-Standards

2023-10-21 23:09 UTC, Snailedlt approved these changes
LGTM! ✔️ 
Thank you for another great contribution! 💯 🙇

2023-10-22 10:59 UTC, ConX approved these changes
LGTM! Thanks @canaleal!

2023-10-22 12:33 UTC, merged