new icon: ngrok (original)
devicons/devicon pull request #1891
Opened 2023-10-07 10:49 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1801**

## Link to prove your SVG is correct and up-to-date.

Website Brand: https://ngrok.com/brand
Github: https://github.com/ngrok

## Notes
The Ngrok website offers a variety of SVG icons, but their preferred one is the blue 'ngrok' icon with the color `#02228e`.
Ngrok does make use of a smaller icon `n` as shown in the brands page, but this is only used for the favicon and literally nowhere else. 

Given the original icon's simplicity and single color, I set the terms plain, plain-wordmark, and original-wordmark as aliases with the base being "original".

2023-10-21 14:29 UTC, Snailedlt requested changes
Paths need to be unified since it's an alias for the plain and plain-wordmark versions.
Excellent use of aliases btw!

2023-10-22 00:23 UTC, Snailedlt submitted a review, later dismissed
LGTM! ✔️ 
Thank you for another great contribution! 💯 🙇

2023-11-09 22:59 UTC, lunatic-fox approved these changes
Great! And perfect use of aliases! 💯
Thank you for this contribution! 🚀

2024-06-17 08:26 UTC, weh approved these changes
LGTM :+1:

2024-06-17 08:59 UTC, merged