update icon: twitter (original, original-wordmark)
devicons/devicon pull request #1912
Opened 2023-10-19 08:26 UTC by Yashh56

### New Twitter icon was added in SVG form          #1890 
altnames was also added in devicon.json

#1909

2023-10-19 14:31 UTC, Snailedlt requested changes
This is still based on the master branch it seems. Notice the conflicts
![image](https://github.com/devicons/devicon/assets/43886029/6d58356e-7ecb-4d80-90c3-82e322ef3f23)

and the updated workflows file:
![image](https://github.com/devicons/devicon/assets/43886029/405e361f-af6b-461e-8f4a-63f06c502427)

2023-10-19 15:05 UTC, Yashh56 commented
How should I resolve this ? I change the base branch to develop

2023-10-19 15:11 UTC, Yashh56 commented
![update altname of twitter (original, original-wordmark) by Yashh56 · Pull Request #1912 · devicons_devicon - Google Chrome 10_19_2023 8_39_10 PM](https://github.com/devicons/devicon/assets/141008488/4dcbc872-b50b-4ec5-8041-f402e24c9fc3)
![update altname of twitter (original, original-wordmark) by Yashh56 · Pull Request #1912 · devicons_devicon - Google Chrome 10_19_2023 8_39_44 PM](https://github.com/devicons/devicon/assets/141008488/7cc34596-6fd7-42db-b716-5a52ab825b34)

2023-10-19 15:13 UTC, Snailedlt commented
You need to either:
1. Remove the commit that's from the master branch
2. Make a new branch based on the develop branch... That is, checkout the develop branch and create a new branch from there: `git checkout develop && git pull && git checkout -b your_branch_name`

2023-10-19 15:35 UTC, Yashh56 commented
@Snailedlt  review this PR

2023-10-19 22:00 UTC, Snailedlt submitted a review, later dismissed
Looking good! Thank you for your contribution! 💯

2023-10-20 13:04 UTC, Yashh56 commented
when will the PR get merged ? @Snailedlt

2023-10-20 15:25 UTC, Snailedlt commented
@Yashh56 when it has at least 2 approvals from the maintainers :)

2023-10-20 15:26 UTC, Snailedlt commented
Looks like the PR still has merge conflicts though

2023-10-20 15:33 UTC, Yashh56 commented
How should I resolve this I want to merge atleast 4 PR till this October end for hacktoberfest :)

2023-10-20 16:01 UTC, Yashh56 commented
Hey Maintainer Please Review this PR :)

2023-10-20 19:09 UTC, Snailedlt approved these changes

2023-10-20 19:10 UTC, Snailedlt commented
Fixed it for you. This PR should count towards your octoberfest now :)

2023-10-21 01:18 UTC, Yashh56 commented
Thanks @Snailedlt   :)

2023-10-21 01:26 UTC, Yashh56 commented
What are these commits which you made ? Is my commit are incompletes ?

2023-10-21 05:47 UTC, EnisMulic approved these changes

2023-10-21 12:37 UTC, Snailedlt commented
Everything is fine, just the PR title that needed to change a bit so that the checks go through. Should be fine now :)

2023-10-24 09:15 UTC, weh requested changes
Just a really minimal change. Thx :+1:

2023-10-24 09:15 UTC, weh commented on icons/twitter/twitter-original.svg
> +<svg width="128" height="128" viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M75.916 54.2 122.542 0h-11.05L71.008 47.06 38.672 0H1.376l48.898 71.164L1.376 128h11.05L55.
`width` and `height` can be removed
```suggestion
<svg viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M75.916 54.2 122.542 0h-11.05L71.008 47.06 38.672 0H1.376l48.898 71.164L1.376 128h11.05L55.18 78.303 89.328 128h37.296L75.913 54.2ZM60.782 71.79l-4.955-7.086-39.42-56.386h16.972L65.19 53.824l4.954 7.086 41.353 59.15h-16.97L60.782 71.793Z" fill="#000" style="stroke-width:.104373"/></svg>

```

2023-10-24 11:41 UTC, weh approved these changes
:+1:

2023-10-24 18:18 UTC, Snailedlt commented on icons/twitter/twitter-original.svg
> +
Remove extra newline (there were two here)
```suggestion
```

2023-10-24 18:23 UTC, merged