New Icon: Forgejo (Original)
devicons/devicon pull request #1926
Opened 2023-10-23 09:29 UTC by Yashh56

### (Hacktobeberfest PR)
PR name matches the format new icon: Icon name (versions separated by a comma). More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)

PR's base is the develop branch.

Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)

SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)

A new object is added in the devicon.json file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

This PR closes #1902

**Link to prove your SVG is correct and up-to-date.**
https://codeberg.org/forgejo/governance/media/branch/main/branding/logo/forgejo.svg

2023-10-23 09:29 UTC, Yashh56 commented
**Hey, Maintainer Please Review This PR !!**

2023-10-23 15:44 UTC, Yashh56 commented
how should I convert the original to plain?  @weh

2023-10-23 16:34 UTC, weh commented
I prefer to use Inkscape for this.
The goal is to "union all paths". you may need to convert some parts using "Object to Path" or "Stroke to Path" and finally mark all elements and use "path/Union"

Followed by
- Resize Page to Content (to remove padding)
- Change the Page format back to square
- Center the Logo
- Resize the image using `Iloveimg`
- Optimize using `Vecta.io`
- re-add the viewBox

That is my preferred workflow. You can find the Links here: https://github.com/devicons/devicon/wiki/Recommended-resources-and-tools

2023-10-23 17:14 UTC, Yashh56 commented
After merging the path it looks like this

![_forgejo-original-wordmark svg - Inkscape 10_23_2023 10_43_22 PM](https://github.com/devicons/devicon/assets/141008488/821c293d-c67e-46d1-85f3-076dd4131f4e)

2023-10-24 01:26 UTC, canaleal commented
Hey @Yashh56 , sorry for the super long comment, but here's the workflow I follow to create new Icons. 

## Resize the SVG and Align Horizontally/ Vertically (Inkscape)

1. Inside Inkscape, select the `File` option from the toolbar and in the dropdown and select `Document properties`.
   
![image](https://github.com/canaleal/devicon-ui/assets/49886351/a837d718-01c2-4b31-a132-13625c8677cc)


2. Inside document properties change the `width` to 128.
3. Change the `height` to 128.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/271af42a-6475-4876-84e4-781b5cc4cfd1)

3. To resize the SVG while maintaining the Aspect Ratio, press `ctrl-a` to select all paths.
4. Right click on the SVG and then select `group` from the dropdown.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/44fe39b4-1fb6-4b41-b2a1-91d3b99e7942)


5. Click the lock icon in the toolbar.
6. Then select the largest of these 2 numbers (width or height) and change the value to 128. This will resize the icon to fit the viewbox. In the example below, the width was changed to 128.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/09e4a071-a4d5-48d4-a1de-3ce9fe295bc0)

    
7. To align the SVG, open the align menu.
8. Then click the center horizontally button.
9. Then click the align vertically button.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/d9b95a3b-a8e1-49c0-84ea-3c09257886af)


10. Right click on the SVG (Make sure all paths are selected using `ctrl-a`) and then select `ungroup` from the dropdown.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/27666c30-947f-4f7a-b6ec-6cdb50128784)

12. You can now save the SVG.
13. Make sure to optimize the SVG prior to making a new PR. You can follow the steps below to optimize the SVG. 

## Unify the Paths and create Plain Icons (Inkscape)
Shout out to @yeyeto2788 and @lunatic-fox for these [steps](https://github.com/devicons/devicon/pull/1468#issuecomment-1290185341). 

1. Load the Icon inside inkscape and press `ctrl-a` to select all paths.
2. Right click on the SVG and select `ungroup` in the menu to ungroup all paths.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/39853416-286d-487f-8f3d-7c65396e2a22)
   
3. Next, click the `Path` option in the toolbar and in the the dropdown select `union` to combine all paths into 1 path.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/219b80e9-c329-4853-b8e4-9f947447a43a)

4. Open the SVG inside your text editor (I use VS Code) and check that only 1 path exists.
5. Next, update the SVG fill to be in hexadecimal format and only use 1 color (The main/ most prominent color from original SVG, black, or white).

![image](https://github.com/devicons/devicon/assets/49886351/f1237fa1-4546-4613-926d-77484eeedd99)


5. You can now save the SVG.
6. Make sure to resize and optimize the SVG prior to making a new PR. You can follow the steps below to optimize the SVG. 


## Why Optimize the SVG (Inkscape)

1. After making the changes and saving the SVG, Inkscape will add a lot of new attributes inside the SVG. These attributes are used when you need to edit the SVGs inside inkscape, but are not required in Devicon and they should be removed.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/ad79212f-b74c-482c-8589-8adde04b0875)


2. To remove the attributes from the SVG, use tools like SVGOMG or SVGViewer to optimize the SVG Code. I prefer using SVGOMG as you only need to select a few options to optimize the SVG.

## Optimizing the SVG using SVGOMG
Shout out to @BenSouchet, all the steps I used were from this [comment](https://github.com/devicons/devicon/issues/1279#issuecomment-1195433256)

1. Copy the full SVG code of the SVG you want to optimize.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/59b640d5-b06d-434b-b3db-972f363e5f4b)
 
2. Go to [SVGOMG](https://jakearchibald.github.io/svgomg/), and on the left side click on `Paste markup`.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/3eadc8cb-7daa-4976-8f21-1b28251b2a5b)

3. Paste the SVG code into the input box.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/a76e687d-233b-47a9-b19e-cadd127413de)
   
4. Now that the SVG has been loaded in the interface, let's start optimizing the SVG using the `Features` menu.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/ac093c5c-6c8a-40ad-ae0a-56ccea992f6e)


5. Disable `Compare gzipped`, enable `Multipass`, and do not touch the `precision slidebar`.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/3111262f-2ca2-469e-b0ba-16a2dec92c9b)

6. Enable **ALL** the features **EXCEPT**:
- Remove xmlns
- Round/rewrite number lists
- Replace duplicate elements with links

![image](https://github.com/canaleal/devicon-ui/assets/49886351/7a6b83cd-8cec-4f74-8e75-8f95a85eb492)
![image](https://github.com/canaleal/devicon-ui/assets/49886351/35d09a87-9cbe-400e-a0b3-3afbe983a908)
![image](https://github.com/canaleal/devicon-ui/assets/49886351/d2545ce7-ef17-4d7b-9075-78a94d88ee47)

7. Click the copy button to copy the SVG code.

![image](https://github.com/canaleal/devicon-ui/assets/49886351/94043ddd-4e19-46ab-b73d-89ced82d4fd6)
 
8. Paste the SVG code inside your SVG file.
10. Add an empty newline at the end of file to ensure compatibility with older Devicon versions. 

![image](https://github.com/canaleal/devicon-ui/assets/49886351/e9a033a3-81db-4c63-89b9-acfc56c883cd)

2023-10-24 02:07 UTC, Yashh56 commented
Hey @canaleal Are these changes correct?

2023-10-24 02:09 UTC, Yashh56 commented
After merging the path I am facing the same issue

![_forgejo-original-wordmark svg - Inkscape 10_23_2023 10_43_22 PM](https://github.com/devicons/devicon/assets/141008488/821c293d-c67e-46d1-85f3-076dd4131f4e)

2023-10-24 03:51 UTC, canaleal commented
Hey @Yashh56, I took a look at the Icon and I see what the problem is. 
The symbol on the left is a stroke, not an object. So when you try to unify all paths together, it gets messed up.

The strokes can be converted into paths by selecting all elements on the page `ctrl-a` and then doing `ctrl + alt + a` or selecting stroke-to-path in the path dropdown.

![image](https://github.com/devicons/devicon/assets/49886351/12cd5a4d-32f4-4514-9582-2e2820b09e1b)

You can still follow the workflow I posted above to optimize, resize, and make plain SVGs. 

## Original SVG Wordmark
Here, I cleaned up the original SVG and converted it to object paths. This can be used to create the plain icons. 

`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 300"><path fill="#f50" d="M91.65 20.65c-39.052 0-71 31.948-71 71v115h27v-115c0-24.46 19.54-44 44-44h23v-27z"/><path fill="#c00" d="M91.65 95.4c-39.052 0-71 31.948-71 71v40.25h27V166.4c0-24.46 19.54-44 44-44h23v-27Z"/><path fill="#f50" d="M126.15 7.15c-14.817 0-27 12.183-27 27s12.183 27 27 27 27-12.183 27-27-12.183-27-27-27zm0 16c6.17 0 11 4.83 11 11s-4.83 11-11 11-11-4.83-11-11 4.83-11 11-11z"/><path fill="#c00" d="M126.15 81.9c-14.817 0-27 12.183-27 27s12.183 27 27 27 27-12.183 27-27-12.183-27-27-27zm0 16c6.17 0 11 4.83 11 11s-4.83 11-11 11-11-4.83-11-11 4.83-11 11-11zm-92 93.25c-14.817 0-27 12.183-27 27s12.183 27 27 27 27-12.183 27-27-12.183-27-27-27zm0 16c6.17 0 11 4.83 11 11s-4.83 11-11 11-11-4.83-11-11 4.83-11 11-11z"/><path fill="#f50" d="M202.327 241.983q-17.68 0-31.734-7.706-13.826-7.934-21.986-21.76-7.934-13.827-7.934-31.507 0-17.907 7.934-31.507 8.16-13.826 21.986-21.533 13.827-7.933 31.734-7.933 17.68 0 31.506 7.933 14.054 7.707 21.987 21.533 7.933 13.6 7.933 31.507 0 17.68-7.933 31.507-7.933 13.826-21.987 21.76-13.826 7.706-31.506 7.706zm0-16.546q12.24 0 21.76-5.44 9.52-5.667 14.96-15.64 5.666-10.2 5.666-23.347 0-13.373-5.666-23.347-5.44-9.973-14.96-15.413-9.52-5.44-21.76-5.44-12.24 0-21.76 5.44-9.52 5.44-15.187 15.413-5.44 9.974-5.44 23.347 0 13.147 5.44 23.347 5.667 9.973 15.187 15.64 9.52 5.44 21.76 5.44zm77.523 15.413V121.17h18.134v32.64l-1.813-7.027q4.986-12.92 16.773-19.72 11.786-7.027 29.24-7.027v18.587q-1.133-.226-2.267-.226-1.133-.227-2.266-.227-17.907 0-28.334 11.107-10.426 10.88-10.426 31.28v60.293zm125.297 45.107c-10.88 0-21.457-1.587-31.733-4.76-10.124-3.022-18.435-7.405-24.933-13.147l9.52-14.733c5.59 4.986 12.466 8.915 20.626 11.786 8.311 2.871 16.925 4.307 25.84 4.307 14.658 0 25.463-3.475 32.414-10.427 6.951-6.8 9.393-17.34 10.426-31.506l2-27.427 2.267-22.213-1.587-22.214 8.72-9.746c11.18 15.476 7.414 50.817 7.414 79.56 0 20.853-5.138 36.115-15.413 45.786-10.276 9.823-25.463 14.734-45.56 14.734zm1.28-49.867c-11.484 0-21.835-2.418-31.053-7.253-9.067-4.987-16.244-11.863-21.533-20.627-5.29-8.764-7.934-18.889-7.934-30.373 0-11.485 2.645-21.534 7.934-30.147 5.289-8.765 12.466-15.565 21.533-20.4 9.218-4.836 19.569-7.254 31.053-7.254 10.427 0 23.796 2.192 32.107 6.574 8.462 4.231 15.187 10.653 20.174 19.266 5.137 8.614 5.706 19.267 5.706 31.96 0 12.845-4.569 23.574-9.706 32.187-4.987 8.614-11.712 15.111-20.174 19.494-8.311 4.382-17.68 6.573-28.106 6.573zm-.186-16.773c8.462 0 15.942-1.738 22.44-5.214 6.498-3.475 11.56-8.31 15.187-14.506 3.777-6.347 5.666-13.6 5.666-21.76 0-8.16-1.889-15.338-5.666-21.534-3.627-6.195-8.69-10.955-15.187-14.28-6.498-3.475-13.978-5.213-22.44-5.213-8.311 0-15.716 1.738-22.214 5.213-6.497 3.325-11.635 8.085-15.413 14.28-3.627 6.196-5.44 13.374-5.44 21.534 0 8.16 1.813 15.413 5.44 21.76 3.778 6.195 8.916 11.03 15.413 14.506 6.497 3.476 13.903 5.214 22.214 5.214zm195.621 66.64c-4.987 0-9.747-.605-14.28-1.814-4.533-1.208-8.311-3.097-11.333-5.666l6.346-14.28c4.685 3.778 10.73 5.666 18.134 5.666 6.044 0 10.653-1.813 13.826-5.44 3.325-3.626 4.987-9.066 4.987-16.32V141.17h19.04v106.933c0 11.636-3.173 20.854-9.52 27.654-6.346 6.8-15.413 10.2-27.2 10.2zm115.47-43.974q-17.68 0-31.733-7.706-13.826-7.934-21.986-21.76-7.934-13.827-7.934-31.507 0-17.907 7.934-31.507 8.16-13.826 21.986-21.533 13.827-7.933 31.734-7.933 17.68 0 31.506 7.933 14.054 7.707 21.987 21.533 7.933 13.6 7.933 31.507 0 17.68-7.933 31.507-7.933 13.826-21.987 21.76-13.826 7.706-31.506 7.706zm0-16.546q12.24 0 21.76-5.44 9.52-5.667 14.96-15.64 5.667-10.2 5.667-23.347 0-13.373-5.666-23.347-5.44-9.973-14.96-15.413-9.52-5.44-21.76-5.44-12.24 0-21.76 5.44-9.52 5.44-15.187 15.413-5.44 9.974-5.44 23.347 0 13.147 5.44 23.347 5.667 9.973 15.187 15.64 9.52 5.44 21.76 5.44zm-170.194 16.81q-18.813 0-33.32-7.707-14.28-7.933-22.44-21.76-7.933-13.827-7.933-31.507t7.707-31.506q7.706-13.827 21.08-21.534 13.6-7.933 30.826-7.933 16.32 0 29.24 7.253 12.92 7.254 20.627 20.4 7.934 12.92 8.387 30.374l-101.774 19.946-.906-13.826 91.573-17.68-7.026 9.973q0-11.333-5.214-20.4-4.986-9.067-14.053-14.28-9.067-5.44-20.854-5.44-12.013 0-21.533 5.44-9.293 5.44-14.507 15.187-5.213 9.746-5.213 22.893 0 13.827 5.667 24.253 5.893 10.2 16.093 15.867 10.427 5.44 24.027 5.44 10.88 0 19.947-3.627 9.066-3.853 15.64-11.56l10.426 12.24q-7.707 9.52-19.72 14.507-12.013 4.987-26.747 4.987zM628 84.75c-13.256 0-24.15 10.894-24.15 24.15 0 13.256 10.894 24.15 24.15 24.15s24.15-10.894 24.15-24.15c0-13.256-10.894-24.15-24.15-24.15Zm0 13.8c5.798 0 10.35 4.553 10.35 10.35 0 5.798-4.552 10.35-10.35 10.35s-10.35-4.552-10.35-10.35c0-5.797 4.552-10.35 10.35-10.35z"/></svg>
`

2023-10-24 04:06 UTC, Yashh56 commented
I will make this changes ASAP @canaleal Thanks for the help

2023-10-24 06:24 UTC, Yashh56 commented
**Hey @canaleal Are these changes correct?**

2023-10-24 09:01 UTC, weh requested changes
Still some things to fix here

2023-10-24 09:01 UTC, weh commented on icons/forgejo/forgejo-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><g fill="#f9f9f9" stroke="#000"><path stroke-width="15.166" d="M37.261 105.534v-59.45c0-16.754 13.581-30.33 30.33-30.33h12.133"/><path st
It looks like there are two white line left from editing.
![image](https://github.com/devicons/devicon/assets/482423/4ba96e35-505a-44c5-89fc-9105d844c54a)

2023-10-24 09:01 UTC, weh commented on icons/forgejo/forgejo-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><g fill="#f9f9f9" stroke="#000"><path stroke-width="15.166" d="M37.261 105.534v-59.45c0-16.754 13.581-30.33 30.33-30.33h12.133"/><path st
Newline is missing at the end of the file
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><g fill="#f9f9f9" stroke="#000"><path stroke-width="15.166" d="M37.261 105.534v-59.45c0-16.754 13.581-30.33 30.33-30.33h12.133"/><path stroke-width="15.166" d="M37.261 105.534V87.332c0-16.75 13.581-30.33 30.33-30.33h12.133"/><path stroke-width="9.099" d="M99.136 15.754c0 6.028-4.886 10.918-10.918 10.918-6.029 0-10.918-4.89-10.918-10.918 0-6.033 4.89-10.922 10.918-10.922 6.032 0 10.918 4.89 10.918 10.922zm0 41.248c0 6.033-4.886 10.918-10.918 10.918-6.029 0-10.918-4.885-10.918-10.918 0-6.028 4.89-10.918 10.918-10.918 6.032 0 10.918 4.89 10.918 10.918zM48.18 112.81c0 6.033-4.89 10.922-10.919 10.922-6.032 0-10.918-4.89-10.918-10.922 0-6.028 4.886-10.918 10.918-10.918 6.029 0 10.918 4.89 10.918 10.918zm0 0"/></g></svg>

```

2023-10-24 09:41 UTC, Yashh56 commented on icons/forgejo/forgejo-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.74 0c-1.644 0-3.092 2.504-3.87 6.198h-1.853C7.54 6.198 2.24 20.865 2.24 38.794v47.373C.906 88.324 0 92.322 0 96.87c0 6.802 2
I followed all the instructions @weh

2023-10-24 09:57 UTC, Yashh56 commented
**Are these changes are fine?  @weh**

2023-10-24 16:15 UTC, weh requested changes
Ok, let me help you a bit with the images here.

Next time try to fix what the reviewers tell you. Don't worry if you need a bit of time and maybe also need to learn Inkscape. Don't rush and ask for multiple reviews, if you can see with your own eyes, that the images look wrong.

I guess i should also take some time and try to add some more hints, on how to fix specific things, when editing SVG images.

Thank you for your contribution, and happy hacktoberfest :)

2023-10-24 16:15 UTC, weh commented on icons/forgejo/forgejo-original-wordmark.svg
> +</svg>
What is wrong with this image
- Aspect ratio is wrong, logo is squished
- Image contains Inkscape metadata and is not optimized

what did i change here:
- Ungroup all paths
- convert all strokes to paths
- group all elements by color (2 path elements left)
- make sure the logo is square and centered
- resized the image to 128x128 using iloveimg
- optimize the image using vecta

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.73 40.855c-1.645 0-3.09.902-3.867 2.238h-1.852a11.81 11.81 0 0 0-11.773 11.77v19.07h4.477v-19.07a7.26 7.26 0 0 1 7.297-7.293h1.852a4.49 4.49 0 0 0 3.867 2.238 4.5 4.5 0 0 0 4.477-4.477 4.5 4.5 0 0 0-4.477-4.477zm0 2.652c1.023 0 1.824.801 1.824 1.824s-.801 1.824-1.824 1.824-1.824-.801-1.824-1.824.801-1.824 1.824-1.824zm83.207 10.211c-2.195 0-4.004 1.809-4.004 4.004a4.03 4.03 0 0 0 4.004 4.008c2.199 0 4.004-1.809 4.004-4.008s-1.805-4.004-4.004-4.004zm0 2.289a1.7 1.7 0 1 1 0 3.434c-.961 0-1.715-.754-1.715-1.719s.754-1.715 1.715-1.715zM32.359 59.57c-1.977 0-3.73.438-5.262 1.316a9.6 9.6 0 0 0-3.645 3.57c-.875 1.504-1.316 3.246-1.316 5.223 0 1.957.441 3.695 1.316 5.227.902 1.527 2.117 2.73 3.645 3.605 1.555.852 3.309 1.277 5.262 1.277s3.695-.426 5.227-1.277a9.53 9.53 0 0 0 3.645-3.605c.875-1.531 1.316-3.27 1.316-5.227 0-1.977-.441-3.719-1.316-5.223-.879-1.527-2.094-2.719-3.645-3.57-1.531-.879-3.27-1.316-5.227-1.316zm23.191 0c-1.93 0-3.547.391-4.848 1.164a6.17 6.17 0 0 0-2.48 2.602v-3.578h-3.008v19.844h3.156v-9.996c0-2.254.578-3.984 1.73-5.187 1.152-1.227 2.719-1.84 4.695-1.84.125 0 .25.012.379.035.125 0 .25.016.375.039zm10.652 0c-1.906 0-3.621.402-5.148 1.203-1.504.801-2.695 1.93-3.574 3.383-.875 1.43-1.312 3.094-1.312 5s.438 3.582 1.313 5.035a9.36 9.36 0 0 0 3.574 3.418c1.527.801 3.242 1.203 5.148 1.203 1.727 0 3.281-.363 4.66-1.09.84-.437 1.578-1 2.215-1.691l-.098 1.355c-.172 2.348-.578 4.094-1.73 5.223-1.152 1.152-2.945 1.727-5.375 1.727a13.09 13.09 0 0 1-4.281-.711c-1.355-.477-2.496-1.129-3.422-1.957l-1.578 2.445c1.078.949 2.457 1.676 4.133 2.18 1.703.523 3.457.789 5.262.789 3.332 0 5.852-.816 7.555-2.445 1.703-1.602 2.555-4.133 2.555-7.59 0-4.766.625-10.625-1.227-13.191-.828-1.43-1.941-2.492-3.348-3.195-1.375-.727-3.594-1.09-5.32-1.09zm51.547 0c-1.98 0-3.734.438-5.262 1.316a9.6 9.6 0 0 0-3.645 3.57c-.879 1.504-1.316 3.246-1.316 5.223 0 1.957.438 3.695 1.316 5.227.902 1.527 2.117 2.73 3.645 3.605 1.555.852 3.309 1.277 5.262 1.277s3.695-.426 5.223-1.277c1.555-.875 2.77-2.078 3.648-3.605s1.313-3.27 1.313-5.227c0-1.977-.437-3.719-1.312-5.223-.879-1.527-2.094-2.719-3.648-3.57-1.527-.879-3.27-1.316-5.223-1.316zm-28.895.043c-1.906 0-3.609.441-5.109 1.316-1.48.852-2.645 2.043-3.496 3.57s-1.277 3.27-1.277 5.223.438 3.695 1.313 5.227c.902 1.527 2.145 2.73 3.723 3.605 1.602.852 3.445 1.277 5.523 1.277 1.629 0 3.105-.273 4.434-.824s2.418-1.355 3.27-2.406l-1.727-2.027c-.727.852-1.59 1.488-2.594 1.914-1.004.402-2.105.602-3.309.602-1.5 0-2.828-.301-3.98-.902a6.91 6.91 0 0 1-2.672-2.629c-.199-.371-.367-.762-.504-1.176l16.066-3.148c-.051-1.93-.516-3.605-1.391-5.035-.852-1.453-1.992-2.582-3.422-3.383s-3.043-1.203-4.848-1.203zm0 2.707c1.301 0 2.457.301 3.457.902a6.09 6.09 0 0 1 2.332 2.367 6.39 6.39 0 0 1 .73 1.98l-13.34 2.574a10.36 10.36 0 0 1-.02-.609c0-1.453.289-2.719.863-3.793s1.379-1.918 2.406-2.52c1.051-.602 2.242-.902 3.57-.902zm-56.496.031c1.355 0 2.559.301 3.609.902s1.879 1.453 2.48 2.555c.625 1.105.938 2.395.938 3.871 0 1.453-.312 2.746-.937 3.871-.602 1.102-1.43 1.969-2.48 2.594-1.051.602-2.254.902-3.609.902s-2.555-.301-3.605-.902c-1.055-.625-1.891-1.492-2.52-2.594-.602-1.125-.902-2.418-.902-3.871 0-1.477.301-2.766.902-3.871.629-1.102 1.465-1.953 2.52-2.555s2.254-.902 3.605-.902zm33.813 0c1.402 0 2.641.289 3.719.863 1.078.555 1.918 1.344 2.52 2.371.625 1.023.938 2.215.938 3.57s-.312 2.555-.937 3.605c-.602 1.027-1.441 1.828-2.52 2.406s-2.316.863-3.719.863c-1.379 0-2.605-.289-3.684-.863s-1.93-1.379-2.555-2.406c-.602-1.051-.902-2.254-.902-3.605s.301-2.547.902-3.57c.625-1.027 1.477-1.816 2.555-2.371 1.078-.574 2.305-.863 3.684-.863zm51.578 0c1.352 0 2.555.301 3.609.902s1.879 1.453 2.48 2.555c.625 1.105.938 2.395.938 3.871 0 1.453-.312 2.746-.937 3.871-.602 1.102-1.43 1.969-2.48 2.594-1.055.602-2.258.902-3.609.902s-2.555-.301-3.609-.902c-1.051-.625-1.891-1.492-2.516-2.594-.602-1.125-.902-2.418-.902-3.871 0-1.477.301-2.766.902-3.871.625-1.102 1.465-1.953 2.516-2.555s2.258-.902 3.609-.902zm-16.215.723v17.73c0 1.203-.273 2.105-.824 2.707-.527.602-1.293.902-2.293.902-1.23 0-2.23-.312-3.008-.941l-1.051 2.367c.5.426 1.125.738 1.879.941s1.539.301 2.367.301c1.953 0 3.457-.566 4.508-1.691s1.578-2.656 1.578-4.586v-17.73zm0 0" fill="#ff5500"/><path d="M19.73 53.246a4.49 4.49 0 0 0-3.867 2.238h-1.852c-6.477 0-11.773 5.301-11.773 11.773v4.711C.906 72.75 0 74.195 0 75.84a4.5 4.5 0 0 0 4.477 4.477 4.5 4.5 0 0 0 4.477-4.477c0-1.645-.902-3.09-2.238-3.871v-4.711a7.26 7.26 0 0 1 7.297-7.293h1.852a4.49 4.49 0 0 0 3.867 2.238c2.457 0 4.477-2.023 4.477-4.48a4.5 4.5 0 0 0-4.477-4.477zm0 2.656c1.023 0 1.824.801 1.824 1.82s-.801 1.824-1.824 1.824-1.824-.801-1.824-1.824.801-1.82 1.824-1.82zM4.477 74.016c1.023 0 1.824.801 1.824 1.824s-.801 1.824-1.824 1.824-1.824-.801-1.824-1.824.801-1.824 1.824-1.824zm0 0" fill="#cc0000"/></svg>

```

2023-10-24 16:15 UTC, weh commented on icons/forgejo/forgejo-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.74 0c-1.644 0-3.092 2.504-3.87 6.198h-1.853C7.54 6.198 2.24 20.865 2.24 38.794v47.373C.906 88.324 0 92.322 0 96.87c0 6.802 2
Aspect ratio is wrong, logo is squished

so what did i need to change here:

- take the forgejo-original-wordmark.svg and merge all paths into a single one
- change color to black
- resized the image to 128x128 using iloveimg
- optimize the image using vecta

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.73 40.855c-1.645 0-3.09.902-3.867 2.238h-1.852a11.81 11.81 0 0 0-11.773 11.77v17.105C.906 72.75 0 74.195 0 75.84a4.5 4.5 0 0 0 4.477 4.477 4.5 4.5 0 0 0 4.477-4.477c0-1.645-.902-3.09-2.238-3.871v-4.711a7.26 7.26 0 0 1 7.297-7.293h1.852a4.49 4.49 0 0 0 3.867 2.238 4.5 4.5 0 0 0 4.477-4.477 4.5 4.5 0 0 0-4.477-4.477c-1.645 0-3.09.902-3.867 2.238h-1.852a11.71 11.71 0 0 0-7.297 2.551v-3.176a7.26 7.26 0 0 1 7.297-7.293h1.852a4.49 4.49 0 0 0 3.867 2.238 4.5 4.5 0 0 0 4.477-4.477 4.5 4.5 0 0 0-4.477-4.477zm0 2.652c1.023 0 1.824.801 1.824 1.824s-.801 1.824-1.824 1.824-1.824-.801-1.824-1.824.801-1.824 1.824-1.824zm83.207 10.211a4.03 4.03 0 0 0-4.004 4.008c0 2.195 1.809 4.004 4.004 4.004s4.004-1.809 4.004-4.004-1.805-4.008-4.004-4.008zM19.73 55.902c1.023 0 1.824.801 1.824 1.824s-.801 1.82-1.824 1.82-1.824-.801-1.824-1.82.801-1.824 1.824-1.824zm83.207.105a1.7 1.7 0 1 1 0 3.434c-.961 0-1.715-.754-1.715-1.715s.754-1.719 1.715-1.719zM32.359 59.57c-1.977 0-3.73.438-5.262 1.316a9.6 9.6 0 0 0-3.645 3.57c-.875 1.504-1.316 3.246-1.316 5.223 0 1.957.441 3.695 1.316 5.227.902 1.527 2.117 2.73 3.645 3.605 1.555.852 3.309 1.277 5.262 1.277s3.695-.426 5.227-1.277c1.551-.875 2.766-2.078 3.645-3.609s1.316-3.266 1.316-5.223c0-1.977-.441-3.719-1.316-5.223-.879-1.527-2.094-2.719-3.645-3.57-1.531-.879-3.27-1.316-5.227-1.316zm23.191 0c-1.93 0-3.547.391-4.848 1.164a6.17 6.17 0 0 0-2.48 2.602v-3.578h-3.008v19.844h3.156v-9.996c0-2.254.578-3.984 1.73-5.187 1.152-1.227 2.719-1.84 4.695-1.84.125 0 .25.012.379.035.125 0 .25.016.375.039zm10.652 0c-1.906 0-3.621.402-5.148 1.203-1.504.801-2.695 1.93-3.574 3.383-.875 1.43-1.312 3.094-1.312 5s.438 3.582 1.313 5.035a9.36 9.36 0 0 0 3.574 3.418c1.527.805 3.242 1.203 5.148 1.203 1.727 0 3.281-.363 4.66-1.09.84-.437 1.578-1 2.215-1.691l-.098 1.355c-.172 2.348-.578 4.094-1.73 5.223-1.152 1.152-2.945 1.727-5.375 1.727a12.99 12.99 0 0 1-4.281-.711c-1.355-.477-2.496-1.129-3.422-1.957l-1.578 2.445c1.078.953 2.457 1.676 4.133 2.18 1.703.523 3.457.789 5.262.789 3.332 0 5.852-.816 7.555-2.445 1.703-1.602 2.555-4.133 2.555-7.59 0-4.766.625-10.625-1.227-13.191-.828-1.43-1.941-2.492-3.348-3.195-1.375-.727-3.594-1.09-5.32-1.09zm51.547 0c-1.98 0-3.734.438-5.262 1.316a9.6 9.6 0 0 0-3.645 3.57c-.879 1.504-1.316 3.246-1.316 5.223 0 1.957.438 3.695 1.316 5.227.902 1.527 2.117 2.73 3.645 3.605 1.555.852 3.309 1.277 5.262 1.277s3.695-.426 5.223-1.277c1.555-.875 2.77-2.078 3.648-3.609s1.313-3.266 1.313-5.223c0-1.977-.437-3.719-1.312-5.223-.879-1.527-2.094-2.719-3.648-3.57-1.527-.879-3.27-1.316-5.223-1.316zm-28.895.043c-1.906 0-3.609.441-5.109 1.316-1.48.852-2.645 2.043-3.496 3.57s-1.277 3.27-1.277 5.223.438 3.695 1.313 5.227c.902 1.527 2.145 2.73 3.723 3.605 1.602.855 3.445 1.277 5.523 1.277 1.629 0 3.105-.273 4.434-.824s2.418-1.352 3.27-2.406l-1.727-2.027c-.727.852-1.59 1.488-2.594 1.914-1.004.402-2.105.602-3.309.602-1.5 0-2.828-.301-3.98-.902a6.91 6.91 0 0 1-2.672-2.629c-.199-.371-.367-.762-.504-1.176l16.066-3.148c-.051-1.93-.516-3.605-1.391-5.035-.852-1.453-1.992-2.582-3.422-3.383s-3.043-1.203-4.848-1.203zm0 2.707c1.301 0 2.457.301 3.457.902 1.004.578 1.777 1.363 2.332 2.367a6.39 6.39 0 0 1 .73 1.98l-13.34 2.574a10.36 10.36 0 0 1-.02-.609c0-1.453.289-2.719.863-3.793s1.379-1.918 2.406-2.52c1.051-.602 2.242-.902 3.57-.902zm-56.496.031c1.355 0 2.559.301 3.609.902s1.879 1.453 2.48 2.555c.625 1.105.938 2.395.938 3.871 0 1.453-.312 2.746-.937 3.871-.602 1.102-1.43 1.969-2.48 2.594-1.051.602-2.254.902-3.609.902s-2.555-.301-3.605-.902c-1.055-.625-1.891-1.492-2.52-2.594-.602-1.125-.902-2.418-.902-3.871 0-1.477.301-2.766.902-3.871.629-1.102 1.465-1.953 2.52-2.555s2.254-.902 3.605-.902zm33.813 0c1.402 0 2.641.289 3.719.863 1.078.555 1.918 1.34 2.52 2.367.625 1.027.938 2.219.938 3.574s-.312 2.555-.937 3.605c-.602 1.027-1.441 1.828-2.52 2.406s-2.316.863-3.719.863c-1.379 0-2.605-.289-3.684-.863s-1.93-1.379-2.555-2.406c-.602-1.051-.902-2.254-.902-3.605s.301-2.547.902-3.574c.625-1.027 1.477-1.812 2.555-2.367 1.078-.574 2.305-.863 3.684-.863zm51.578 0c1.352 0 2.555.301 3.609.902s1.879 1.453 2.48 2.555c.625 1.105.938 2.395.938 3.871 0 1.453-.312 2.746-.937 3.871-.602 1.102-1.43 1.969-2.48 2.594-1.055.602-2.258.902-3.609.902s-2.555-.301-3.609-.902c-1.051-.625-1.891-1.492-2.516-2.594-.602-1.125-.902-2.418-.902-3.871 0-1.477.301-2.766.902-3.871.625-1.102 1.465-1.953 2.516-2.555s2.258-.902 3.609-.902zm-16.215.723v17.73c0 1.203-.273 2.105-.824 2.707-.527.602-1.293.902-2.293.902-1.23 0-2.23-.312-3.008-.941l-1.051 2.367c.5.426 1.125.738 1.879.941s1.539.301 2.367.301c1.953 0 3.457-.566 4.508-1.691s1.578-2.656 1.578-4.586v-17.73zM4.477 74.016c1.023 0 1.824.801 1.824 1.824s-.801 1.824-1.824 1.824-1.824-.801-1.824-1.824.801-1.824 1.824-1.824zm0 0" fill="#000000"/></svg>

```

2023-10-24 16:33 UTC, Yashh56 commented
**thank you for the help @weh**

2023-10-24 18:32 UTC, weh approved these changes

2023-10-24 19:19 UTC, Snailedlt commented
Wow great tutorial here @canaleal! 
https://github.com/devicons/devicon/pull/1926#issuecomment-1776317249

Would you mind adding the thing with objects, and adding it to this issue?
https://github.com/devicons/devicon/issues/1306

2023-10-24 19:22 UTC, Snailedlt requested changes
Looking great!
Just some small suggestions for `devicon.json`

2023-10-24 19:22 UTC, Snailedlt commented on devicon.json
> +                "original"
A little whoopsie that needs to be fixed ;)
```suggestion
                "plain",
                "plain-wordmark"
```

2023-10-24 19:22 UTC, Snailedlt commented on devicon.json
> +            "software"
```suggestion
            "software",
            "git",
            "version-control"
```

2023-11-03 03:17 UTC, lunatic-fox requested changes
It seems that we have to do some little adjustments here. 🔧
- All icons need to have one line with the SVG code and another with the newline character, but the files have 3 lines instead. If you're using some code editor, please take a look if you have just 2 lines or if when you trying to remove the third line it inserts a newline automatically - if that is the case, remove any newlines until the SVG code and wait for the code editor autocomplete it.
- `#000000` is the only fill color that can be omitted in most cases.

2023-11-03 03:17 UTC, lunatic-fox commented on icons/forgejo/forgejo-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.73 40.855c-1.645 0-3.09.902-3.867 2.238h-1.852a11.81 11.81 0 0 0-11.773 11.77v17.105C.906 72.75 0 74.195 0 75.84a4.5 4.5 0 0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.73 40.855c-1.645 0-3.09.902-3.867 2.238h-1.852a11.81 11.81 0 0 0-11.773 11.77v17.105C.906 72.75 0 74.195 0 75.84a4.5 4.5 0 0 0 4.477 4.477 4.5 4.5 0 0 0 4.477-4.477c0-1.645-.902-3.09-2.238-3.871v-4.711a7.26 7.26 0 0 1 7.297-7.293h1.852a4.49 4.49 0 0 0 3.867 2.238 4.5 4.5 0 0 0 4.477-4.477 4.5 4.5 0 0 0-4.477-4.477c-1.645 0-3.09.902-3.867 2.238h-1.852a11.71 11.71 0 0 0-7.297 2.551v-3.176a7.26 7.26 0 0 1 7.297-7.293h1.852a4.49 4.49 0 0 0 3.867 2.238 4.5 4.5 0 0 0 4.477-4.477 4.5 4.5 0 0 0-4.477-4.477zm0 2.652c1.023 0 1.824.801 1.824 1.824s-.801 1.824-1.824 1.824-1.824-.801-1.824-1.824.801-1.824 1.824-1.824zm83.207 10.211a4.03 4.03 0 0 0-4.004 4.008c0 2.195 1.809 4.004 4.004 4.004s4.004-1.809 4.004-4.004-1.805-4.008-4.004-4.008zM19.73 55.902c1.023 0 1.824.801 1.824 1.824s-.801 1.82-1.824 1.82-1.824-.801-1.824-1.82.801-1.824 1.824-1.824zm83.207.105a1.7 1.7 0 1 1 0 3.434c-.961 0-1.715-.754-1.715-1.715s.754-1.719 1.715-1.719zM32.359 59.57c-1.977 0-3.73.438-5.262 1.316a9.6 9.6 0 0 0-3.645 3.57c-.875 1.504-1.316 3.246-1.316 5.223 0 1.957.441 3.695 1.316 5.227.902 1.527 2.117 2.73 3.645 3.605 1.555.852 3.309 1.277 5.262 1.277s3.695-.426 5.227-1.277c1.551-.875 2.766-2.078 3.645-3.609s1.316-3.266 1.316-5.223c0-1.977-.441-3.719-1.316-5.223-.879-1.527-2.094-2.719-3.645-3.57-1.531-.879-3.27-1.316-5.227-1.316zm23.191 0c-1.93 0-3.547.391-4.848 1.164a6.17 6.17 0 0 0-2.48 2.602v-3.578h-3.008v19.844h3.156v-9.996c0-2.254.578-3.984 1.73-5.187 1.152-1.227 2.719-1.84 4.695-1.84.125 0 .25.012.379.035.125 0 .25.016.375.039zm10.652 0c-1.906 0-3.621.402-5.148 1.203-1.504.801-2.695 1.93-3.574 3.383-.875 1.43-1.312 3.094-1.312 5s.438 3.582 1.313 5.035a9.36 9.36 0 0 0 3.574 3.418c1.527.805 3.242 1.203 5.148 1.203 1.727 0 3.281-.363 4.66-1.09.84-.437 1.578-1 2.215-1.691l-.098 1.355c-.172 2.348-.578 4.094-1.73 5.223-1.152 1.152-2.945 1.727-5.375 1.727a12.99 12.99 0 0 1-4.281-.711c-1.355-.477-2.496-1.129-3.422-1.957l-1.578 2.445c1.078.953 2.457 1.676 4.133 2.18 1.703.523 3.457.789 5.262.789 3.332 0 5.852-.816 7.555-2.445 1.703-1.602 2.555-4.133 2.555-7.59 0-4.766.625-10.625-1.227-13.191-.828-1.43-1.941-2.492-3.348-3.195-1.375-.727-3.594-1.09-5.32-1.09zm51.547 0c-1.98 0-3.734.438-5.262 1.316a9.6 9.6 0 0 0-3.645 3.57c-.879 1.504-1.316 3.246-1.316 5.223 0 1.957.438 3.695 1.316 5.227.902 1.527 2.117 2.73 3.645 3.605 1.555.852 3.309 1.277 5.262 1.277s3.695-.426 5.223-1.277c1.555-.875 2.77-2.078 3.648-3.609s1.313-3.266 1.313-5.223c0-1.977-.437-3.719-1.312-5.223-.879-1.527-2.094-2.719-3.648-3.57-1.527-.879-3.27-1.316-5.223-1.316zm-28.895.043c-1.906 0-3.609.441-5.109 1.316-1.48.852-2.645 2.043-3.496 3.57s-1.277 3.27-1.277 5.223.438 3.695 1.313 5.227c.902 1.527 2.145 2.73 3.723 3.605 1.602.855 3.445 1.277 5.523 1.277 1.629 0 3.105-.273 4.434-.824s2.418-1.352 3.27-2.406l-1.727-2.027c-.727.852-1.59 1.488-2.594 1.914-1.004.402-2.105.602-3.309.602-1.5 0-2.828-.301-3.98-.902a6.91 6.91 0 0 1-2.672-2.629c-.199-.371-.367-.762-.504-1.176l16.066-3.148c-.051-1.93-.516-3.605-1.391-5.035-.852-1.453-1.992-2.582-3.422-3.383s-3.043-1.203-4.848-1.203zm0 2.707c1.301 0 2.457.301 3.457.902 1.004.578 1.777 1.363 2.332 2.367a6.39 6.39 0 0 1 .73 1.98l-13.34 2.574a10.36 10.36 0 0 1-.02-.609c0-1.453.289-2.719.863-3.793s1.379-1.918 2.406-2.52c1.051-.602 2.242-.902 3.57-.902zm-56.496.031c1.355 0 2.559.301 3.609.902s1.879 1.453 2.48 2.555c.625 1.105.938 2.395.938 3.871 0 1.453-.312 2.746-.937 3.871-.602 1.102-1.43 1.969-2.48 2.594-1.051.602-2.254.902-3.609.902s-2.555-.301-3.605-.902c-1.055-.625-1.891-1.492-2.52-2.594-.602-1.125-.902-2.418-.902-3.871 0-1.477.301-2.766.902-3.871.629-1.102 1.465-1.953 2.52-2.555s2.254-.902 3.605-.902zm33.813 0c1.402 0 2.641.289 3.719.863 1.078.555 1.918 1.34 2.52 2.367.625 1.027.938 2.219.938 3.574s-.312 2.555-.937 3.605c-.602 1.027-1.441 1.828-2.52 2.406s-2.316.863-3.719.863c-1.379 0-2.605-.289-3.684-.863s-1.93-1.379-2.555-2.406c-.602-1.051-.902-2.254-.902-3.605s.301-2.547.902-3.574c.625-1.027 1.477-1.812 2.555-2.367 1.078-.574 2.305-.863 3.684-.863zm51.578 0c1.352 0 2.555.301 3.609.902s1.879 1.453 2.48 2.555c.625 1.105.938 2.395.938 3.871 0 1.453-.312 2.746-.937 3.871-.602 1.102-1.43 1.969-2.48 2.594-1.055.602-2.258.902-3.609.902s-2.555-.301-3.609-.902c-1.051-.625-1.891-1.492-2.516-2.594-.602-1.125-.902-2.418-.902-3.871 0-1.477.301-2.766.902-3.871.625-1.102 1.465-1.953 2.516-2.555s2.258-.902 3.609-.902zm-16.215.723v17.73c0 1.203-.273 2.105-.824 2.707-.527.602-1.293.902-2.293.902-1.23 0-2.23-.312-3.008-.941l-1.051 2.367c.5.426 1.125.738 1.879.941s1.539.301 2.367.301c1.953 0 3.457-.566 4.508-1.691s1.578-2.656 1.578-4.586v-17.73zM4.477 74.016c1.023 0 1.824.801 1.824 1.824s-.801 1.824-1.824 1.824-1.824-.801-1.824-1.824.801-1.824 1.824-1.824zm0 0"/></svg>
```

2023-11-03 03:17 UTC, lunatic-fox commented on icons/forgejo/forgejo-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 128 128"><path d="M89.457 0C83.719 0 78.68 3.195 76.012 7.887h-7.176c-20.844 0-37.902 17.059-37.902 37.902v41.238 12.027c-4.691 2.6
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M89.457 0C83.719 0 78.68 3.195 76.012 7.887h-7.176c-20.844 0-37.902 17.059-37.902 37.902v41.238 12.027c-4.691 2.672-7.883 7.709-7.883 13.443 0 8.488 6.977 15.471 15.465 15.471s15.465-6.982 15.465-15.471c0-5.738-3.199-10.775-7.887-13.443V87.027c0-12.645 10.094-22.738 22.742-22.738h7.176c2.668 4.688 7.707 7.883 13.445 7.883 8.484 0 15.465-6.98 15.465-15.465s-6.977-15.465-15.465-15.465c-5.738 0-10.777 3.195-13.445 7.883h-7.176c-8.515 0-16.396 2.849-22.742 7.639V45.789a22.62 22.62 0 0 1 22.742-22.738h7.176c2.668 4.688 7.707 7.883 13.445 7.883 8.488 0 15.465-6.98 15.465-15.465S97.945 0 89.457 0zm0 9.098c3.574 0 6.367 2.797 6.367 6.371s-2.793 6.367-6.367 6.367a6.3 6.3 0 0 1-6.367-6.367 6.3 6.3 0 0 1 6.367-6.371zm0 41.242c3.574 0 6.367 2.797 6.367 6.367a6.29 6.29 0 0 1-6.367 6.363 6.29 6.29 0 0 1-6.367-6.363 6.3 6.3 0 0 1 6.367-6.367zm-50.941 55.793a6.3 6.3 0 0 1 6.363 6.367c0 3.574-2.797 6.371-6.363 6.371-3.574 0-6.367-2.797-6.367-6.371s2.793-6.367 6.367-6.367z"/></svg>
```

2024-02-06 03:39 UTC, closed without merging

2024-02-29 16:34 UTC, AnshSinghSonkhia commented
> Optimizing the SVG using SVGOMG

# Optimizing is a 1 Click task with SVGVIEWER

I found it more easier to do with it.

1. Visit [https://www.svgviewer.dev](https://www.svgviewer.dev)
2. Upload SVG or past code

![beforeSVG](https://github.com/devicons/devicon/assets/110414565/79bb6f1d-7856-4ff0-aefe-03dc7145b454)

4. Click on `Prettify` Button.
5. Click on `Optimize` Button.

**BOOM !!!** The SVG is optimized, **without ruining the viewbox**.


![optimizedSVG](https://github.com/devicons/devicon/assets/110414565/f1c5ca53-f24f-4cb8-8cb8-76b2ff9596c4)