New icon: Twilio (original, original-wordmark)
devicons/devicon pull request #1956
Opened 2023-10-30 03:52 UTC by dariakiseleva

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

https://www.twilio.com/

2023-10-30 16:06 UTC, Snailedlt requested changes
Hi, thank you for the PR! :D
The icons look good, and the devicon.json is mostly good as well.
It seems like twilio is the company, and that they have multiple different products... in which case it would be out of scope for devicons.
But if twilio is also a platform I do believe it's within scope. You can read more about which icons are accepted here: https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F

@dariakiseleva Could you provide some more info (perhaps some links) to confirm that twilio is within scope of devicons?

2023-10-30 16:06 UTC, Snailedlt commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            },
            {
                "base": "original-wordmark",
                "alias": "plain-wordmark"
            }
        ]
```

2025-03-10 02:04 UTC, canaleal commented
> Hi, thank you for the PR! :D The icons look good, and the devicon.json is mostly good as well. It seems like twilio is the company, and that they have multiple different products... in which case it would be out of scope for devicons. But if twilio is also a platform I do believe it's within scope. You can read more about which icons are accepted here: https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F
> 
> @dariakiseleva Could you provide some more info (perhaps some links) to confirm that twilio is within scope of devicons?

Looks like twilio is a platform. 

The messaging, voice, email, lookup, verify, etc tools make use of the twilio logo.

2025-03-10 10:38 UTC, Snailedlt commented
Then it's fine by me. Thanks for checking up on this again @canaleal!

2025-03-16 04:19 UTC, canaleal approved these changes

2025-03-16 04:19 UTC, merged