update icon: yarn (original, original-wordmark, line, line-wordmark)
devicons/devicon pull request #1960
Opened 2023-10-30 12:52 UTC by Snailedlt

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes NONE**

Refer to https://github.com/devicons/devicon/pull/1952#issuecomment-1784951429 for more info

## Link to prove your SVG is correct and up-to-date.

2023-10-31 06:03 UTC, canaleal commented on icons/yarn/yarn-original.svg
Looks like `fill="#2c8ebb"` was removed during optimization.

2023-10-31 06:03 UTC, canaleal commented on icons/yarn/yarn-original-wordmark.svg
The resize is good, but was the `fill="#2c8ebb"` accidentally removed. 
Aside from that, all icons are good.

2023-10-31 06:09 UTC, canaleal requested changes
Overall, great updates!
Nice work with the line icons. 

Only the fill="#2c8ebb" needs to be added to the original icons.

2023-10-31 08:12 UTC, Snailedlt commented on icons/yarn/yarn-original.svg
That was intentional. The fill can be removed since it's a single path. The fill is added via the color in `devicon.json` in the api

2023-10-31 08:47 UTC, canaleal commented on icons/yarn/yarn-original.svg
Ah okay. Will approve then.

2023-10-31 08:50 UTC, canaleal approved these changes

2023-11-01 09:40 UTC, weh approved these changes

2023-11-01 15:48 UTC, Snailedlt commented on icons/yarn/yarn-original.svg
Actually... The color needs to be there I think, since it's used as as an an SVG.

2023-11-01 15:54 UTC, merged