new icon: neovim (original, original-wordmark, plain , plain-wordmark, line, line-wordmark)
devicons/devicon pull request #1962
Opened 2023-10-30 22:14 UTC by Snailedlt

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #717**

## Link to prove your SVG is correct and up-to-date.

http://neovim.io/
https://neovim.io/logos/neovim-logos.zip
Since all of the colors in the main icon are gradients the color in `devicon.json` is based on the color of the wordmark logo's text on the website (which is what they use for all the links on the website):
![image](https://github.com/devicons/devicon/assets/43886029/34136573-6cfb-47c6-b530-715f844ca990)

2023-10-31 20:06 UTC, canaleal requested changes
Overall great work. 

Only thing that needs to be done is reduce SVG code to 1 line and throw in an empty line at end for all SVGs. 

Also, the neovim line SVG looks a little thick on left. It looks to be made from the plain icon so technically that's how it should appear, but the thickness is not seen in the line-wordmark svg. 

I don't believe it's an issue, but just pointing out just in case.

2023-10-31 21:49 UTC, Snailedlt commented
@canaleal I joined the lines for all icons.

bleh... you're right about the line icons, but I cba to change it. Too much work for too little. Feel free to fix it if you want though, but to me it's good enough to release... then hopefully someone improves upon it later on :)

2023-10-31 21:59 UTC, canaleal approved these changes
Alright, all is good.

2023-11-01 09:44 UTC, weh approved these changes

2023-11-01 15:56 UTC, merged