new icon: apollographql (original, original-wordmark, line, line-wordmark)
devicons/devicon pull request #1965
Opened 2023-11-02 01:31 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1670**

## Link to prove your SVG is correct and up-to-date.

- [Apollo Website](https://www.apollographql.com/)
- [Apollo Brand Github](https://github.com/apollographql/apollo-client/blob/main/docs/source/logo/large.png)
- [Apollo Client Brand Logo](https://www.apollographql.com/docs/react/) is the same as the Apollo Server Logo. It is all referred to as Apollo. 

Apollo GraphQl is a platform; There are three components: Apollo Client, Apollo Server and Apollo Engine. All these products use the same Apollo logo and branding. Although the Apollo website uses white, it's official color is `#112b49`.

Almost everyone calls it Apollo and even the official SVG just has the word "Apollo" in it, but the official name is Apollo GraphQL.

2023-11-12 20:35 UTC, Snailedlt requested changes
`devicon.json` looks good!.
There's some artifacting on the icomoon generated fonts that needs to be fixed. All icon versions except the `original-wordmark` have artifacting. Here's the previews:
![image](https://github.com/devicons/devicon/assets/43886029/2f6d0db1-b971-4e19-9ed6-6e6ac238ca3c)
![image](https://github.com/devicons/devicon/assets/43886029/f7b0f965-13d1-44d2-92ae-13883d2dc755)
![image](https://github.com/devicons/devicon/assets/43886029/33e8c655-57f2-4ee8-a8a8-510db2a5be06)
![image](https://github.com/devicons/devicon/assets/43886029/c8fbb4f5-d88b-4b59-a5b4-5458a638bb42)
![image](https://github.com/devicons/devicon/assets/43886029/694cec52-7eaa-40ce-9ad6-eb172cdf9710)

2023-11-17 22:40 UTC, canaleal commented
Should be good now:

![image](https://github.com/devicons/devicon/assets/49886351/1bd48d0a-7876-4b0b-b30e-9958ff4c18b2)
![image](https://github.com/devicons/devicon/assets/49886351/4b4e8545-b1c8-47f1-ae79-9211b78607c1)

2024-09-12 11:06 UTC, Snailedlt requested changes
Old artifacts have been fixed, but I noticed another one

2024-09-12 11:06 UTC, Snailedlt commented on icons/apollographql/apollographql-line-wordmark.svg
Looks like there's still some artifacts here. The gap is filled in here instead of being a gap (if that makes sense).

Here's how it looks compared to the `original` version:
![image](https://github.com/user-attachments/assets/c86dea06-a5bb-4443-9e51-58ed14024a88)
![image](https://github.com/user-attachments/assets/ebbc6a17-58a2-4804-a507-e26d0d8f7f7d)

2025-03-12 13:28 UTC, gewaleelek commented on icons/apollographql/apollographql-line-wordmark.svg
@Snailedlt 

Hi, I noticed this old, open PR (perk of sorting stuff by old create date for things to do) and thought I'd try my hand at it:

![apollographql-line-wordmark](https://github.com/user-attachments/assets/49e94729-967a-4dd8-adb3-060ffe1726d3)

Would this work?

I can't help but think that the original logo is almost already the line version of itself, though. I wonder if we can just reduce the original's line thickness of APOLLO wordmark to match that of the orbiting thingy around the A?

2025-03-12 19:11 UTC, Snailedlt commented on icons/apollographql/apollographql-line-wordmark.svg
@gewaleelek your suggested icon looks great in my opinion.

> I can't help but think that the original logo is almost already the line version of itself, though. I wonder if we can just reduce the original's line thickness of APOLLO wordmark to match that of the orbiting thingy around the A?

This would work for larger icon sizes, but I think the lines would be too thin when scaled down, so the logo you already created will probably be better in smaller sizes.

@canaleal take a look when you have time and implement it if you agree :)

2025-03-14 03:19 UTC, canaleal commented on icons/apollographql/apollographql-line-wordmark.svg
I like it. Lines might be a little on the thinner side, but it still looks good.

2025-03-17 14:46 UTC, Snailedlt approved these changes
Great work as always @canaleal !
:heavy_check_mark:

2025-03-17 14:58 UTC, merged