new icon: kaldi (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #1966
Opened 2023-11-02 01:39 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1850**

## Link to prove your SVG is correct and up-to-date.

- [Kaldi Website](http://kaldi-asr.org/doc/)
- [Kaldi Brand Github](https://github.com/kaldi-asr/kaldi/blob/master/misc/logo/KaldiTextAndLogo.png)

The Kaldi logo makes use of a mid tone brown `#8b6331` and a gray color. I choose the brown as it makes the logo stand out from the sea of grays/ blacks and it's main color for kaldi.

2023-11-12 21:19 UTC, Snailedlt submitted a review, later dismissed
You've used two different colors in the icons: `#8b6331` and `#8a6230`.
When using a color picker on the GitHub branding logos and the icon on their website I found that the brown color was actually `#8c6432`, so I think we should change the colors to that

2024-08-26 08:43 UTC, weh requested changes
Good work, also going the extra mile adding line versions.

The only thing i found, was that SVGOMG could optimize the size more.
I added the optimized versions as suggestions.

2024-08-26 08:43 UTC, weh commented on icons/kaldi/kaldi-line-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M13.1007 48.9292c-2.6541-.0022-4.9011.6489-6.9882 2.0348-2.468 1.6388-4.189 4.0947-5.2053 7.366-.7167 2.3072-.901
Image can be optimized with SVGOMG

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M13.1 48.93c-2.653-.003-4.9.648-6.987 2.034-2.469 1.639-4.19 4.095-5.206 7.366-.717 2.307-.9 3.663-.907 6.7-.002 1.356.013 2.226.07 2.817.028.296.065.522.132.723.066.2.18.4.374.527.358.234.735.103.977-.068.064-.046.065-.159.122-.219.034.072.046.062.075.148.198.587.503 1.082.925 1.447.318.276.712.476 1.089.603.188.064.37.109.556.122.186.013.418.033.653-.201a1.21 1.21 0 0 0 .058-.07.52.52 0 0 0 .062-.12.59.59 0 0 0 .023-.078c.01-.04.013-.07.018-.103a4.219 4.219 0 0 0 .023-.236c.014-.187.026-.44.039-.748.003-.067.003-.182.006-.254.037.727-.06 1.567.021 2.037.681 3.908 2.92 7.013 5.779 7.616 1.61.34 3.196-.212 4.703-1.556 1.552-1.384 2.63-3.174 3.46-5.647-.006.161-.024.316.073.486.13.228.38.317.487.345a2.63 2.63 0 0 0 2.158-.386c.627-.427 1.115-1.109 1.419-1.965.009-.024.008-.012.017-.035.081.083.074.235.18.276.324.123.709.022.96-.23.221-.22.252-.406.33-.671.077-.265.149-.594.218-.99.14-.793.267-1.85.374-3.094.278-3.216-.18-6.774-1.223-9.279-1.982-4.767-5.815-7.294-11.057-7.298Zm3.35 1.402c.098.026.18.076.277.105-.092-.029-.185-.079-.277-.105zm-6.669.027c-.113.033-.236.088-.349.126.117-.037.23-.093.349-.126zm54.146.03a1.177 1.177 0 0 0-.636.238c-.18.134-.342.3-.573.54-.84.871-1.784 2.47-4.066 6.733-2.103 3.928-3.497 6.25-5.956 9.907-.569.847-1.119 1.687-1.546 2.36-.427.673-.71 1.118-.837 1.403-.063.14-.069.249-.113.359.02-.11.051-.225.053-.336.003-.211-.065-.485-.248-.668-.184-.184-.399-.247-.617-.293a6.44 6.44 0 0 0-.769-.097c-.862-.073-1.428-.212-2.502-.849-1.074-.636-2.616-1.776-5.232-3.784a723.774 723.774 0 0 0-2.37-1.814 191.38 191.38 0 0 0-.783-.593c-.043-.032-.05-.034-.084-.06.153-.154.367-.36.892-.81 5.446-4.672 7.638-6.75 8.321-8.258.133-.293.236-.498.245-.781.008-.282-.097-.5-.214-.744a2.69 2.69 0 0 0-1.498-1.357.972.972 0 0 0-.657.014 1.497 1.497 0 0 0-.529.384c-.32.335-.65.834-1.114 1.6-.764 1.264-1.159 1.71-3.858 4.386-1.697 1.682-3.172 3.034-4.213 3.885a9.98 9.98 0 0 1-.92.673c.005-.256-.006-.383.028-.78.061-.713.163-1.608.289-2.553.252-1.89.602-3.986.901-5.225.202-.838.265-1.51.091-2.09-.174-.578-.647-1.003-1.232-1.181a1.219 1.219 0 0 0-.6-.02 1.96 1.96 0 0 0-1.37 1.014c-.17.33-.271.771-.406 1.465-.135.694-.28 1.613-.436 2.763-.314 2.3-.675 5.522-1.08 9.655-.202 2.066-.522 4.66-.701 5.706-.196 1.14-.297 1.828-.221 2.39.038.282.138.547.31.75.172.205.39.331.61.427l.326.14a8.697 8.697 0 0 0 .112.046l.041.018.025.007c.01.004.07.02.072.02h.002s.098.011.124.01c.026-.002.044-.006.058-.008a.6.6 0 0 0 .056-.012c.027-.007.043-.013.06-.02.035-.011.07-.026.109-.042a7.9 7.9 0 0 0 .28-.122c.564-.256.91-.83 1.146-1.643.236-.813.387-1.922.504-3.46.108-1.424.258-2.42.455-3.057.198-.638.405-.867.634-.971.111-.051.048-.045.138-.024.09.022.32.12.713.324.401.208 1.84 1.18 3.015 2.07 3.3 2.497 5.202 3.91 6.492 4.751 1.29.841 2.02 1.122 2.814 1.27 1.177.218 2.254-.538 2.601-1.68a.92.92 0 0 0 .112.42c.06.11.121.188.19.281.257.346.588.636.928.845.34.209.666.403 1.128.271.396-.112.726-.405 1.09-.885.363-.481.793-1.185 1.412-2.264.704-1.226 1.205-2.068 1.553-2.602.173-.267.31-.458.403-.572.037-.045.001-.017.023-.035.04.016.08.03.116.054.263.172.662.285 1.16.221.496-.064 1.188-.24 2.437-.568a46.834 46.834 0 0 1 3.57-.775c1.133-.2 2.151-.302 2.356-.285l.254.022 1.229 2.457c.373.748.76 1.5 1.081 2.108.321.61.561 1.053.707 1.277.318.49.747 1.009 1.17 1.448.425.44.792.79 1.2.973.692.309 1.484.132 2.063-.419.455-.432.729-1.016.602-1.608-.127-.592-.531-1.12-1.159-1.777-1.003-1.051-1.443-1.69-2.418-3.54-.956-1.813-1.797-3.855-3.16-7.683-1.124-3.16-1.676-4.712-1.94-5.585-.266-.873-.247-1.008-.255-1.577-.006-.482-.006-.766-.087-1.05-.08-.285-.302-.517-.49-.652a2.727 2.727 0 0 0-1.024-.434 1.624 1.624 0 0 0-.387-.043zm62.475.054c-.468-.003-.89.203-1.26.488s-.692.663-.837 1.132c-.127.41-.294 1.356-.508 2.618a141.78 141.78 0 0 0-.63 4.077c-.658 4.782-1.01 7.404-1.176 9.08-.165 1.675-.139 2.432-.04 3.368.079.756.165 1.285.327 1.713.162.428.444.76.789.951.602.334 1.344.19 1.982-.265.372-.265.642-.678.742-1.177.101-.498.079-1.085-.011-1.88-.372-3.29.264-9.4 1.575-14.749.235-.957.404-1.719.51-2.289.053-.284.092-.52.113-.717.02-.196.036-.336.001-.52-.154-.814-.502-1.503-1.17-1.757a1.165 1.165 0 0 0-.407-.073zm-45.224.126a2.36 2.36 0 0 0-.65.116c-.257.08-.526.183-.757.403-.23.22-.38.52-.49.901-.22.762-.338 1.94-.55 4.155-.58 6.05-1.488 13.41-1.851 15.137-.15.717-.156 1.355.029 1.903.185.549.59.989 1.128 1.212.274.113.61.13 1.021.056.412-.075.953-.228 1.806-.489 3.198-.975 5.79-1.315 9.281-1.215 1.194.035 1.838.051 2.302.018a2.64 2.64 0 0 0 1.074-.299c.974-.491 1.519-1.511 1.2-2.478-.143-.433-.429-.84-.872-.994-.444-.154-.917-.105-1.572.005-.514.087-1.888.229-2.971.303-2.716.185-3.454.262-5.554.59-.97.153-2.177.251-2.457.235l-.314-.017-.022-.487c-.012-.285.028-1.032.12-2.05.094-1.018.235-2.33.415-3.833.36-3.008.872-6.792 1.444-10.595.055-.365.085-.627.058-.891a1.785 1.785 0 0 0-.252-.715c-.347-.597-.921-.987-1.566-.971zm26.959.174c-.733.02-1.577.064-2.583.128-1.95.123-4.24.188-4.965.153-.93-.045-1.573-.03-2.117.2s-.886.7-1.124 1.271a1.24 1.24 0 0 0 .155 1.176c.241.33.6.572 1.062.793.31.148.409.23.402.22-.007-.008.017.026.036.303a8.64 8.64 0 0 1-.054.88 25.684 25.684 0 0 1-.188 1.428c-.435 2.704-.975 7.432-1.22 10.684-.11 1.452-.197 2.345-.305 2.957-.108.613-.227.935-.436 1.345-.118.231-.211.43-.23.677-.02.247.053.466.14.674.163.385.457.735.786 1.012.337.283.805.49 1.304.397.499-.093 1.018-.361 1.89-.83.96-.515 1.743-.798 3.6-1.286 2.713-.714 4.266-1.254 6.029-2.097 4.12-1.97 7.201-5.227 8.141-8.742.357-1.335.37-3.444.022-4.77-.741-2.823-2.82-5.032-5.647-6.015-1.297-.45-2.502-.616-4.698-.558zm-94.947.141c2.09.008 3.281.282 4.882 1.115 2.547 1.325 4.203 3.662 5.061 7.242.282 1.176.308 1.578.3 4.5-.003 1.613-.04 2.6-.102 3.277-.286-.85-.744-1.601-1.463-1.95a3.485 3.485 0 0 0-.558-.217 1.484 1.484 0 0 0-.26-.054c-.092-.01-.19-.057-.415.081-.204.127-.208.216-.246.295a1.687 1.687 0 0 0-.093.24c-.032.103-.051.23-.075.351.095-1.404.107-2.563-.146-3.508-.279-1.044-.826-1.9-1.65-2.792-1.078-1.166-2.156-1.668-3.718-1.729a7.374 7.374 0 0 0-.89.006 1.36 1.36 0 0 0-.325.058c-.058.02-.126.04-.223.122-.022.02-.018.086-.04.119-.122-.092-.186-.262-.326-.314-.406-.152-.842-.169-1.355-.16-1.67.032-3.151.758-4.253 2.003-1 1.128-1.65 2.714-1.996 4.563l.01-.672h-.985c-1.107 0-1.95.961-2.442 2.205.004-.37-.003-.546.02-1.302.102-3.391.514-5.258 1.647-7.521 1.208-2.415 2.6-3.832 4.804-4.91 1.72-.843 2.697-1.055 4.837-1.047zm50.764.497c.015 0 .066.003.163.023.164.033.548.2.643.267.134.096.092.041.113.115.02.073.043.326.05.796.008.559.015.925.296 1.85.282.927.833 2.47 1.958 5.63 1.368 3.845 2.23 5.938 3.217 7.81.99 1.878 1.531 2.67 2.577 3.766.58.608.852 1.05.905 1.298.053.248.01.373-.314.68-.389.37-.588.405-.973.233-.09-.04-.508-.356-.891-.754a9.376 9.376 0 0 1-1.052-1.298c-.08-.122-.348-.6-.665-1.202a111.677 111.677 0 0 1-1.07-2.087l-1.477-2.957-.811-.068c-.551-.046-1.45.092-2.61.296s-2.504.49-3.65.791c-1.245.327-1.94.497-2.314.545-.373.048-.326.04-.488-.066a1.613 1.613 0 0 0-.43-.202c-.15-.044-.287-.105-.553-.004-.25.096-.333.225-.467.388a7.542 7.542 0 0 0-.467.659c-.369.567-.874 1.419-1.581 2.65-.613 1.068-1.037 1.751-1.345 2.158-.308.407-.465.502-.568.53.118-.033-.108-.021-.337-.162a2.496 2.496 0 0 1-.65-.589 2.445 2.445 0 0 1-.096-.138c.004.026.025-.076.153-.362.026-.058.346-.615.767-1.279.422-.664.967-1.497 1.531-2.337 2.47-3.674 3.898-6.046 6.01-9.992 2.276-4.252 3.238-5.822 3.903-6.512.224-.233.375-.376.455-.436.08-.06.047-.04.068-.04zm62.44.054a.19.19 0 0 1 .062.008c.137.052.43.398.547 1.015-.007-.036.005.075-.012.23-.017.156-.05.373-.1.642-.101.538-.269 1.286-.5 2.233-1.335 5.444-1.997 11.553-1.596 15.098.085.752.086 1.26.024 1.57-.063.31-.144.422-.343.564-.47.334-.68.344-.929.207-.166-.092-.238-.162-.34-.434-.104-.272-.192-.742-.268-1.467-.095-.903-.12-1.528.04-3.167.162-1.638.514-4.26 1.173-9.04.178-1.292.412-2.797.624-4.048.212-1.252.424-2.317.479-2.492.059-.192.2 [...]

2024-08-26 08:43 UTC, weh commented on icons/kaldi/kaldi-line.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M63.9992.0086c-1.023.0154-1.9595.0522-2.7325.1124-4.8744.3798-10.0343 1.4267-14.1936 2.8837-3.0753 1.0772-6.4327
Optimized version
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M64 .009c-1.024.015-1.96.052-2.733.112-4.875.38-10.035 1.427-14.194 2.884-3.075 1.077-6.433 2.611-7.909 3.66a23.77 23.77 0 0 1-1.552.993c-.9.517-2.19 1.416-4.132 2.87-.824.617-2.17 1.778-3.422 2.914-1.252 1.137-2.37 2.2-2.814 2.752-.34.423-1.09 1.31-1.647 1.95a50.374 50.374 0 0 0-1.737 2.093 14.2 14.2 0 0 0-.537.73 3.32 3.32 0 0 0-.166.266c-.045.083-.109.102-.109.362 0-.177.026-.156.03-.162.002-.007-.001.003-.008.017a3.819 3.819 0 0 1-.084.15 21.465 21.465 0 0 1-.343.563 83.04 83.04 0 0 1-1.145 1.773c-2.182 3.293-4.985 8.893-6.099 12.208-3.073 9.143-4.337 15.02-4.92 22.897-.3 4.043-.385 11.78-.167 15.222.105 1.657.26 4.231.345 5.717.11 1.902.241 3.075.641 3.894.2.409.497.731.867.916.37.185.78.237 1.228.237.762 0 1.425-.206 1.857-.702.431-.496.583-1.186.583-2.029 0-.241.01-.417.025-.513.017-.097.032-.092.012-.072-.02.02-.031.008.06-.008.092-.016.262-.025.498-.025.212 0 .379.065.473.138.094.072.118.127.118.197 0 .274.066.56.163.934s.23.814.388 1.28c.314.93.72 1.96 1.106 2.753 1.73 3.555 4.773 5.855 8.438 6.341.533.07 1.047.023 1.487-.137.44-.16.833-.444 1.005-.892.041-.107.03-.112.033-.14a1.617 1.617 0 0 0 .01-.079 6.587 6.587 0 0 0 .015-.21c.01-.17.021-.405.033-.7.024-.591.052-1.42.082-2.421.06-2.004.13-4.699.196-7.539.132-5.68.251-11.936.255-14.432.003-1.61.059-2.411-.246-3.05a1.217 1.217 0 0 0-.794-.628c-.316-.073-.625-.06-1.01-.052-2.486.05-4.705 1.211-7.093 3.624-1.059 1.07-1.573 1.763-2.085 2.833-.911 1.904-1.556 3.708-1.886 5.306-.072.351-.157.696-.234.96a4.58 4.58 0 0 1-.105.317c-.028.075-.081.137-.008.049.108-.13.057-.047-.06-.022-.116.026-.29.046-.47.05a3.12 3.12 0 0 1-.791-.092c-.01-.023-.026-.061-.047-.177-.05-.276-.094-.816-.143-1.72-.288-5.257-.03-14.569.508-18.626.827-6.246 2.801-13.944 4.97-19.39 2.056-5.16 5.998-11.643 9.624-15.825 4.324-4.986 10.528-9.308 16.89-11.761 1.11-.429 2.195-.863 2.548-1.033.504-.244 1.809-.635 3.39-1a68.391 68.391 0 0 1 5.259-.989c2.292-.336 9.928-.486 12.542-.24 1.936.182 4.269.543 6.27.94 2 .397 3.731.87 4.234 1.126.364.186 1.193.51 1.973.789 5.445 1.943 10.624 5.255 14.614 9.345 2.098 2.15 3.479 3.81 3.812 4.457.205.396.721 1.194 1.211 1.897 1.825 2.618 3.414 5.674 5.08 9.783.302.746.797 2.193 1.21 3.488.208.648.396 1.258.53 1.729.067.235.121.438.157.585.035.147.044.287.044.206 0 .133.018.205.041.33.023.127.055.279.093.452.077.348.18.78.295 1.216 1.82 6.895 2.682 16.38 2.265 25.026a157.301 157.301 0 0 1-.854 10.17 74.12 74.12 0 0 1-.541 3.869 16.76 16.76 0 0 1-.246 1.196c-.075.29-.205.504-.122.405.066-.08.024-.02-.088.006-.11.025-.275.04-.441.036a2.193 2.193 0 0 1-.463-.056c-.126-.031-.2-.09-.167-.058.036.036-.029-.045-.062-.161a1.559 1.559 0 0 1-.056-.403c0-1.361-.638-4.094-1.256-5.525-.823-1.902-2.043-3.834-3.08-4.733-1.232-1.067-3.307-2.09-4.697-2.234-.375-.039-.688-.135-1.097-.027a1.147 1.147 0 0 0-.562.358c-.149.175-.253.383-.349.638-.384 1.021-.681 2.94-1.41 7.09-.232 1.318-1.178 6.26-2.098 10.952a352.65 352.65 0 0 0-1.19 6.349c-.15.857-.272 1.582-.356 2.13-.085.548-.136.867-.136 1.114 0 .457-.015.735.11 1.047.127.31.406.489.656.618.354.183.96.397 1.477.543 1.41.396 3.45.256 4.978-.305 1.53-.561 3.145-1.727 4.543-3.24 1.343-1.454 2.658-3.982 3.467-6.566.343-1.097.556-1.704.697-1.961.07-.129.107-.156.118-.163.012-.007.03-.019.136-.03a.776.776 0 0 1 .262.003c.034.01.018 0 .029.014.02.027.105.258.105.722 0 .405.005.696.12.99.115.296.327.503.571.708.962.81 2.317.723 3.295-.16.318-.289.577-.561.746-.999.17-.438.28-1.005.492-2.077 1.036-5.232 1.92-11.955 2.29-17.413.227-3.34.228-11.319 0-14.416-.481-6.581-1.677-13.305-3.398-19.11-1.316-4.438-3.516-9.431-5.706-12.932a79.599 79.599 0 0 1-1.496-2.49c-.71-1.262-1.165-1.863-3.49-4.582-2.237-2.616-5.432-5.487-8.159-7.331-1.066-.722-2.189-1.518-2.37-1.665-.452-.367-1.43-.899-2.612-1.508-1.182-.609-2.513-1.245-3.487-1.645-3.829-1.574-9.08-2.9-13.668-3.454-2.356-.284-6.185-.426-9.254-.38Zm.015.992c3.025-.046 6.852.098 9.118.372 4.489.542 9.698 1.86 13.412 3.388.925.38 2.245 1.009 3.407 1.608 1.163.599 2.223 1.218 2.444 1.397.323.262 1.363.987 2.44 1.715 2.627 1.778 5.791 4.62 7.957 7.153 2.32 2.714 2.694 3.2 3.382 4.423.32.57.997 1.697 1.52 2.533 2.122 3.394 4.309 8.346 5.596 12.687 1.697 5.725 2.883 12.39 3.36 18.901.218 2.97.22 11.046 0 14.277-.366 5.406-1.25 12.107-2.275 17.285-.212 1.07-.332 1.625-.444 1.913-.11.288-.183.345-.488.62-.702.634-1.366.661-1.988.137-.212-.178-.259-.237-.287-.31-.028-.072-.052-.249-.052-.628 0-.542-.035-.969-.31-1.327a1.071 1.071 0 0 0-.557-.368 1.648 1.648 0 0 0-.633-.03c-.17.02-.375.061-.564.185-.19.123-.331.304-.448.517-.233.426-.428 1.039-.773 2.144-.77 2.462-2.084 4.923-3.25 6.185-1.31 1.418-2.836 2.5-4.155 2.985-1.288.473-3.29.585-4.37.28-.454-.127-1.092-.367-1.287-.468-.217-.112-.185-.095-.192-.11s-.039-.23-.039-.675c0-.023.042-.427.124-.963a105.1 105.1 0 0 1 .353-2.109c.3-1.704.718-3.941 1.186-6.33.92-4.696 1.863-9.618 2.1-10.972.73-4.154 1.074-6.143 1.363-6.912.073-.193.14-.3.177-.343.037-.044.031-.036.058-.043.053-.014.317.012.744.056.945.098 3.124 1.108 4.147 1.994.77.667 2.047 2.593 2.82 4.38.521 1.207 1.174 4.13 1.174 5.13 0 .236.034.467.095.678.061.212.13.402.314.587.196.196.407.263.626.318.22.055.454.083.686.087.233.005.462-.013.679-.062.216-.048.437-.104.633-.34.217-.261.235-.459.32-.791.085-.333.172-.76.262-1.272.179-1.022.368-2.379.55-3.922.364-3.087.7-6.916.86-10.24.423-8.747-.44-18.288-2.296-25.325a30.879 30.879 0 0 1-.287-1.177 11.41 11.41 0 0 1-.085-.414c-.02-.107-.025-.204-.025-.155 0-.186-.033-.269-.074-.438a16.177 16.177 0 0 0-.166-.624 60.341 60.341 0 0 0-.537-1.76c-.419-1.31-.911-2.75-1.239-3.558-1.683-4.154-3.306-7.283-5.184-9.977-.473-.678-1.017-1.537-1.145-1.785-.495-.959-1.863-2.525-3.983-4.697-4.102-4.205-9.396-7.59-14.99-9.585-.754-.27-1.649-.633-1.856-.739-.807-.412-2.458-.814-4.49-1.217-2.033-.403-4.388-.767-6.37-.953-2.82-.265-10.234-.126-12.78.248-1.822.267-3.729.63-5.338 1.002-1.61.372-2.893.732-3.597 1.071-.2.097-1.375.578-2.475 1.002-6.524 2.517-12.836 6.91-17.28 12.037-3.726 4.296-7.688 10.81-9.8 16.108-2.21 5.551-4.192 13.282-5.032 19.626-.557 4.21-.808 13.46-.515 18.812.05.913.088 1.458.158 1.845.036.193.08.351.163.505a.953.953 0 0 0 .36.365c.412.22.858.225 1.318.213.23-.007.453-.029.657-.074.204-.045.399-.06.61-.316.124-.148.131-.218.173-.33a5.432 5.432 0 0 0 .128-.389c.087-.296.178-.66.256-1.037.308-1.491.924-3.23 1.808-5.077.476-.994.871-1.531 1.896-2.566 2.287-2.31 4.21-3.284 6.406-3.33.38-.007.647 0 .766.028.118.027.08-.002.124.09.087.18.152 1.013.15 2.621-.005 2.467-.124 8.732-.257 14.409-.066 2.838-.135 5.53-.195 7.53-.03 1-.058 1.83-.082 2.413a44.165 44.165 0 0 1-.03.683c-.005.063-.01.104-.012.141-.039.084-.153.213-.403.304-.261.095-.627.137-1.014.086-3.335-.443-6.073-2.494-7.678-5.791a24.341 24.341 0 0 1-1.427-3.847 4.238 4.238 0 0 1-.13-.686c0-.4-.212-.76-.507-.986a1.754 1.754 0 0 0-1.076-.341 3.85 3.85 0 0 0-.67.04 1.082 1.082 0 0 0-.597.29c-.17.172-.246.394-.281.6-.035.206-.039.42-.039.68 0 .72-.14 1.147-.341 1.378-.2.23-.509.36-1.107.36-.366 0-.616-.047-.784-.131-.17-.085-.29-.201-.42-.465-.257-.529-.432-1.645-.54-3.516-.086-1.49-.243-4.062-.349-5.72-.21-3.33-.127-11.125.167-15.088.579-7.808 1.815-13.552 4.874-22.653 1.06-3.154 3.872-8.794 5.983-11.978.45-.68.86-1.315 1.16-1.795.15-.24.273-.439.36-.59a4.332 4.332 0 0 0 .11-.196 1.127 1.127 0 0 0 .04-.088c.014-.034.047-.03.047-.219 0 .214-.031.149-.012.113a2.58 2.58 0 0 1 .116-.186c.112-.166.285-.4.5-.677a49.415 49.415 0 0 1 1.7-2.05c.566-.65 1.31-1.528 1.67-1.977.307-.38 1.471-1.517 2.71-2.641 1.238-1.124 2.589-2.286 3.348-2.855 1.93-1.444 3.212-2.33 4.035-2.804a23.674 23.674 0 0 0 1.63-1.043c1.255-.892 4.658-2.48 7.665-3.532 4.057-1.422 9.154-2.46 13.941-2.834a44.35 44.35 0 0 1 2.67-.108zM59.94 37.33c-2.308-.005-4.947.34-7.223 1.003-4.32 1.259-6.78 2.674-9.536 5.494-2.165 2.214-2.973 3.2-3.963 4.839-.192.317-.367.609-.495.827a15.371 15.371 0 0 0-.153.268 3.096 3.096 0 0 0-.048.089c-.007.013-.015.026-.023.046- [...]

2024-08-26 08:43 UTC, weh commented on icons/kaldi/kaldi-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M10.6915 78.6004c-2.5824-.545-4.7727-3.4766-5.435-7.2743-.2477-1.4208-.2846-5.0544-.0668-6.5834.5839-4.098 2.863-
Optimized version
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M10.691 78.6c-2.582-.545-4.772-3.476-5.435-7.274-.247-1.42-.284-5.054-.066-6.583.584-4.098 2.863-6.672 5.959-6.73 1.978-.037 2.21.474 2.234 4.935.018 3.313-.234 5.022-1.033 7.02-.589 1.471-.747 2.747-.588 4.754l.13 1.65.027-2.297c.02-1.68.086-2.451.249-2.871.893-2.305 1.205-3.434 1.427-5.17.3-2.343.228-5.967-.14-6.963-.13-.355-.252-.71-.27-.79-.02-.089.403-.126 1.117-.098 1.49.058 2.369.467 3.4 1.583 1.598 1.731 1.964 3.1 1.695 6.34-.191 2.31-.47 3.818-1.013 5.464-.824 2.499-1.873 4.226-3.389 5.577-1.444 1.289-2.844 1.761-4.303 1.453z"/><path fill="#4d4d4d" d="M98.082 74.341c-.258-.217-.552-.59-.652-.83-.157-.372-.146-.506.075-.94.452-.89.576-1.592.798-4.526.247-3.259.791-8.027 1.225-10.726.162-1.002.274-2.1.25-2.44-.043-.58-.086-.637-.725-.943-.845-.403-1.18-.862-.98-1.343.434-1.043.95-1.261 2.781-1.173.805.038 3.08-.032 5.057-.157 4.044-.255 5.47-.173 7.143.408 2.703.94 4.666 3.03 5.371 5.717.312 1.19.303 3.348-.019 4.552-.896 3.352-3.89 6.555-7.936 8.488-1.75.836-3.27 1.365-5.99 2.08-1.885.497-2.735.801-3.737 1.34-1.743.935-2.065.995-2.661.493zm6.365-4.074c2.754-.754 3.918-1.177 5.444-1.975 2.42-1.265 4.41-3.176 5.344-5.129.664-1.388.847-2.358.765-4.042-.057-1.153-.142-1.568-.465-2.246-.748-1.576-2.457-2.868-4.401-3.326-1.096-.258-4.075-.291-6.376-.07-2.107.202-2.18.222-2.28.62-.17.675-1.228 8.39-1.446 10.537-.223 2.196-.299 5.556-.135 5.982.147.383 1.284.27 3.55-.35zm-74.224 4.105c-.744-.324-.804-.773-.412-3.053.187-1.09.508-3.694.713-5.787.816-8.324 1.45-12.971 1.883-13.81.258-.499.968-.883 1.393-.754.958.292 1.199 1.094.811 2.701-.62 2.572-1.405 8.458-1.259 9.446.079.532 2.607-1.536 6.043-4.94 2.724-2.7 3.18-3.221 3.964-4.518.921-1.524 1.324-1.945 1.722-1.802.505.18 1 .629 1.229 1.111.227.48.225.537-.037 1.116-.581 1.282-2.777 3.448-8.258 8.15-1.285 1.102-1.39 1.229-1.149 1.39.146.097 1.737 1.307 3.535 2.688 5.278 4.053 6.231 4.617 8.056 4.772 1.22.103 1.311.194 1.102 1.102-.233 1.012-1.143 1.628-2.133 1.444-1.5-.279-2.52-.943-9.171-5.974-1.198-.906-2.597-1.865-3.108-2.13-.807-.419-.978-.46-1.296-.315-.792.36-1.168 1.573-1.389 4.478-.233 3.068-.614 4.38-1.37 4.725-.2.091-.377.163-.393.16-.016-.003-.23-.093-.476-.2zm42.23.009c-.503-.225-1.582-1.345-2.173-2.255-.227-.35-1.026-1.863-1.776-3.363l-1.364-2.728-.536-.044c-.762-.064-3.867.483-6.14 1.08-2.514.662-2.796.698-3.225.417-.193-.126-.435-.197-.538-.157-.252.096-.858 1.028-2.28 3.506-1.242 2.162-1.723 2.8-2.225 2.942-.347.099-1.11-.37-1.534-.942-.276-.373-.276-.383.003-1.005.154-.345 1.216-2.02 2.359-3.72 2.483-3.693 3.905-6.058 6.03-10.026 2.296-4.29 3.257-5.888 4.015-6.675.613-.636.713-.687 1.15-.599.264.054.641.213.839.354.324.232.36.358.373 1.317.016 1.137-.023 1.007 2.244 7.378 1.375 3.866 2.233 5.95 3.212 7.806.99 1.879 1.484 2.601 2.517 3.683 1.217 1.275 1.362 1.956.578 2.702-.488.464-.988.571-1.53.329zm-12.564-9.642c.75-.114 2.495-.424 3.877-.69 2.238-.43 2.51-.512 2.484-.756-.045-.443-2.796-8.53-2.901-8.53-.053 0-.31.437-.572.97-.261.533-1.365 2.649-2.452 4.702a898.888 898.888 0 0 0-2.225 4.22l-.25.487.338-.098c.185-.054.95-.191 1.701-.305zm18.45 9.274c-.844-.35-1.145-1.245-.866-2.574.389-1.85 1.288-9.204 1.873-15.311.427-4.46.518-4.774 1.462-5.073.745-.235 1.26-.037 1.653.637.218.374.239.58.132 1.292-1.154 7.675-2.062 15.27-1.999 16.705l.042.94.766.044c.42.024 1.584-.084 2.584-.241 2.112-.331 2.818-.407 5.552-.593 1.106-.075 2.475-.215 3.043-.31 1.27-.213 1.665-.076 1.908.66.24.729-.141 1.48-.96 1.894-.567.287-.76.3-3.163.232-3.558-.102-6.25.25-9.514 1.246-1.712.522-2.153.601-2.513.452zm45.435-.504c-.515-.285-.713-.81-.87-2.303-.195-1.853-.103-2.785 1.225-12.422.36-2.618.947-6.08 1.13-6.671.234-.761 1.286-1.459 1.866-1.238.406.154.73.676.866 1.396.057.3-.153 1.423-.623 3.342-1.333 5.44-1.987 11.597-1.598 15.041.176 1.56.045 2.206-.53 2.616-.558.398-1.037.476-1.466.239zM19.507 72.182c-.336-.088-.328-.19.234-3 .267-1.336.53-2.735.583-3.108.053-.373.16-.717.236-.765.076-.047.418.05.76.215.708.342 1.284 1.246 1.452 2.278.076.463.16.606.334.572.387-.074.503-1.128.511-4.636.007-2.95-.026-3.448-.316-4.654-.887-3.704-2.654-6.218-5.358-7.625-1.667-.867-2.996-1.171-5.149-1.179-2.194-.008-3.321.236-5.097 1.105-2.306 1.129-3.815 2.67-5.068 5.173-1.17 2.339-1.61 4.336-1.714 7.79-.077 2.58-.074 2.62.219 2.62.234 0 .344-.159.52-.754.4-1.352 1.286-2.261 2.204-2.261h.484l-.045 3.29c-.025 1.81-.088 3.333-.139 3.384-.198.197-1.137-.12-1.634-.55-.347-.302-.609-.716-.786-1.242-.268-.798-.717-1.167-.717-.59 0 .321-.431.626-.668.472-.284-.186-.358-.957-.353-3.681.006-3.042.177-4.307.89-6.604.999-3.213 2.662-5.572 5.048-7.156 2.028-1.347 4.17-1.97 6.764-1.967 5.13.004 8.747 2.39 10.684 7.047 1.004 2.414 1.469 5.956 1.196 9.117-.214 2.488-.516 4.212-.785 4.481-.273.273-.665.123-.665-.253 0-.546-.362-.295-.62.429-.554 1.563-1.75 2.38-3.005 2.052z"/></svg>
```

2024-08-26 08:43 UTC, weh commented on icons/kaldi/kaldi-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M58.2349 127.8993c-3.688-.5217-7.9022-2.351-10.7057-4.647-2.5818-2.1145-6.2208-6.404-7.6075-8.9677-.2937-.5428-.8
Optimized version
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M58.235 127.9c-3.688-.522-7.902-2.352-10.706-4.648-2.582-2.114-6.22-6.404-7.607-8.967-.294-.543-.857-1.557-1.25-2.253-1.387-2.449-2.956-5.889-2.956-6.481 0-.116-.195-.691-.433-1.278-2.915-7.173-4.07-22.105-2.682-34.686.536-4.863.986-7.024 2.3-11.054 1.102-3.378 1.651-4.679 2.863-6.776.545-.943.99-1.732.99-1.755 0-.023.315-.562.699-1.198.982-1.626 1.75-2.562 3.924-4.785 2.734-2.797 5.087-4.15 9.395-5.406 3.581-1.044 8.147-1.298 10.699-.595 2.8.77 4.124 2.701 4.894 7.138.506 2.915.643 6.061.663 15.233.017 7.945-.02 9.497-.28 11.392-.79 5.795-2.014 11.739-2.935 14.25-.326.888-.7 1.956-.834 2.374-.133.417-.577 1.556-.986 2.531-.962 2.288-1.87 5.307-2.11 7.01-.325 2.3-.401 6.747-.187 10.83.276 5.282.53 5.924.454 1.146-.072-4.432.131-10.644.405-12.404.136-.876.53-2.029 1.277-3.742.595-1.362 1.081-2.55 1.081-2.64 0-.09.304-.93.675-1.866 2.394-6.041 3.215-9.883 4.418-20.696.291-2.615.289-16.984-.003-19.998-.368-3.797-.918-6.21-1.8-7.894-.417-.798-.758-1.547-.758-1.663 0-.758 1.627-.895 6.835-.573 3.617.223 5.622.883 8.607 2.834 2.07 1.352 6.202 5.397 7.367 7.211 1.793 2.791 2.494 3.947 3.018 4.979 1.676 3.299 2.397 8.99 2.025 15.99-.165 3.114-.336 4.996-1.019 11.266-.488 4.473-2.027 11.436-3.473 15.704-.41 1.212-.746 2.317-.746 2.456 0 .37-1.644 4.262-2.914 6.902a130.81 130.81 0 0 0-1.442 3.073c-.399.92-1.374 2.46-3.29 5.196-.998 1.425-2.17 2.753-4.409 4.996-4.738 4.745-6.639 6.164-10.56 7.88-2.091.915-2.534 1.002-5.4 1.057-1.532.03-3.246-.011-3.81-.09z"/><path fill="#505050" d="M96.174 99.799c-.49-.138-1.116-.368-1.393-.51-.47-.244-.503-.325-.503-1.233 0-.546.741-4.751 1.686-9.574.927-4.73 1.88-9.701 2.116-11.047 1.47-8.37 1.285-7.878 2.902-7.711 1.176.121 3.321 1.147 4.458 2.131.91.789 2.168 2.732 2.971 4.592.575 1.328 1.225 4.18 1.225 5.37 0 .372.115.772.266.922.329.33 1.643.355 1.907.037.54-.65 1.57-9.388 1.891-16.058.423-8.765-.445-18.351-2.298-25.372-.228-.867-.416-1.716-.416-1.887 0-.42-1.359-4.676-1.993-6.241-1.688-4.164-3.307-7.28-5.173-9.958-.485-.696-1.02-1.531-1.187-1.856-.418-.809-1.802-2.435-3.927-4.613-4.078-4.18-9.357-7.555-14.92-9.54-.773-.276-1.641-.622-1.93-.769-1.32-.674-6.814-1.764-10.764-2.135-2.737-.257-10.323-.11-12.76.248-3.646.535-7.644 1.458-8.861 2.045-.279.135-1.418.596-2.532 1.026-6.493 2.504-12.8 6.897-17.218 11.993-3.705 4.272-7.688 10.82-9.787 16.09-2.208 5.541-4.202 13.317-5.042 19.662-.552 4.166-.807 13.52-.514 18.865.1 1.833.164 2.182.422 2.32.442.237 1.774.2 1.985-.054.1-.12.305-.818.456-1.55.322-1.558.957-3.343 1.862-5.234.497-1.04.955-1.661 2.005-2.722 2.356-2.38 4.442-3.454 6.802-3.502 1.54-.032 1.563.015 1.558 3.258-.008 5.001-.48 25.242-.596 25.543-.206.536-1.051.843-1.979.72-3.527-.468-6.441-2.66-8.121-6.114-.749-1.538-1.62-4.113-1.62-4.788 0-.475-.474-.837-1.095-.837-.989 0-1.099.113-1.099 1.124 0 1.574-.59 2.252-1.96 2.252-1.641 0-2.039-.813-2.258-4.616-.087-1.5-.244-4.093-.35-5.763-.216-3.413-.13-11.24.17-15.274.585-7.904 1.844-13.759 4.934-22.952 1.096-3.26 3.925-8.924 6.088-12.188.905-1.366 1.646-2.552 1.646-2.636 0-.19 1.09-1.593 2.445-3.15.566-.65 1.319-1.54 1.672-1.98.758-.94 4.6-4.427 6.197-5.622 1.95-1.46 3.247-2.362 4.115-2.861a23.831 23.831 0 0 0 1.603-1.025c1.377-.978 4.783-2.552 7.848-3.626C51.248 1.55 56.416.5 61.284.12c3.054-.237 8.876-.107 11.98.268 4.575.553 9.847 1.884 13.648 3.447 1.913.786 5.342 2.554 6.02 3.104.255.205 1.346.972 2.426 1.702 2.698 1.825 5.902 4.705 8.12 7.3 2.342 2.737 2.76 3.284 3.464 4.536a79.82 79.82 0 0 0 1.519 2.531c2.173 3.475 4.384 8.487 5.695 12.911 1.723 5.81 2.923 12.558 3.407 19.155.224 3.058.223 11.147-.001 14.458-.371 5.475-1.26 12.238-2.3 17.484-.427 2.16-.466 2.26-1.094 2.827-.847.765-1.864.822-2.662.15-.46-.386-.52-.54-.52-1.329 0-1.014-.238-1.324-.954-1.241-.557.065-.686.301-1.38 2.52-.796 2.543-2.12 5.057-3.385 6.426-1.365 1.477-2.946 2.608-4.382 3.135-1.419.521-3.456.649-4.711.296z"/></svg>
```

2024-08-26 08:43 UTC, weh commented on icons/kaldi/kaldi-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M12.7031 49.3086c-2.5947-.0022-4.7383.6206-6.7656 1.9668-2.386 1.5844-4.0487 3.9432-5.0469 7.1562C.177 60.7288.00
Optimized version
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M12.703 49.309c-2.595-.003-4.738.62-6.766 1.966C3.551 52.86 1.89 55.22.891 58.432.177 60.729.006 61.993 0 65.035c-.005 2.725.07 3.496.353 3.682.237.154.669-.151.669-.473 0-.577.448-.207.716.59.177.526.439.941.785 1.242.497.431 1.437.748 1.635.551.051-.051.114-1.573.139-3.383l.045-3.29h-.485c-.918 0-1.803.908-2.203 2.26-.176.596-.286.755-.521.755-.293 0-.295-.041-.217-2.621.104-3.454.543-5.45 1.713-7.79 1.253-2.504 2.763-4.045 5.068-5.173 1.776-.87 2.903-1.114 5.098-1.106 2.153.008 3.482.313 5.148 1.18 2.705 1.407 4.47 3.921 5.358 7.625.29 1.207.323 1.705.316 4.654-.008 3.509-.125 4.563-.511 4.637-.176.034-.259-.11-.334-.574-.169-1.032-.744-1.935-1.452-2.278-.341-.165-.683-.262-.76-.214-.076.047-.182.392-.236.765-.053.374-.317 1.772-.584 3.108-.561 2.809-.57 2.912-.234 3 1.255.328 2.452-.49 3.008-2.053.257-.724.619-.973.619-.428 0 .377.391.527.664.254.269-.269.57-1.994.785-4.482.273-3.162-.191-6.703-1.195-9.117-1.937-4.657-5.555-7.043-10.684-7.047zm51.238 1.47c-.241.007-.413.156-.873.633-.758.786-1.718 2.383-4.015 6.674-2.124 3.968-3.546 6.334-6.03 10.027-1.143 1.7-2.204 3.374-2.359 3.719-.279.622-.278.633-.002 1.006.424.572 1.186 1.04 1.533.941.502-.142.984-.779 2.225-2.941 1.422-2.478 2.029-3.411 2.281-3.508.103-.04.345.032.537.158.429.281.711.245 3.225-.416 2.274-.597 5.379-1.145 6.14-1.082l.538.045 1.363 2.729c.75 1.5 1.548 3.014 1.775 3.363.591.91 1.672 2.03 2.174 2.254.542.242 1.042.136 1.53-.328.784-.746.638-1.428-.579-2.703-1.032-1.083-1.527-1.804-2.517-3.682-.98-1.857-1.837-3.94-3.213-7.807-2.267-6.37-2.227-6.241-2.242-7.379-.014-.958-.049-1.084-.373-1.316a2.617 2.617 0 0 0-.84-.354 1.242 1.242 0 0 0-.278-.033zm62.948.055c-.594-.004-1.426.613-1.631 1.28-.182.59-.768 4.051-1.13 6.67-1.327 9.636-1.418 10.57-1.224 12.423.157 1.493.355 2.016.87 2.3.428.238.908.16 1.466-.238.575-.409.706-1.056.53-2.615-.39-3.444.264-9.602 1.597-15.04.47-1.92.68-3.043.623-3.343-.136-.72-.46-1.242-.865-1.396a.673.673 0 0 0-.236-.041zm-93.45.127c-.39.077-.84.388-1.033.762-.434.838-1.067 5.486-1.883 13.81-.205 2.093-.525 4.695-.713 5.785-.392 2.28-.331 2.73.413 3.053.246.107.46.198.476.201a2.94 2.94 0 0 0 .393-.16c.756-.345 1.138-1.656 1.37-4.725.222-2.904.597-4.117 1.39-4.478.318-.145.488-.104 1.295.314.51.265 1.91 1.225 3.109 2.131 6.65 5.031 7.67 5.696 9.17 5.975.99.184 1.9-.433 2.133-1.445.209-.908.118-.999-1.102-1.102-1.825-.154-2.779-.719-8.057-4.771-1.798-1.382-3.389-2.593-3.535-2.69-.24-.16-.134-.287 1.15-1.389 5.482-4.701 7.677-6.868 8.258-8.15.263-.578.263-.636.036-1.115a2.315 2.315 0 0 0-1.229-1.112c-.398-.143-.8.277-1.72 1.801-.784 1.297-1.242 1.818-3.965 4.518-3.436 3.405-5.965 5.473-6.044 4.941-.145-.988.64-6.873 1.26-9.445.388-1.607.148-2.41-.81-2.701a.753.753 0 0 0-.361-.008zm47.887 0c-.159.004-.331.035-.517.094-.945.299-1.036.612-1.463 5.072-.585 6.107-1.485 13.462-1.873 15.312-.28 1.33.023 2.225.867 2.575.36.15.8.069 2.512-.453 3.264-.996 5.955-1.349 9.513-1.247 2.404.07 2.597.057 3.164-.23.82-.413 1.2-1.167.96-1.895-.244-.736-.638-.872-1.907-.66-.568.096-1.937.236-3.043.31-2.734.187-3.441.262-5.553.593-1 .157-2.163.266-2.584.242l-.765-.045-.043-.94c-.064-1.435.846-9.029 2-16.705.107-.71.085-.918-.133-1.293-.294-.505-.657-.742-1.135-.73zm27.172.176c-.728.019-1.575.063-2.586.127-1.977.124-4.254.194-5.059.156-1.83-.088-2.346.13-2.78 1.174-.2.48.135.938.98 1.342.639.305.683.363.724.943.025.34-.086 1.438-.248 2.441-.434 2.699-.98 7.466-1.226 10.725-.222 2.934-.347 3.636-.8 4.525-.22.434-.23.57-.073.942.1.239.394.613.652.83.596.502.918.441 2.66-.494 1.002-.539 1.854-.844 3.738-1.34 2.72-.716 4.24-1.244 5.989-2.08 4.045-1.934 7.041-5.137 7.937-8.488.322-1.205.332-3.361.02-4.551-.705-2.688-2.668-4.777-5.371-5.717-1.255-.436-2.372-.593-4.557-.535zm-.1 2.197c1.17.013 2.189.086 2.737.215 1.944.458 3.652 1.75 4.4 3.326.322.679.409 1.094.465 2.246.082 1.685-.102 2.655-.766 4.043-.933 1.953-2.924 3.864-5.343 5.129-1.527.798-2.69 1.22-5.444 1.975-2.265.62-3.404.732-3.55.35-.164-.427-.089-3.786.134-5.981.218-2.147 1.278-9.864 1.447-10.54.1-.397.173-.416 2.28-.619 1.15-.11 2.471-.157 3.64-.144zm-45.048 1.43c.105 0 2.854 8.086 2.9 8.529.025.244-.246.326-2.484.756-1.382.265-3.127.575-3.877.69-.75.113-1.516.252-1.702.306l-.337.098.25-.487c.137-.268 1.139-2.167 2.226-4.22 1.087-2.054 2.19-4.17 2.451-4.704.262-.533.52-.968.573-.968zm-52.202 3.25c-3.096.058-5.375 2.63-5.959 6.728-.217 1.53-.18 5.163.067 6.584.662 3.798 2.853 6.729 5.435 7.274 1.46.308 2.86-.165 4.305-1.453 1.516-1.352 2.565-3.078 3.389-5.577.542-1.645.82-3.153 1.011-5.463.269-3.24-.097-4.61-1.695-6.341-1.03-1.117-1.907-1.524-3.398-1.582-.715-.028-1.137.008-1.118.097.018.08.14.434.27.79.367.995.441 4.62.14 6.964-.222 1.735-.534 2.863-1.427 5.168-.163.42-.23 1.194-.25 2.873l-.025 2.297-.131-1.652c-.159-2.007-.001-3.281.588-4.752.8-1.998 1.05-3.708 1.033-7.022-.024-4.46-.256-4.97-2.235-4.933z"/></svg>
```

2024-08-26 08:43 UTC, weh commented on icons/kaldi/kaldi-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M64.0078.0078c-1.0237.0154-1.9593.0519-2.7226.1113C56.4167.4985 51.2479 1.5496 47.1074 3c-3.0646 1.0735-6.4712 2.
Optimized version
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#8c6432" d="M64.008.008a45.11 45.11 0 0 0-2.723.111C56.417.5 51.248 1.55 47.107 3c-3.064 1.073-6.47 2.647-7.847 3.625-.418.297-1.14.759-1.604 1.025-.868.5-2.165 1.4-4.115 2.86-1.596 1.195-5.438 4.684-6.195 5.625a84.743 84.743 0 0 1-1.672 1.978c-1.356 1.557-2.445 2.96-2.445 3.15 0 .085-.742 1.27-1.647 2.635-2.163 3.264-4.992 8.928-6.088 12.188-3.09 9.193-4.35 15.05-4.935 22.953-.3 4.035-.385 11.861-.168 15.273.106 1.671.263 4.265.35 5.764.219 3.803.616 4.615 2.257 4.615 1.37 0 1.959-.677 1.959-2.252 0-1.01.111-1.123 1.1-1.123.621 0 1.095.363 1.095.838 0 .675.871 3.25 1.62 4.787 1.68 3.453 4.593 5.646 8.12 6.114.928.123 1.773-.185 1.98-.721.115-.3.587-20.54.595-25.541.005-3.244-.016-3.292-1.557-3.26-2.36.049-4.446 1.124-6.803 3.504-1.05 1.06-1.508 1.68-2.005 2.72-.905 1.891-1.54 3.676-1.862 5.233-.151.734-.355 1.433-.455 1.553-.211.254-1.542.291-1.984.055-.259-.139-.324-.49-.424-2.323-.292-5.345-.036-14.699.516-18.865.84-6.344 2.833-14.119 5.04-19.66 2.1-5.27 6.083-11.82 9.788-16.092 4.418-5.096 10.725-9.488 17.219-11.992 1.113-.43 2.252-.891 2.53-1.025 1.218-.588 5.217-1.512 8.862-2.047 2.438-.358 10.022-.504 12.76-.246 3.949.371 9.445 1.46 10.765 2.134.288.147 1.157.494 1.93.77 5.563 1.985 10.84 5.36 14.918 9.539 2.125 2.178 3.51 3.804 3.928 4.613.168.325.702 1.16 1.187 1.856 1.866 2.677 3.484 5.793 5.172 9.957.635 1.565 1.994 5.82 1.994 6.242 0 .17.188 1.02.416 1.887 1.853 7.02 2.722 16.608 2.3 25.373-.323 6.67-1.353 15.405-1.893 16.056-.264.318-1.577.293-1.907-.037-.15-.15-.265-.55-.265-.922 0-1.19-.65-4.04-1.225-5.369-.804-1.859-2.062-3.803-2.973-4.592-1.136-.984-3.28-2.009-4.457-2.13-1.616-.167-1.431-.66-2.902 7.71-.236 1.346-1.188 6.317-2.115 11.047-.945 4.823-1.686 9.027-1.686 9.573 0 .908.032.991.502 1.234.277.143.904.372 1.393.51 1.255.353 3.292.226 4.71-.295 1.436-.527 3.019-1.66 4.384-3.137 1.264-1.368 2.589-3.883 3.384-6.426.694-2.219.823-2.455 1.38-2.52.716-.082.954.229.954 1.243 0 .79.06.942.52 1.328.798.672 1.815.615 2.662-.15.628-.568.666-.667 1.094-2.826 1.038-5.246 1.93-12.01 2.3-17.485.225-3.312.225-11.4 0-14.459-.483-6.597-1.683-13.344-3.406-19.154-1.311-4.424-3.522-9.436-5.695-12.91a80.226 80.226 0 0 1-1.52-2.531c-.704-1.252-1.122-1.8-3.463-4.538-2.218-2.594-5.423-5.474-8.12-7.298-1.08-.73-2.17-1.498-2.425-1.704-.678-.55-4.108-2.317-6.02-3.103C83.11 2.272 77.84.939 73.265.387c-2.33-.282-6.187-.425-9.258-.38zm-4.1 37.615c-2.275-.005-4.899.338-7.137.99-4.308 1.256-6.66 2.61-9.394 5.406-2.174 2.224-2.942 3.16-3.924 4.786-.384.636-.7 1.174-.7 1.197 0 .023-.445.811-.99 1.754-1.211 2.098-1.761 3.4-2.863 6.777-1.314 4.03-1.762 6.192-2.298 11.055-1.388 12.581-.233 27.512 2.681 34.685.238.587.434 1.162.434 1.278 0 .592 1.568 4.032 2.955 6.48.394.696.956 1.711 1.25 2.254 1.387 2.564 5.026 6.852 7.607 8.967 2.804 2.296 7.017 4.125 10.705 4.646.564.08 2.28.122 3.81.092 2.867-.055 3.31-.141 5.401-1.056 3.921-1.716 5.82-3.135 10.559-7.881 2.24-2.243 3.412-3.571 4.41-4.996 1.916-2.736 2.89-4.275 3.29-5.196.189-.437.837-1.82 1.44-3.074 1.271-2.64 2.915-6.531 2.915-6.9 0-.14.336-1.246.746-2.457 1.445-4.269 2.985-11.23 3.472-15.703.684-6.27.854-8.154 1.02-11.268.372-7-.35-12.69-2.025-15.988-.525-1.032-1.225-2.19-3.018-4.98-1.165-1.815-5.297-5.86-7.367-7.212-2.985-1.95-4.99-2.61-8.608-2.834-5.207-.321-6.834-.183-6.834.574 0 .117.34.865.758 1.663.882 1.684 1.433 4.098 1.8 7.894.293 3.015.294 17.383.003 19.998-1.204 10.813-2.023 14.654-4.418 20.695-.371.937-.676 1.777-.676 1.868 0 .09-.486 1.276-1.08 2.638-.748 1.713-1.141 2.867-1.277 3.743-.274 1.76-.476 7.971-.405 12.404.077 4.777-.178 4.137-.455-1.145-.214-4.083-.136-8.531.188-10.832.24-1.702 1.148-4.721 2.11-7.01.409-.974.853-2.113.985-2.53.134-.418.509-1.486.835-2.374.92-2.511 2.145-8.455 2.935-14.25.259-1.895.297-3.447.28-11.392-.02-9.172-.157-12.319-.663-15.233-.77-4.437-2.093-6.367-4.894-7.138-.957-.264-2.198-.392-3.563-.395z"/></svg>
```

2024-09-09 08:31 UTC, weh approved these changes
:+1:

2024-09-12 11:15 UTC, Snailedlt commented
@canaleal The conflicts need to be resolved before we can merge this PR

2025-02-18 12:21 UTC, weh approved these changes

2025-03-03 01:49 UTC, merged