new icon: zsh (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #1973
Opened 2023-11-03 18:03 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #1717**

## Link to prove your SVG is correct and up-to-date.

- [ZSH Website](https://www.zsh.org/)
- [ZSH Github Official Branding](https://github.com/Zsh-art/logo/blob/main/svg/color_vertical_icon.svg)

ZSH uses and orange and black color scheme for the original SVGs. As per the ZSH official branding guide, black should be used for a flat plain icon instead of orange. 

The logo with the ZSH is the original, whereas the logo with ZSHELL is the wordmark as shown in the [guide](https://github.com/Zsh-art/logo#the-official-zsh-z-shell-logo).

2023-11-13 09:33 UTC, weh requested changes
only some really minor changes :+1:

2023-11-13 09:33 UTC, weh commented on icons/zsh/zsh-line-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#000" d="M13.469 22.975C6.059 22.975 0 29.035 0 36.444v55.073c0 7.41 6.06 13.47 13.469 13.47h29.605a2.686 2.686 0 0 0 2.678-2
`fill="#000"` can be removed
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M13.469 22.975C6.059 22.975 0 29.035 0 36.444v55.073c0 7.41 6.06 13.47 13.469 13.47h29.605a2.686 2.686 0 0 0 2.678-2.677 2.685 2.685 0 0 0-2.678-2.678H13.469a8.069 8.069 0 0 1-8.112-8.115v-48.17h76.488v45.39h-2.59V80.72c.002-.027 0-.04 0-.039a2.657 2.657 0 0 0-2.654-2.657 2.657 2.657 0 0 0-1.878.78 2.657 2.657 0 0 0-.78 1.877c0 .088.003.095.003.023a.496.496 0 0 0 0 .016c-.003-.093-.002-.088-.002.01v21.64c0 .704.281 1.38.779 1.877a2.656 2.656 0 0 0 1.878.777 2.656 2.656 0 0 0 1.878-.777 2.656 2.656 0 0 0 .777-1.878v-8.562h2.589v8.502a.496.496 0 0 0 .013.116c.007.03.016.059.024.087.009.179.024.36.071.54a2.647 2.647 0 0 0 1.444 1.719 2.648 2.648 0 0 0 1.122.245h.018c.346 0 .69-.067 1.01-.2a2.645 2.645 0 0 0 .856-.573 2.633 2.633 0 0 0 .57-.855l.023-.056a.496.496 0 0 0 .006-.015 2.152 2.152 0 0 0 .013-.041l.006-.018a2.626 2.626 0 0 0 .072-.232 2.684 2.684 0 0 0 .107-.71.496.496 0 0 0 0-.007V36.444c0-7.41-6.06-13.47-13.47-13.47zm0 .992h60.262c6.868 0 12.476 5.608 12.476 12.477v65.858a1.68 1.68 0 0 1-.07.45.496.496 0 0 0-.005.023 1.623 1.623 0 0 1-.05.165.496.496 0 0 0-.007.017 2.067 2.067 0 0 1-.011.035l-.006.018a1.638 1.638 0 0 1-.357.533 1.652 1.652 0 0 1-.535.356 1.645 1.645 0 0 1-.63.126h-.017a.496.496 0 0 0-.002 0 1.649 1.649 0 0 1-.701-.153 1.668 1.668 0 0 1-.574-.438 1.651 1.651 0 0 1-.331-.637 1.647 1.647 0 0 1-.053-.41.496.496 0 0 0-.02-.131l-.001-.008v-8.67a.496.496 0 0 0-.052-.224.979.979 0 0 0-.872-.538h-2.671a.977.977 0 0 0-.692.286.98.98 0 0 0-.286.69v8.578a1.661 1.661 0 0 1-1.663 1.663 1.662 1.662 0 0 1-1.177-.486 1.665 1.665 0 0 1-.488-1.177V80.73c0 .063.002.018.002-.03a1.665 1.665 0 0 1 .486-1.194 1.664 1.664 0 0 1 1.177-.489c.44 0 .863.176 1.176.489a1.663 1.663 0 0 1 .486 1.176v.008a.496.496 0 0 0 0 .03v8.03c0 .26.104.508.287.692a.976.976 0 0 0 .692.287h2.67a.977.977 0 0 0 .69-.287.968.968 0 0 0 .183-.254.496.496 0 0 0 .052-.223V42.85a.496.496 0 0 0-.496-.496H4.861a.496.496 0 0 0-.497.496v48.666a9.084 9.084 0 0 0 9.105 9.107h29.605a1.678 1.678 0 0 1 1.686 1.686 1.678 1.678 0 0 1-1.686 1.684H13.469C6.6 103.994.992 98.386.992 91.517V36.444c0-6.87 5.608-12.477 12.477-12.477zm0 3.37a9.084 9.084 0 0 0-9.105 9.107v2.044a.496.496 0 0 0 .497.496h77.48a.496.496 0 0 0 .496-.496v-2.044a9.086 9.086 0 0 0-9.107-9.107zm0 .992h60.262a8.07 8.07 0 0 1 8.114 8.115v1.548H5.357v-1.548a8.069 8.069 0 0 1 8.112-8.115zm10.415 18.215a1.263 1.263 0 0 0-.859.444l-5.424 6.46A4.56 4.56 0 0 0 18 51.604c0-2.542-2.092-4.631-4.634-4.631-2.542 0-4.632 2.09-4.632 4.632s2.09 4.631 4.632 4.631c1.04 0 1.958-.414 2.735-1.002l-7.312 8.712a1.27 1.27 0 0 0 .153 1.78.496.496 0 0 0 .002 0 1.27 1.27 0 0 0 1.777-.154l5.335-6.353a4.56 4.56 0 0 0-.356 1.746c0 2.542 2.091 4.632 4.633 4.632s4.632-2.09 4.632-4.632-2.09-4.632-4.632-4.632c-1 0-1.882.392-2.643.94l7.27-8.659a1.272 1.272 0 0 0-.154-1.779 1.264 1.264 0 0 0-.922-.29zm.085.989a.27.27 0 0 1 .198.062c.118.1.132.26.033.38L9.96 64.932a.264.264 0 0 1-.38.035.264.264 0 0 1-.033-.382l14.237-16.957a.27.27 0 0 1 .184-.095zm-10.603.432c1.999 0 3.642 1.641 3.642 3.64s-1.643 3.64-3.642 3.64a3.655 3.655 0 0 1-3.64-3.64 3.655 3.655 0 0 1 3.64-3.64zm0 1.401a2.238 2.238 0 1 0 .003 4.476 2.238 2.238 0 0 0-.003-4.476zm0 .992c.717 0 1.246.53 1.246 1.246 0 .717-.529 1.245-1.246 1.245s-1.244-.528-1.244-1.245.528-1.246 1.244-1.246zm6.967 6.967a3.655 3.655 0 0 1 3.64 3.64 3.655 3.655 0 0 1-3.64 3.64c-1.998 0-3.641-1.642-3.641-3.64s1.643-3.64 3.641-3.64zm0 1.402a2.24 2.24 0 0 0 0 4.476 2.238 2.238 0 0 0 0-4.476zm0 .992c.717 0 1.244.529 1.244 1.246s-.527 1.246-1.244 1.246c-.716 0-1.246-.53-1.246-1.246s.53-1.246 1.246-1.246zm9.55 3.353a1.27 1.27 0 0 0-1.263 1.263 1.27 1.27 0 0 0 1.264 1.262H40.05a1.27 1.27 0 0 0 1.264-1.262 1.27 1.27 0 0 0-1.264-1.263zm0 .992H40.05c.156 0 .272.116.272.271 0 .155-.116.27-.272.27H29.884a.263.263 0 0 1-.272-.27c0-.155.116-.271.272-.271zm20.138 13.95c-.355 0-.704.072-1.029.207a2.677 2.677 0 0 0-.87.58 2.69 2.69 0 0 0-.583.871 2.682 2.682 0 0 0-.204 1.028v.001c0 .352.068.7.204 1.028h-.002a2.685 2.685 0 0 0 2.484 1.657c.045 0 .074-.003.101-.004h3.7l-6.28 15.686a2.901 2.901 0 0 0-.207 1.08v1.96c0 .77.306 1.51.851 2.055a2.903 2.903 0 0 0 2.052.85h7.508a2.738 2.738 0 0 0 1.049-.207.496.496 0 0 0 0-.002 2.736 2.736 0 0 0 1.484-1.482 2.747 2.747 0 0 0 .21-1.05 2.746 2.746 0 0 0-2.745-2.745c-.054 0-.07.002-.05.002h-4.7l7.256-18.091a2.49 2.49 0 0 0 .165-1.192 2.49 2.49 0 0 0-.415-1.13 2.493 2.493 0 0 0-.895-.804 2.487 2.487 0 0 0-1.167-.29h-7.756c-.026-.002-.079-.008-.16-.008zm38.98 0c-.728 0-1.33.601-1.33 1.33v24.286c0 .728.6 1.33 1.329 1.33h8.06a2.749 2.749 0 0 0 2.74-2.743 2.749 2.749 0 0 0-2.74-2.742h-4.159c-.017 0-.021-.004-.021-.022v-5.69c0-.015 0-.015.015-.015h4.3c1.395 0 2.538-1.14 2.538-2.535s-1.142-2.537-2.537-2.537h-4.3c-.016 0-.016 0-.016-.015v-5.345c0-.02.003-.023.023-.023h4.293a2.647 2.647 0 0 0 2.64-2.64 2.647 2.647 0 0 0-2.64-2.64zm13.918 0a2.612 2.612 0 0 0-2.605 2.604v23.233c0 .605.5 1.108 1.107 1.108h9.75a2.75 2.75 0 0 0 2.742-2.742 2.75 2.75 0 0 0-2.742-2.742h-5.648V80.618a2.612 2.612 0 0 0-2.604-2.605zm14.087 0a2.612 2.612 0 0 0-2.605 2.604v23.233c0 .605.5 1.108 1.107 1.108h9.75a2.75 2.75 0 0 0 2.742-2.742 2.75 2.75 0 0 0-2.742-2.742h-5.647V80.618a2.612 2.612 0 0 0-2.605-2.605zm-49.345.122c-1.053 0-2.225.09-3.027.314a3.893 3.893 0 0 0-1.913 1.094.496.496 0 0 0-.014.014c-.478.54-.802 1.25-.998 2.099-.195.827-.286 1.843-.286 3.058 0 1.149.01 2.076.033 2.79a.496.496 0 0 0 0 .01c.03.6.102 1.196.213 1.785a.496.496 0 0 0 .004.02 3.839 3.839 0 0 0 .511 1.215.496.496 0 0 0 .01.017c.219.313.477.6.765.851a7.48 7.48 0 0 0 1.24.88c.465.27.939.527 1.425.773.467.237.914.485 1.335.742a.496.496 0 0 0 .016.01c.37.208.71.46 1.02.748.114.125.222.256.32.395a.496.496 0 0 0 .028.035.565.565 0 0 1 .1.177.496.496 0 0 0 .003.004c.033.09.06.18.081.273a1.834 1.834 0 0 1 .039.407.496.496 0 0 0 .002.05c.02.241.033.594.033 1.049a.496.496 0 0 0 0 .007 13.085 13.085 0 0 1-.099 1.814.496.496 0 0 0-.004.031 2.183 2.183 0 0 1-.215.816.442.442 0 0 1-.25.194c.008-.003-.27.04-.525.056a12.784 12.784 0 0 1-.692.023.496.496 0 0 0-.01 0 2.47 2.47 0 0 1-.63-.075.633.633 0 0 1-.247-.223 3.33 3.33 0 0 1-.225-.82 15.35 15.35 0 0 1-.066-1.583.496.496 0 0 0 0-.002.496.496 0 0 0 0-.002.496.496 0 0 0 0-.002.496.496 0 0 0 0-.002 2.345 2.345 0 0 0-.012-.233.496.496 0 0 0-.13-.118l.113.099a2.337 2.337 0 0 0-.785-1.436 2.35 2.35 0 0 0-1.537-.57 2.348 2.348 0 0 0-1.535.57 2.336 2.336 0 0 0-.785 1.436l.18-.157a.496.496 0 0 0-.192.173 2.265 2.265 0 0 0-.015.261.496.496 0 0 0 0 .004c0 .047.002.06.002.039 0-.133-.002-.13-.002.014a.59.59 0 0 0 .002.04c.005.429.011.818.011 1 0 1.324.09 2.413.285 3.283a.496.496 0 0 0 .004.016c.22.852.573 1.563 1.076 2.1a.496.496 0 0 0 .011.012 3.782 3.782 0 0 0 1.886 1.025 10.05 10.05 0 0 0 2.543.277c1.12 0 2.503-.086 3.347-.314 0 0 0-.002.002-.002a3.72 3.72 0 0 0 2.005-1.29c.524-.635.868-1.475 1.06-2.498.216-1.042.317-2.335.317-3.898 0-1.12-.034-2.02-.103-2.726v-.004a6.448 6.448 0 0 0-.332-1.824v-.002a3.24 3.24 0 0 0-.767-1.246 5.888 5.888 0 0 0-1.082-.866h-.002a10.213 10.213 0 0 0-1.075-.59l.035.016a16.252 16.252 0 0 0-1.252-.637l-.018-.01a29.778 29.778 0 0 1-1.191-.641 9.782 9.782 0 0 1-.929-.652 2.893 2.893 0 0 1-.314-.304.945.945 0 0 1-.124-.3.496.496 0 0 0 0-.002 4.707 4.707 0 0 1-.093-.686V85.31a.496.496 0 0 0 0-.006 11.157 11.157 0 0 1 .066-1.362.496.496 0 0 0 .002-.01c.02-.217.083-.425.178-.618a.323.323 0 0 1 .188-.134.496.496 0 0 0 .043-.01c-.003.001.198-.037.392-.052a7.69 7.69 0 0 1 .55-.023c.317 0 .545.05.682.112.137.063.188.12.23.217a.496.496 0 0 0 .02.04c.108.2.17.418.178.642.008.23.011.539.012.863a.496.496 0 0 0 .012.011c0 .621.248 1.216.688 1.653a2.353 2.353 0 0 0 1.659.686 2.356 2.356 0 0 0 1.66-.686 2.33 2.33 0 0 0 .686-1.653v-.013l.002-.872a11.922 11.922 0 0 0-.25-2.65c-.15-.772-.463-1.426-.945-1.924-.463-.521-1.103-.878-1.876-1.071-.749-.216-1.662-.314-2.758-.314zm-17.64.87c.008 0 .04.004.103.007a.496.496 0 [...]

2023-11-13 09:33 UTC, weh commented on icons/zsh/zsh-line.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#000" d="M19.61 3.793C8.822 3.793 0 12.615 0 23.403v81.138c0 10.788 8.822 19.61 19.61 19.61h43.615a3.718 3.718 0 0 0 3.711-3.
`fill="#000"` can be removed
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.61 3.793C8.822 3.793 0 12.615 0 23.403v81.138c0 10.788 8.822 19.61 19.61 19.61h43.615a3.718 3.718 0 0 0 3.711-3.711 3.718 3.718 0 0 0-3.711-3.711H19.61A12.13 12.13 0 0 1 7.42 104.54V33.337h113.16v67.283a.216.216 0 0 1-.136.058h-3.934a.217.217 0 0 1-.151-.064.214.214 0 0 1-.062-.15V88.646c0-.036-.001-.016-.002-.019v-.016s.002.003.002-.036a3.68 3.68 0 0 0-3.679-3.679 3.679 3.679 0 0 0-3.678 3.678c0 .066.002.08.002.037v.016c-.002-.062-.002-.057-.002.02v31.881a3.679 3.679 0 0 0 3.678 3.679 3.68 3.68 0 0 0 3.679-3.679v-12.636a.213.213 0 0 1 .062-.15.214.214 0 0 1 .15-.063h3.935c.051 0 .098.024.136.056v12.766l.015.06c.01.042.02.083.033.124.01.26.033.524.103.789a3.66 3.66 0 0 0 .734 1.413c.346.411.778.74 1.266.967a3.663 3.663 0 0 0 1.556.34c.1 0 .126-.001.011-.001a3.662 3.662 0 0 0 1.41-.275 3.654 3.654 0 0 0 1.185-.793 3.655 3.655 0 0 0 .787-1.176v-.002c.034-.079.042-.109.03-.078v-.002h.001l.033-.089a3.679 3.679 0 0 0 .103-.341 3.714 3.714 0 0 0 .153-.99V23.403c0-10.788-8.82-19.61-19.608-19.61zm0 .992h88.782c10.247 0 18.616 8.37 18.616 18.618v97.03a2.711 2.711 0 0 1-.11.726l-.005.012-.002.01a2.688 2.688 0 0 1-.081.261l-.023.064c-.029.073-.032.086-.014.045l-.002.006-.004.004a2.662 2.662 0 0 1-.575.864 2.67 2.67 0 0 1-1.882.779c.13 0 .154-.002-.012-.002-.142 0-.171.002-.013.002h-.002a2.663 2.663 0 0 1-1.134-.248 2.685 2.685 0 0 1-.925-.707 2.665 2.665 0 0 1-.536-1.03 2.708 2.708 0 0 1-.084-.664v-.068l-.019-.066-.014-.048v-12.915l-.052-.105a1.206 1.206 0 0 0-.223-.312 1.206 1.206 0 0 0-.852-.352h-3.934a1.206 1.206 0 0 0-.853.352 1.206 1.206 0 0 0-.353.853v12.636a2.687 2.687 0 0 1-2.686 2.686 2.685 2.685 0 0 1-1.9-.787 2.685 2.685 0 0 1-.786-1.899V88.648c0 .042.002.007.002-.04a2.685 2.685 0 0 1 .785-1.93 2.685 2.685 0 0 1 3.798-.001 2.687 2.687 0 0 1 .787 1.9c0-.033 0-.025-.002.02v.016c0 .066.002.077.002.035v11.816c0 .318.126.626.353.852a1.204 1.204 0 0 0 .852.355h3.935c.321 0 .627-.129.852-.355a1.206 1.206 0 0 0 .223-.312l.052-.104V32.345H6.428v72.196c0 7.308 5.874 13.18 13.182 13.18h43.615a2.71 2.71 0 0 1 2.719 2.719 2.711 2.711 0 0 1-2.72 2.719H19.61c-10.247 0-18.618-8.37-18.618-18.618V23.403c0-10.248 8.37-18.618 18.618-18.618Zm0 5.436A13.146 13.146 0 0 0 6.428 23.403v3.506h115.144v-3.506a13.145 13.145 0 0 0-13.18-13.182zm0 .992h88.782a12.13 12.13 0 0 1 12.188 12.19v2.514H7.42v-2.514c0-6.779 5.412-12.19 12.19-12.19zm14.502 27.305a1.627 1.627 0 0 0-1.104.571L12.03 64.072v.002a1.632 1.632 0 0 0 .2 2.288h.002a1.633 1.633 0 0 0 2.286-.197l20.979-24.983v-.002a1.632 1.632 0 0 0-.2-2.289h-.002a1.623 1.623 0 0 0-1.184-.373zm-15.515.63c-3.617 0-6.59 2.974-6.59 6.59s2.973 6.59 6.59 6.59 6.59-2.973 6.59-6.59-2.974-6.59-6.59-6.59zm15.6.358a.635.635 0 0 1 .462.145.628.628 0 0 1 .08.894l-20.98 24.98a.626.626 0 0 1-.889.078.628.628 0 0 1-.08-.894l20.978-24.98a.633.633 0 0 1 .43-.223zm-15.6.634c3.072 0 5.597 2.526 5.597 5.598s-2.524 5.597-5.597 5.597c-3.073 0-5.597-2.524-5.597-5.597 0-3.072 2.524-5.598 5.597-5.598zm0 2.536a3.054 3.054 0 0 0-3.062 3.062 3.054 3.054 0 0 0 3.062 3.062 3.054 3.054 0 0 0 3.062-3.062 3.054 3.054 0 0 0-3.062-3.062zm0 .993c1.178 0 2.07.89 2.07 2.07 0 1.178-.892 2.07-2.07 2.07-1.179 0-2.07-.892-2.07-2.07 0-1.18.891-2.07 2.07-2.07zM28.86 52.94c-3.616 0-6.59 2.973-6.59 6.59s2.974 6.588 6.59 6.588 6.59-2.972 6.59-6.589-2.973-6.589-6.59-6.589zm0 .992c3.073 0 5.597 2.524 5.597 5.597 0 3.073-2.524 5.597-5.597 5.597-3.072 0-5.598-2.524-5.598-5.597 0-3.073 2.526-5.597 5.598-5.597zm0 2.535a3.054 3.054 0 0 0-3.062 3.062 3.054 3.054 0 0 0 3.062 3.062 3.054 3.054 0 0 0 3.062-3.062 3.054 3.054 0 0 0-3.062-3.062zm0 .992c1.179 0 2.07.892 2.07 2.07 0 1.179-.891 2.07-2.07 2.07-1.178 0-2.07-.891-2.07-2.07 0-1.178.892-2.07 2.07-2.07zm14.07 5.41a1.633 1.633 0 0 0-1.626 1.623c0 .893.734 1.626 1.626 1.626h14.98c.892 0 1.626-.733 1.626-1.626a1.634 1.634 0 0 0-1.626-1.624zm0 .991h14.98c.355 0 .633.277.634.632a.626.626 0 0 1-.634.634H42.93a.626.626 0 0 1-.633-.634c0-.355.278-.632.633-.632zm30.53 21.022c-.49 0-.974.096-1.425.283a3.739 3.739 0 0 0-1.21.808 3.728 3.728 0 0 0-.806 1.207 3.72 3.72 0 0 0-.283 1.425v.002a3.711 3.711 0 0 0 .283 1.424h-.002a3.718 3.718 0 0 0 2.018 2.014 3.711 3.711 0 0 0 1.424.283c.085 0 .143-.007.175-.008h5.775l-9.384 23.432a4.043 4.043 0 0 0-.289 1.504v2.89a4.043 4.043 0 0 0 1.184 2.858 4.048 4.048 0 0 0 2.861 1.186h11.06c.5 0 .994-.098 1.456-.289v-.002a3.811 3.811 0 0 0 1.234-.823 3.798 3.798 0 0 0 .826-1.235 3.794 3.794 0 0 0 .288-1.455v-.002a3.809 3.809 0 0 0-1.114-2.692 3.809 3.809 0 0 0-2.692-1.114c-.05 0-.065.003-.075.004H77.49l10.822-26.977a3.433 3.433 0 0 0 .227-1.644 3.427 3.427 0 0 0-.57-1.558 3.444 3.444 0 0 0-1.236-1.11 3.434 3.434 0 0 0-1.61-.401h-11.44c-.055-.004-.13-.01-.225-.01zm25.988.178c-1.539 0-3.266.138-4.403.456a5.495 5.495 0 0 0-2.704 1.548l-.006.008-.007.006c-.672.758-1.139 1.764-1.421 2.99-.282 1.193-.415 2.671-.415 4.45 0 1.69.015 3.058.049 4.106v.01c.045.872.148 1.74.31 2.599l.002.01.002.01a5.417 5.417 0 0 0 .723 1.715l.004.01.006.008a6.755 6.755 0 0 0 1.089 1.21 10.765 10.765 0 0 0 1.788 1.272 41.812 41.812 0 0 0 2.09 1.132c.693.352 1.354.719 1.98 1.101l.008.006.007.004a8.082 8.082 0 0 1 1.555 1.142c.178.193.344.397.498.614l.013.017.014.018a1.062 1.062 0 0 1 .192.331v.002l.002.002c.052.143.096.288.13.43.046.218.067.437.064.657v.026l.002.025c.03.363.046.891.046 1.566v.008a19.475 19.475 0 0 1-.145 2.705l-.002.016-.002.015a3.464 3.464 0 0 1-.345 1.3.89.89 0 0 1-.51.398 7.998 7.998 0 0 1-.825.09c-.384.024-.797.036-1.033.036h-.01a3.876 3.876 0 0 1-1.02-.122 1.164 1.164 0 0 1-.49-.446 5.17 5.17 0 0 1-.353-1.287 22.993 22.993 0 0 1-.1-2.362v-.006c0-.106-.005-.213-.016-.322l-.046-.446h-.21c-.175-.572-.385-1.148-.845-1.544a3.23 3.23 0 0 0-2.11-.783 3.22 3.22 0 0 0-2.107.783c-.459.396-.669.972-.845 1.544h-.205l-.047.442a3.081 3.081 0 0 0-.017.357v.124c.008.64.017 1.218.017 1.496 0 1.939.134 3.528.415 4.785l.002.008.002.008c.318 1.228.822 2.234 1.53 2.99l.005.006.006.006a5.34 5.34 0 0 0 2.661 1.45 14.58 14.58 0 0 0 3.692.4c1.637 0 3.69-.13 4.88-.453l.004-.002a5.239 5.239 0 0 0 2.825-1.817v-.002c.74-.895 1.236-2.096 1.516-3.576v-.004c.312-1.51.463-3.404.463-5.698 0-1.652-.05-2.981-.151-4.011v-.004a9.247 9.247 0 0 0-.479-2.62V106a4.538 4.538 0 0 0-1.076-1.748 8.392 8.392 0 0 0-1.548-1.24h-.002a14.798 14.798 0 0 0-1.562-.855l.035.015c-.578-.329-1.19-.64-1.833-.936l-.018-.01a43.973 43.973 0 0 1-1.775-.953 14.666 14.666 0 0 1-1.397-.981 4.472 4.472 0 0 1-.508-.492 1.617 1.617 0 0 1-.221-.535l-.002-.002a7.147 7.147 0 0 1-.14-1.047V95.39a16.748 16.748 0 0 1 .097-2.035l.002-.004v-.006c.033-.352.135-.691.293-1.008a.714.714 0 0 1 .43-.306l.021-.004.022-.006c.046-.015.34-.066.632-.089a11.3 11.3 0 0 1 .829-.035c.49 0 .856.074 1.1.186.245.113.372.244.458.442l.01.021.01.02c.177.323.276.68.29 1.048.012.345.017.802.018 1.281l.002.494h.215c.11.656.27 1.318.747 1.793a3.231 3.231 0 0 0 2.279.94 3.231 3.231 0 0 0 2.279-.94c.477-.475.636-1.137.746-1.793h.198v-1.796a17.342 17.342 0 0 0-.363-3.845c-.214-1.107-.658-2.026-1.335-2.721-.646-.731-1.546-1.232-2.653-1.51-1.072-.309-2.398-.455-4-.455zm-25.989.814c.038 0 .089.005.163.01h11.5a2.442 2.442 0 0 1 2.428 2.182 2.448 2.448 0 0 1-.16 1.17l-10.88 27.13a.873.873 0 0 0-.062.419v.002l.002.002a.872.872 0 0 0 .147.397.873.873 0 0 0 .314.285.872.872 0 0 0 .413.103h7.46c.05-.002.067-.004.055-.004a2.815 2.815 0 0 1 2.814 2.814v.002a2.807 2.807 0 0 1-.215 1.075 2.805 2.805 0 0 1-.608.913 2.823 2.823 0 0 1-.913.61v-.001a2.811 2.811 0 0 1-1.076.215h-11.06a3.055 3.055 0 0 1-2.159-.896 3.049 3.049 0 0 1-.893-2.157v-2.89c0-.388.075-.775.219-1.135l9.436-23.564a.893.893 0 0 0 .06-.428v-.002h-.002a.9.9 0 0 0-.147-.405v-.002a.902.902 0 0 0-.32-.287h-.002l-.002-.002a.895.895 0 0 0-.419-.103h-5.969c-.069.004-.107.008-.124.008a2.724 2.724 0 0 1-1.044-.21 2.724 2.724 0 0 1-.888-.588 2.725 2.725 0 0 1-.591-.886h-.002a2.72 2.72 0 0 1-.205-1.045v-.002c0-.358.071-.713.209-1.044a2.724 2.724 0 0 1 .589-.886 2.74  [...]

2023-11-13 09:33 UTC, weh commented on icons/zsh/zsh-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#f15a24" d="M23.613 46.906a.773.773 0 0 0-.525.273L8.74 64.268a.773.773 0 0 0 .095 1.089.773.773 0 0 0 1.089-.095l14.35-17.09
- `fill="#000"` can be removed
- missing newline at EOF

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#f15a24" d="M23.613 46.906a.773.773 0 0 0-.525.273L8.74 64.268a.773.773 0 0 0 .095 1.089.773.773 0 0 0 1.089-.095l14.35-17.09a.773.773 0 0 0-.096-1.088.773.773 0 0 0-.564-.178zm-10.642.433c-2.288 0-4.169 1.88-4.169 4.168 0 2.288 1.88 4.17 4.169 4.17 2.288 0 4.169-1.882 4.169-4.17 0-2.288-1.881-4.168-4.17-4.168zm0 2.414c.983 0 1.755.77 1.755 1.754s-.772 1.756-1.755 1.756a1.737 1.737 0 0 1-1.755-1.756c0-.983.771-1.754 1.755-1.754zm7.02 7.02c-2.288 0-4.168 1.88-4.168 4.169 0 2.288 1.88 4.168 4.168 4.168 2.288 0 4.17-1.88 4.17-4.168 0-2.288-1.882-4.169-4.17-4.169zm0 2.413c.984 0 1.756.772 1.756 1.756 0 .983-.772 1.755-1.755 1.755a1.737 1.737 0 0 1-1.755-1.755c0-.984.77-1.756 1.755-1.756zm9.625 4.379a.773.773 0 0 0-.773.772.773.773 0 0 0 .773.773h10.247a.773.773 0 0 0 .773-.773.773.773 0 0 0-.773-.772z" color="#000" style="-inkscape-stroke:none"/><path d="M13.075 23.154C5.88 23.154 0 29.034 0 36.228v55.504c0 7.195 5.88 13.075 13.075 13.075H42.91a2.199 2.199 0 0 0 2.199-2.198 2.199 2.199 0 0 0-2.2-2.2H13.076a8.644 8.644 0 0 1-8.677-8.677V42.686h78.086V89.16a.481.481 0 0 1-.089.127.485.485 0 0 1-.343.142H79.36a.484.484 0 0 1-.342-.142.486.486 0 0 1-.143-.344v-8.131a2.18 2.18 0 0 0-.637-1.54 2.177 2.177 0 0 0-1.54-.637 2.178 2.178 0 0 0-2.176 2.177l.001.024-.001.025v21.808a2.178 2.178 0 0 0 2.177 2.177 2.177 2.177 0 0 0 1.539-.637c.408-.408.637-.962.637-1.54v-8.643a.485.485 0 0 1 .143-.343.485.485 0 0 1 .343-.143h2.691a.486.486 0 0 1 .343.143.481.481 0 0 1 .089.126v8.8a2.199 2.199 0 0 0 .022.082c.002.181.023.362.07.538.082.307.23.592.434.836a2.168 2.168 0 0 0 1.67.773h.017a2.16 2.16 0 0 0 1.527-.632 2.163 2.163 0 0 0 .468-.7c.007-.016.01-.03.016-.046a2.199 2.199 0 0 0 .017-.046 2.149 2.149 0 0 0 .066-.218 2.199 2.199 0 0 0 .09-.588v-66.38c0-7.195-5.879-13.075-13.074-13.075zm0 4.397h60.732a8.644 8.644 0 0 1 8.677 8.678v2.06H4.398v-2.06a8.644 8.644 0 0 1 8.677-8.678zM49.91 78.624a2.208 2.208 0 0 0-2.039 1.362 2.206 2.206 0 0 0-.168.845v.001c0 .29.057.577.168.845a2.205 2.205 0 0 0 2.04 1.361c.034 0 .068-.004.102-.005h4.066a.276.276 0 0 1 .128.032.276.276 0 0 1 .098.088.273.273 0 0 1 .027.255l-6.455 16.12a2.425 2.425 0 0 0-.174.902v1.977a2.427 2.427 0 0 0 2.427 2.427h7.566a2.263 2.263 0 0 0 1.6-.663 2.263 2.263 0 0 0 .663-1.6v-.002a2.265 2.265 0 0 0-.663-1.6 2.265 2.265 0 0 0-1.6-.664l-.053.002h-5.089a.26.26 0 0 1-.217-.115.262.262 0 0 1-.044-.119.261.261 0 0 1 .018-.125l7.444-18.56a2.01 2.01 0 0 0 .133-.962 2.01 2.01 0 0 0-.334-.912 2.01 2.01 0 0 0-1.665-.884h-7.845c-.045-.003-.089-.007-.134-.007zm39.287 0a.842.842 0 0 0-.842.842v24.473c0 .464.375.84.839.84h8.122a2.264 2.264 0 0 0 0-4.527h-4.19a.522.522 0 0 1-.521-.521v-5.734a.516.516 0 0 1 .516-.516h4.334a2.056 2.056 0 1 0 0-4.112h-4.334a.516.516 0 0 1-.517-.516v-5.386c0-.29.235-.524.525-.524h4.326a2.16 2.16 0 0 0 0-4.319zm14.024 0a2.125 2.125 0 0 0-2.125 2.125v23.413c0 .34.276.616.617.616h9.825a2.263 2.263 0 0 0 0-4.526h-5.782a.41.41 0 0 1-.41-.41V80.749a2.125 2.125 0 0 0-2.125-2.125zm14.198 0a2.125 2.125 0 0 0-2.125 2.125v23.413c0 .34.276.616.616.616h9.826a2.263 2.263 0 0 0 0-4.526h-5.782a.41.41 0 0 1-.41-.41V80.749a2.125 2.125 0 0 0-2.125-2.125zm-49.73.121c-1.034 0-2.217.1-2.929.3a3.423 3.423 0 0 0-1.688.966c-.413.467-.712 1.1-.896 1.9-.183.777-.275 1.766-.275 2.965 0 1.155.011 2.088.034 2.798.03.582.1 1.16.207 1.733.086.378.238.74.448 1.066.198.282.429.54.689.766a7.02 7.02 0 0 0 1.171.833c.46.267.93.522 1.412.767.483.244.942.5 1.379.766a5.861 5.861 0 0 1 1.136.833 4.709 4.709 0 0 1 .38.467 1.071 1.071 0 0 1 .191.333 2.941 2.941 0 0 1 .1.332c.038.176.056.354.053.534.023.266.034.633.034 1.1a13.695 13.695 0 0 1-.103 1.898 2.705 2.705 0 0 1-.276 1.033.947.947 0 0 1-.55.434c-.23.066-1.024.1-1.369.1a3.013 3.013 0 0 1-.827-.1 1.139 1.139 0 0 1-.516-.467 3.869 3.869 0 0 1-.276-1 16 16 0 0 1-.069-1.663 1.864 1.864 0 0 0-.01-.185h-.013a1.851 1.851 0 0 0-.624-1.138 1.868 1.868 0 0 0-2.441 0 1.851 1.851 0 0 0-.624 1.138h-.011a1.766 1.766 0 0 0-.01.204v.061l.001.023c.006.437.012.83.012 1.027 0 1.31.092 2.377.275 3.2.207.799.528 1.431.965 1.898a3.317 3.317 0 0 0 1.653.9 9.633 9.633 0 0 0 2.446.266c1.103 0 2.528-.1 3.263-.3a3.246 3.246 0 0 0 1.757-1.132c.459-.556.78-1.322.964-2.3.207-.999.31-2.276.31-3.831 0-1.133-.034-2.043-.103-2.732a5.984 5.984 0 0 0-.31-1.7 2.766 2.766 0 0 0-.654-1.066 5.431 5.431 0 0 0-1-.799 9.811 9.811 0 0 0-1.033-.566 15.912 15.912 0 0 0-1.24-.634 30.608 30.608 0 0 1-1.24-.666 10.376 10.376 0 0 1-1-.7 3.403 3.403 0 0 1-.412-.4 1.443 1.443 0 0 1-.207-.5 5.273 5.273 0 0 1-.104-.765v-1.266a11.734 11.734 0 0 1 .07-1.434 2.281 2.281 0 0 1 .24-.832.831.831 0 0 1 .517-.367c.207-.066.782-.1 1.103-.1.735 0 1.195.211 1.378.633.146.267.228.563.24.867.008.242.011.558.012.888h.013v.014c0 .492.196.964.546 1.312a1.87 1.87 0 0 0 1.32.545c.494 0 .968-.196 1.318-.545a1.851 1.851 0 0 0 .546-1.312v-.014l.001-.888a11.526 11.526 0 0 0-.241-2.566c-.138-.71-.413-1.277-.826-1.699-.391-.444-.942-.755-1.654-.933-.689-.2-1.574-.3-2.653-.3Z"/></svg>

```

2023-11-13 09:33 UTC, weh commented on icons/zsh/zsh-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#f15a24" d="M33.921 38.816a1.138 1.138 0 0 0-.773.402l-21.14 25.177a1.138 1.138 0 0 0 .14 1.604 1.138 1.138 0 0 0 1.603-.14l2
fill="#000" can be removed
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#f15a24" d="M33.921 38.816a1.138 1.138 0 0 0-.773.402l-21.14 25.177a1.138 1.138 0 0 0 .14 1.604 1.138 1.138 0 0 0 1.603-.14l21.14-25.177a1.138 1.138 0 0 0-.14-1.604 1.138 1.138 0 0 0-.83-.262zm-15.68.638c-3.37 0-6.14 2.77-6.14 6.141 0 3.37 2.77 6.142 6.14 6.142 3.372 0 6.142-2.771 6.142-6.142 0-3.37-2.77-6.141-6.141-6.141zm0 3.556c1.45 0 2.587 1.136 2.587 2.585s-1.137 2.586-2.586 2.586a2.56 2.56 0 0 1-2.586-2.586 2.56 2.56 0 0 1 2.586-2.585zm10.344 10.343c-3.37 0-6.141 2.77-6.141 6.141 0 3.37 2.77 6.141 6.141 6.141 3.37 0 6.142-2.77 6.142-6.14 0-3.372-2.771-6.142-6.142-6.142zm0 3.555a2.56 2.56 0 0 1 2.586 2.586 2.56 2.56 0 0 1-2.586 2.586A2.559 2.559 0 0 1 26 59.494a2.559 2.559 0 0 1 2.585-2.586zm14.18 6.45a1.138 1.138 0 0 0-1.138 1.139 1.138 1.138 0 0 0 1.138 1.138h15.096A1.138 1.138 0 0 0 59 64.497a1.138 1.138 0 0 0-1.138-1.138z" color="#000" style="-inkscape-stroke:none"/><path d="M19.263 3.822C8.663 3.822 0 12.485 0 23.085v81.772c0 10.6 8.663 19.263 19.263 19.263h43.956a3.24 3.24 0 0 0 3.24-3.24 3.24 3.24 0 0 0-3.24-3.239H19.263a12.735 12.735 0 0 1-12.784-12.784V32.598H121.52v68.47a.712.712 0 0 1-.13.186.715.715 0 0 1-.506.21h-3.965a.713.713 0 0 1-.506-.21.716.716 0 0 1-.21-.506v-11.98a3.207 3.207 0 0 0-.938-2.267 3.208 3.208 0 0 0-2.268-.94 3.205 3.205 0 0 0-2.267.94 3.207 3.207 0 0 0-.94 2.267l.002.036-.002.037v32.13c0 .85.338 1.666.94 2.267a3.205 3.205 0 0 0 2.267.94 3.208 3.208 0 0 0 2.268-.94 3.207 3.207 0 0 0 .938-2.267v-12.735c0-.19.076-.371.21-.505a.715.715 0 0 1 .506-.21h3.965c.19 0 .372.076.506.21a.713.713 0 0 1 .13.186v12.964a3.24 3.24 0 0 0 .033.122c.003.266.034.533.103.792.12.452.338.872.64 1.231a3.199 3.199 0 0 0 1.103.844c.425.197.888.298 1.356.296l.013-.001h.013c.417 0 .831-.081 1.217-.241a3.184 3.184 0 0 0 1.032-.69 3.178 3.178 0 0 0 .69-1.032l.022-.062a3.24 3.24 0 0 0 .028-.08 3.183 3.183 0 0 0 .096-.313 3.24 3.24 0 0 0 .133-.866V23.085c0-10.6-8.662-19.263-19.262-19.263Zm0 6.48h89.475a12.735 12.735 0 0 1 12.783 12.783v3.034H6.48v-3.034a12.735 12.735 0 0 1 12.784-12.784zm54.27 75.243a3.253 3.253 0 0 0-2.3.952 3.256 3.256 0 0 0-.704 1.055 3.25 3.25 0 0 0-.248 1.245v.001a3.248 3.248 0 0 0 .952 2.3 3.24 3.24 0 0 0 1.055.703 3.243 3.243 0 0 0 1.245.247c.051 0 .1-.005.15-.008h5.99a.407.407 0 0 1 .19.047.41.41 0 0 1 .144.13.406.406 0 0 1 .067.183.406.406 0 0 1-.027.193l-9.51 23.75a3.573 3.573 0 0 0-.256 1.328v2.913c0 .948.377 1.858 1.047 2.528a3.576 3.576 0 0 0 2.529 1.047h11.147a3.335 3.335 0 0 0 3.08-2.058 3.328 3.328 0 0 0 .254-1.275v-.002a3.337 3.337 0 0 0-.977-2.36 3.337 3.337 0 0 0-2.359-.976c-.026 0-.05.003-.076.004h-7.498a.384.384 0 0 1-.181-.045.384.384 0 0 1-.138-.125.386.386 0 0 1-.065-.175.385.385 0 0 1 .026-.184l10.966-27.344a2.962 2.962 0 0 0 .196-1.418 2.956 2.956 0 0 0-.49-1.343 2.96 2.96 0 0 0-2.454-1.303H73.729c-.065-.004-.13-.01-.196-.01zm26.193.179c-1.523 0-3.266.147-4.315.441a5.043 5.043 0 0 0-2.487 1.424c-.609.687-1.05 1.62-1.32 2.798-.27 1.146-.405 2.602-.405 4.37 0 1.7.016 3.075.05 4.122.044.856.146 1.71.304 2.552a4.959 4.959 0 0 0 .66 1.571 6.296 6.296 0 0 0 1.015 1.129 10.337 10.337 0 0 0 1.726 1.227 41.656 41.656 0 0 0 2.08 1.13c.711.36 1.388.735 2.031 1.128a8.632 8.632 0 0 1 1.674 1.227 6.937 6.937 0 0 1 .559.688c.123.145.219.311.283.49.058.16.108.324.147.49.055.259.082.522.078.786.034.393.05.934.05 1.62a20.163 20.163 0 0 1-.152 2.798 3.992 3.992 0 0 1-.406 1.522 1.395 1.395 0 0 1-.812.639c-.338.098-1.508.146-2.016.146a4.41 4.41 0 0 1-1.217-.146 1.68 1.68 0 0 1-.762-.688 5.714 5.714 0 0 1-.406-1.473 23.676 23.676 0 0 1-.102-2.45c0-.09-.004-.182-.014-.273h-.02a2.727 2.727 0 0 0-.919-1.677 2.754 2.754 0 0 0-1.799-.669 2.75 2.75 0 0 0-1.798.67 2.727 2.727 0 0 0-.918 1.676h-.017a2.601 2.601 0 0 0-.015.301l.001.069v.02l.001.034c.008.645.018 1.223.018 1.514 0 1.93.135 3.502.406 4.713.304 1.177.778 2.11 1.42 2.797a4.888 4.888 0 0 0 2.437 1.325 14.193 14.193 0 0 0 3.603.393c1.625 0 3.724-.147 4.807-.442a4.782 4.782 0 0 0 2.588-1.668c.677-.818 1.15-1.947 1.421-3.387.305-1.473.457-3.355.457-5.645 0-1.67-.05-3.01-.152-4.025a8.814 8.814 0 0 0-.457-2.504 4.072 4.072 0 0 0-.965-1.57 7.973 7.973 0 0 0-1.471-1.178 14.42 14.42 0 0 0-1.522-.835 23.44 23.44 0 0 0-1.827-.933 44.852 44.852 0 0 1-1.828-.982 15.286 15.286 0 0 1-1.471-1.03 4.987 4.987 0 0 1-.61-.59 2.126 2.126 0 0 1-.304-.736 7.718 7.718 0 0 1-.152-1.128v-1.866c-.01-.705.024-1.41.1-2.111a3.369 3.369 0 0 1 .357-1.227 1.225 1.225 0 0 1 .76-.54c.305-.098 1.152-.147 1.626-.147 1.082 0 1.76.31 2.03.933a2.917 2.917 0 0 1 .354 1.276c.01.358.016.822.017 1.31h.02l-.001.019c0 .726.289 1.421.804 1.934a2.755 2.755 0 0 0 1.944.802 2.754 2.754 0 0 0 1.943-.802 2.729 2.729 0 0 0 .805-1.934v-1.329a16.985 16.985 0 0 0-.355-3.78c-.203-1.047-.609-1.881-1.218-2.503-.575-.655-1.387-1.113-2.435-1.375-1.016-.294-2.319-.441-3.909-.441z"/></svg>
```

2023-11-13 09:33 UTC, weh commented on icons/zsh/zsh-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#000" d="M13.074 23.154C5.88 23.154 0 29.034 0 36.228v55.504c0 7.195 5.88 13.075 13.074 13.075H42.91a2.199 2.199 0 0 0 2.2-2.
fill="#000" can be removed
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M13.074 23.154C5.88 23.154 0 29.034 0 36.228v55.504c0 7.195 5.88 13.075 13.074 13.075H42.91a2.199 2.199 0 0 0 2.2-2.198 2.199 2.199 0 0 0-2.2-2.199H13.074a8.643 8.643 0 0 1-8.676-8.678V42.685h78.086V89.16a.49.49 0 0 1-.09.127.482.482 0 0 1-.341.143H79.36a.487.487 0 0 1-.486-.487v-8.13a2.177 2.177 0 0 0-2.176-2.178 2.178 2.178 0 0 0-1.539.638 2.178 2.178 0 0 0-.639 1.54l.002.023-.002.025v21.809c0 .577.231 1.131.64 1.539a2.176 2.176 0 0 0 1.538.637 2.175 2.175 0 0 0 1.54-.637 2.176 2.176 0 0 0 .636-1.539v-8.645a.483.483 0 0 1 .143-.342.487.487 0 0 1 .343-.142h2.692a.483.483 0 0 1 .431.267v8.801a2.199 2.199 0 0 0 .022.082 2.169 2.169 0 0 0 .07.537 2.167 2.167 0 0 0 .434.836 2.174 2.174 0 0 0 1.67.774h.017c.284 0 .564-.056.826-.164a2.165 2.165 0 0 0 .702-.469 2.153 2.153 0 0 0 .466-.7l.018-.044a2.199 2.199 0 0 0 .016-.047 2.144 2.144 0 0 0 .066-.217 2.199 2.199 0 0 0 .09-.588V36.23c0-7.195-5.88-13.075-13.074-13.075H13.074zm0 4.397h60.733a8.645 8.645 0 0 1 8.677 8.678v2.06H4.398v-2.06a8.643 8.643 0 0 1 8.676-8.678zm10.54 19.355a.773.773 0 0 0-.526.272L8.74 64.268a.773.773 0 0 0 .094 1.09.773.773 0 0 0 1.088-.096l14.35-17.09a.773.773 0 0 0-.094-1.088.773.773 0 0 0-.565-.178zm-10.643.434c-2.288 0-4.168 1.88-4.168 4.168 0 2.288 1.88 4.168 4.168 4.168 2.288 0 4.17-1.88 4.17-4.168 0-2.288-1.882-4.168-4.17-4.168zm0 2.412c.983 0 1.756.772 1.756 1.756s-.773 1.754-1.756 1.754c-.984 0-1.754-.77-1.754-1.754s.77-1.756 1.754-1.756zm7.021 7.021c-2.288 0-4.17 1.88-4.17 4.168 0 2.288 1.882 4.168 4.17 4.168 2.288 0 4.168-1.88 4.168-4.168 0-2.288-1.88-4.168-4.168-4.168zm0 2.412c.984 0 1.754.773 1.754 1.757 0 .983-.77 1.755-1.754 1.755a1.738 1.738 0 0 1-1.756-1.756c0-.983.772-1.755 1.756-1.755zm9.625 4.38a.773.773 0 0 0-.773.773.773.773 0 0 0 .773.771h10.246a.773.773 0 0 0 .774-.771.773.773 0 0 0-.774-.773H29.617zm20.295 15.058a2.214 2.214 0 0 0-1.56.647 2.21 2.21 0 0 0-.647 1.56v.002a2.193 2.193 0 0 0 .645 1.56 2.207 2.207 0 0 0 .716.48c.268.11.556.165.846.165.035 0 .067-.002.102-.004h4.066a.271.271 0 0 1 .127.031.278.278 0 0 1 .1.088.277.277 0 0 1 .044.125.276.276 0 0 1-.02.131l-6.452 16.12a2.427 2.427 0 0 0-.174.902v1.976c0 .644.256 1.262.71 1.717a2.424 2.424 0 0 0 1.716.711h7.566a2.259 2.259 0 0 0 .865-.172 2.257 2.257 0 0 0 1.225-1.224 2.27 2.27 0 0 0 .174-.868 2.267 2.267 0 0 0-2.266-2.265l-.05.002h-5.09a.26.26 0 0 1-.123-.03.262.262 0 0 1-.094-.086.262.262 0 0 1-.043-.119.26.26 0 0 1 .017-.125l7.444-18.558a2.01 2.01 0 0 0-.201-1.875 2.01 2.01 0 0 0-.723-.649 2.005 2.005 0 0 0-.941-.234h-7.846c-.045-.003-.088-.008-.133-.008zm39.285 0a.842.842 0 0 0-.842.842v24.474c0 .464.377.84.84.84h8.123a2.263 2.263 0 0 0 0-4.527h-4.191a.521.521 0 0 1-.521-.521v-5.735a.515.515 0 0 1 .515-.516h4.334a2.056 2.056 0 1 0 0-4.111h-4.334a.515.515 0 0 1-.515-.516v-5.386a.523.523 0 0 1 .523-.524h4.326a2.16 2.16 0 0 0 0-4.32h-8.258zm14.026 0a2.125 2.125 0 0 0-2.125 2.125v23.414c0 .34.275.617.615.617h9.826a2.264 2.264 0 0 0 0-4.527h-5.781a.41.41 0 0 1-.41-.41V80.748a2.125 2.125 0 0 0-2.125-2.125zm14.197 0a2.125 2.125 0 0 0-2.125 2.125v23.414c0 .34.275.617.615.617h9.826a2.264 2.264 0 0 0 0-4.527h-5.78a.41.41 0 0 1-.411-.41V80.748a2.125 2.125 0 0 0-2.125-2.125zm-49.73.123c-1.034 0-2.216.1-2.928.299a3.428 3.428 0 0 0-1.69.967c-.413.466-.71 1.099-.894 1.898-.184.778-.276 1.767-.276 2.967 0 1.155.01 2.086.033 2.797a13.003 13.003 0 0 0 .207 1.732c.087.379.238.74.448 1.067a4.284 4.284 0 0 0 .69.767 7.026 7.026 0 0 0 1.171.832c.46.267.93.522 1.412.766.482.245.943.5 1.38.768.41.23.792.51 1.136.832a4.7 4.7 0 0 1 .379.466c.083.099.148.213.191.334.04.109.073.22.1.332a2.35 2.35 0 0 1 .053.534c.023.266.035.633.035 1.1a13.69 13.69 0 0 1-.104 1.898 2.705 2.705 0 0 1-.275 1.033.947.947 0 0 1-.551.433c-.23.067-1.025.1-1.37.1a3.008 3.008 0 0 1-.825-.1 1.141 1.141 0 0 1-.518-.466 3.87 3.87 0 0 1-.275-1 15.986 15.986 0 0 1-.069-1.663 1.867 1.867 0 0 0-.01-.185h-.013a1.851 1.851 0 0 0-.623-1.139 1.872 1.872 0 0 0-1.223-.453c-.448 0-.881.16-1.22.453a1.851 1.851 0 0 0-.623 1.139h-.01a1.784 1.784 0 0 0-.012.205l.002.047-.002.013.002.022c.005.438.012.83.012 1.027 0 1.31.091 2.378.275 3.2.207.799.529 1.434.965 1.9a3.317 3.317 0 0 0 1.654.898 9.63 9.63 0 0 0 2.446.268c1.102 0 2.526-.1 3.261-.3a3.25 3.25 0 0 0 1.758-1.134c.46-.555.781-1.321.965-2.298.207-1 .308-2.278.308-3.832 0-1.133-.034-2.042-.103-2.73a5.994 5.994 0 0 0-.309-1.702 2.76 2.76 0 0 0-.654-1.065 5.444 5.444 0 0 0-1-.8 9.809 9.809 0 0 0-1.033-.567 15.916 15.916 0 0 0-1.24-.633 30.6 30.6 0 0 1-1.24-.666 10.361 10.361 0 0 1-.999-.699 3.416 3.416 0 0 1-.414-.4 1.444 1.444 0 0 1-.207-.5 5.266 5.266 0 0 1-.103-.766v-1.265a11.743 11.743 0 0 1 .07-1.434 2.287 2.287 0 0 1 .24-.834.828.828 0 0 1 .516-.365c.207-.067.782-.1 1.104-.1.735 0 1.195.21 1.378.633.146.267.228.562.24.865.009.243.011.558.012.889h.014l-.002.013c0 .493.197.965.547 1.313a1.868 1.868 0 0 0 1.318.545c.495 0 .97-.197 1.32-.545a1.85 1.85 0 0 0 .546-1.313v-.013l.002-.889a11.516 11.516 0 0 0-.243-2.564c-.138-.711-.413-1.277-.826-1.7-.39-.444-.94-.755-1.652-.933-.69-.2-1.575-.299-2.654-.299z"/></svg>
```

2023-11-13 09:33 UTC, weh commented on icons/zsh/zsh-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#000" d="M19.264 3.822C8.664 3.822 0 12.486 0 23.086v81.771c0 10.6 8.664 19.264 19.264 19.264h43.955a3.24 3.24 0 0 0 3.24-3.2
fill="#000" can be removed
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M19.264 3.822C8.664 3.822 0 12.486 0 23.086v81.771c0 10.6 8.664 19.264 19.264 19.264h43.955a3.24 3.24 0 0 0 3.24-3.24 3.24 3.24 0 0 0-3.24-3.24H19.264a12.736 12.736 0 0 1-12.785-12.784v-72.26h115.043v68.471a.713.713 0 0 1-.131.186.716.716 0 0 1-.506.21h-3.965a.716.716 0 0 1-.506-.21.715.715 0 0 1-.209-.506V88.84l-.002-.035.002-.037a3.208 3.208 0 0 0-3.207-3.207 3.207 3.207 0 0 0-2.267.939 3.206 3.206 0 0 0-.94 2.268l.002.037-.002.035v32.13c0 .851.338 1.667.94 2.268a3.206 3.206 0 0 0 4.535 0 3.208 3.208 0 0 0 .94-2.267v-12.735c0-.19.074-.371.208-.505a.715.715 0 0 1 .506-.21h3.965c.19 0 .372.076.506.21a.716.716 0 0 1 .13.185v12.965a3.24 3.24 0 0 0 .034.12c.003.267.033.535.101.794a3.187 3.187 0 0 0 .64 1.23 3.2 3.2 0 0 0 1.104.844 3.189 3.189 0 0 0 1.356.297l.014-.002.011.002a3.18 3.18 0 0 0 2.94-1.965c.009-.02.013-.042.021-.062a3.24 3.24 0 0 0 .03-.078 3.18 3.18 0 0 0 .095-.313 3.24 3.24 0 0 0 .133-.867V23.086c0-10.6-8.662-19.264-19.262-19.264H19.264zm0 6.479h89.474a12.736 12.736 0 0 1 12.783 12.785v3.033H6.478v-3.033a12.737 12.737 0 0 1 12.786-12.785zm14.658 28.515a1.138 1.138 0 0 0-.774.4l-21.14 25.178a1.138 1.138 0 0 0 .14 1.604 1.138 1.138 0 0 0 1.602-.139l21.143-25.177a1.138 1.138 0 0 0-.141-1.604 1.138 1.138 0 0 0-.83-.262zm-15.68.637c-3.37 0-6.14 2.772-6.14 6.143s2.77 6.14 6.14 6.14c3.37 0 6.14-2.77 6.14-6.14 0-3.371-2.77-6.143-6.14-6.143zm0 3.557c1.45 0 2.586 1.137 2.586 2.586s-1.137 2.586-2.586 2.586a2.56 2.56 0 0 1-2.586-2.586 2.56 2.56 0 0 1 2.586-2.586zm10.344 10.344c-3.37 0-6.143 2.77-6.143 6.14 0 3.37 2.772 6.14 6.143 6.14 3.37 0 6.14-2.77 6.14-6.14s-2.77-6.14-6.14-6.14zm0 3.554a2.56 2.56 0 0 1 2.586 2.586 2.56 2.56 0 0 1-2.586 2.586A2.56 2.56 0 0 1 26 59.494a2.56 2.56 0 0 1 2.586-2.586zm14.18 6.451a1.138 1.138 0 0 0-1.139 1.137 1.138 1.138 0 0 0 1.139 1.139H57.86A1.138 1.138 0 0 0 59 64.496a1.138 1.138 0 0 0-1.139-1.137H42.766zm30.767 22.186a3.253 3.253 0 0 0-1.244.248 3.265 3.265 0 0 0-1.057.705 3.251 3.251 0 0 0-.703 1.055 3.25 3.25 0 0 0-.248 1.244v.002a3.24 3.24 0 0 0 .951 2.299 3.246 3.246 0 0 0 1.057.703 3.241 3.241 0 0 0 1.244.248c.051 0 .1-.006.15-.008h5.99a.404.404 0 0 1 .335.176.41.41 0 0 1 .066.183.408.408 0 0 1-.027.194l-9.51 23.748a3.58 3.58 0 0 0-.256 1.33v2.912c0 .948.377 1.857 1.047 2.527a3.58 3.58 0 0 0 2.53 1.05h11.146a3.334 3.334 0 0 0 1.275-.255 3.343 3.343 0 0 0 1.082-.722 3.327 3.327 0 0 0 .723-1.082 3.326 3.326 0 0 0 .254-1.276v-.002a3.338 3.338 0 0 0-.977-2.36 3.338 3.338 0 0 0-2.359-.976c-.026 0-.05.003-.076.004h-7.498a.387.387 0 0 1-.182-.045.38.38 0 0 1-.137-.125.39.39 0 0 1-.066-.176.382.382 0 0 1 .027-.183l10.967-27.344a2.964 2.964 0 0 0 .195-1.418 2.955 2.955 0 0 0-.49-1.344 2.97 2.97 0 0 0-1.066-.957 2.961 2.961 0 0 0-1.389-.345H73.728c-.065-.004-.128-.01-.195-.01zm26.192.18c-1.523 0-3.266.147-4.315.441a5.042 5.042 0 0 0-2.486 1.424c-.609.687-1.05 1.619-1.32 2.797-.272 1.145-.405 2.602-.405 4.369 0 1.701.015 3.076.049 4.123a19.145 19.145 0 0 0 .305 2.553 4.957 4.957 0 0 0 .66 1.57 6.3 6.3 0 0 0 1.015 1.129 10.337 10.337 0 0 0 1.725 1.228c.677.393 1.372.767 2.082 1.127a29.432 29.432 0 0 1 2.03 1.13 8.647 8.647 0 0 1 1.675 1.228c.2.217.386.447.557.687.123.146.22.311.283.49.059.16.11.325.148.49.056.26.082.522.079.786.033.392.048.934.048 1.62a20.153 20.153 0 0 1-.15 2.798 3.99 3.99 0 0 1-.406 1.521 1.397 1.397 0 0 1-.813.639c-.338.098-1.508.146-2.015.146a4.42 4.42 0 0 1-1.219-.146 1.676 1.676 0 0 1-.76-.688 5.713 5.713 0 0 1-.406-1.472 23.667 23.667 0 0 1-.104-2.45c0-.09-.004-.182-.013-.273h-.02a2.728 2.728 0 0 0-.918-1.678 2.757 2.757 0 0 0-1.8-.668 2.747 2.747 0 0 0-1.798.668 2.728 2.728 0 0 0-.917 1.678h-.018a2.6 2.6 0 0 0-.014.301v.123c.009.645.018 1.223.018 1.514 0 1.93.136 3.501.406 4.713.305 1.177.78 2.11 1.422 2.796a4.887 4.887 0 0 0 2.436 1.327 14.194 14.194 0 0 0 3.603.392c1.625 0 3.724-.147 4.807-.441a4.78 4.78 0 0 0 2.588-1.668c.676-.818 1.15-1.949 1.422-3.389.304-1.472.457-3.354.457-5.644 0-1.67-.051-3.011-.153-4.026a8.816 8.816 0 0 0-.457-2.504 4.07 4.07 0 0 0-.965-1.57 7.968 7.968 0 0 0-1.47-1.178 14.43 14.43 0 0 0-1.524-.834 23.424 23.424 0 0 0-1.826-.933 44.885 44.885 0 0 1-1.828-.98 15.28 15.28 0 0 1-1.47-1.032 5 5 0 0 1-.61-.59 2.125 2.125 0 0 1-.305-.736 7.721 7.721 0 0 1-.152-1.13V95.64a17.363 17.363 0 0 1 .101-2.112 3.367 3.367 0 0 1 .356-1.226 1.222 1.222 0 0 1 .76-.54c.304-.098 1.153-.148 1.627-.148 1.082 0 1.758.312 2.029.934.214.393.335.828.353 1.275.012.358.017.824.018 1.31h.02v.02c0 .726.289 1.421.804 1.934a2.753 2.753 0 0 0 1.944.8c.728 0 1.428-.287 1.943-.8a2.728 2.728 0 0 0 .805-1.934l-.002-.02h.002v-1.31a16.978 16.978 0 0 0-.356-3.779c-.203-1.047-.61-1.88-1.219-2.502-.575-.655-1.387-1.113-2.435-1.375-1.015-.294-2.317-.441-3.906-.441h-.002z"/></svg>
```

2023-11-17 14:09 UTC, weh approved these changes

2024-11-12 03:59 UTC, canaleal commented
Very minor artifacts on the line logo version that have to be fixed:

![image](https://github.com/user-attachments/assets/9e768911-da0b-4198-aff2-99aeb07b53d9)

2025-03-09 01:15 UTC, merged