updated icon: msdos (original, plain, line)
devicons/devicon pull request #1980
Opened 2023-11-06 22:47 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to this issue #1977**

## Link to prove your SVG is correct and up-to-date.

- [MSDOS wikipedia](https://commons.wikimedia.org/wiki/File:Msdos-icon.svg)

It's not the official link, but I didn't change the icon from the previous PR.
- https://github.com/devicons/devicon/pull/726

I updated the color to `#000` as that is the most common color in the original logo, and it's already used in the line svg.

2023-11-09 23:35 UTC, lunatic-fox submitted a review, later dismissed
Problem solved! 👍🏼
Thank you for this contribution! 🚀 

What do you think about remove the padding of those icons @canaleal and @Snailedlt?

2023-11-11 14:25 UTC, Snailedlt reviewed
Looks good, but like @lunatic-fox mentioned the padding should be removed :)

2023-11-11 19:04 UTC, Snailedlt requested changes
Size looks good now. I now noticed that msdos-plain has multiple paths though, so those need to be unified

2023-11-11 19:04 UTC, Snailedlt commented on icons/msdos/msdos-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="M84.21 32.242v3.85h3.97v3.73h11.428v-3.25h-3.85v-4.33Zm15.4-12.39v-7.22H88.185v7.22zm0 0"/><path d="M103.583.599H84.211v3.855h-8
This one has multiple paths :O
Should be unified

2023-11-12 13:50 UTC, Snailedlt approved these changes
Everything looks good now! Great work as always! 💯 
![image](https://github.com/devicons/devicon/assets/43886029/dac75777-c8db-4900-8deb-488a6e033a07)
![image](https://github.com/devicons/devicon/assets/43886029/581d2b4d-d672-4461-b9b0-f11a3509bf54)
![image](https://github.com/devicons/devicon/assets/43886029/e6b7dfdb-e057-4d1e-96b9-3f1dbc2dc31a)

2023-11-12 17:20 UTC, lunatic-fox approved these changes
Great one! 👍🏼
Thank you for this contribution! 🚀

> *PS: This icon is really nostalgic.*

2023-11-12 17:34 UTC, merged