Add alias and remove duplicate files
devicons/devicon pull request #2001
Opened 2023-11-13 12:15 UTC by weh

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

This solves a part of the open tasks from https://github.com/devicons/devicon/pull/1998#issuecomment-1807542194

* [x]  digitalocean
* [x]  gatsby
* [x]  mysql
* [x]  nodejs
* [ ]  opensuse
* [x]  postcss
* [x]  spring
* [x]  typo3

## Notes

I will check on the opensuse icons later. the svg files currently include inkscape metadata. either there is a open PR or i add it later

2023-11-13 12:16 UTC, weh commented
Oh, btw this is the PR where i asked myself if we want to have newlines in the svg files, or if we need to remove them.

2023-11-13 23:17 UTC, canaleal requested changes
Some minor modifications need to be made for `digitalocean`, `postcss`, and `gatsby`, but aside from that all is good.

2023-11-13 23:17 UTC, canaleal commented on icons/gatsby/gatsby-plain-wordmark.svg
The `gatsby-original-wordmark.svg` has 2 paths and 2 different fill colors. It unfortunately cant be used for `plain-wordmark`.

2023-11-13 23:17 UTC, canaleal commented on icons/digitalocean/digitalocean-plain-wordmark.svg
Thankfully both plain svgs for digital ocean can be removed, but the original svgs have to be updated to have 1 path and fill color. They also have to be scaled to fit the viewbox.

![image](https://github.com/devicons/devicon/assets/49886351/d7b037d0-29d8-44c5-b4b3-53d6cec25fcb)

2023-11-14 03:45 UTC, lunatic-fox commented
> Oh, btw this is the PR where i asked myself if we want to have newlines in the svg files, or if we need to remove them.

@weh, the newline character at the end of the file is used, if I'm not mistaken, for compatibility reasons.

2023-11-14 04:00 UTC, lunatic-fox commented
First of all, thank you @weh and @canaleal for quickly make pull requests to fix the found errors. That means a lot! 🚀

@weh, as @canaleal had explained in this [comment](https://github.com/devicons/devicon/pull/2001#discussion_r1391798515), we need to make some changes in the icons.

This type of error needs a pull request for each icon, like the one you made for [opensuse](https://github.com/devicons/devicon/pull/2002), because even if we are not modifying an icon, some icon will be deleted eventually. I'm not sure, but since pull request titles together with `devicon.json` affect what icons will be built I think this is a safer strategy.

2023-11-15 10:30 UTC, weh commented
sure, i will split the request, and also fix the mentioned svg files when i find time :+1:

2023-11-15 12:43 UTC, weh commented on icons/digitalocean/digitalocean-plain-wordmark.svg
done in https://github.com/devicons/devicon/pull/2005

2023-11-15 15:49 UTC, weh commented on icons/gatsby/gatsby-plain-wordmark.svg
updated in #2001

2023-11-16 12:55 UTC, weh commented on icons/postcss/postcss-plain.svg
updated in #2012

2023-11-19 13:04 UTC, Snailedlt commented
Closing this PR since it's being split into multiple PR's

2023-11-19 13:04 UTC, closed without merging