update icon: mysql (original, original-wordmark, plain-wordmark)
devicons/devicon pull request #2007
Opened 2023-11-15 16:03 UTC by weh

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

- Replace plain version with alias
- Add newlines

**This PR closes NONE**

related to #2001
## Notes

2023-11-15 22:16 UTC, canaleal requested changes
Great stuff. Everything looks real good. 
All that's left is to do is remove the padding around each SVG and it's ready for merging. 

![image](https://github.com/devicons/devicon/assets/49886351/7aeffe8f-de76-4ccd-992a-7f14840e9dc9)

2023-11-16 09:32 UTC, weh commented
Padding is removed, should be ready now (?)

2023-11-17 03:52 UTC, canaleal approved these changes
Excellent, great stuff.

2023-11-19 13:35 UTC, Snailedlt approved these changes
LGTM! ✔️ 
Thank you for another great contribution! 💯 🙇
![image](https://github.com/devicons/devicon/assets/43886029/7e4c0d16-105d-435b-9a86-c0a134637132)
![image](https://github.com/devicons/devicon/assets/43886029/4792cdc0-799e-4fe6-b052-9f5bde81391a)
![image](https://github.com/devicons/devicon/assets/43886029/60a6c945-bfc0-4f02-9c16-9581bf07e7c7)

2023-11-24 01:37 UTC, lunatic-fox approved these changes
Great work! 👍🏼
Thank you for this contribution! 🚀

2023-11-25 15:28 UTC, merged