update icon: zend (original, original-wordmark, line, line-wordmark)
devicons/devicon pull request #2026
Opened 2023-11-20 08:41 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Zend website](https://framework.zend.com/)

An older icon sir, but it still checks out:
- https://github.com/devicons/devicon/commit/c63fc2849ce4b5e905c6711490a9c55603e1813e

Used the color `#68b604` for the font SVGs.

2023-11-20 20:32 UTC, Snailedlt requested changes
Great PR again!
Unfortunately there are some artifacts on the wordmark versions:
![image](https://github.com/devicons/devicon/assets/43886029/3451d3f6-6856-48b0-b268-4747608837fb)
![image](https://github.com/devicons/devicon/assets/43886029/deb1dc3a-4a7c-409a-9e9a-181a681fa9a2)

2023-11-25 16:14 UTC, Snailedlt requested changes
There's unfortunately still some artifacts here :/
![image](https://github.com/devicons/devicon/assets/43886029/7776f596-ef1c-4380-9296-caa44f0b0656)
![image](https://github.com/devicons/devicon/assets/43886029/fc27a7b8-ff23-4d83-9a5c-4b67f1669b4c)

2023-11-25 17:11 UTC, canaleal commented
I might need some help solving the artifact problem. 

Before optimizing the SVGs using SVGOMG, the artifacts do not appear in any of the wordmark logos. It's only after optimizing the SVGs, that the artifacts show. 

![image](https://github.com/devicons/devicon/assets/49886351/8edb6ca1-29ff-4569-9233-28fe6a47e434)
![image](https://github.com/devicons/devicon/assets/49886351/64ddb596-68b4-454a-92e3-26f0c2633d75)

2023-11-25 17:15 UTC, Snailedlt commented
@canaleal Could you please add the non-optimized versions to a comment so that we can help more easily? :)

2023-11-25 18:12 UTC, canaleal commented
Here are the non-optimized versions:

zend-original-wordmark.svg
```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svgviewBox="0 0 128 128"version="1.1"id="svg1"sodipodi:docname="zend-original-wordmark.svg"inkscape:version="1.3 (0e150ed6c4, 2023-07-21)"xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"xmlns="http://www.w3.org/2000/svg"xmlns:svg="http://www.w3.org/2000/svg"><defsid="defs1" /><sodipodi:namedviewid="namedview1"pagecolor="#ffffff"bordercolor="#000000"borderopacity="0.25"inkscape:showpageshadow="2"inkscape:pageopacity="0.0"inkscape:pagecheckerboard="0"inkscape:deskcolor="#d1d1d1"inkscape:zoom="3.4140625"inkscape:cx="64"inkscape:cy="64"inkscape:window-width="1366"inkscape:window-height="697"inkscape:window-x="-8"inkscape:window-y="-8"inkscape:window-maximized="1"inkscape:current-layer="svg1" /><pathfill="#68b604"d="m 53.329,57.608 c -8.468,0.03 -16.936,0.213 -25.404,0.213 H 26.707 C 38.408,41.392 49.945,25.774 61.565,9.847 61.171,9.82 60.981,9.699 60.791,9.699 42.462,9.697 24.134,9.652 5.804,9.638 c -0.643,0 -0.864,0.14 -0.858,0.819 0.032,3.788 0.015,7.564 0.015,11.353 0,1.08 10e-4,1.075 1.096,1.075 9.276,10e-4 18.552,-0.003 27.828,10e-4 0.365,0 0.73,0.048 1.29,0.089 L 0.114,70.81 l 0.6,0.034 c 17.605,0.001 35.21,-0.003 52.814,0.017 0.72,10e-4 0.815,-0.288 0.812,-0.889 -0.018,-3.844 -0.03,-7.59 0.01,-11.434 0.006,-0.8 -0.212,-0.932 -1.021,-0.93 z M 60.267,26.49 c 0.027,0.73 0.454,0.527 0.892,0.527 h 25.493 c 4.29,0 8.581,0.12 12.872,0.094 4.677,-0.028 9.364,0.127 14.028,-0.15 4.83,-0.287 8.686,-2.542 11.347,-6.667 1.79,-2.775 2.582,-5.864 2.974,-9.1 0.107,-0.885 -0.46,-0.763 -0.989,-0.763 -16.605,0.001 -33.21,-0.018 -49.817,0.035 -1.841,0.007 -3.73,0.196 -5.514,0.655 -6.41,1.645 -11.537,8.719 -11.286,15.37 z m 16.055,5.649 c -2.71,0.003 -5.32,0.53 -7.704,1.839 -5.55,3.041 -7.682,8.133 -8.337,14.09 -0.086,0.787 0.39,0.766 0.93,0.765 4.427,-0.008 8.853,-0.005 13.28,-0.005 1.504,0 3.008,0.022 4.512,-0.004 3.308,-0.055 6.637,0.071 9.92,-0.254 4.268,-0.423 7.737,-2.503 10.205,-6.076 1.94,-2.808 2.909,-5.968 3.246,-9.347 0.099,-0.99 0.139,-1.011 -0.825,-1.012 -8.41,-10e-4 -16.819,-0.006 -25.227,0.004 z m 9.12,22.293 c -0.004,-0.59 -0.234,-0.694 -0.742,-0.69 -2.56,0.016 -5.122,-0.024 -7.682,0.021 -1.192281,0.02099 -2.381727,0.123564 -3.56,0.307 -9.197,1.434 -12.629,9.13 -13.18,15.697 -0.048,0.588 0.163,0.782 0.75,0.77 1.53,-0.031 3.061,-0.012 4.592,-0.012 l 0.003,0.086 c 2.082,-0.093 4.183,-0.037 6.242,-0.303 7.733,-0.997 13.636,-7.972 13.577,-15.877 z m -52.533,49.937 c -0.095,-0.287 -0.24,-0.38 -0.526,-0.376 -0.963,0.012 -1.925,0.018 -2.888,-0.003 -0.351,-0.007 -0.501,0.118 -0.611,0.452 -1.24,3.795 -2.498,7.585 -3.753,11.374 -0.205,0.615 -0.42,1.226 -0.667,1.95 l -4.394,-5.668 0.31,-0.211 c 1.284,-0.753 2.137,-1.806 2.299,-3.33 0.202,-1.891 -0.338,-3.433 -2.408,-4.218 -0.530357,-0.19207 -1.088999,-0.29447 -1.653,-0.303 -2.062,-0.043 -4.126,-0.026 -6.188,-0.044 -0.337,-0.003 -0.483,0.072 -0.482,0.457 0.012,4.4 0.012,8.801 0,13.202 0,0.359 0.13,0.438 0.457,0.43 0.809506,-0.0235 1.619533,-0.0228 2.429,0.002 0.41,0.015 0.557,-0.087 0.548,-0.527 -0.028,-1.405 -0.014,-2.812 -0.004,-4.217 10e-4,-0.15 0.04,-0.368 0.14,-0.436 0.327,-0.22 1.185,0.007 1.43,0.336 1.112,1.496 2.218,2.996 3.347,4.479 0.127,0.168 0.38,0.339 0.577,0.34 2.185,0.025 4.37,0.01 6.555,0.023 0.294,0.002 0.4,-0.117 0.47,-0.373 l 0.614,-2.106 c 0.085,-0.314 0.246,-0.443 0.581,-0.438 1.192,0.016 2.384,0.015 3.575,0 0.342,-0.005 0.482,0.138 0.567,0.452 0.191,0.707 0.406,1.406 0.638,2.099 0.047,0.14 0.213,0.339 0.33,0.342 1.05,0.026 2.102,0.015 3.192,0.015 l -0.064,-0.338 c -1.476,-4.452 -2.955,-8.907 -4.421,-13.365 z m -14.821,5.78 c -0.792,0.216 -1.649,0.204 -2.48,0.26 -0.07,0.005 -0.22,-0.224 -0.227,-0.349 -0.024,-0.55 -0.01,-1.099 -0.01,-1.649 0,-0.518 0.006,-1.039 -0.003,-1.558 -0.004,-0.234 0.053,-0.397 0.321,-0.386 0.715,0.028 1.439,0.004 2.142,0.11 0.84,0.124 1.29,0.664 1.36,1.436 0.095,1.051 -0.261,1.904 -1.103,2.135 z m 11.313,2.092 c 0.48,-1.027 0.94,-2.886 1.399,-4.402 l 0.14,-0.109 c 0.461,1.517 0.922,3.485 1.405,4.512 z m 55.75,-8.245 c -0.84,0.006 -1.682,0.025 -2.52,-0.01 -0.401,-0.016 -0.526,0.157 -0.598,0.505 -0.491,2.37 -0.992,4.737 -1.493,7.105 -0.124,0.582 -0.257,1.162 -0.386,1.74 -0.118427,-0.11807 -0.197974,-0.26949 -0.228,-0.434 -0.666,-2.831 -1.336,-5.661 -1.985,-8.495 -0.075,-0.329 -0.22,-0.418 -0.528,-0.413 -0.824,0.012 -1.651,0.024 -2.475,-0.006 -0.382,-0.013 -0.535,0.132 -0.62,0.488 -0.548,2.295 -1.11,4.588 -1.672,6.88 -0.16,0.65 -0.333,1.296 -0.5,1.944 l -0.134,-0.006 c -0.109,-0.511 -0.225,-1.021 -0.327,-1.535 -0.495,-2.461 -0.983,-4.924 -1.49,-7.384 -0.028,-0.14 -0.204,-0.352 -0.314,-0.355 -1.065,-0.028 -2.131,-0.016 -3.227,-0.016 l 0.05,0.408 c 1.1,4.433 2.202,8.867 3.299,13.301 0.064,0.26 0.178,0.376 0.469,0.37 0.962204,-0.0238 1.924866,-0.0225 2.887,0.004 0.383,0.012 0.53,-0.113 0.616,-0.476 0.543,-2.265 1.105,-4.526 1.664,-6.787 0.112,-0.453 0.239,-0.902 0.36,-1.353 l 0.114,0.017 0.12,0.387 c 0.665,2.58 1.335,5.158 1.981,7.745 0.086,0.347 0.214,0.475 0.577,0.465 0.947199,-0.0226 1.894801,-0.0226 2.842,0 0.333,0.008 0.48,-0.093 0.562,-0.424 1.085543,-4.42175 2.180879,-8.8411 3.286,-13.258 0.082,-0.338 -0.037,-0.409 -0.33,-0.407 z m -32.15,0.472 c 0,-0.356 -0.11,-0.484 -0.473,-0.477 -0.993234,0.0202 -1.986779,0.0198 -2.98,-0.001 -0.356,-0.007 -0.542,0.103 -0.687,0.443 -0.796,1.866 -1.62,3.721 -2.434,5.58 l -0.44,0.949 -0.283,-0.56 c -0.88,-1.997 -1.764,-3.992 -2.631,-5.994 -0.127,-0.294 -0.28,-0.422 -0.61,-0.416 -1.023595,0.0166 -2.047385,0.0172 -3.071,0.002 -0.334,-0.005 -0.487,0.066 -0.486,0.455 0.014,4.4 0.013,8.801 10e-4,13.203 0,0.357 0.126,0.44 0.454,0.43 0.748831,-0.0236 1.498235,-0.0226 2.247,0.003 0.411,0.018 0.695,-0.092 0.692,-0.53 -0.022,-2.735 0.135,-5.47 0.135,-8.206 v -0.473 c 0,0.139 0.12,0.293 0.187,0.455 0.68,1.633 1.297,3.262 1.956,4.904 0.15,0.374 0.312,0.515 0.71,0.486 0.456,-0.034 0.9,-0.024 1.357,-0.002 0.308,0.014 0.457,-0.104 0.571,-0.388 0.408,-1.02 0.835,-2.03 1.258,-3.044 l 1.01,-2.44 0.14,0.023 v 0.482 c 0,2.735 0.015,5.47 0,8.206 -0.002,0.386 0.08,0.545 0.505,0.528 0.794716,-0.0294 1.590236,-0.0301 2.385,-0.002 0.353,0.01 0.487,-0.086 0.486,-0.457 -0.01,-4.386 -0.008,-8.773 10e-4,-13.159 z m 57.301,7.55 0.111,-0.078 c 1.413,-0.791 2.28,-1.943 2.41,-3.599 0.123,-1.567 -0.324,-2.87 -1.79,-3.72 -0.705,-0.407 -1.481,-0.578 -2.278,-0.59 -2.062,-0.03 -4.125,-0.02 -6.186,-0.038 -0.34,-0.004 -0.483,0.076 -0.482,0.458 0.013,4.4 0.012,8.8 0,13.2 0,0.353 0.124,0.439 0.454,0.43 0.8245,-0.0248 1.64958,-0.0235 2.474,0.004 0.422,0.018 0.51,-0.134 0.503,-0.524 -0.021,-1.421 -0.01,-2.842 -0.001,-4.262 0,-0.137 0.033,-0.334 0.125,-0.398 0.299,-0.207 1.18,0.008 1.402,0.307 1.112,1.495 2.227,2.987 3.33,4.49 0.197,0.268 0.402,0.397 0.755,0.387 1.053,-0.026 2.108,-0.009 3.162,-0.01 l 0.508,-0.028 -4.579,-5.914 z m -2.612,-1.685 c -0.587,0.071 -1.185,0.064 -1.776,0.105 -0.33,0.023 -0.42,-0.126 -0.408,-0.432 0.019,-0.518 0.005,-1.037 0.005,-1.556 0,-0.55 -0.014,-1.099 0.013,-1.647 0.005,-0.115 0.168,-0.32 0.256,-0.32 0.73,0.006 1.47,-0.02 2.183,0.098 0.978,0.165 1.415,0.827 1.368,1.853 -0.047,1.014 -0.688,1.782 -1.641,1.9 z m -12.204,-6.345 c -1.063,-0.317 -2.148,-0.383 -3.256,-0.249 -1.494,0.182 -2.793,0.74 -3.82,1.86 -1.407,1.535 -1.81,3.41 -1.877,5.422 0.083,0.71 0.112,1.432 0.259,2.127 0.47,2.227 1.632,3.925 3.825,4.784 0.998,0.39 2.043,0.447 3.103,0.427 2.603,-0.049 4.77,-1.54 5.653,-3.986 0.777,-2.152 0.782,-4.349 0.066,-6.508 -0.64,-1.94 -1.956,-3.286 -3.953,-3.877 z m 0.297,10.159 c -0.537,1.008 -1.332,1.605 -2.507,1.616 -1.198,0.012 -2.051,-0.576 -2.536,-1.625 -0.288931,-0.61866 -0.48117,-1.278 -0.57,-1.955 -0.17,-1.401 -0.127,-2.805 0.485,-4.123 0.396,-0.853 0.987,-1.505 1.95,-1.713 1.322,-0.285 2.493,0.261 3.142,1.472 0.547,1.022 0.697,2.132 0.66,3.275 0.029,1.067 -0.113,2.095 -0.624,3.053 z m 31.806,3.292 c -1.476,-2.172 -2.947,-4.348 -4.438,-6.51  [...]

2023-11-30 22:21 UTC, lunatic-fox approved these changes
Seems that everything is ok right now! 🔧
Thank you for this contribution! 🚀
![image](https://github.com/devicons/devicon/assets/76992016/90e16530-2ab5-40eb-9d27-b4137c126030)
![image](https://github.com/devicons/devicon/assets/76992016/21dd3871-2a73-42aa-82de-538511632723)
![image](https://github.com/devicons/devicon/assets/76992016/5421cdfa-a0e7-490c-b10b-7eaae3f7ed3d)
![image](https://github.com/devicons/devicon/assets/76992016/b3d61636-c3b2-489b-89bc-3f32540cd859)

2023-12-05 16:06 UTC, Snailedlt approved these changes
LGTM! ✔️ 
Thank you for another great contribution! 💯 🙇

Also thank you @lunatic-fox for fixing the artifacting issue. I'm wondering how you did it, when you have time, could you please explain how, and possible make a tutorial if it's something that's generic enough to apply to other similar problems? :)

2023-12-05 16:09 UTC, merged