update icon: vertx (original, original-wordmark, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #2045
Opened 2023-11-22 06:34 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Vertx Website](https://vertx.io/)
- [Vertx Github](https://github.com/eclipse-vertx/vert.x)

## Additional Notes

Some wordmarks have the TM (Trade Mark) text; I went with the version without the TX. 
The purple color `#782a90` was used for the font SVGs.

2023-12-07 15:45 UTC, Snailedlt requested changes
Looks like you made some typos on the color code for a few of the icons. Other than that it looks great!
![image](https://github.com/devicons/devicon/assets/43886029/ba8161ce-d230-4874-919a-118a337a2107)
![image](https://github.com/devicons/devicon/assets/43886029/c178229f-2614-46f7-b414-870a23a13464)
![image](https://github.com/devicons/devicon/assets/43886029/b9c58483-8ae9-4c5f-bf82-8a584af9ddd0)
![image](https://github.com/devicons/devicon/assets/43886029/7d899274-8352-45b2-bf23-4697e30a7d13)

2023-12-07 15:45 UTC, Snailedlt commented on icons/vertx/vertx-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#782a90" d="M16.878 0h94.244A16.84 16.84 0 0 1 128 16.878v94.244A16.84 16.84 0 0 1 111.122 128H16.878A16.84 16.84 0 0 1 0 111
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#782a91" d="M16.878 0h94.244A16.84 16.84 0 0 1 128 16.878v94.244A16.84 16.84 0 0 1 111.122 128H16.878A16.84 16.84 0 0 1 0 111.122V16.878A16.84 16.84 0 0 1 16.878 0Z"/><path fill="#fff" d="M0 26.309v6.03l26.58 60.369 3.803 8.636h7.465a18.19 18.19 0 0 1-.014-.182A17.282 17.282 0 0 1 48.7 85.158l19.564-42.814L83.449 63.68l-17.19 24.276a17.282 17.282 0 0 1 6.129 12.809h7.79l13.896-19.624 9.234-13.04L127.8 33.519v-7.21h-18.394L94.869 47.554 80.295 26.31H56.852l.041.058L36.745 70.46l-19.44-44.15Zm109.788 46.199L98.84 88.215l8.456 12.55h20.502v-2.948Zm-54.672 17.87c-5.956 0-10.785 4.828-10.785 10.784 0 5.957 4.829 10.786 10.785 10.786 5.957 0 10.785-4.83 10.785-10.786 0-5.956-4.828-10.784-10.785-10.785Z"/></svg>
```

2023-12-07 15:45 UTC, Snailedlt commented on icons/vertx/vertx-line.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#782a90" d="M17.205 0A17.177 17.177 0 0 0 0 17.205v9.365l.445.448H17.34l19.185 43.58.817.004 19.916-43.584h22.69l14.34 20.902
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#782a91" d="M17.205 0A17.177 17.177 0 0 0 0 17.205v9.365l.445.448H17.34l19.185 43.58.817.004 19.916-43.584h22.69l14.34 20.902h.735l14.301-20.902H128v-9.813C128 7.681 120.32 0 110.795 0h-93.59zm0 .893h93.59a16.268 16.268 0 0 1 16.312 16.312v8.92h-18.02l-.368.193-14.065 20.56-14.103-20.56-.37-.193h-23.28l-.366.701-.105-.15-19.49 42.646-18.9-42.931-.408-.266H.893v-8.92A16.268 16.268 0 0 1 17.205.893zM.855 32.38 0 32.56v78.234C0 120.319 7.68 128 17.205 128h93.59c9.524 0 17.205-7.68 17.205-17.205v-10.73h-20.765L99.138 88.05l10.334-14.824 17.435 24.498H128V33.588h-1.092L102.67 67.814 93.5 80.766l-13.666 19.296h-7.113a17.558 17.558 0 0 0-5.903-12.314l16.86-23.807v-.517l-15.08-21.19-.772.075-19.37 42.394a17.567 17.567 0 0 0-10.845 15.934h-6.703l-3.658-8.31L.855 32.38zm.038 2.303 25.539 58.004 3.775 8.576.41.265h7.412l.448-.48a18.744 18.744 0 0 1-.012-.156 16.713 16.713 0 0 1 10.51-15.467l.24-.23 19.103-41.81 14.448 20.298L65.877 87.53l.076.602a16.713 16.713 0 0 1 5.932 12.387l.445.435h7.734l.366-.187 13.8-19.487 9.17-12.95 23.707-33.48v61.61l-17.275-24.272-.73.004L98.23 87.791l-.003.506 8.398 12.465.37.193h20.112v9.842a16.268 16.268 0 0 1-16.312 16.312h-93.59A16.268 16.268 0 0 1 .893 110.795V34.684zM55.18 89.746c-6.156 0-11.159 5-11.159 11.156 0 6.157 5.002 11.157 11.159 11.157 6.157 0 11.152-5 11.152-11.157 0-6.156-4.996-11.156-11.152-11.156zm0 .893c5.673 0 10.261 4.59 10.261 10.263a10.256 10.256 0 0 1-10.261 10.266 10.259 10.259 0 0 1-10.268-10.266A10.26 10.26 0 0 1 55.18 90.641v-.002z"/></svg>
```

2023-12-07 16:25 UTC, lunatic-fox approved these changes
Great work! 👍🏼
And thank you @Snailedlt for noticing the wrong color.
Thank for this contribution! 🚀

2023-12-17 12:04 UTC, Snailedlt approved these changes

2023-12-17 12:06 UTC, merged