update icon: vsphere (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #2058
Opened 2023-11-25 13:37 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Vsphere Website](https://blogs.vmware.com/vsphere/2023/05/vsphere-8-update-1-general-availability.html)
- [Vsphere 8 Website](https://core.vmware.com/resource/whats-new-vsphere-8)

## Additional Notes

There are different versions of VMware vSphere, with the latest being 8.
The blue color `#0091da` was used for the font SVGs.

2023-12-05 15:41 UTC, Snailedlt submitted a review, later dismissed
Great work!
The fonts look great now! 💯 
![image](https://github.com/devicons/devicon/assets/43886029/86cd7e10-f0c0-487b-88d8-09874827e791)
![image](https://github.com/devicons/devicon/assets/43886029/ed7c7f2f-b1e0-4452-a35c-4dbc9fdefc31)
![image](https://github.com/devicons/devicon/assets/43886029/0d4c5faf-3b1e-48bf-a37c-8d53d8bad67b)
![image](https://github.com/devicons/devicon/assets/43886029/72a9640a-01e3-4f49-aa00-1a6c8ed040f4)
![image](https://github.com/devicons/devicon/assets/43886029/9cb50d30-cccd-494f-b1a8-e0522eb79e4f)

2023-12-07 09:09 UTC, weh requested changes
Just a tiny small missing newline, the rest is perfect :+1:

2023-12-07 09:09 UTC, weh commented on icons/vsphere/vsphere-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#0091da" d="M46.824 0s-7.41.418-8.455 8.457V49.07s.522 8.144 8.979 8.979h16.496l2.506-2.506H47.66s-5.95-.73-6.681-6.682V8.981
missing newline at eof

2023-12-07 10:16 UTC, Snailedlt approved these changes

2023-12-07 16:43 UTC, lunatic-fox approved these changes
The wordmark versions were tilted a little bit to the right.
Fixed! 🔧
![image](https://github.com/devicons/devicon/assets/76992016/077b3cd7-3666-489e-b7b9-ae364e01014b)
![image](https://github.com/devicons/devicon/assets/76992016/8e26a980-4089-46e3-956e-11daee24bf9f)

2023-12-17 12:06 UTC, Snailedlt approved these changes

2023-12-17 12:08 UTC, merged