update icon: kubernetes (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #2066
Opened 2023-11-27 19:13 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Kubernetes Website](https://kubernetes.io/)

## Additional Notes

The ship wheel was clipped out from the plain and line SVGs. I did this because the ship wheel is ontop the blue heptagon as a white path. 

The blue color `#326ce5` was used for the font SVGs.

2023-11-30 04:17 UTC, lunatic-fox approved these changes
Everything looks fine! 👍🏼
Thank you for this contribution! 🚀
![image](https://github.com/devicons/devicon/assets/76992016/d03dc802-3d4e-434b-8a33-8eab8916a88c)
![image](https://github.com/devicons/devicon/assets/76992016/aaacfd11-eb91-4389-b903-8d62fec61241)
![image](https://github.com/devicons/devicon/assets/76992016/b7afb21b-71f4-49a5-8f35-5196f55c92f0)
![image](https://github.com/devicons/devicon/assets/76992016/a3ab7d84-b6db-42bd-80ec-1cace0082daf)

2023-12-05 09:47 UTC, weh requested changes
Just one image looks like it is not centered (vertical)
The rest is good.

2023-12-05 09:47 UTC, weh commented on icons/kubernetes/kubernetes-plain-wordmark.svg
this looks like it is not vertically centered.
The rest ist good :+1:

2023-12-05 15:24 UTC, Snailedlt requested changes
Like @weh already mentioned the wordmark versions appear to not be vertically centered

2023-12-05 15:24 UTC, Snailedlt commented on icons/kubernetes/kubernetes-original-wordmark.svg
This needs to be vertically centered too

2023-12-05 22:50 UTC, weh approved these changes
Top 👍

2023-12-07 23:02 UTC, lunatic-fox approved these changes
💡 It appears to not be vertically centered, however if you zoom in you can see that it's properly centered. Here's an example:
![image](https://github.com/devicons/devicon/assets/76992016/1d838b43-7efa-4b41-a50a-bcfa2f9d1cf7)
![image](https://github.com/devicons/devicon/assets/76992016/161054ac-a299-4765-bf2a-98247306eb2a)

2023-12-17 11:56 UTC, Snailedlt approved these changes

2023-12-17 11:56 UTC, merged