update icon: travis (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #2084
Opened 2023-12-01 05:52 UTC by canaleal

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR is related to #1998**

## Link to prove your SVG is correct and up-to-date.

- [Travis Website](https://www.travis-ci.com/)
- [Travis Logos Github](https://github.com/travis-ci/travis-web/blob/master/public/images/logos/TravisCI-Mascot-1.svg)

## Additional Notes

The main Travis logo mark is the engineer with the red mustache and yellow hard hat with T symbol. It was somewhat difficult finding a way to simplify the SVG for the `plain` version, but I decided that it might be best to keep the gray borders and simply remove the fills from the SVGs. 

The `plain.svg` looks simple enough to be used as the `line.svg`, but maybe both should be added?

The gray color `#2d3136` was used for the font SVGs.

2023-12-05 20:50 UTC, Snailedlt requested changes
Finally something I can complain about, LOL! (jk)
I just suggested some very minor changes

2023-12-05 20:50 UTC, Snailedlt commented on icons/travis/travis-line-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#2d3136" d="M23.795 42.053c-3.769 0-7.39 1.237-10.466 3.57-2.96 2.247-5.203 5.466-6.52 9.091-.456.169-.91.35-1.354.56h-.002c-
Add newline at EOF
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#2d3136" d="M23.795 42.053c-3.769 0-7.39 1.237-10.466 3.57-2.96 2.247-5.203 5.466-6.52 9.091-.456.169-.91.35-1.354.56h-.002c-.558.267-1.11.572-1.626.977l-.12.095-.046.166a7.153 7.153 0 0 0-.117.493c-.032.163-.055.326-.078.486a11.564 11.564 0 0 0-.095.97 12.133 12.133 0 0 0 .056 1.94c.068.644.19 1.281.361 1.913.089.315.193.627.314.936.06.154.125.309.199.464.037.08.078.155.117.23h.002l.062.117h.002c.024.04.044.077.082.134l.08.127.133.066c.11.057.2.1.298.146l.29.131c-1.27 1.19-2.637 2.688-3.827 4.566L0 71.662l.187.16 2.164-1.899c.008-.006.476-.412 1.308-1.03.468-.346 1.302-.859 1.993-1.313-.235.21-.378.476-.427.82-.051.362-.024.803.039 1.37.065.59.283 1.708.577 2.742.253.89.473 1.42.68 1.747.207.326.418.454.607.497.16.038.357.055.575.055.56 0 1.237-.112 1.733-.25a17.833 17.833 0 0 0 2.228 4.506 523.474 523.474 0 0 0-3.238-1.492l-1.832-.824 1.084 1.69c.056.087 1.541 2.404 2.756 3.966 1.138 1.462 2.733 2.98 5.693 2.98.356 0 .727-.021 1.11-.064.864-.098 1.512-.176 2.01-.24 3.078 1.121 6.472 1.19 9.691-.029a14.196 14.196 0 0 0 2.406-1.189l.031-.006c1.192-.287 2.543-.608 3.217-.797.104-.029.235-.06.374-.094.931-.214 2.545-.59 3.398-2.299a172.7 172.7 0 0 1 1.414-2.749l.565-1.07.17-.32.047-.09c.01-.02.023-.039.017-.029v-.002l.804-1.51-1.57.678v.002c-.023.01-.443.192-.947.421-.44.2-.926.432-1.324.634.516-1.12.854-2.077.969-2.476.477.093 1.09.093 1.552.093.259 0 .517-.042.692-.087.18-.046.371-.157.544-.468.172-.312.354-.828.59-1.745.276-1.068.474-2.223.529-2.83.053-.58.071-1.031.014-1.399-.058-.368-.2-.657-.46-.871a4.92 4.92 0 0 0-.61-.392c-.127-.072-.23-.124-.35-.19l.328-1.245c.096-.04.193-.079.306-.123a19.453 19.453 0 0 0 .579-.236h.002l.288-.13a7.684 7.684 0 0 0 .299-.147l.13-.068.084-.127h.002c.037-.057.057-.093.08-.134l.062-.113a4.024 4.024 0 0 0 .12-.232 8.51 8.51 0 0 0 .196-.462l.002-.002c.121-.31.225-.622.314-.936.17-.632.291-1.27.359-1.913.072-.645.09-1.294.058-1.942a10.708 10.708 0 0 0-.093-.967v-.002a7.403 7.403 0 0 0-.08-.483v-.002a6.008 6.008 0 0 0-.115-.495l-.047-.166-.119-.092-.002-.002c-.514-.403-1.067-.71-1.624-.976h-.002c-.446-.21-.899-.39-1.355-.56-1.317-3.624-3.561-6.844-6.521-9.09-3.076-2.335-6.697-3.57-10.466-3.57zm0 .25c3.715 0 7.28 1.217 10.313 3.52 2.934 2.225 5.17 5.425 6.47 9.032l.019.054.054.02c.467.172.927.358 1.379.571.549.263 1.085.559 1.579.948h.002l.055.044.023.084c.049.172.08.317.111.478v.002c.032.155.06.31.08.468v.002c.044.314.074.63.09.945a11.774 11.774 0 0 1-.059 1.903 12.068 12.068 0 0 1-.35 1.874 9.797 9.797 0 0 1-.307.912 8.328 8.328 0 0 1-.19.449 3.718 3.718 0 0 1-.112.216l-.062.113a1.812 1.812 0 0 1-.072.119l-.047.072-.072.037a7.449 7.449 0 0 1-.29.143l-.286.128a19.185 19.185 0 0 1-.569.23 14.735 14.735 0 0 0-.37.15l-.057.024-.302 1.15-.164-.041-.136-.033-.043.35.076.042c.174.09.433.23.676.368s.474.281.576.365c.212.175.323.392.374.72.051.327.034.762-.018 1.337-.052.58-.249 1.736-.52 2.79-.235.908-.416 1.413-.568 1.686-.15.273-.243.31-.388.347-.153.04-.398.08-.63.08-.5 0-1.179.011-1.606-.092l-.117-.029-.033.117a17.37 17.37 0 0 1-1.105 2.83l-.16.324.325-.156a2.822 2.822 0 0 0 .1-.05v.002c.404-.212 1-.491 1.503-.72.501-.227.9-.4.944-.42l.002-.003.912-.394-.468.88-.017.033-.047.09-.17.32a286.696 286.696 0 0 0-.565 1.071c-.448.854-.997 1.913-1.416 2.751-.804 1.61-2.3 1.957-3.23 2.17h-.002c-.14.033-.272.063-.384.094-.662.186-2.017.51-3.21.797l-.03.008-.026.004-.023.014c-.728.45-1.52.847-2.388 1.177-3.177 1.203-6.523 1.138-9.56.022l-.029-.01-.029.004c-.496.064-1.151.139-2.022.238a9.793 9.793 0 0 1-1.082.064c-2.876 0-4.373-1.444-5.494-2.884-1.202-1.545-2.676-3.843-2.745-3.95l-.631-.982 1.068.48c.69.31 2.752 1.266 3.342 1.54l.042.02.043-.012.145-.043.167-.049-.101-.142a17.619 17.619 0 0 1-2.336-4.728l-.037-.115-.117.035a6.994 6.994 0 0 1-1.77.253c-.205 0-.386-.016-.517-.046h-.002c-.134-.031-.268-.098-.452-.388s-.4-.802-.65-1.68c-.289-1.02-.506-2.141-.568-2.705-.063-.56-.087-.986-.041-1.306.045-.32.15-.53.36-.706.122-.101.433-.29.73-.456.296-.167.582-.316.68-.367l.078-.04-.076-.623-.164.098a40.704 40.704 0 0 0-3.57 2.351 22.782 22.782 0 0 0-1.323 1.043l-1.515 1.33 1.078-1.702a23.56 23.56 0 0 1 3.905-4.658l.146-.134-.183-.073-.152-.062-.004-.002-.28-.127H5.18a7.66 7.66 0 0 1-.288-.142l-.07-.035-.048-.074-.002-.002c-.034-.051-.048-.077-.072-.117l-.002-.002-.058-.11-.002-.001c-.04-.077-.079-.147-.111-.216a6.68 6.68 0 0 1-.191-.449 9.736 9.736 0 0 1-.306-.912 11.919 11.919 0 0 1-.353-1.874 11.895 11.895 0 0 1-.057-1.9 11.263 11.263 0 0 1 .17-1.418 6.88 6.88 0 0 1 .113-.48l.021-.085.057-.045h.002c.494-.388 1.028-.683 1.577-.946.452-.212.913-.4 1.379-.571l.054-.02.02-.054c1.3-3.608 3.535-6.806 6.468-9.033 3.035-2.302 6.6-3.519 10.314-3.519zm0 .58c-7.012 0-13.428 4.57-16.11 11.58l-.091.242.245-.078a23.65 23.65 0 0 1 1.125-.324c.042-.01.084-.017.125-.027l-.119.046c-.554.224-1.108.454-1.65.708-.54.247-1.072.514-1.582.811a9.15 9.15 0 0 0-1.328.909l-.035.029-.008.045c-.017.103-.031.214-.045.318H4.32v.002c-.017.146-.035.294-.046.446-.027.3-.038.6-.041.9a13.3 13.3 0 0 0 .113 1.804v.002c.082.596.19 1.189.353 1.765a9.333 9.333 0 0 0 .448 1.257c.03.067.063.132.094.193l.054.107.037.02a4.5 4.5 0 0 0 .139.068l.265.125c.146.067.351.165.522.242l.07.03.059-.046c.017-.014.03-.028.037-.035l.05-.05L6 62.155c.162-.043.984-.256 2.517-.548v-.246a7.381 7.381 0 0 1-.386-.081 7.935 7.935 0 0 1-1.057-.34h-.002a4.925 4.925 0 0 1-.493-.24c-.036-.02-.06-.048-.095-.07.895.218 2.006.328 3.368.297 1.546-.036 3.274-.184 4.9-.351 2.967-.306 5.938-.506 8.925-.513 2.987.007 5.96.206 8.926.513 1.626.167 3.355.315 4.9.35 1.364.032 2.474-.078 3.37-.296-.035.022-.06.05-.096.07a4.962 4.962 0 0 1-.495.24c-.344.139-.697.25-1.059.34a8.268 8.268 0 0 1-.16.035l.003.245c1.687.313 2.6.55 2.77.595l-.503 1.909.238-.108c.094-.041.19-.082.284-.126l.266-.125h.002a5.53 5.53 0 0 0 .136-.068l.037-.02.053-.107.002-.002a4.585 4.585 0 0 0 .093-.191 7.229 7.229 0 0 0 .172-.41 9.303 9.303 0 0 0 .277-.848c.163-.575.271-1.168.353-1.764v-.002a13.15 13.15 0 0 0 .074-2.704 11.471 11.471 0 0 0-.047-.447 6.696 6.696 0 0 0-.049-.32l-.008-.044-.035-.03a9.143 9.143 0 0 0-1.327-.908 17.799 17.799 0 0 0-1.585-.81 31.227 31.227 0 0 0-1.648-.709l-.117-.046c.04.01.08.017.121.027.377.097.755.207 1.127.323l.246.078-.092-.241c-2.682-7.01-9.1-11.58-16.11-11.58Zm0 .249c6.81 0 13.03 4.407 15.737 11.173-.28-.085-.562-.17-.846-.244-.576-.148-1.16-.28-1.75-.378-.009-.001-.016-.004-.024-.006l-.062.24c.282.103.565.205.842.312h.002c.278.103.556.212.832.323.553.223 1.103.453 1.636.704.538.245 1.065.508 1.566.8.45.259.877.544 1.257.86a11.01 11.01 0 0 1 .084.694c.025.291.035.586.037.883v.002a12.9 12.9 0 0 1-.107 1.768c-.08.588-.19 1.17-.35 1.731a9.043 9.043 0 0 1-.268.825 6.934 6.934 0 0 1-.164.394 4.514 4.514 0 0 1-.092.185l-.017.035a6.794 6.794 0 0 1-.096.047l-.263.125-.043.02.435-1.652-.119-.033a74.68 74.68 0 0 0-2.423-.519c.261-.075.524-.147.778-.25h.002a4.99 4.99 0 0 0 .522-.251c.167-.096.339-.208.478-.367l.3-.343-.433.143c-.854.279-2.203.362-3.737.327-1.535-.035-3.257-.185-4.88-.353-2.972-.307-5.955-.506-8.953-.512-2.997.007-5.979.206-8.952.512-1.623.167-3.344.316-4.878.351-1.534.035-2.883-.046-3.738-.325l-.433-.14.3.34c.14.159.31.27.478.367.17.096.348.177.523.251h.002c.311.126.634.223.957.308a83.173 83.173 0 0 0-2.123.46l-.12.034.467 1.78-.318-.148-.265-.125a4.89 4.89 0 0 1-.096-.047l-.017-.035c-.03-.062-.062-.123-.09-.185a5.944 5.944 0 0 1-.162-.392v-.002a9.07 9.07 0 0 1-.27-.825 12.858 12.858 0 0 1-.35-1.731v-.002a13.032 13.032 0 0 1-.109-1.766c.003-.296.015-.592.041-.884v-.002c.011-.144.03-.291.047-.438l-.002.002c.011-.087.024-.174.037-.258.38-.315.808-.6 1.257-.86a17.76 17.76 0 0 1 1.564-.799 31.758 31.758 0 0 1 1.638-.704c.278-.111.553-.22.83-.323h.002c.279-.108.56-.21.844-.312l-.062-.24c-.008.001-.015.005-.023.006-.591.098-1.176.23-1.753.378-.283.074-.564.16-.844.244 2.707-6.766 8.925-11.173 15.737-11.173zm-5.379 2.138-.01.022v.002c-1.73 3.03-1.837 6.52-1.809 7.974l-.008-.008-.052-.053-.016-.013-.006-.006c [...]

2023-12-05 20:50 UTC, Snailedlt commented on icons/travis/travis-line.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 128 128"><path fill="#2d3136" d="M68.873.5c-10.9 0-21.367 3.573-30.262 10.322-8.577 6.51-15.096 15.837-18.907 26.35a50.16 50.
Remove `xml:space="preserve"`
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#2d3136" d="M68.873.5c-10.9 0-21.367 3.573-30.262 10.322-8.577 6.51-15.096 15.837-18.907 26.35a50.16 50.16 0 0 0-3.943 1.635h-.002v.002c-1.613.773-3.208 1.647-4.692 2.812l-.323.253-.12.442.002-.002c-.144.52-.24.963-.335 1.432v.002a25.77 25.77 0 0 0-.232 1.398 33.25 33.25 0 0 0-.27 2.798v.002a35.083 35.083 0 0 0 .167 5.607c.196 1.86.544 3.702 1.04 5.527h.001v.002c.257.909.553 1.808.903 2.701.174.447.363.89.574 1.335.105.223.22.44.335.662l.002.004.187.333.002.002c.067.113.117.21.228.377l.223.345.353.18c.317.165.58.288.864.42h.002l.833.378h.004l.114.047c-3.698 3.456-7.686 7.874-11.155 13.352L0 86.261l.374.321 6.27-5.503h.002c.03-.026 1.381-1.2 3.799-2.99 2.34-1.732 5.784-4.087 9.968-6.567l.052.44a68.1 68.1 0 0 0-1.837.992c-.867.487-1.756 1.011-2.205 1.385-.725.605-1.114 1.4-1.26 2.427-.147 1.028-.068 2.296.114 3.935.187 1.7.819 4.95 1.668 7.94.731 2.576 1.364 4.1 1.954 5.031.589.93 1.168 1.272 1.69 1.392.453.106 1.016.151 1.642.151 1.635 0 3.645-.321 5.075-.726a51.629 51.629 0 0 0 6.601 13.374l-.013.004c-1.77-.82-7.615-3.528-9.612-4.427l-4.965-2.23 2.937 4.579.002.002c.169.26 4.465 6.966 7.98 11.486 3.29 4.228 7.868 8.598 16.41 8.598a29.03 29.03 0 0 0 3.208-.19c2.505-.284 4.379-.507 5.819-.692 8.911 3.258 18.74 3.454 28.063-.078a41.044 41.044 0 0 0 6.974-3.446 2.88 2.88 0 0 0 .107-.024c3.455-.83 7.37-1.763 9.318-2.312.307-.083.69-.172 1.096-.268 2.698-.62 7.319-1.7 9.771-6.605h.003a490.13 490.13 0 0 1 4.094-7.968 822.963 822.963 0 0 1 1.637-3.106l.49-.926.136-.255.049-.093.002-.002 2.18-4.099-4.255 1.847c-.077.035-1.283.56-2.744 1.224-1.352.614-2.885 1.34-4.061 1.944 1.655-3.498 2.574-6.294 2.921-7.504 1.368.284 3.19.275 4.56.275a8.42 8.42 0 0 0 1.98-.251c.505-.13 1.02-.419 1.511-1.305.491-.885 1.013-2.374 1.7-5.028.795-3.089 1.367-6.436 1.525-8.182.152-1.681.208-2.982.044-4.03-.164-1.048-.563-1.855-1.296-2.46h-.002c-.372-.307-1.04-.712-1.755-1.121a57.867 57.867 0 0 0-1.555-.847l.267.067.239.06.952-3.616c.292-.123.594-.248.94-.383.56-.218 1.119-.443 1.677-.681l.002-.002.833-.376h.002c.286-.133.547-.256.864-.42l.352-.183.224-.345c.105-.161.164-.26.232-.381l.18-.327a11.553 11.553 0 0 0 .341-.668v-.002c.207-.443.397-.889.574-1.335.35-.893.646-1.79.903-2.699v-.002l.002-.002a35.61 35.61 0 0 0 1.038-5.525v-.002c.209-1.863.26-3.736.167-5.607a30.94 30.94 0 0 0-.268-2.796v-.002a21.21 21.21 0 0 0-.232-1.398h.002c-.093-.47-.19-.914-.337-1.434v-.002l-.12-.436-.321-.253c-1.483-1.165-3.08-2.04-4.693-2.814v-.002a49.749 49.749 0 0 0-3.946-1.637c-3.809-10.51-10.33-19.839-18.907-26.348C90.238 4.072 79.773.5 68.873.5Zm0 .498c10.79 0 21.147 3.534 29.96 10.221 8.522 6.468 15.014 15.755 18.786 26.228l.039.109.109.04c1.355.5 2.69 1.042 4.005 1.663v-.002c1.595.765 3.157 1.626 4.599 2.76l.192.151.078.278v.002c.142.504.233.932.325 1.398h.002c.092.452.163.91.224 1.368v.002c.128.913.22 1.832.265 2.752a34.214 34.214 0 0 1-.164 5.53v.002a35.127 35.127 0 0 1-1.025 5.45 28.457 28.457 0 0 1-.886 2.648c-.174.438-.36.874-.562 1.308-.101.213-.206.423-.325.638l-.181.327a5.405 5.405 0 0 1-.212.35l-.154.236-.236.12c-.31.16-.56.281-.844.413l-.827.372c-.55.235-1.102.46-1.656.675h-.003c-.39.153-.737.293-1.066.432l-.113.049-.89 3.38c-.12-.03-.213-.055-.581-.144l-.269-.066-.109.814.156.08c.506.264 1.257.666 1.964 1.07.706.403 1.376.82 1.685 1.074.637.527.972 1.182 1.123 2.15.151.969.104 2.24-.047 3.908-.153 1.694-.725 5.044-1.514 8.104-.681 2.638-1.204 4.104-1.652 4.912-.448.808-.765.952-1.199 1.062a8.034 8.034 0 0 1-1.857.236c-1.45 0-3.414.033-4.678-.273l-.233-.056-.065.23c-.337 1.193-1.304 4.321-3.217 8.226l-.317.648.65-.315c.088-.043.185-.083.286-.137 1.175-.617 2.904-1.424 4.361-2.086 1.457-.661 2.623-1.17 2.739-1.222l2.944-1.279-1.508 2.838c-.015.026-.023.04-.053.097l-.136.257-.492.926a892.832 892.832 0 0 0-1.635 3.108 493.16 493.16 0 0 0-4.102 7.977h.002c-2.355 4.709-6.744 5.721-9.441 6.34h-.002c-.406.097-.793.188-1.113.275v.002H100c-1.923.541-5.845 1.477-9.3 2.308h-.003a1.105 1.105 0 0 1-.1.022l-.051.008-.045.027a40.57 40.57 0 0 1-6.942 3.429c-9.233 3.497-18.962 3.302-27.787.059l-.056-.022-.06.008c-1.44.185-3.334.412-5.858.699a28.544 28.544 0 0 1-3.153.185c-8.374 0-12.762-4.224-16.016-8.408-3.49-4.486-7.76-11.147-7.956-11.449l-.002-.002-2.032-3.168 3.435 1.545c2.005.903 7.984 3.67 9.694 4.463l.083.039.09-.025.412-.12.333-.096-.198-.285c-2.828-4.033-5.149-8.633-6.788-13.73l-.076-.233-.234.07c-1.366.412-3.516.74-5.16.74-.601 0-1.136-.048-1.529-.14-.414-.096-.84-.315-1.383-1.172-.544-.858-1.171-2.348-1.896-4.9-.84-2.963-1.47-6.213-1.652-7.859-.18-1.627-.251-2.866-.117-3.811.135-.945.457-1.59 1.088-2.115.37-.31 1.27-.85 2.13-1.333.859-.483 1.69-.918 1.975-1.065l.153-.08-.186-1.557-.33.193A117.913 117.913 0 0 0 10.15 77.69c-2.43 1.799-3.758 2.948-3.834 3.015l-4.967 4.361 3.538-5.581v-.002c3.522-5.561 7.592-10.059 11.337-13.524l.288-.266-.364-.148c-.15-.06-.29-.12-.442-.183l-.827-.372-.002-.002a22.107 22.107 0 0 1-.843-.41h-.002l-.233-.12-.154-.237v-.002c-.1-.15-.143-.229-.214-.35l-.002-.004-.18-.315-.003-.008a17.115 17.115 0 0 1-.32-.636v-.002a19.42 19.42 0 0 1-.562-1.302V61.6a28.296 28.296 0 0 1-.885-2.653A34.65 34.65 0 0 1 10.45 53.5v-.002a34.61 34.61 0 0 1-.163-5.529 32.767 32.767 0 0 1 .266-2.754c.067-.46.134-.917.224-1.368v-.002c.096-.466.188-.895.327-1.399l.076-.28.195-.152c1.441-1.132 3.001-1.991 4.596-2.756l.002-.002a50.031 50.031 0 0 1 4.004-1.658l.109-.039.039-.11C23.9 26.972 30.39 17.685 38.91 11.218 47.724 4.532 58.082.998 68.873.998Zm-.002 1.901c-20.274 0-38.829 13.215-46.584 33.493l-.183.48.49-.153a68.567 68.567 0 0 1 3.264-.94c.58-.148 1.169-.243 1.751-.38-.555.214-1.113.424-1.666.647a92.99 92.99 0 0 0-4.77 2.05c-1.566.717-3.106 1.484-4.58 2.344-1.362.784-2.671 1.647-3.833 2.625l-.07.059-.015.091a25.738 25.738 0 0 0-.137.915v.004c-.05.425-.102.856-.136 1.292a33.612 33.612 0 0 0-.115 2.606 38.335 38.335 0 0 0 .323 5.206v.004c.239 1.724.554 3.442 1.024 5.104.233.832.495 1.652.802 2.447a17.833 17.833 0 0 0 .757 1.732l.002.002.146.28.07.037c.131.068.266.134.393.194l.77.366c.428.198 1.022.479 1.515.699l.138.062.119-.095a1.03 1.03 0 0 0 .097-.09l.101-.1-1.391-5.318c.419-.112 2.9-.752 7.413-1.611l-.002-.49a21.27 21.27 0 0 1-1.117-.238h-.002a23.189 23.189 0 0 1-3.085-.987l-.004-.002a14.293 14.293 0 0 1-1.44-.696h-.002c-.174-.1-.3-.242-.463-.352 2.584.645 6.005.885 10 .794 4.477-.103 9.482-.537 14.192-1.022 8.603-.888 17.221-1.46 25.883-1.481 8.662.02 17.286.592 25.883 1.48 4.713.486 9.72.92 14.197 1.022 3.997.092 7.42-.147 10.003-.793-.163.11-.29.252-.465.352-.458.26-.948.485-1.446.698a23.353 23.353 0 0 1-3.09.987c-.154.035-.309.071-.463.103l.006.489c4.96.919 7.705 1.632 8.146 1.75l-1.428 5.421.474-.212c.273-.122.551-.242.826-.37l.77-.368c.126-.06.263-.124.395-.192l.072-.037.14-.279v-.002c.094-.18.185-.37.273-.56.174-.381.34-.772.494-1.173h.002c.304-.794.565-1.616.794-2.447v-.002c.47-1.661.79-3.38 1.026-5.104v-.002c.222-1.723.338-3.464.321-5.206a33.86 33.86 0 0 0-.113-2.608c-.036-.432-.083-.86-.136-1.288v-.002a19.579 19.579 0 0 0-.138-.92l-.016-.09-.07-.059c-1.161-.978-2.47-1.838-3.832-2.623a51.531 51.531 0 0 0-4.587-2.345h.004c-1.561-.736-3.165-1.404-4.772-2.051-.552-.223-1.11-.435-1.667-.648.583.136 1.174.232 1.753.38a68.45 68.45 0 0 1 3.268.94l.49.155-.183-.481C107.7 16.113 89.14 2.899 68.871 2.899Zm0 .499c19.885 0 38.095 12.878 45.895 32.692a65.209 65.209 0 0 0-2.76-.794c-1.69-.434-3.402-.827-5.132-1.113l-.126.479c.818.298 1.638.593 2.442.905l.002.002h.002a85.45 85.45 0 0 1 2.415.94c1.604.646 3.197 1.31 4.745 2.04h.004a51.165 51.165 0 0 1 4.544 2.325c1.32.76 2.577 1.594 3.692 2.524.044.26.087.534.119.796v.002a33.253 33.253 0 0 1 .245 3.84 37.492 37.492 0 0 1-.317 5.14c-.233 1.707-.549 3.402-1.01 5.034v.002a26.353 26.353 0 0 1-.783 2.401 20.156 20.156 0 0 1-.48 1.147 13.014 13.014 0 0 1-.265.539v.002l-.068.134c-.104.052-.208.105-.31.154v-.002l-.768.366-.34.153 1.291-4.906-.237-.066c-.294-.08-3.372-.802-7.425-1.594.893-.24 1.782-.496 2.643-.842l.002-.002h.002a14.882 1 [...]

2023-12-05 20:50 UTC, Snailedlt commented on icons/travis/travis-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 128 128"><path fill="#2d3136" d="M68.91.52c-10.884 0-21.334 3.566-30.22 10.308-8.595 6.524-15.134 15.884-18.938 26.44a50.419
Remove `xml:space="preserve"`
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#2d3136" d="M68.91.52c-10.884 0-21.334 3.566-30.22 10.308-8.595 6.524-15.134 15.884-18.938 26.44a50.419 50.419 0 0 0-4.04 1.673c-1.61.772-3.193 1.642-4.661 2.795l-.26.203-.098.362a20.42 20.42 0 0 0-.332 1.422c-.092.46-.162.924-.228 1.388a33.111 33.111 0 0 0-.27 2.787 34.976 34.976 0 0 0 .166 5.588 35.05 35.05 0 0 0 1.037 5.508c.256.905.55 1.8.899 2.688a18.312 18.312 0 0 0 .9 1.98l.186.328c.07.12.116.208.222.367l.19.293.295.15c.314.163.572.286.857.419l.832.375c.153.063.297.125.453.187-3.77 3.49-7.87 8.02-11.418 13.623L0 86.474l6.293-5.523c.106-.093 5.382-4.663 14.182-9.834l.12 1.012c-.573.297-3.342 1.752-4.163 2.437-1.362 1.134-1.428 2.889-1.063 6.166.185 1.68.818 4.94 1.666 7.928 1.461 5.146 2.533 6.055 3.475 6.27.423.1.975.146 1.59.146 1.683 0 3.847-.328 5.252-.752 1.653 5.139 3.993 9.778 6.845 13.846l-.412.12c-1.716-.796-7.713-3.573-9.73-4.481l-4.215-1.895 2.494 3.889c.182.28 4.482 6.99 7.998 11.51 3.284 4.22 7.783 8.533 16.271 8.533a28.9 28.9 0 0 0 3.192-.188c2.534-.288 4.436-.515 5.883-.701 8.91 3.274 18.737 3.473 28.06-.059a40.971 40.971 0 0 0 7.01-3.462c.043-.006.086-.018.127-.028 3.468-.834 7.401-1.772 9.344-2.318.315-.086.702-.177 1.11-.274 2.706-.622 7.228-1.671 9.64-6.496 2.429-4.87 6.394-12.328 6.437-12.404l1.85-3.479-3.611 1.569c-.193.086-4.764 2.079-7.143 3.328-.086.046-.183.086-.28.133 1.929-3.936 2.904-7.089 3.245-8.297 1.328.321 3.304.281 4.754.281a8.26 8.26 0 0 0 1.926-.244c.94-.24 1.668-.865 3.04-6.176.795-3.085 1.37-6.446 1.526-8.172.305-3.362.207-5.16-1.168-6.297-.683-.563-2.687-1.646-3.707-2.18l.049-.366c.52.124.799.197.822.203l.924-3.512a40.773 40.773 0 0 1 1.064-.432 56.403 56.403 0 0 0 1.676-.681l.832-.375c.286-.133.543-.256.858-.418l.294-.153.19-.29c.103-.16.156-.249.222-.368l.182-.328c.123-.222.231-.438.334-.656a24.543 24.543 0 0 0 .57-1.326c.349-.888.643-1.781.899-2.686.49-1.82.84-3.656 1.035-5.508.209-1.856.26-3.725.166-5.59a30.734 30.734 0 0 0-.268-2.785 21.03 21.03 0 0 0-.228-1.388c-.093-.47-.187-.908-.332-1.422l-.1-.36-.257-.203c-1.468-1.153-3.053-2.025-4.663-2.797a50.105 50.105 0 0 0-4.04-1.675c-3.802-10.553-10.343-19.914-18.938-26.438C90.243 4.085 79.795.52 68.91.52Zm-.002 2.408c20.234 0 38.77 13.192 46.52 33.453a66.943 66.943 0 0 0-3.291-.947c-1.692-.435-3.404-.829-5.13-1.114.822.3 1.645.596 2.456.91.815.302 1.626.62 2.432.946 1.61.649 3.215 1.317 4.775 2.053a51.564 51.564 0 0 1 4.582 2.343c1.359.783 2.66 1.64 3.81 2.608.05.29.1.61.137.912.053.427.099.854.135 1.285.073.861.107 1.73.113 2.598a37.843 37.843 0 0 1-.32 5.191c-.235 1.723-.554 3.437-1.022 5.09a27.02 27.02 0 0 1-.79 2.434c-.154.398-.318.785-.49 1.164a13.383 13.383 0 0 1-.27.552l-.106.21a15.467 15.467 0 0 1-.388.19l-.772.368c-.271.126-.549.246-.824.369l1.367-5.19c-.318-.086-3.307-.86-8.44-1.812a24.213 24.213 0 0 0 .475-.105 23.653 23.653 0 0 0 3.139-1.002 14.676 14.676 0 0 0 1.478-.715c.474-.272.94-.58 1.301-.99-5.14 1.68-15.768.917-25.22-.057-8.636-.892-17.299-1.469-26.003-1.488-8.704.02-17.36.596-26.002 1.488-9.447.973-20.072 1.736-25.214.057.36.41.828.718 1.302.99.474.269.973.5 1.477.715 1.017.41 2.071.737 3.135 1.002.373.09.759.172 1.136.242-4.681.89-7.4 1.593-7.7 1.676l1.427 5.447a.969.969 0 0 1-.078.072c-.49-.219-1.085-.5-1.516-.7l-.771-.366a12.696 12.696 0 0 1-.387-.192l-.11-.209a17.802 17.802 0 0 1-.265-.552 17.686 17.686 0 0 1-.486-1.164 26.855 26.855 0 0 1-.797-2.434c-.467-1.653-.782-3.367-1.02-5.09a38.204 38.204 0 0 1-.322-5.191 33.44 33.44 0 0 1 .115-2.598c.034-.43.085-.86.135-1.287a25.638 25.638 0 0 1 .135-.91c1.15-.969 2.453-1.828 3.81-2.61 1.472-.857 3.011-1.625 4.578-2.341 1.565-.736 3.166-1.404 4.776-2.053.809-.325 1.62-.645 2.432-.945.815-.316 1.633-.613 2.459-.91-1.727.284-3.437.679-5.133 1.113-1.1.285-2.198.606-3.287.947C30.14 16.12 48.67 2.928 68.908 2.928ZM53.572 9.69c-5.222 9.09-5.405 20.057-5.289 23.88a29.097 29.097 0 0 1-.806-.774c-.011-.011-.025-.017-.036-.027-.007-.007-.012-.015-.02-.022-.009-.01-.022-.014-.032-.021a1.211 1.211 0 0 0-.114-.07c-.02-.011-.033-.022-.054-.032a.8.8 0 0 0-.143-.049c-.014-.003-.025-.01-.035-.01a.755.755 0 0 0-.19-.017c-.016 0-.033.004-.046.004a1.032 1.032 0 0 0-.145.02l-.027.007-11.602 3.297c-.092-2.368-.14-12.537 5.188-21.111-.186.21-6.151 7.02-6.557 21.5l-1.867.53a.857.857 0 0 0-.615.69c-1.138 6.903-.484 11.729-.453 11.932.007.04.017.075.027.113-.151.048-.3.089-.45.137-1.766.578-3.54 1.194-5.146 2.133.86-.34 1.75-.585 2.64-.805a46.3 46.3 0 0 1 2.692-.588 84.053 84.053 0 0 1 5.44-.85 116.328 116.328 0 0 1 5.468-.59c1.829-.154 3.655-.311 5.487-.417 7.326-.433 14.672-.57 22.021-.575 7.351.008 14.698.122 22.024.573 1.833.107 3.657.262 5.486.416a122.018 122.018 0 0 1 5.469.59c1.822.22 3.634.51 5.44.85.9.171 1.796.364 2.687.591.894.22 1.78.464 2.64.805-1.606-.94-3.38-1.552-5.142-2.13-.152-.048-.3-.091-.453-.136.01-.037.02-.076.027-.117.028-.203.684-5.029-.453-11.932a.864.864 0 0 0-.616-.69l-1.87-.53c-.403-14.48-6.366-21.29-6.551-21.5 5.328 8.573 5.28 18.743 5.187 21.11L91.18 32.58c-.01-.003-.02-.004-.028-.008a1.044 1.044 0 0 0-.146-.02c-.014 0-.028-.003-.045-.003a.73.73 0 0 0-.19.017c-.01 0-.02.006-.03.006a1.195 1.195 0 0 0-.153.053c-.017.01-.033.021-.05.027-.038.025-.076.048-.114.075-.01.007-.021.01-.031.021-.01.007-.014.015-.022.022-.009.01-.025.017-.035.027-.01.01-.32.316-.807.773.117-3.823-.069-14.79-5.287-23.879.11.32 4.252 12.435 2.822 26.014-.467.371-.947.735-1.422 1.055a.876.876 0 0 0-.378.699c0 .045-.101 4.373-2.012 8.055a.88.88 0 0 0-.068.181c-4.754-.327-9.519-.463-14.278-.466-4.758.003-9.525.133-14.279.457a1.192 1.192 0 0 0-.067-.172c-1.911-3.682-2.01-8.01-2.013-8.055a.866.866 0 0 0-.375-.7c-.476-.32-.963-.683-1.426-1.054-1.428-13.579 2.716-25.695 2.826-26.014zm1.996 2.973V23.56h7.72v-3.183h1.734v14.707h-2.618v8.225h13.51v-8.225h-2.63V20.375h1.74v3.184h7.724V12.664Zm2.315 2.314h22.545v6.266h-3.082V18.06h-6.377v19.344h2.623v3.588h-8.873v-3.588h2.625V18.06h-6.377v3.184h-3.084zm-11.957 19.59c-.113 2.224-.168 7.048 1.096 11.648a.94.94 0 0 0 .062.156c-.13.018-.257.028-.389.045-1.842.223-3.685.458-5.521.764-1.832.31-3.662.647-5.477 1.049a88.817 88.817 0 0 0-3.283.822c-.089-.777-.5-5.004.383-10.752zm45.965 0 13.132 3.734c.884 5.755.469 9.98.38 10.752a93.438 93.438 0 0 0-3.28-.82c-3.634-.798-7.31-1.39-11.002-1.813-.127-.017-.257-.028-.387-.041.028-.055.048-.11.065-.164 1.262-4.6 1.21-9.425 1.092-11.649zm-1.692.728c.08 2.32.022 6.525-1.058 10.46a.856.856 0 0 0 0 .452 172.326 172.326 0 0 0-4.127-.379c1.543-3.234 1.882-6.679 1.955-7.893 1.185-.842 2.364-1.853 3.23-2.64zm-42.58.002c.866.787 2.043 1.796 3.233 2.639.071 1.212.408 4.65 1.949 7.882a161.976 161.976 0 0 0-4.123.383.849.849 0 0 0 0-.443c-1.08-3.93-1.135-8.137-1.059-10.461zm20.942 19.978h.003c1.479.004 2.96.018 4.438.041a92.374 92.374 0 0 0-7.201 1.9c-7.685 2.367-14.213 5.419-18.656 7.755 4.956-4.741 10.225-7.4 10.828-7.694l.054-.03 4.014-1.901a352.183 352.183 0 0 1 6.52-.07zm-14.659.295a96.091 96.091 0 0 0-7.56 1.79c-15.39 4.307-27.853 11.78-35.008 16.751 7.363-8.803 18.087-15.536 20.883-17.209.304-.04.603-.074.908-.103 1.064-.117 2.131-.2 3.205-.283a319.45 319.45 0 0 1 6.442-.428 561.822 561.822 0 0 1 11.13-.518zm31.71.09c2.915.122 5.832.262 8.747.428 2.102.118 4.193.26 6.288.416.006 0 .015.004.021.008-.212.148-.426.308-.64.46-8.573 5.982-18.481 8.516-24.194 9.54 4.036-3.34 7.183-7.28 8.77-9.428.494-.675.838-1.172 1.007-1.424zm-3.397.588a44.275 44.275 0 0 1-.668.858 55.569 55.569 0 0 1-4.988 5.519 246.38 246.38 0 0 0-7.297-.111c-4.136 0-8.1.108-11.868.29 5.318-2.206 11.71-4.36 18.631-5.656a71.798 71.798 0 0 1 6.19-.9zm21.88 1.215c6.932.981 12.022 2.028 14.786 2.654l-1.906 7.225c-3.893-.858-12.45-2.545-24.098-3.678 3.807-1.623 7.68-3.656 11.219-6.201zm-53.011 1.166a47.575 47.575 0 0 0-6.123 5.1 230.85 230.85 0 0 0-13.799 1.798c5.891-2.71 12.616-5.201 19.922-6.898zm-26.928.547a66.47 66.47 0 0 0-3.982 2.941l-.53-2c1.126-.255 2.647-.58 4.512-.941zm45.106 5.742c1.58 0 3.128.02 4.656.047a30.35 30.35 0 0 1-3.36 2.375l-3.898 2.355c-2.448.2 [...]

2023-12-07 16:53 UTC, lunatic-fox approved these changes
Great job! 👍🏼
Thank you for this contribution! 🚀
![image](https://github.com/devicons/devicon/assets/76992016/cfc425f6-dc2a-48a2-a79b-0b08cd988468)
![image](https://github.com/devicons/devicon/assets/76992016/134c45ea-8a6b-481f-a2e5-0695ad265b51)
![image](https://github.com/devicons/devicon/assets/76992016/17a2705f-048f-49f4-b374-b4bea37339d4)
![image](https://github.com/devicons/devicon/assets/76992016/99356112-7e88-4ae3-807c-9f298e2a7465)

2023-12-14 21:21 UTC, weh approved these changes
Awesome 👍

2023-12-17 12:01 UTC, Snailedlt approved these changes
LGTM! ✔️ 
Thank you for another great contribution! 💯 🙇

2023-12-17 12:05 UTC, merged