new icon: kubeflow (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #2117
Opened 2024-01-18 13:28 UTC by weh

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #2086 **

## Link to prove your SVG is correct and up-to-date.

2024-01-19 05:31 UTC, canaleal requested changes
Nice! Thank you for the contribution!  😄 

The json looks excellent, but the SVGs need a few modifications.

The viewboxes for all SVGs are not `0 0 128 128` and the plain-wordmark svg has strokes that should be converted into a unified path.

2024-01-22 08:33 UTC, weh commented
sorry @canaleal, looks like i committed the unfinished files. should be fixed now.

2024-01-27 09:52 UTC, canaleal submitted a review, later dismissed
Great work. 

I left a few comments about the padding/alignment on some of the SVGs, but aside from that everything else looks excellent.

2024-01-27 09:52 UTC, canaleal commented on icons/kubeflow/kubeflow-line-wordmark.svg
The SVG is not centered, the tip of the triangle is cut off at the top. 
There's also a little bit of padding left over for the width and height.

![image](https://github.com/devicons/devicon/assets/49886351/2d4611bd-a946-40ce-b582-8933389dc8ce)

2024-01-27 09:52 UTC, canaleal commented on icons/kubeflow/kubeflow-plain-wordmark.svg
There's still a little bit of padding on this SVG and the `plain.svg`. 
It's honestly not much, but best to remove it. 

![image](https://github.com/devicons/devicon/assets/49886351/fe865641-68f5-4710-b0e9-ad94839e58c6)

2024-01-27 09:52 UTC, canaleal commented on icons/kubeflow/kubeflow-line.svg
The SVG has a width that's slightly over 128, causing the right side to be outside the viewbox. 

![image](https://github.com/devicons/devicon/assets/49886351/1e8331e0-bb12-4fb8-9f62-d795ca3886b5)

2024-01-31 08:49 UTC, weh commented
@canaleal i fixed the image box issues. hope this time i got it right :crossed_fingers:

2024-01-31 08:50 UTC, weh commented on icons/kubeflow/kubeflow-line.svg
fixed in https://github.com/devicons/devicon/pull/2117/commits/452be760b339f2625ff0ed74325145731977c8d0

2024-01-31 08:50 UTC, weh commented on icons/kubeflow/kubeflow-plain-wordmark.svg
fixed in https://github.com/devicons/devicon/pull/2117/commits/452be760b339f2625ff0ed74325145731977c8d0

2024-01-31 08:50 UTC, weh commented on icons/kubeflow/kubeflow-line-wordmark.svg
fixed in https://github.com/devicons/devicon/pull/2117/commits/452be760b339f2625ff0ed74325145731977c8d0

2024-12-26 03:20 UTC, canaleal approved these changes

2024-12-26 03:21 UTC, merged