Update icon: cosmosdb (original, original-wordmark)
devicons/devicon pull request #2140
Opened 2024-02-08 16:27 UTC by weh

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

- Centered icon in 128x128
- Optimized images

**This PR closes  #2134**

## Notes

2024-02-18 18:35 UTC, canaleal requested changes
Overall excellent 👍 

2 changes needed:
- (OPTIONAL) Ungroup the paths in the `original.svg`
- There's some bottom padding in the `original-wordmark.svg`

2024-02-22 05:10 UTC, canaleal requested changes

2024-02-22 05:10 UTC, canaleal commented on icons/cosmosdb/cosmosdb-original-wordmark.svg
Excellent work on `original.svg` 👍

However, there's another issue with `original-wordmark.svg`. While the padding problem has been resolved, the SVG has been enlarged and is not properly centered.

![image](https://github.com/devicons/devicon/assets/49886351/ff68ab1b-5a51-408c-9cf9-96201f874dbe)

If using inkscape the following steps will help solve the issue:
1. Select all paths and group them
2. Press the lock icon in the top right
3. Set the height to 128 in the input box
4. Center the SVG horizontally and vertically using the options in the `align and distribute` menu

2024-02-22 12:25 UTC, weh commented on icons/cosmosdb/cosmosdb-original-wordmark.svg
Just found out, that this happened while resizing with https://www.iloveimg.com/resize-image
i will check later what is wrong.

2024-04-23 08:45 UTC, weh commented on icons/cosmosdb/cosmosdb-original-wordmark.svg
i think i finally fixed this now. Can you please review it again @canaleal :)

2025-03-30 05:12 UTC, canaleal approved these changes

2025-03-30 05:19 UTC, merged