new icon: remix (plain, plain-wordmark, line, line-wordmark)
devicons/devicon pull request #2150
Opened 2024-02-17 04:29 UTC by AnshSinghSonkhia

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format new icon: Icon name (versions separated by comma). More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the develop branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the devicon.json file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes** #2127 

# Link to prove your SVG is correct and up-to-date.
- https://remix.run/
- https://drive.google.com/drive/u/0/folders/1pbHnJqg8Y1ATs0Oi8gARH7wccJGv4I2c

2024-02-17 18:11 UTC, canaleal commented on devicon.json
> +                "plain",
Instead of **plain** and **plain-wordmark** use original and **original-wordmark**

2024-02-20 09:06 UTC, weh requested changes
hi @AnshSinghSonkhia, thx for your contribution.
You need to check your SVG files according to https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards

- The plain and line versions (with or without wordmark) need to stay as simple as possible. They must have only one color and the paths are united. The color will be removed when being turned into icons so the .svg can have any color. 
- The SVG should be on a single line, with a following empty line
- Check the Line version, to be a path, not strokes

2024-02-21 18:26 UTC, AnshSinghSonkhia commented
I made some changes @weh.
Kindly, guide me on any additional changes that you may need.

2024-02-22 06:01 UTC, canaleal requested changes

2024-02-22 06:01 UTC, canaleal commented on devicon.json
> +        "aliases": [
Flip these aliases around. 
The base should be `original` and the alias should be `plain`. Do the same for the wordmark version.

2024-02-22 06:33 UTC, AnshSinghSonkhia commented on icons/remix/remix-plain.svg
Hey @canaleal, which tools do you use for editing the SVGs?

2024-02-22 06:53 UTC, AnshSinghSonkhia commented on devicon.json
> +        "versions": {
Done

2024-02-22 15:30 UTC, canaleal commented on icons/remix/remix-plain.svg
I use a tool called [Inkscape](https://inkscape.org/). It is easy to use and provides utility functions such as resizing, center alignment, etc.

2024-02-22 17:39 UTC, Snailedlt commented on icons/remix/remix-plain.svg
Worth mentioning that we have a lot of guides for how to do common things in the comments of this issue: #1306 
Most of them are for Inkscape :)

We also have some [recommended resources and tools](https://github.com/devicons/devicon/wiki/Recommended-resources-and-tools) in our wiki

2024-02-28 05:21 UTC, canaleal requested changes
Nice, almost there. 👍 
Now we gotta make sure to update the SVGs as they don't meet the standards layed out in the [wiki](https://github.com/devicons/devicon/wiki/SVG-Standards). 

Here's a [tutorial](https://github.com/devicons/devicon/pull/1926#issuecomment-1776317249) on how to update the SVGs, and optimize them.

2024-02-28 17:09 UTC, AnshSinghSonkhia commented
> Nice, almost there. 👍 Now we gotta make sure to update the SVGs as they don't meet the standards layed out in the [wiki](https://github.com/devicons/devicon/wiki/SVG-Standards).
> 
> Here's a [tutorial](https://github.com/devicons/devicon/pull/1926#issuecomment-1776317249) on how to update the SVGs, and optimize them.

Thanks for sharing the tutorial @canaleal !!
I have updated the SVGs according to the standards!

2024-02-28 22:58 UTC, canaleal requested changes
Excellent work 👍 Almost there.

Don't forget to that all the SVGs need to have 1 path only and must be optimized. 

You can follow the [tutorial](https://github.com/devicons/devicon/pull/1926#issuecomment-1776317249) I provided before on how to unify the paths and optimize the SVGs. The section is called `Unify the Paths and create Plain Icons (Inkscape)`. You don't need to create plain icons, but make sure that the original svgs and the line svgs only have 1 path and 1 fill color. 

Dont forget to optimize all the SVGs too using SVGOMG. You can also find this step in the tutorial.

2024-02-29 16:51 UTC, AnshSinghSonkhia commented
> Optimizing the SVG using SVGOMG

# Optimizing is a 1 Click task with SVGVIEWER

I found it more easier to do with it.

1. Visit [https://www.svgviewer.dev](https://www.svgviewer.dev)
2. Upload SVG or paste code

![beforeSVG](https://github.com/devicons/devicon/assets/110414565/79bb6f1d-7856-4ff0-aefe-03dc7145b454)

4. Click on `Prettify` Button.
5. Click on `Optimize` Button.

**BOOM !!!** The SVG is optimized, **without ruining the viewbox**.


![optimizedSVG](https://github.com/devicons/devicon/assets/110414565/f1c5ca53-f24f-4cb8-8cb8-76b2ff9596c4)

2024-03-02 05:14 UTC, canaleal commented
SVG Viewer is an awesome alternative, a previous contributor even [recommended it](https://github.com/devicons/devicon/issues/1279#issuecomment-1195438321), but notice how the SVGs still have the height, width and even stroke attributes after optimizing them in svg viewer. 

`
<svg width="128" height="128" viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg"><path style="stroke-width:.270613;fill:#121212;fill-opacity:1" d="M8.389 0v26.09h55.445c14.656 0 21.986 6.29 21.986 16.67 0 11.804-7.33 16.263-21.986 16.263H8.389v26.663h53.818c11.603 0 17.912 3.255 18.93 17.91.77 10.01.674 14.965.582 19.718-.03 1.53-.06 3.038-.06 4.686h34.218c0-7.567 0-14.5-1.15-29.29-1.425-14.857-9.161-22.386-22.393-25.032 15.674-2.036 27.277-14.248 27.277-32.973C119.611 15.671 103.122 0 69.941 0zm0 108.125V128h43.535v-12.72c0-2.674-1.312-7.155-7.356-7.155z"/></svg>
`

For example, I just copied the original svg code from above into SVGOMG and this is how it turned out. The viewbox is still `0 0 128 128`.

`
<svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 128 128"><path fill="#121212" d="M8.389 0v26.09h55.445c14.656 0 21.986 6.29 21.986 16.67 0 11.804-7.33 16.263-21.986 16.263H8.389v26.663h53.818c11.603 0 17.912 3.255 18.93 17.91.77 10.01.674 14.965.582 19.718-.03 1.53-.06 3.038-.06 4.686h34.218c0-7.567 0-14.5-1.15-29.29-1.425-14.857-9.161-22.386-22.393-25.032 15.674-2.036 27.277-14.248 27.277-32.973C119.611 15.671 103.122 0 69.941 0zm0 108.125V128h43.535v-12.72c0-2.674-1.312-7.155-7.356-7.155z"/></svg>
`

2024-03-02 07:05 UTC, AnshSinghSonkhia commented
> SVG Viewer is an awesome alternative, a previous contributor even [recommended it](https://github.com/devicons/devicon/issues/1279#issuecomment-1195438321), but notice how the SVGs still have the height, width and even stroke attributes after optimizing them in svg viewer.
> 
> `<svg width="128" height="128" viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg"><path style="stroke-width:.270613;fill:#121212;fill-opacity:1" d="M8.389 0v26.09h55.445c14.656 0 21.986 6.29 21.986 16.67 0 11.804-7.33 16.263-21.986 16.263H8.389v26.663h53.818c11.603 0 17.912 3.255 18.93 17.91.77 10.01.674 14.965.582 19.718-.03 1.53-.06 3.038-.06 4.686h34.218c0-7.567 0-14.5-1.15-29.29-1.425-14.857-9.161-22.386-22.393-25.032 15.674-2.036 27.277-14.248 27.277-32.973C119.611 15.671 103.122 0 69.941 0zm0 108.125V128h43.535v-12.72c0-2.674-1.312-7.155-7.356-7.155z"/></svg>`
> 
> And this is how it looks when I copied the original svg code from above into SVGOMG. The viewbox is still `0 0 128 128`.
> 
> `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#121212" d="M8.389 0v26.09h55.445c14.656 0 21.986 6.29 21.986 16.67 0 11.804-7.33 16.263-21.986 16.263H8.389v26.663h53.818c11.603 0 17.912 3.255 18.93 17.91.77 10.01.674 14.965.582 19.718-.03 1.53-.06 3.038-.06 4.686h34.218c0-7.567 0-14.5-1.15-29.29-1.425-14.857-9.161-22.386-22.393-25.032 15.674-2.036 27.277-14.248 27.277-32.973C119.611 15.671 103.122 0 69.941 0zm0 108.125V128h43.535v-12.72c0-2.674-1.312-7.155-7.356-7.155z"/></svg>`

Okay, so what do you want me to do now, for the best results?

2024-03-02 14:54 UTC, AnshSinghSonkhia commented
# With SVGOMG

```svg
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 128 128"><path fill="#121212" d="M8.389 0v26.09h55.445c14.656 0 21.986 6.29 21.986 16.67 0 11.804-7.33 16.263-21.986 16.263H8.389v26.663h53.818c11.603 0 17.912 3.255 18.93 17.91.77 10.01.674 14.965.582 19.718-.03 1.53-.06 3.038-.06 4.686h34.218c0-7.567 0-14.5-1.15-29.29-1.425-14.857-9.161-22.386-22.393-25.032 15.674-2.036 27.277-14.248 27.277-32.973C119.611 15.671 103.122 0 69.941 0zm0 108.125V128h43.535v-12.72c0-2.674-1.312-7.155-7.356-7.155z"/></svg>
```

![Screenshot 2024-03-02 201942](https://github.com/devicons/devicon/assets/110414565/06a1d3dd-6306-46e0-861b-2a65ca5d4feb)

I have not committed these changes, @canaleal 
## It is showing 150px height & width, Will it work?

2024-03-02 18:47 UTC, canaleal commented
Yes, I just check the SVG code you provided in the comment above and it looks good on inkscape and icomoon. 

![image](https://github.com/devicons/devicon/assets/49886351/e8664134-461e-4a0d-9393-7f2c2a562f2c)

![image](https://github.com/devicons/devicon/assets/49886351/e8c9b1f2-37ab-44c9-9840-3ed3ec36ddd2)

2024-03-04 14:53 UTC, AnshSinghSonkhia commented
Hey @canaleal & @weh,
The required changes are **DONE**. It's good to go, hopefully!!

I Got to learn a lot with this PR. Let me know if we need any more changes.

2024-03-05 05:15 UTC, canaleal submitted a review, later dismissed
Excellent work! 🚀 
SVGs are good and properly optimized. 

The font icons look good on icomoon, and there are no artifacts. 

![image](https://github.com/devicons/devicon/assets/49886351/1219018f-4b1e-498a-a404-bb248b380a20)

2024-03-05 05:22 UTC, canaleal approved these changes

2024-03-08 05:04 UTC, AnshSinghSonkhia commented
Still, this pr has one pending review @canaleal

2024-03-08 06:47 UTC, canaleal commented
Yup, thats pretty much the process. At least 2 reviewers are need to ensure that the changes are correct.

2024-04-19 15:07 UTC, weh approved these changes
LGTM :+1:

2024-05-25 03:37 UTC, merged