new icon: glitch (original, plain)
devicons/devicon pull request #2163
Opened 2024-03-08 16:45 UTC by AnshSinghSonkhia

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format new icon: Icon name (versions separated by comma). More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] PR's base is the develop branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the devicon.json file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR** fixes #2158 

# Link to prove your SVG is correct and up-to-date.
Home page: https://glitch.me/
Icon (on Simple Icons): https://simpleicons.org/icons/glitch.svg

### SVGs
<img src="https://github.com/devicons/devicon/assets/110414565/03637605-4240-4235-9ccc-035dbed41057" alt="plain-svg" width="300"> <img src="https://github.com/devicons/devicon/assets/110414565/096c31f4-6901-4805-895d-05dd25fdf12b" alt="original-svg" width="300">

2024-03-09 23:42 UTC, Kaamkiya commented
Thanks for fixing my issue :)

2024-03-10 04:21 UTC, AnshSinghSonkhia commented
> Thanks for fixing my issue :)

@Kaamkiya Thanks for raising it, I'm glad to help you :)

2024-04-07 07:41 UTC, canaleal requested changes

2024-04-07 07:41 UTC, canaleal commented on devicon.json
> +            "font": []
Make sure there's at least 1 font version. In this case, use `plain`.

2024-04-07 07:41 UTC, canaleal commented on devicon.json
> +        "aliases": [
The original and plain SVGs do not include the word "glitch". Therefore, they cannot serve as aliases for the wordmark SVGs.

2024-04-07 07:41 UTC, canaleal commented on icons/glitch/glitch-original.svg
Just add an empty new line to this SVG.

2024-04-07 07:41 UTC, canaleal commented on icons/glitch/glitch-plain.svg
Just add a new line. 

Also, I don't see any version of the glitch fish that are all black. I think combining the pink and blue color into a new color would be better than using the all black fish.

2025-02-23 06:46 UTC, canaleal approved these changes

2025-02-23 06:47 UTC, merged