Add Phoenix icon
devicons/devicon pull request #217
Opened 2020-06-08 20:35 UTC by Kartstig

- Fixes #101 
- Fixes #33 
- From https://github.com/konpa/devicon/pull/102

2020-10-12 01:23 UTC, Thomas-Boi commented
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

2021-01-06 01:12 UTC, Thomas-Boi commented
Hello there,

We notice that this PR has been inactive for awhile now. It would be a waste of your time and effort if we just close this PR and throw away the SVGs in here. Thus, 1 month from now, if this PR remains inactive/stale, we will fork your repo, fix any issues, and merge your icons ourselves.

Since GitHub tracks contributions by commits, you will still be credited. We also hope that you will help us merge this PR before the deadline comes.

Cheers,
Devicon Team

2021-01-06 17:53 UTC, Kartstig commented
@amacado I added a plain icon per guidelines.

I am not able to figure out the correct fonts to make the wordmark versions

2021-01-07 00:19 UTC, amacado requested changes
I suggest to remove `phoenix-plain.svg`, because I can't see any difference compared to `phoenix-original.svg` but the svg code does not look very pretty.

I suggested a code change to `devicon.json` to fulfill our updated requirements. If you could remove the depreceated ` enable-background="new 0 0 128 128"` from the svg I'm happy 👍🏻 

Also changed the branch to `develop`.

2021-01-07 00:19 UTC, amacado commented on devicon.json
> +  },
```suggestion
  {
    "name": "phoenix",
    "tags": ["framework", "elixir"],
    "versions": {
      "svg": ["original"],
      "font": ["original"]
    },
    "color": "#ff6f61",
    "aliases": []
  },
```

2021-01-07 03:11 UTC, Kartstig commented
Done!

2021-01-07 21:51 UTC, amacado commented
@Kartstig could you resolve the conflichts with devicon.json? Probably you need to merge with current development branch.

2021-01-09 00:25 UTC, amacado requested changes

2021-01-09 00:25 UTC, amacado commented on devicon.json
> +            "svg": ["original", "plain"]
A `font` version is missing for `phoenix`. We need at least one font version to add the icon to our set :)

2021-04-08 17:16 UTC, Panquesito7 commented
#551.

2021-04-08 17:16 UTC, closed without merging