new icon: Cloudrun
devicons/devicon pull request #2186
Opened 2024-04-23 23:05 UTC by this-is-emma

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/wiki/Organizing-SVGs)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [x] A new object is added in the `devicon.json` file at the correct alphabetic position as seen [here](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)

**This PR closes #2180 **

## Link to prove your SVG is correct and up-to-date.
Google Tutorial on Cloudrun with [icon displayed](https://codelabs.developers.google.com/codelabs/cloud-starting-cloudrun-jobs#0)

2024-04-24 03:00 UTC, canaleal requested changes

2024-04-24 23:43 UTC, this-is-emma commented on icons/cloudrun/cloudrun-original.svg
Thanks for the tutorial, this is will be helpful!

2024-04-25 05:05 UTC, canaleal requested changes
Nice work. We just need to make the sure that the SVGs are optimized and that the plain and line svgs only have 1 path.

2024-04-25 05:05 UTC, canaleal commented on icons/cloudrun/cloudrun-plain.svg
In this SVG the paths have to be unified into a single path and optimized just like the original.svg

2024-04-25 05:05 UTC, canaleal commented on icons/cloudrun/cloudrun-line.svg
In this SVG the paths have to be unified into a single path and optimized just like the original.svg.

2024-11-03 02:11 UTC, canaleal approved these changes
It's been some time so I decided to optimize the SVGs using SVGOMG. 

No artifacts on icomoon:

![image](https://github.com/user-attachments/assets/8568c5a5-a970-4011-8872-352fadafeb64)

2024-11-11 00:15 UTC, canaleal commented
All issues have been resolved and there are no artifacts in the SVGs.

![image](https://github.com/user-attachments/assets/fa5785ef-ec10-46ff-b809-e4dce91a870c)

2024-11-11 00:22 UTC, merged