Add arduino icon
devicons/devicon pull request #219
Opened 2020-06-08 20:39 UTC by Kartstig

- Adds the arduino icon

2020-10-12 01:23 UTC, Thomas-Boi commented
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

2021-01-06 01:12 UTC, Thomas-Boi commented
Hello there,

We notice that this PR has been inactive for awhile now. It would be a waste of your time and effort if we just close this PR and throw away the SVGs in here. Thus, 1 month from now, if this PR remains inactive/stale, we will fork your repo, fix any issues, and merge your icons ourselves.

Since GitHub tracks contributions by commits, you will still be credited. We also hope that you will help us merge this PR before the deadline comes.

Cheers,
Devicon Team

2021-01-08 18:53 UTC, Kartstig commented
- [x] Changed the base
- [x] Set devicon.json
- [x] Updated the svgs

2021-01-09 00:18 UTC, amacado requested changes
Please have a look at our guidelines regarding [svg requirements](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#svg-standards). The when you update this pull request, those requirements should be checked by out bot.. Let's see :)

2021-01-09 00:18 UTC, amacado commented on icons/arduino/arduino-original-wordmark.svg
> +   viewBox="0 0 17.197916 12.273544"
viewBox, height and width does not fulfill our requirements (0 0 128 128).

2021-04-27 00:45 UTC, merged