new icon: <i>langchain</i> (<i>original, original-wordmark</i>)
devicons/devicon pull request #2213
Opened 2024-06-12 13:17 UTC by kimjiwook0129

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/wiki/Organizing-SVGs)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [x] A new object is added in the `devicon.json` file at the correct alphabetic position as seen [here](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)

**This PR closes NONE**

## Link to prove your SVG is correct and up-to-date.

2024-06-13 11:06 UTC, Snailedlt requested changes

2024-06-13 11:06 UTC, Snailedlt commented on icons/langchain/langchain-original-wordmark.svg
This (and the original) icon is very large. Please look into optimizing it. If you don't know how, take a look at this guide: https://github.com/devicons/devicon/issues/1306#issuecomment-1296015861
There are many other guides also under that issue that might be worth looking at. For example this one for creating line versions from plain or original versions: https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294

2024-07-02 17:53 UTC, kimjiwook0129 commented on devicon.json
> +            ]
I've optimized both icons based on [#1306 (comment)](https://github.com/devicons/devicon/issues/1306#issuecomment-1296015861).
Could you recommend a tool I can use to make the svgs mono-colored?

2024-07-03 11:37 UTC, Snailedlt commented on devicon.json
> +            ]
@kimjiwook0129 Great!
We don't have any guides for making plain icons afaik, but I recommend trying to make it using inkscape.

Alternatively you could make a line icon using this guide: https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294

If it's okey with you I'll review the PR once you've added a font supported version (plain or line) with and without wordmark :)

2024-07-05 21:30 UTC, kimjiwook0129 commented on devicon.json
> +            ]
I've followed the guide using InkScape and attempted to convert the icons to outlined paths. However, at stage 7 of [#1306 (comment)](https://github.com/devicons/devicon/issues/1306#issuecomment-1297625294), I encountered an issue. 

We have approximately 300 folders containing both the stroke (as a path) and the initial path at the end of stage 6, and each initial path and folder needs to be manually removed while moving each stroke to the root of the SVG. 

I managed to handle around 100 folders, but it has proven to be quite challenging. There doesn't seem to be an automatic feature to drag all the strokes to the root of the SVG at once afaik. 

It appears that the current icons I am using do not meet the devicon guidelines. 
If it is acceptable to you, we can close this PR, and I will revisit it later with a suitable icon.

2024-07-12 14:57 UTC, closed without merging