update icon: vyper (original, original-wordmark)
devicons/devicon pull request #2221
Opened 2024-06-17 15:38 UTC by itsacoyote

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features
Updates Vyper logo to latest branding design. 
https://vyperlang.org/

## Notes
Removed `vyper-plain` and `vyper-plain-wordmark`. 
Updated `vyper-original` and `vyper-original-wordmark` and added aliases to cover `plain`.

2024-07-27 08:56 UTC, canaleal requested changes
Overall, great work!

All that's left is to optimize the SVGs and add "original-wordmark" to the SVG and Font entries inside the devicon.json file.

2024-07-27 08:56 UTC, canaleal commented on icons/vyper/vyper-original-wordmark.svg
Great work on this icon! However, it needs to be optimized and formatted to be on one line with an extra empty line.

You can follow the steps in this [comment](https://github.com/devicons/devicon/issues/1279#issuecomment-1195433256) to optimize the SVG.

2024-07-27 08:56 UTC, canaleal commented on icons/vyper/vyper-original.svg
This SVG also needs to be optimized, be on 1 line, and have an empty line.

2024-07-30 15:38 UTC, itsacoyote commented
> Overall, great work!
> 
> All that's left is to optimize the SVGs and add "original-wordmark" to the SVG and Font entries inside the devicon.json file.

Thanks for the suggestions! I tried to find as much of the documentation to make sure I was following things correctly, but had trouble finding the little bits. I'll make those changes 👍🏻

2024-09-05 08:24 UTC, weh approved these changes
Looking good, images are optimized. :+1:

2024-09-12 11:18 UTC, Snailedlt approved these changes
Looks good to me! ✔️ 
Thank you for the contribution! :rocket:

2024-09-13 09:11 UTC, canaleal approved these changes

2024-09-13 10:52 UTC, merged