awk: Add plain icon
devicons/devicon pull request #2262
Opened 2024-09-05 06:50 UTC by Finii

[why]
There are only wordmark icons for awk.

[how]
Just isolate the bird from the wordmark icons and put it into one dedicated plain icon.

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

Did a bit of research; the wordmark icon is obviously a scan of the 'original' awk book title. Later books all feature a similar but slightly different bird. But it seems this type of bird has become to represent awk.

![image](https://github.com/user-attachments/assets/1494bfdf-65db-4131-8726-e73024b5893e)
_'Original'_

![image](https://github.com/user-attachments/assets/ac39041c-bc44-4315-91e6-ec79e0f55b16)
_OReilly version_

![image](https://github.com/user-attachments/assets/5eb14b81-2d8f-4275-8382-1f3256902c57)

**This PR closes NONE**

## Notes

@Snailedlt as per https://github.com/ryanoasis/nerd-fonts/pull/1691#issuecomment-2313090871

2024-09-12 10:57 UTC, Snailedlt requested changes
Good idea using the bird as the non-wordmark version. Just some minor things that need to be fixed before this can be merged.

Also same issue here as before, make sure the base branch is `develop`

2024-09-12 11:16 UTC, Finii commented on icons/awk/awk-plain.svg
Sorry I am not familiar with the naming rules here and the alias creation. 😬 

About SVGO ... As I took the SVG from inside this repo I thought it must have been optimized already and running the optimizer multiple times degrades outlines and should be avoided, right?

And then there is this sentense [here](https://github.com/devicons/devicon/wiki/SVG-Standards):
>You no longer need to convert classes to fill. We now use SVGO to ensure all IDs and classes are unique.

From this I assumed SVGO is part of the CI.

2024-09-12 11:30 UTC, Snailedlt commented on icons/awk/awk-plain.svg
@Finii No worries at all. It's not very clear, and the wiki could use some updating.

A lot of the older icons in this repo are not optimized. Running it through SVGOMG should pose no issues, as it will just stop optimizing the icon at some point. When optimizing using SVGOMG you can use this guide: https://github.com/devicons/devicon/issues/1306#issuecomment-1296015861

The developer who made the optimization CI is not working on devicons anymore. I'm not sure how it works, but I think it's only applied before making the font version, so the SVGs still need optimization.

2024-09-12 11:35 UTC, Snailedlt approved these changes
Great work!
Thank you for the contribution!

We just need one more approval before this can be merged into the `develop` branch

2024-09-12 11:41 UTC, Finii commented on icons/awk/awk-plain.svg
Hmm, at NerdFonts the post-PR-created CI adds commits with optimized SVGs (if the optimized version is a certain amount of smaller than the originally PRed one). [1]

I can have a look at your CI if there is no one 'responsible'. Otoh, some contributors don't get it if the CI adds commits to their branch ;-)
Whatever you do, it's wrong ;)

[1] https://github.com/ryanoasis/nerd-fonts/blob/master/.github/workflows/packsvgs.yml#L23-L40

2024-09-12 11:46 UTC, Finii commented
There is one CI issue, something with the PR title I gleam from the error snippet :grimacing: 
Fini - clueless

2024-09-12 12:01 UTC, Snailedlt commented on icons/awk/awk-plain.svg
> I can have a look at your CI if there is no one 'responsible'.

That would be awesome! We need someone to work on automation in general too if you're interested. We have an issue about creating a CI for optimization. Here it is: https://github.com/devicons/devicon/issues/1547

There are also a ton of other automation and workflow issues open in case you're interested: https://github.com/devicons/devicon/issues?q=is%3Aopen+is%3Aissue+label%3Adevops

2024-09-12 12:03 UTC, Snailedlt commented
> There is one CI issue, something with the PR title I gleam from the error snippet 

Ahh yes, the title was incorrect. I fixed it now. If you take a look at the PR template when you create a PR you'll see what the title should look like depending on which kind of PR it is :)

2024-10-03 03:43 UTC, canaleal approved these changes

2024-10-03 03:45 UTC, merged