llvm: Simplify plain icon
devicons/devicon pull request #2264
Opened 2024-09-05 07:45 UTC by Finii

[why]
While the plain icon is plainer than the original icon, it is still quite complex with very thin strokes.

[how]
Just take the outermost outlines of the plain icon and crate a solid icon from it.

### Note

This can be **controversial**.
For me the plain icon is not really plain, it has lots and lots of detail and consists of 2600 nodes:

![image](https://github.com/user-attachments/assets/4ae04a1e-9f69-42bc-9902-c6cf6d408e68)

The simple plain icon proposed here drops all the details and uses just the outline (260 nodes)

![image](https://github.com/user-attachments/assets/29711897-bf2f-4cc3-a351-7ca26612a1a2)

If one needs an icon with all the glory details the `-original` should be a good fit, the plain should be a simple(r) version, I believe. But anyhow, this is very opinionated and I do not want to mess with your ideas here. For a small text icon the current plain icon is far too complex and all the small detail hairlines can not be seen anyhow.

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened

## Features

**This PR closes NONE**

## Notes

@Snailedlt as per https://github.com/ryanoasis/nerd-fonts/pull/1691#issuecomment-2313090871

2024-09-05 08:27 UTC, Finii commented
Hmm, hand-remove the gaps in the tail, that is an obvious artifact of the fill related broken outline in the original svg.
Force push.

![image](https://github.com/user-attachments/assets/d2444657-267b-47dd-8c84-70aa4e577b57)

2024-09-12 11:01 UTC, Snailedlt reviewed
hmmm, I don't agree with this one. While I agree that the icon could benefit from some simplification I think going all black is too much simplification, making it less recognizable... but let's see what the other maintainers think too :)

### Edit: 
Good that you fixed the artifact though. That should probably be fixed in the original icon too.

Some context: The original icon is made by converting a png to svg with inkscape. The process is not ideal so there are a few artifacts. I think it could be improved upon now though, since I know there are better png to svg converters out there now than when we made this icon :)

2024-09-12 12:20 UTC, Finii commented
> hmmm, I don't agree with this one

:laughing: 

As I said, controversial (see image below).

For me, as "in a font" the current plain one is just too intricate. Have a look at it sized down:

![image](https://github.com/user-attachments/assets/6109f423-a8e7-4a56-9937-eddc591d9624)

But that is just for ME and font usage, which might or might not be important for you.
Just wanted to share this icon version with you.

![image](https://github.com/user-attachments/assets/bc2cc22b-6980-4cd8-94bd-e1c23e48432c)

2024-09-12 13:05 UTC, Snailedlt commented
I agree it looks better in the font, but in larger sizes it looks significantly worse. Perhaps we could find some middle ground?
One way would be to roughly inverse the current plain version, and remove some of the detailing lines.

I'm thinking something like this:
![image](https://github.com/user-attachments/assets/1001827e-e271-4b42-b9fe-6c1a44b83383)

2024-09-12 13:15 UTC, Snailedlt commented
@Finii
Here's a suggestion. Though it should be optimized more, because it's very large (80Kb)
![llvm-original](https://github.com/user-attachments/assets/8c836f40-1efa-4bdc-8596-abb1be5694f5)

2024-09-12 13:17 UTC, Snailedlt commented
Sidenote: The old `plain` version can still be used as a `line` version instead :)

2024-10-03 08:36 UTC, weh submitted a review, later dismissed
great work :+1:

2025-04-21 14:08 UTC, Snailedlt requested changes
I don't believe the suggested version is close enough to the original to justify the original. Most of the lines should be kept imo. I added a suggestion as to how it could look in a previous comment, I think if some of the nodes are removed on that version we'll have both a pretty nice looking and optimized plain version

2025-06-02 10:55 UTC, Snailedlt commented
@Finii What do you think about my suggested version?
Is it something you could get behind, and if so, would you like to optimize it a bit by removing some of the nodes, etc..?
https://github.com/devicons/devicon/pull/2264#issuecomment-2346256393

2025-06-03 05:21 UTC, Finii commented
Ok, if you explicitly ask me ;-)

At first glance the icon looked two color, but in fact it is monochrome. The outline of the outline :grimacing: is rather thin in some places, down to non-existing. So the impression is that the transparent 'line' of the outside is line-art style, but the actual outside 'line' is not line-art anymore and just a suggestion.

![image](https://github.com/user-attachments/assets/92b38fe1-a46f-4bdf-8a29-30f1d0968f98)

This is not quite what I would call 'simple'. If we compare to the original logo material (https://llvm.org/img/LLVMWyvernBig.png)

![image](https://github.com/user-attachments/assets/89223fff-cec7-4f8e-80d9-064b92ddada1)

you turned the actual outline (originally black) into transparent and filled the internal areas; but to keep the line characteristic on a transparent backdrop you added this small suggestion of a outline-outline.

I understand the reasons for the extra outline and also for its slimness, but I wonder if there is a better solution to the problem to transform the two-color-on-transparent filled-area line style into a one-color line style.

One solution could be to non-uniformely use the original outline, sometimes as line-art, sometimes just combine it with the area (to keep the original apprearance), so that the outside of the logo is not line art, but only the inside is drawn with a line-art pen. Hmm, if that makes sense.
Like this:

![image](https://github.com/user-attachments/assets/bf766ab2-63f8-416f-aa12-3f644d465723)

So just considering the black line in the original icon, it is converted into a white/transparent line if it is surrounded by filled areas on both sides, but if it is only neighbored on one side by an area and on the other side there is 'the nothing' it gets combined to the area.

-----

Also interesting is the approach taken by the _Clang Powertools_ to get a monochrome icon from the old dragon:

![image](https://github.com/user-attachments/assets/e92b37e4-a962-4435-b6dd-fa8d0e8a58a2)

_https://clangpowertools.com/_

![image](https://github.com/user-attachments/assets/b1f72741-1721-4d63-9613-7fcd43bfbc8a)

_Original_

This is a somewhat loose interpretation, note the neck, and the number of spikes everywhere.

----

Whatever. Back to the llvm icon, I have the feeling that your suggested one is too intricate, and the thinner than thin outline - which is needed to keep the outer line a line when the line is transmogrified into 'transparent' - can even be hard to render small.

I'm not sure.

* Is the icon itself worth all the hours of work? :grimacing: :wink: 
* How simple is simple (as defined by your 'icon guidelines')
* Would it make sense to create at least a potion of the dragon into something concrete following the pink/green pattern above

Maybe I can find some time to spare on this today.

2025-06-03 05:28 UTC, Finii commented
Already in this very fast threshold-to-black-and-white image one can glimpse that the outlying lines are thinner (and should than vanish by combining with the inner areas) while the inside lines really appear more fat more substantial and would be converted to white/transparent lines in a monochrome version.

:thinking: 

![image](https://github.com/user-attachments/assets/6cbcb3a6-c7fd-4c3c-b682-49e98ffafe00)

2025-06-03 05:48 UTC, Finii commented
The design problem reminds me of that one spiky fish icon, that I solved in a comparable manner, lets see if I can find it...

Ah, it was OpenBSD, here: https://github.com/lukas-w/font-logos/pull/93, but apparently did not materialize?

![image](https://github.com/user-attachments/assets/b924165d-8ab7-46b5-9c66-f03deeda48db)

![image](https://github.com/user-attachments/assets/d01581a6-7b6c-4b1d-af3b-259e889dafd8)

2025-06-03 06:31 UTC, Finii commented
Something like this, this is a rough sketch needing cleanup:

![image](https://github.com/user-attachments/assets/c5b7f66c-689e-4079-8988-fb5da6a264dd)

2025-06-03 13:12 UTC, Snailedlt commented
@Finii damn you're good!
hmm, I think your version looks better at a distance, while mine looks better closeup... but with some minor changes your version could look a lot better close-up.

There are some places where the transparent lines are inset (in line with the black outline) instead of being outside the black outline. And also some places where the transparent line doesn't reach the outline of the dragon. See this example:
Yours:
![image](https://github.com/user-attachments/assets/7fbb60b0-35d1-4a5a-9978-f171e74a0875)
Mine:
![image](https://github.com/user-attachments/assets/8db60fc7-8ca9-410a-bab1-6199a9d9772e)

Notice how the transparent lines at the bottom kinda cut into the thicker part of the tail. I think it would look better if the transparent lines here were shifted outwards a bit so it instead cut through the thinner parts of the tail.
I think you can see the issue a bit better here: 
![image](https://github.com/user-attachments/assets/283f9c9c-95fe-4b3a-99ff-1776509a6358)

A rough sketch of what I suggest is something like this: 
![image](https://github.com/user-attachments/assets/d8fa5e75-83c0-4740-b213-214634ce38db)


As for the top left red arrow, you can see that the transparent line doesn't fully reach the edge of the dragon. There are more places where this is the case, so this is just an example.
![image](https://github.com/user-attachments/assets/31c31e0a-2b44-47b8-91ea-2463fc3dd464)

a rough fix: 
![image](https://github.com/user-attachments/assets/ead6292c-32d3-48c0-ae9d-4ed001141c54)


Another thing I think looks a bit weird is the tip of the fingers on the wings, like here:
![image](https://github.com/user-attachments/assets/87863bab-9830-44e4-a773-16b0de96e3e5)

I get the idea of adding a thicker part to make the tips visible at smaller sizes, but I think it's too detrimental to the detail to be worth it.

Looking at your version did give me an idea though.
What if the skin part (the blue colored part) of the wings were outlined instead of colored in. I think that would make it look much better.
For reference, I'm talking about this part of the wings being transparent instead of black, and then outlined with black lines...

![image](https://github.com/user-attachments/assets/eaa1538a-1163-4f24-9292-f94ab4c025d4)

So kinda reverse of what it is now. That way the tips of the wings should be visible at smaller sizes while still making the larger sizes look detailed.

I think overall it just needs cleaner lines and outlining of the wings instead of filling them :)

It's very difficult to do this changes when the path is unified, so it would be nice if you uploaded the ungrouped/un-unified version too next time :)

2025-06-03 14:29 UTC, Snailedlt commented
hmm, I spent some time to make another suggestion.
To make it I started with the llvm-original version and removed all but two of the paths. I then added a small stroke to one of the paths, and used the path + stroke as a cutout for the other black path.

Here's the optimized version:
![llvm-plain-optimized-svgomg](https://github.com/user-attachments/assets/a3602335-4e19-4daa-a258-80e28b0d0221)

The size of this version is just over 43KB

Let me know what you think, and if you find any flaws :)

Here's the non-optimized bi-colored version in case you want to make any tweaks:
![llvm-bicolored](https://github.com/user-attachments/assets/7d090bfd-0e88-46f7-894b-6e3d9bd1770a)

2025-06-03 14:30 UTC, Snailedlt commented
I'm personally very happy with the last suggestion, but I haven't looked very closely at the result, so let me know if you find any flaws

2025-06-03 14:46 UTC, Snailedlt commented
If we want to make a line version as well, I think we should make it with the original png as a base: 
https://llvm.org/Logo.html
https://llvm.org/img/LLVMWyvernBig.png
![](https://llvm.org/img/LLVMWyvernBig.png)

2025-06-03 15:28 UTC, Snailedlt commented
I made a line version too. So here are my two suggested versions:

llvm-line.svg
![llvmplainsvgomg-unified](https://github.com/user-attachments/assets/ddac1fdc-0e02-4170-a4b6-ffc313affc09)
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"> <path d="M96.13 24.025c-.049 0-.503.232-.894.43h-.002a1.552 1.552 0 0 0-.156.06 8.24 8.24 0 0 0-.476.233c-.374.194-.833.453-1.207.688-.738.464-1.367.953-1.936 1.505-.167.163-.33.33-.488.504-.043.048-.083.1-.125.149-.12.137-.239.277-.354.424l-.064.086c-.438.568-.85 1.203-1.262 1.945v.002c-.22.399-.558.897-.74 1.097-.42.465-.614.902-.606 1.405.003.304.096.566.266.808l.027.04c.05.066.107.131.17.195.059.062.122.125.194.185.448.371.714.629.95 1.035.121.208.235.455.362.778.127.322.268.72.44 1.224a68.64 68.64 0 0 1 1.357 4.63c.187.726.514 2.098.793 3.306.14.604.266 1.167.36 1.59.046.211.085.386.11.513.014.064.023.117.03.155.007.037.01.07.01.056 0-.034.001-.014-.01.004a.764.764 0 0 1-.053.076 2.416 2.416 0 0 1-.19.211 2.4 2.4 0 0 0-.429.536c-.123.212-.228.474-.367.892-.067.201-.123.354-.178.473a.926.926 0 0 1-.17.265.641.641 0 0 1-.213.135c-.023.01-.051.018-.078.028-.087.03-.186.061-.32.091l-.016.004-.013.002c-.381.085-1.47.267-2.538.432-1.072.166-2.132.316-2.394.33-.187.011-.267.008-.354.006-.042-.002-.112 0-.142-.006a.295.295 0 0 1-.164-.08.62.62 0 0 1-.192-.285c-.011-.025-.04-.06-.04-.073 0-.005-.011-.015-.012-.021-.019-.107-.173-.293-.25-.293-.004 0 .025.055.025.062-.027-.015-.042-.037-.072-.05-.037-.016-.093-.028-.135-.041a.384.384 0 0 0-.086-.034l-.057-.007a5.617 5.617 0 0 0-.619-.116l-2.086-.289c-.83-.113-1.81-.263-2.804-.422-.238-.038-.467-.078-.705-.117-.923-.151-1.86-.307-2.717-.46a103.54 103.54 0 0 1-2.6-.495 25.1 25.1 0 0 1-.746-.164l-.092-.021c-.01-.003-.008-.004-.017-.006a3.022 3.022 0 0 1-.366-.11h-.001c-.032-.016-.04-.025-.05-.043a.276.276 0 0 1-.013-.127c.007-.144.063-.413.172-.87.045-.19.193-.716.289-1.077a226.2 226.2 0 0 1 .574-2.1c.086-.302.178-.63.246-.863.055-.187.103-.345.139-.459.018-.057.031-.103.043-.136.011-.034.025-.06.02-.051.003-.008.004-.005.007-.01.073-.031.239.058.608.293.019.012.019.009.039.022.1.062.216.142.279.167.177.104.254.126.268.028.003-.027-.013-.078-.024-.123.002-.012.008-.026.008-.037 0-.062-.02-.102-.049-.168a3.518 3.518 0 0 0-.119-.25c-.104-.2-.257-.47-.455-.805v-.002l-.328-.549.074-.66c.054-.479.114-.893.17-1.197.017-.095.033-.157.049-.229.025-.105.052-.238.074-.271l.004-.012.002-.002c.018-.021.028-.03.047-.035a.32.32 0 0 1 .127.002c.136.02.377.092.795.228a28.154 28.154 0 0 0 .732.229l.055.016.021.004.01.001.018.002c.004 0 .01-.007.015-.007.063.015.253.078.258.072.045-.043-.052-.202-.264-.46-.013-.017-.015-.028-.031-.048-.163-.205-.456-.52-.914-.992-.171-.176-.249-.266-.377-.402-.188-.205-.442-.463-.539-.598a1.293 1.293 0 0 1-.154-.28c-.019-.11-.043-.276-.063-.42-.024-.176-.1-.548-.166-.835a3.866 3.866 0 0 1-.101-.748v-.002l.011-.172.282-.016c.377.003.755.033 1.128.086.26.035.46.056.604.063.072.003.13.002.178-.002l.008-.002c.09.004.338.035.345.027.03-.03-.07-.135-.209-.26-.004-.007-.006-.018-.011-.025a.786.786 0 0 0-.15-.149 4.683 4.683 0 0 0-.556-.365c-.053-.03-.124-.064-.181-.095-.03-.018-.055-.041-.084-.057-.049-.027-.13-.058-.188-.088a12.047 12.047 0 0 0-1.039-.482c-.054-.023-.11-.052-.164-.073v-.002a8.134 8.134 0 0 1-2.168-1.207h-.002V30.9a6.808 6.808 0 0 1-.508-.408c-.041-.037-.042-.05-.072-.08-.04-.048-.085-.1-.088-.121v-.002c-.004-.043 0-.065.012-.088a.293.293 0 0 1 .098-.088l.025-.013c.112-.067.362-.163.691-.282.124-.046.253-.097.415-.154.349-.124.699-.247.884-.32.097-.039.158-.066.217-.094.26-.11.408-.193.377-.242-.02-.035-.137-.057-.266-.057-.014 0-.003.004-.015.004-.003 0-.007-.003-.01-.004-.035-.01-.078-.016-.13-.023-.057-.008-.149-.016-.225-.024-.003-.001.013 0 .01-.002-.01-.005-.033.001-.048-.002-.058-.005-.097-.01-.164-.015a16.585 16.585 0 0 0-1.197-.04c-.67 0-1.166.044-1.648.135-.074.013-.166.029-.244.047a8.17 8.17 0 0 0-.698.192c-.372.122-.593.18-.86.205-.064.006-.13.015-.202.017-.351.007-.838-.04-1.787-.138-.435-.045-.7-.081-.842-.121a.344.344 0 0 1-.121-.053c-.013-.012-.012-.009-.012-.027 0 .007.03-.051.094-.116.069-.06.152-.124.285-.209.316-.2.81-.47 1.469-.8l1.418-.711-.266-.07c-.024-.007-.08-.007-.111-.012-.012-.008-.021-.024-.033-.03a.786.786 0 0 0-.262-.047 5.858 5.858 0 0 0-.871.041c-.288.03-.61.083-.926.14-.026.003-.057.003-.082.007l-.043.01c-.186.034-.343.08-.52.12-.165.041-.338.075-.494.124-.04.012-.091.02-.129.033-.966.312-1.55.668-2.365 1.436a4.76 4.76 0 0 1-.71.552c-.11.057-.267.124-.473.196-.075.025-.13.047-.217.074-.124.04-.266.079-.403.119-.232.065-.466.132-.705.19-.333.08-.652.15-.9.193a3.939 3.939 0 0 1-.31.043c-.077.007-.134-.001-.124.004-.005-.002-.011-.003-.021-.028a.364.364 0 0 1-.02-.129c0-.092.114-.342.323-.634 0-.002 0-.003.002-.004 0-.001 0-.003.002-.004.21-.294.51-.644.855-1.006a15.847 15.847 0 0 1 1.678-1.523c.062-.047.125-.095.19-.141a17.657 17.657 0 0 1 1.145-.764l.21-.129-.407-.043a3.337 3.337 0 0 0-.566.004h-.01l-.037.006a8.77 8.77 0 0 0-.707.096c-.127.02-.235.025-.363.05-.31.063-.622.15-.934.227-.07.018-.133.032-.205.051-1.231.32-2.46.742-3.598 1.232-.022.01-.046.016-.068.026-.408.174-.795.36-1.17.549-.019.01-.041.017-.06.027-.036.018-.065.037-.1.055-.33.17-.643.343-.94.52-.104.06-.21.12-.31.183a12.92 12.92 0 0 0-.773.52c-.153.11-.286.219-.42.33-.126.102-.24.203-.348.304a4.32 4.32 0 0 0-.613.678c-.024.033-.044.066-.065.1-.024.04-.057.08-.078.12-.027.051-.044.107-.066.16-.01.025-.03.051-.037.075-.004.01-.005.026-.008.037-.131.38-.157.818-.067 1.299v.002c.023.11.04.232.047.336a.965.965 0 0 1-.006.218 1.04 1.04 0 0 1-.128.202 3.463 3.463 0 0 1-.736.68l-.048.03a3.192 3.192 0 0 1-.39.21 5.4 5.4 0 0 1-.813.297l-.123.03c-.251.064-.524.125-.851.186-.209.04-.412.119-.543.22-.009.008-.024.012-.032.019a.469.469 0 0 0-.175.253c-.004.015-.002.051-.004.067-.055.19-.045.434-.008.687.014.29.053.478.201.784h.002c.096.198.226.387.365.56.009.01.013.025.022.035l.021.024c.179.211.375.387.565.484l.002.002c.13.066.399.136.642.174.214.033.663.171.963.3.118.05.2.073.31.116.09.036.19.072.266.1.105.037.238.094.326.12.122.037.227.063.311.077.02.003.035.002.053.004a3.27 3.27 0 0 0 .343.05h.2l-.43-.421a2.355 2.355 0 0 1-.402-.493.534.534 0 0 1-.06-.25c0-.082.016-.134.038-.164s.053-.05.117-.058c.128-.018.377.034.727.173.106.044.21.065.32.1a4.959 4.959 0 0 0 .02.006c.125.039.257.09.365.113.104.023.193.036.266.04.016 0 .031-.004.046-.005a4.959 4.959 0 0 0 .286.041c.195.023.195.02-.168-.336a3.158 3.158 0 0 1-.416-.51c-.031-.045-.07-.096-.094-.136a.662.662 0 0 1-.068-.17c.003-.01.005-.02.021-.045a.454.454 0 0 1 .094-.101c.076-.06.232-.104.443-.106.047 0 .106.008.158.012.137.012.289.032.479.074.046.01.087.017.135.03.089.023.164.035.238.048.704.167.727.129.322-.256a2.685 2.685 0 0 1-.236-.25c-.018-.022-.02-.03-.033-.05-.087-.121-.12-.218-.086-.295.017-.021.033-.042.07-.07v-.003c.033-.026.124-.076.238-.129.07-.032.161-.066.246-.1.054-.02.098-.041.155-.062l.011-.004c.15-.054.263-.076.403-.117.192-.05.41-.115.5-.115h.004c.064 0 .087.01.127.016a.302.302 0 0 1 .105.078c.07.07.092.095.11.174.017.078.02.219.02.478 0 .315-.03.579-.1.84v.004l-.003.004a2.96 2.96 0 0 1-.093.271c-.04.1-.084.2-.133.301-.025.05-.048.101-.076.154-.048.089-.106.178-.16.268a5.814 5.814 0 0 1-.393.568 8.499 8.499 0 0 1-.508.598 10.94 10.94 0 0 1-.451.455c-.055.053-.107.105-.164.158-.216.2-.443.397-.682.586-.37.294-.618.5-.779.65-.08.076-.14.136-.182.19-.014.019-.014.04-.025.059l-.1.132.078.069c.018.03.04.057.067.082a.984.984 0 0 0 .187.13c.024.014.067.026.094.04.127.067.27.125.42.174.03.01.047.021.078.03.194.061.3.097.406.098.107.002.191-.036.317-.093.023-.01.055-.035.08-.047l.037-.022c.39-.21.973-.71 2.139-1.816 1.137-1.076 1.633-1.477 2.418-1.941l.035-.022c.7-.409.97-.649 1.318-1.184.176-.264.277-.393.494-.503.218-.111.566-.202 1.207-.352.212-.05.379-.082.56-.121.319-.064.637-.129.944-.176.093-.014.193-.036.283-.047h.008a14.185 14.185 0 0 1 1.715-.084c.741-.002 1.153.009 1.418.067.265.058.387.154.592.361.085.085.15.168.213.254.03.044.06.088.088.135.044.075.085.153.117.24l.0 [...]

2025-06-04 07:24 UTC, Finii commented
Your plain version looks awesome!

Zooming in (randomly, on the right paw (left in the image)) is this which shows some technical problems

![image](https://github.com/user-attachments/assets/976b13f7-86a2-41e6-89e0-8c058dc8cafa)

There is this blob of 3 nodes that is 'dirt', and then the arrowed nodes are in fact two nodes.

I set fill to none and turned on 0.2 px stroke to see defects in the path. Did not notice any more 'smudges', but there are a lot of two-node-paires with the exact same coordinates. Inkscape shows them smaller:

![image](https://github.com/user-attachments/assets/68f769c9-1f8b-418c-ba2e-6777a67299c9)

I encountered these strange pairs in the past and my belief is that the path is not 'really' closed here, but this is start and end on the same place, but not in the same node.

Not really a clue if they are generally a problem, but sometimes they are. This is not clear for me.
Anyhow, breaking apart the path and combining it again removes some but not all of the double points. :thinking: 

So my intermediate conclusion is that your new plain icon is great; but you can remove that three-node-smudge between its right hand fingers (left side in the image).
I will investigate a bit more into the two point problem if time permits. Maybe tools like svgo already attack them.
Inscape simplify does not in general. Also simplify does not really enhance your plain svg, so that seems to be already quite compact :+1:

2025-06-04 08:03 UTC, Snailedlt commented
Hmmm, the last plain version I uploaded is already optimized by SVGOMG, so that doesn't seem to remove those nodes.

Might be something that needs to be done manually if it is to be done at all

2025-06-04 14:58 UTC, Finii commented
_Some meetings later, and I can not find my reply I started here ... Sigh. So, again...._

I now think the double points are not much of a problem. Other people also searched for an automatic solution, and theoretically Inkscape could do that maybe, but I could not get it to work.
Additionally they go away when fontforge imports the paths and converts the nodes to font-nodes.

Some can be auto-removed when you break apart and recombine all paths, but not all. (`shift` `ctrl` `k` and `ctrl` `+`).
I think.

So, I would say the plain icon apart from the small 3 point glitch is good to go!

-----

Then I looked at the line version, and what I did not like much was that it does not look like what I would call line-art. I am not sure if that is the design goal here for line versions, but maybe it is. The problem for me is that the stroke width is not comparable overall, but it notably differs especially for inside and outside strokes:

![image](https://github.com/user-attachments/assets/979aa199-7b43-4403-b2a5-687fa9020b46)

_As provided by you_

![image](https://github.com/user-attachments/assets/8f82d879-6a83-4490-9313-8e88d85885db)

_Stroke width unified_

Detail view, with thick in pink and thin in blue:

![image](https://github.com/user-attachments/assets/c5338fd9-1aa3-4fda-8052-cc9cac288de7)

![image](https://github.com/user-attachments/assets/412f49ad-4f4e-4533-b08c-4bb9f8d153d4)

Maybe the point is moot, this is just a suggestion.

How did I do it?
* Export your line version as hires png
* Import png into empty Inkscape
* Trace the bitmap with mode 'centerline'
* Now you have the dragon as open strokes
* Adjust stroke width, ends (rounded), and bends (round)
* Path - Stroke to Path

Of course that does not have sharp pointy ends, and so finally I merged the resultant path with your line path.

But there are some not-so-nice places, especially at the tips of the spikes, etc, that would need some tweaking.

Anyhow, have a look.

Ah, and here the full svg with 'your' and 'my' path. Do `ctrl` `a` and `ctrl` `+` to get 'the end result'.

![image](https://github.com/user-attachments/assets/e29418c9-9b8d-432d-aba7-9000f5020dee)
_Small preview, one path moved to reveal the other_

Full Inkscape SVG for experiments (to download and open in Inkscape):

![unified_lines](https://github.com/user-attachments/assets/77844d26-e9e5-4e7c-86d8-6b24bd38c7fd)

2025-06-05 10:14 UTC, Snailedlt commented
hmm, the reason I made the outline lines thinner was due to aesthetics.
When I made them the same thickness they overlapped and caused some weird artifacting in some of the detailed areas, like the tail and the wing fingertips.
But your version doesn't seem to have the same issues, at least not nearly to the same extent.
There are some places that are a bit worse looking than in my version due to the line thickness making lines merge together without any gaps... and in some places it looks a bit "wavy" like on the bottom of the tail:
![image](https://github.com/user-attachments/assets/7bb8d0f7-c4cc-491a-93d8-f632f665033d)
but other than those the icon as a whole looks much better.

I also agree that having the same line thickness everywhere is a design-goal and that it usually looks better too.

Unless you have any objections I suggest we settle on going for your newly made llvm-line version and my latest llvm-plain suggestion. Let's get this PR merged 💯 

**Sidenote:**
I wasn't able to download or view the images and SVGs you uploaded in fullscreen view because they are private for some reason. Not sure why, but it looks like this:
![image](https://github.com/user-attachments/assets/55bcfab0-05c2-4efa-a413-b4132f70dd0b)


**Edit:** It seems there was something wrong with my browser. After clicking on the PR again, I was able to view the images. Maybe an auth cookie that was malformed or something? I dunno

2025-06-06 14:09 UTC, Finii commented
Well, my line version was just quickly done in boring zoom meetings :grimacing: 
I can improve it taking your comments into account, but not today but I assume tomorrow.

2025-06-06 14:14 UTC, Snailedlt commented
Sounds good to me. Let's try to get this PR merged before the end of next week :)

2025-06-08 21:53 UTC, Finii commented
Use @Snailedlt's plain version sans the smudge at the right hand (which I called left hand in the commit message, sigh).

Use @Snailedlt's line version and increase the outer line a bit to make it as thick as the inside lines.

Force push to
* remove the unneeded merge commits
* have just the final changes and not the development in the repo

2025-06-08 22:27 UTC, Snailedlt requested changes
Line version needs to be added to the font. Let's also add the color as fill to the line and plain versions :)
`#5A90B6`

2025-06-08 22:27 UTC, Snailedlt commented on devicon.json
>                  "plain"
Add line icon to font
```suggestion
                "plain",
                "line"
```

2025-06-09 07:24 UTC, Finii commented on devicon.json
>                  "plain"
Applied

2025-06-09 07:32 UTC, Finii commented
> Let's also add the color as fill to the line and plain versions :) #5A90B6

According to the specs having a unspecified fill color is ... expected?

![image](https://github.com/user-attachments/assets/238737bb-b1ca-4da9-b8a2-35a25d4dfc83)

![image](https://github.com/user-attachments/assets/6173d6b4-b8b6-4155-b07f-24f8b7e1525a)

:thinking: 

----

Edit: Of course if you say the color is expected I change the svgs, thats easy. I just wonder, it somewhat contradicts with how I read the contrib info; and then, maybe _the contrib info_ needs to be changed also.

2025-06-09 07:57 UTC, Snailedlt commented
It's more of a convention we've used since it makes it easier for some third-party tools. It's not really needed for our internal workflow.
Yeah, maybe we should update the wiki.

I don't even remember why we re-added the fill for many icons at this point 😅

2025-06-09 08:02 UTC, Snailedlt commented on icons/llvm/llvm-line.svg
It seems you've accidentally added height, width, version and space attributes. The only attributes needed are xmlns, viewbox and fill for the path.

You can either remove them manually or run it through SVGO. SVGO might be able to further simplify the path, so that's probably the best option :)

2025-06-09 08:12 UTC, Finii commented on icons/llvm/llvm-line.svg
I'll change both (i.e. add concrete fill color and fix the attributes), force push imminent.

I wonder how the attributes got there as I think (!) I explicitly disabled them in the Inkscape export.

2025-06-09 08:21 UTC, Finii commented on icons/llvm/llvm-line.svg
Ah I see... manually removed. Also moved the color to the front as you required that somewhere else.

2025-06-09 20:58 UTC, Finii commented
Dear SVG Checker Bot,

it would probably be more helpful if you hint how to sort the `devicons.json` file.
For example users could just

```shell
$ jq --slurp --indent 4 '.[] | sort_by(.name)' < devicon.json  > devicon_sorted.json
$ mv devicon_sorted.json devicon.json
```

I will add a commit with the result of this. Lets see if you are content then.

2025-06-10 12:39 UTC, ReenigneArcher approved these changes
The order of the json file shouldn't hurt anything, and since everything is supposed to be alphabetical I think this is a good change.

In the future I want to add a PR check that makes sure the json file is properly formatted and properly sorted which can run for every PR.

For the icons, any idea how to fix this? The viewbox is the right size, but it displays as the wrong size.

![image](https://github.com/user-attachments/assets/63e6d406-810c-45eb-92a2-188a03e1021d)

Approving since both of the things I discussed would be future improvements.

2025-06-10 13:45 UTC, Snailedlt commented
@ReenigneArcher yeah, adding a check for formatting and sorting would be nice!

I'm not sure why you have that sizing issue, in my GitHub preview it looks fine: 
![image](https://github.com/user-attachments/assets/e521b8f1-599a-4f54-a17d-f6ae59e8a11c)

2025-06-10 13:46 UTC, Snailedlt commented
@canaleal I know you already started the release process, but do you think we can merge this as well, since there were some issues with the font?

2025-06-15 04:13 UTC, merged