new icon: memcached (original)
devicons/devicon pull request #2273
Opened 2024-09-22 11:56 UTC by ah-aliakbarpour

## Double check these details before you open a PR
* [x]  PR does not match another non-stale PR currently opened
* [x]  PR name matches the format _new icon: Icon name (versions separated by comma)_. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
* [x]  PR's base is the `develop` branch.
* [x]  Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
* [x]  SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
* [x]  A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

**This PR closes #2271**

## Link to prove your SVG is correct and up-to-date.
https://memcached.org/

2024-11-03 01:05 UTC, canaleal requested changes
Thank you for contributing to devicons 👍 

I've left some comments on how to improve the MR. If you have any questions or need help feel free to ask!

2024-11-03 01:05 UTC, canaleal commented on devicon.json
> +                "original"
The original SVG contains multiple paths and colors. Please create a `plain.svg` icon that follows our [SVG guidelines](https://github.com/devicons/devicon/wiki/SVG-Standards) and use that new icon for the font version,

2024-11-03 01:05 UTC, canaleal commented on icons/memcached/memcached-original.svg
Great job with the SVG! There are just a few adjustments needed:

1. The SVG needs to be optimized. Please follow this [tutorial](https://github.com/devicons/devicon/pull/1926#issuecomment-1776317249) for guidance.
2. Since the icon contains multiple paths and colors, it can't be used as the font version. Please create a `plain.svg` version with a single path and color.

2024-12-07 21:29 UTC, canaleal commented
Hey @inpour. Hope you don't mind but I've added the plain and line versions of the icon.

2024-12-07 21:30 UTC, canaleal commented
There are no weird artifacts in the SVGs. 

![image](https://github.com/user-attachments/assets/876fd9d7-8902-4751-8ee5-564250d6d10e)

2024-12-11 09:07 UTC, inpour commented
All good, Thank you @canaleal .

2024-12-26 01:25 UTC, canaleal approved these changes

2024-12-26 01:26 UTC, merged