new icon: hoppscotch (plain, original)
devicons/devicon pull request #2281
Opened 2024-10-08 09:58 UTC by Tiger-Tig74

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/wiki/Organizing-SVGs)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [x] A new object is added in the `devicon.json` file at the correct alphabetic position as seen [here](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)

**This PR closes #2277**

## Link to prove your SVG is correct and up-to-date.

https://github.com/hoppscotch/hoppscotch

2024-10-13 05:06 UTC, canaleal submitted a review, later dismissed
Excellent work. 👍 

The icons are good and there are no artifacts in icomoon. 

![image](https://github.com/user-attachments/assets/cf182054-8675-4235-96bb-3071b9b837fb)

2024-10-14 15:15 UTC, weh requested changes
Just some newlines missing. Newlines should be added for older Editors.

2024-10-14 15:15 UTC, weh commented on icons/hoppscotch/hoppscotch-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 128 128"><defs><radialGradient id="b" cx="0" cy="0" r="1" gradientTransform="matrix(-98.55944 137.6004
Always add a newline in the svg files
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 128 128"><defs><radialGradient id="b" cx="0" cy="0" r="1" gradientTransform="matrix(-98.55944 137.6004 -152.84948 -109.48194 126.528 1.92)" gradientUnits="userSpaceOnUse"><stop stop-color="#00D196" stop-opacity=".5"/><stop offset=".997" stop-color="#00D196" stop-opacity="0"/></radialGradient><radialGradient id="d" cx="0" cy="0" r="1" gradientTransform="matrix(-92.15276 33.57 -20.47767 -56.21308 100.15 53.512)" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient><linearGradient id="a" x1="411.893" x2="411.893" y1="212" y2="612" gradientUnits="userSpaceOnUse"><stop stop-color="#00D196"/><stop offset="1" stop-color="#00B381"/></linearGradient><linearGradient xlink:href="#a" id="c" x1="411.893" x2="411.893" y1="212" y2="612" gradientTransform="scale(.15534)" gradientUnits="userSpaceOnUse"/></defs><rect width="128" height="128" fill="#08110f" rx="28.583"/><rect width="128" height="128" fill="url(#b)" fill-opacity=".5" rx="28.583"/><path fill="url(#c)" d="M63.752 32.934a34.436 34.436 0 0 0-22.236 8.34c-9.06-1.565-19.78-1.576-23.12 5.925-3.745 8.411 5.438 18.094 18.747 26.512 1.884 8.139 7.43 15.329 15.625 18.977 8.195 3.648 17.253 2.959 24.556-1.084 15.162 4.256 28.501 4.601 32.246-3.811 3.34-7.5-3.841-15.461-11.066-21.148a34.411 34.411 0 0 0-20.469-30.711 34.537 34.537 0 0 0-14.283-3zm.842 6.996c3.638.075 7.246.875 10.607 2.37 1.288.574 2.539 1.492 2.399 2.393-.111.583-.436 1.266-2.893 1.274-5.22.24-7.697 1.937-8.826 4.47-1.128 2.535-.082 5.723 2.601 6.918 9.862 4.391 17.423 8.74 22.942 12.684 7.096 5.038 13.29 11.539 11.785 14.922-1.82 4.086-16.978 4.585-43.738-7.328C32.71 65.718 22.938 54.118 24.758 50.03h.002c1.505-3.382 10.477-3.128 18.969-1.226 5.431-5.72 12.366-8.612 19.304-8.864.52-.018 1.041-.022 1.56-.011zM42.447 54.313c-1.457-.026-2.777.562-3.492 1.707-1.205 1.927-.236 4.707 2.164 6.207 2.4 1.499 5.322 1.15 6.526-.778 1.204-1.928.235-4.705-2.165-6.205-.975-.61-2.036-.914-3.033-.931zm19.725 11.226c-1.751-.013-3.3.794-3.94 2.229-.93 2.088.422 4.718 3.02 5.875 2.597 1.156 5.457.4 6.387-1.688.93-2.088-.424-4.717-3.022-5.873a6.143 6.143 0 0 0-2.445-.543zm21.53 7.262c-2.046.014-3.808 1.084-4.298 2.79-.626 2.186 1.07 4.588 3.79 5.368 2.72.78 5.433-.36 6.06-2.545.627-2.185-1.07-4.588-3.79-5.367a6.254 6.254 0 0 0-1.763-.246z"/><path fill="url(#d)" d="M63.752 32.934a34.436 34.436 0 0 0-22.236 8.34c-9.06-1.565-19.78-1.576-23.12 5.925-3.745 8.411 5.438 18.094 18.747 26.512 1.884 8.139 7.43 15.329 15.625 18.977 8.195 3.648 17.253 2.959 24.556-1.084 15.162 4.256 28.501 4.601 32.246-3.811 3.34-7.5-3.841-15.461-11.066-21.148a34.411 34.411 0 0 0-20.469-30.711 34.537 34.537 0 0 0-14.283-3zm.842 6.996c3.638.075 7.246.875 10.607 2.37 1.288.574 2.539 1.492 2.399 2.393-.111.583-.436 1.266-2.893 1.274-5.22.24-7.697 1.937-8.826 4.47-1.128 2.535-.082 5.723 2.601 6.918 9.862 4.391 17.423 8.74 22.942 12.684 7.096 5.038 13.29 11.539 11.785 14.922-1.82 4.086-16.978 4.585-43.738-7.328C32.71 65.718 22.938 54.118 24.758 50.03h.002c1.505-3.382 10.477-3.128 18.969-1.226 5.431-5.72 12.366-8.612 19.304-8.864.52-.018 1.041-.022 1.56-.011zM42.447 54.313c-1.457-.026-2.777.562-3.492 1.707-1.205 1.927-.236 4.707 2.164 6.207 2.4 1.499 5.322 1.15 6.526-.778 1.204-1.928.235-4.705-2.165-6.205-.975-.61-2.036-.914-3.033-.931zm19.725 11.226c-1.751-.013-3.3.794-3.94 2.229-.93 2.088.422 4.718 3.02 5.875 2.597 1.156 5.457.4 6.387-1.688.93-2.088-.424-4.717-3.022-5.873a6.143 6.143 0 0 0-2.445-.543zm21.53 7.262c-2.046.014-3.808 1.084-4.298 2.79-.626 2.186 1.07 4.588 3.79 5.368 2.72.78 5.433-.36 6.06-2.545.627-2.185-1.07-4.588-3.79-5.367a6.254 6.254 0 0 0-1.763-.246z" style="mix-blend-mode:soft-light"/></svg>

```

2024-10-14 15:15 UTC, weh commented on icons/hoppscotch/hoppscotch-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#00d196" d="M63.682 21.176c-11.063.07-21.94 4.019-30.65 11.498-12.49-2.157-27.267-2.171-31.87 8.168C-4 52.437 8.656 65.782 27
Always add a newline in the svg files
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path fill="#00d196" d="M63.682 21.176c-11.063.07-21.94 4.019-30.65 11.498-12.49-2.157-27.267-2.171-31.87 8.168C-4 52.437 8.656 65.782 27 77.387c2.597 11.218 10.243 21.129 21.54 26.158 11.295 5.03 23.784 4.075 33.85-1.498 20.9 5.867 39.285 6.345 44.448-5.25 4.603-10.34-5.294-21.312-15.254-29.15-.433-18.365-11.295-34.801-28.215-42.335a47.604 47.604 0 0 0-19.687-4.136zm-.99 9.662a37.868 37.868 0 0 1 16.77 3.252c1.777.79 3.5 2.057 3.308 3.299-.155.805-.6 1.743-3.987 1.754-7.195.332-10.612 2.668-12.168 6.162-1.555 3.493-.111 7.89 3.588 9.537 13.593 6.052 24.014 12.045 31.621 17.482 9.78 6.944 18.32 15.906 16.244 20.569-2.508 5.633-23.402 6.319-60.289-10.104C20.893 66.366 7.424 50.38 9.932 44.746c2.075-4.662 14.443-4.313 26.148-1.691 7.488-7.884 17.048-11.87 26.611-12.217zM34 50.648c-1.882.051-3.564.857-4.498 2.352-1.66 2.658-.327 6.488 2.98 8.555 3.308 2.067 7.336 1.587 8.997-1.07 1.66-2.658.324-6.488-2.983-8.555-1.447-.905-3.032-1.321-4.496-1.282zm27.504 15.475c-2.414-.017-4.553 1.092-5.434 3.07-1.281 2.878.583 6.504 4.164 8.098 3.581 1.594 7.524.554 8.805-2.324 1.281-2.878-.583-6.504-4.164-8.098a8.467 8.467 0 0 0-3.371-.746zM91.52 76.135c-2.962-.102-5.562 1.394-6.264 3.842-.864 3.012 1.475 6.325 5.224 7.4 3.75 1.075 7.49-.496 8.354-3.508.864-3.012-1.476-6.326-5.225-7.4a8.674 8.674 0 0 0-2.09-.334z"/></svg>

```

2025-01-15 10:36 UTC, weh approved these changes
lgtm :+1:

2025-02-16 05:21 UTC, merged