update icon: illustrator (plain, line)
devicons/devicon pull request #2288
Opened 2024-10-19 20:43 UTC by Anjellyrika

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons)
- [x] PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/wiki/Organizing-SVGs)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/wiki/SVG-Standards)
- [x] A new object is added in the `devicon.json` file at the correct alphabetic position as seen [here](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60)

**This PR closes #1655**

## Link to prove your SVG is correct and up-to-date.
✨ This PR updates the Adobe Illustrator icons in line with Adobe's [brand identity change](https://blog.adobe.com/en/publish/2020/05/28/evolving-our-brand-identity). Also added an 'original' version of the icon that was previously missing, sourced from [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Adobe_Illustrator_CC_icon.svg).

2024-12-23 01:09 UTC, canaleal requested changes
Excellent work on the MR. I just left a few comments.

2024-12-23 01:09 UTC, canaleal commented on icons/illustrator/illustrator-plain.svg
This icon has **2 paths**, but it should only have **1 path**.  

Follow [this tutorial](https://github.com/devicons/devicon/wiki/Creating-plain-Icons#step-5-combine-all-paths) to learn how to combine the paths.

And this tutorial to learn about [optimization](https://github.com/devicons/devicon/wiki/Optimizing-icons).

2024-12-23 01:09 UTC, canaleal commented on icons/illustrator/illustrator-line.svg
This Icon needs to be optimized. 
Follow this tutorial to learn about [optimization](https://github.com/devicons/devicon/wiki/Optimizing-icons).

2024-12-23 08:19 UTC, Anjellyrika commented on icons/illustrator/illustrator-plain.svg
Hi, I believe this is already in one path. There's only one `<path>` element in the SVG file.

My editing program shows this, as well:
![image](https://github.com/user-attachments/assets/c4052d11-06f7-4a8f-8e93-61a7f6ac5f81)

2024-12-23 08:37 UTC, Anjellyrika commented on icons/illustrator/illustrator-plain.svg
Whoops, sorry for the previous reply, that was a mistake 😅
Since the icon is two colors, I don't think it's possible to have them in one path. If I am mistaken, please let me know.

2025-01-15 11:05 UTC, weh approved these changes
Just added empty lines. I think this is ready to merge now. :+1:

2025-02-16 05:09 UTC, canaleal approved these changes

2025-02-16 05:14 UTC, merged