new icon: C3js (original, plain)
devicons/devicon pull request #282
Opened 2020-09-06 20:07 UTC by mjlabe

C3.js icon from PR #136

![c3js-original](https://user-images.githubusercontent.com/28718113/92334357-054f6180-f05b-11ea-8f58-35bcd2c22b57.jpg)

![c3js-plain](https://user-images.githubusercontent.com/28718113/92334366-1dbf7c00-f05b-11ea-8d3d-586b86f20578.jpg)

2020-09-07 10:38 UTC, amacado requested changes
Hello @mjlabe and thanks for your contribution. Looks fine, I would only like to improve the tagging.

2020-09-07 10:38 UTC, amacado commented on devicon.json
> +    "tags": [],
```suggestion
    "tags": ["javascript","chart","library"],
```

2020-09-08 11:54 UTC, mjlabe commented
Done! @amacado

2020-10-12 01:20 UTC, Thomas-Boi commented
Hello there,
Recently, we just introduced an automation pipeline to Devicon which will help us create the icons. Before we can merge your changes in, there are a few things that we need to do first:

1. Merge the current devicon/develop branch into your PR branch. This contains the build script needed for us to build your icons.
2. Read the `CONTRIBUTING.md` for things to do before merging and review our icon standards.
3. Push your changes and/or branches. We will review them once this is done and merge your PR if everything goes well.


Thank you for contributing to this repo. We are sorry that we haven't accept any PR for awhile. Now that we have a build pipeline, we can merge PRs more quickly than before. 

We hope to see your icons in the Devicon repo soon :)

Cheers,
Devicon Team

2021-05-15 23:25 UTC, Thomas-Boi commented
Hi @mjlabe,

I'm working on merging your PR to accept your icon. However, it seems like your branch is a bit out of date. It'd be much appreciated if you can bring the branch up to date with develop and re-push.

After a week, if the branch hasn't been updated I'll make a new PR cherry-picking your commit. This is to ensure you are still the author of the commit and get proper credits. You can also just give me permission to do it this way now.

It'd be quicker if you update the branch yourself though but whichever works 👍.

You got quite a few icons 😄

2021-05-24 22:46 UTC, Thomas-Boi commented
Hi @mjlabe, I am unable to find the the official C3.js logo that matches the one you provided. In fact, it looks like your C3.js logo is similar to the D3.js logo but with the D flipped. Here's the [logo](https://avatars1.githubusercontent.com/u/9966497?s=280&v=4) that I found, which was from [this page](https://c3js.org/)

If you can provide any proof that your logo is the correct one, we'll accept your icon. Until then, we will have to close this PR.

2021-05-24 22:46 UTC, closed without merging