Added Appwrite icon
devicons/devicon pull request #371
Opened 2020-12-02 23:42 UTC by eldadfux

I've added the original, plain, original-wormark, and plain-wordmark icons for https://appwrite.io/. Give it a check and let me know if there's something I should change.

2020-12-12 14:45 UTC, amacado requested changes
Icons looking good! :) Thanks for the contribution. Could you merge the devicon.json with our latest version? :)

2020-12-12 21:16 UTC, eldadfux commented
Merged :)

2020-12-12 23:05 UTC, amacado requested changes
Icons looking good, but we do not them them twice in the set, see my code suggestions 😄 

![new_icons](https://user-images.githubusercontent.com/8781699/101998813-d50d0400-3cd6-11eb-9cd0-209125d38134.png)

2020-12-12 23:05 UTC, amacado commented on devicon.json
> +        }
Adding the `color` for colored versions and aliases to not have the same icon twice in the font (only in css).

```suggestion
        },
        "color": "#f02e65",
        "aliases": [
            {
                "base": "plain",
                "alias": "original"
            },
            {
                "base": "plain-wordmark",
                "alias": "original-wordmark"
            }
        ]
```

2021-01-06 01:04 UTC, Thomas-Boi commented
Hello there,

We notice that this PR has been inactive for awhile now. It would be a waste of your time and effort if we just close this PR and throw away the SVGs in here. Thus, 1 month from now, if this PR remains inactive/stale, we will fork your repo, fix any issues, and merge your icons ourselves.

Since GitHub tracks contributions by commits, you will still be credited. We also hope that you will help us merge this PR before the deadline comes.

Cheers,
Devicon Team

2021-01-07 10:25 UTC, eldadfux commented
So sorry for the delays, its been a hectic few weeks. I will set myself a reminder to try and finish in in the next couple of weeks!

2021-01-07 17:49 UTC, Thomas-Boi commented
Thank you for picking up this PR again! Just take your time and we really appreciate it 😄

2021-01-14 07:09 UTC, eldadfux commented
Seems like I just needed to accept all the code suggestions? @amacado let me know if I missed something...

2021-01-19 09:45 UTC, amacado approved these changes
Sorry for the delay, been a little busy. Thanks for the update @eldadfux. appwrite.io will be in the upcomming devicon release! :)

2021-01-19 09:46 UTC, merged

2021-01-19 09:47 UTC, eldadfux commented
Ohh this is awesome, we're so gonna tweet about it 🤟

2021-01-20 11:44 UTC, eldadfux commented
Thanks guys!

![image](https://user-images.githubusercontent.com/1297371/105170470-a54aea80-5b25-11eb-9c8c-83ccc6d6586f.png)