Add new icon Bash (Original, Plain), Closes #303
devicons/devicon pull request #415
Opened 2020-12-30 14:41 UTC by EnisMulic

I took the bash SVG from #170 and cleaned it up in so it doesn't use inline styles, not sure if I did this correctly.

2020-12-30 15:38 UTC, amacado commented
Related issue: https://github.com/devicons/devicon/issues/303

2020-12-30 15:41 UTC, amacado requested changes

2020-12-30 15:41 UTC, amacado commented on devicon.json
> +            "font": []
We need a font version of the icon to fulfill our https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md guidelines.

2020-12-30 15:41 UTC, amacado commented on icons/bash/bash-original.svg
> +<!-- Generator: Adobe Illustrator 23.0.3, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
This comment is not required and should be removed.

2020-12-30 23:56 UTC, Thomas-Boi commented
Hi @EnisMulic  ,

Unfortunately, we are running into some issues checking your SVGs. It seems that your forked repo is from an older version of our master branch. In order for us to check your icons, please pull our latest commit from our develop to your fork.

You might find this link useful to update your repo.

Cheers,
Thomas

2020-12-31 20:04 UTC, Thomas-Boi requested changes

2020-12-31 20:04 UTC, Thomas-Boi commented on devicon.json
> +    {
It seems that there are two entries for `bash` in the `devicon.json`. Can you please remove one of them please?

2021-01-01 08:20 UTC, EnisMulic commented
Any tips to fix this upload issue, it seems to work fine when I do it manually 
![image](https://user-images.githubusercontent.com/17247763/103435692-9ce04d80-4c12-11eb-8ef0-e4724f4fdd91.png)

2021-01-01 08:28 UTC, Thomas-Boi commented
Hello @EnisMulic ,

Sorry for the long wait. It seems that we ran into a very peculiar error that we never see before. As you might know, our repo use [icomoon](https://icomoon.io/) to create our icons. This is a browser and not an API, which means that we have to be precise in choosing which element to click etc...

Normally, when we upload icons, we would remove its colors entirely using Icomoon. This is available here:
![image](https://user-images.githubusercontent.com/43018778/103435695-3a159480-4bc7-11eb-8bbf-fcc7fba8cac1.png)

When we upload your icon, we see this instead:
![image](https://user-images.githubusercontent.com/43018778/103435688-0c305000-4bc7-11eb-8688-b9c97c76d0c7.png)

This has never happened before so our script didn't know how to handle it. In fact, I would not be surprised if the Icomoon team just upload a new version of their app which might have cause this to happen.

![image](https://user-images.githubusercontent.com/43018778/103435706-67624280-4bc7-11eb-97b8-c5c32d33ad6f.png)

Any how, I had to clone your repo and test it locally to fix this issue. I have also seen your icon and it looks great to me. Thus, if you want, we can accept your PR right now. @amacado what do you think? I will open another PR that contain the fix for this issue.

2021-01-01 13:49 UTC, amacado approved these changes

2021-01-01 13:50 UTC, merged

2021-01-01 19:45 UTC, Thomas-Boi commented
@EnisMulic congratulation, you are our first PR for 2021. Happy New Year and thanks for your work.