new icon: googlecloud (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #428
Opened 2021-01-02 13:29 UTC by EnisMulic

Taken from #170

2021-01-03 03:48 UTC, amacado commented
Hi @EnisMulic! Nice to see you have decided to pick up some old pull requests and fix them. We are currently investigating some issues regarding our `bot:peek` command (https://github.com/devicons/devicon/issues/414) so it can take some time until the review. Sorry for that.

2021-01-03 07:15 UTC, EnisMulic commented
That's fine, I still have a few icons from this PR to fix up.

2021-01-04 10:12 UTC, amacado requested changes
@EnisMulic Thanks for your contribution!

In the font versions (plain and workmark) of the svg you can see "cutting lines" which does not look like they are intended. 

![image](https://user-images.githubusercontent.com/8781699/103524242-82f67300-4e7d-11eb-8988-b2109f557d84.png)

Here are the `bot:peek` results as font preview:

![new_icons](https://user-images.githubusercontent.com/8781699/103524340-ae795d80-4e7d-11eb-84c8-dde6365899ff.png)
![screenshot_0](https://user-images.githubusercontent.com/8781699/103524342-afaa8a80-4e7d-11eb-9e97-9ba42e6452a8.png)
![screenshot_1](https://user-images.githubusercontent.com/8781699/103524344-b0dbb780-4e7d-11eb-936f-d3e76c36c969.png)

2021-01-04 10:12 UTC, amacado commented on icons/googlecloud/googlecloud-plain.svg
> +	 viewBox="0 0 128 128" style="enable-background:new 0 0 128 128;" xml:space="preserve">
```suggestion
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 viewBox="0 0 128 128" xml:space="preserve">
```

2021-01-04 10:12 UTC, amacado commented on icons/googlecloud/googlecloud-plain-wordmark.svg
> +	 viewBox="0 0 128 128" style="enable-background:new 0 0 128 128;" xml:space="preserve">
```suggestion
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	 viewBox="0 0 128 128" xml:space="preserve">
```

2021-01-04 10:12 UTC, amacado commented on icons/googlecloud/googlecloud-original-wordmark.svg
> +	 viewBox="0 0 128 128" style="enable-background:new 0 0 128 128;" xml:space="preserve">
```suggestion
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 viewBox="0 0 128 128" xml:space="preserve">
```

2021-01-04 10:12 UTC, amacado commented on icons/googlecloud/googlecloud-original.svg
> +	 viewBox="0 0 128 128" style="enable-background:new 0 0 128 128;" xml:space="preserve">
```suggestion
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 viewBox="0 0 128 128" xml:space="preserve">
```

2021-01-05 00:19 UTC, Thomas-Boi commented
Hello there,

Here are the icon build results:
![new_icons](https://user-images.githubusercontent.com/43018778/103592385-c9f95e00-4ea7-11eb-9b07-db361bb2ce0c.png)

![screenshot_0](https://user-images.githubusercontent.com/43018778/103592386-ca91f480-4ea7-11eb-988e-e4afd4e82333.png)

![screenshot_1](https://user-images.githubusercontent.com/43018778/103592387-ca91f480-4ea7-11eb-9f73-37197ebaed4d.png)

While the cut off lines have been fixed, I couldn't help but notice that the `plain-wordmark` icon looks like it's shifted upwards and it's different from before. I think it looks better before so is this change intentional? 

Besides that, everything looks great. If the change above is intentional, I can accept your PR. However, I think it would better centered.

2021-01-05 06:18 UTC, EnisMulic commented
When I took a closer look the previous icons looked terrible when you would zoom in closer as the parts that it was made out of obviously looked detached and not aligned, so I replaces everything entirely. As for the shift, It's caused by setting the viewBox to 0 0 128 128 so I left it like that as I didn't know how to fix that and the guidelines say that should be the specified settings.

2021-01-05 10:43 UTC, amacado requested changes
@EnisMulic thanks for updating. The `0 0 128 128` requirement for the icons was developed to have all icons in the same view box which helps when making global changes. 
The off-centering does not look good and should be fixed before adding this icon to to project.

2021-01-05 16:18 UTC, amacado requested changes
Still a slight left/right margin difference (for original and plain), but much better!

![image](https://user-images.githubusercontent.com/8781699/103670519-f4b3e700-4f79-11eb-9fff-ca109322772b.png)

2021-01-05 19:00 UTC, amacado commented
@EnisMulic could you please request a review once you're done? So we don't have to check every commit.. :)

2021-01-05 19:49 UTC, amacado approved these changes
📦 and will be in the next release. Thanks @EnisMulic for the work! :) well done.

2021-01-05 19:49 UTC, merged