New icon: arduino (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #532
Opened 2021-03-17 07:21 UTC by EnisMulic

2021-03-17 18:03 UTC, Panquesito7 requested changes
In the [Wikipedia](https://en.wikipedia.org/wiki/Arduino) page for [Arduino](https://www.arduino.cc), the logo has the `TM` text on the corner right, but in your icon, it says `R`. I guess it should be `TM`.

2021-03-17 18:34 UTC, EnisMulic commented on devicon.json
> +                "original-wordmark",
I've found multiple examples where `original` is used as the font version
![image](https://user-images.githubusercontent.com/17247763/111519691-a5e3b400-8757-11eb-9e32-67a5cc9870df.png)

2021-03-23 19:07 UTC, maltejur commented
The icon should probably be centered

2021-04-01 20:35 UTC, Panquesito7 commented
@EnisMulic, is this PR ready for review now? I think you marked it as "Draft" accidentally. Thank you anyways. 🙂

2021-04-02 05:15 UTC, EnisMulic commented
@Panquesito7 Sorry, I still haven't aligned the icons

2021-04-09 23:05 UTC, Panquesito7 requested changes

2021-04-09 23:05 UTC, Panquesito7 commented on icons/arduino/arduino-original-wordmark.svg
> +</svg>
The SVG can be optimized using the [SVG Viewer](https://www.svgviewer.dev/).
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128"><g fill="#00979C"><path style="stroke:none;fill-rule:evenodd;fill-opacity:1" d="M.316 55.504v-9.555c.223-.125.164-.355.207-.547C3.531 32.316 11.734 24.45 24.668 21.31c1.133-.274 2.32-.247 3.422-.653h6.37c.145.274.415.164.63.188 6.422.687 12.203 2.957 17.316 6.914 4.364 3.37 7.84 7.547 10.938 12.058.383.559.566.575.953.004 1.773-2.61 3.707-5.097 5.86-7.41 5.35-5.738 11.706-9.695 19.511-11.144 1.172-.22 2.383-.207 3.52-.61h6.19c.13.23.36.157.556.18 1.843.207 3.664.547 5.453 1.062 13.449 3.864 22.933 16.184 22.136 30.133-.668 11.645-6.562 20.032-16.78 25.418-5.157 2.719-10.75 3.489-16.524 3.375-7.625-.148-14.254-2.77-19.969-7.773-3.965-3.469-7.082-7.64-9.945-12.016-.426-.652-.59-.57-.973.02-1.812 2.789-3.758 5.492-5.96 8-3.868 4.406-8.337 8-13.93 9.96-6.915 2.422-13.965 2.516-20.954.54C12.414 76.707 5.468 70.3 1.723 60.48c-.618-1.617-.875-3.335-1.407-4.976zm31.79 14.684c5.734.238 10.62-1.688 14.765-5.543 4.324-4.024 7.383-9.004 10.488-13.946.188-.297.13-.531-.05-.808-2.645-4.121-5.356-8.203-8.934-11.602-6.883-6.543-14.992-8.742-24.04-5.852C16.778 34.855 12 40.234 10.884 48.22c-1.043 7.445 1.855 13.457 7.812 17.941 3.965 2.988 8.532 4.164 13.41 4.028zm63.347 0c2.246.058 4.457-.09 6.59-.731 7.82-2.332 13.105-7.293 14.578-15.43 1.469-8.105-1.668-14.593-8.39-19.226-7.493-5.168-18.415-4.66-26.055 1.023-5.074 3.774-8.524 8.91-11.875 14.133-.196.3-.145.531.027.805 2.688 4.3 5.379 8.597 8.863 12.324 4.407 4.715 9.704 7.394 16.262 7.102zm32.227 29.007c-.297.942-.535 1.903-.895 2.82-2.234 5.68-10.222 7.204-14.055 2.684-1.304-1.539-1.878-3.386-2.097-5.347-.305-2.743-.297-5.465.734-8.098 1.457-3.695 4.61-5.613 8.754-5.3 3.777.284 6.29 2.538 7.188 6.433.117.5.058 1.047.37 1.5zm-12.618-2.61c.004 1.509.086 3.009.622 4.438.406 1.106 1.086 1.942 2.293 2.254 2.156.559 3.925-.328 4.582-2.472.843-2.77.804-5.59.007-8.364-.515-1.808-1.605-2.601-3.316-2.632-1.828-.036-2.96.746-3.617 2.507-.512 1.38-.563 2.825-.57 4.27zm-17.753-3.14v12.278c0 1.21 0 1.21-1.254 1.21-.618 0-1.239-.042-1.856.012-.691.063-.906-.18-.898-.882.031-3.626.015-7.25.015-10.876 0-2.71.02-5.421-.011-8.132-.008-.618.168-.817.789-.793 1.207.047 2.418.05 3.625-.004.601-.024.883.191 1.125.719 1.886 4.09 3.8 8.164 5.71 12.242.048.097.114.191.31.515V98.68c0-3.86.015-7.72-.016-11.578-.004-.649.144-.891.824-.84.851.062 1.707.035 2.562.008.48-.02.672.117.672.636a4570.62 4570.62 0 0 0 0 19.364c0 .488-.144.68-.652.671a90.154 90.154 0 0 0-3.98.004c-.544.016-.684-.316-.864-.703a3437.438 3437.438 0 0 0-5.64-12.176c-.094-.199-.106-.464-.461-.62zm-65.496 3.7c1.515 1.218 2.117 2.906 2.914 4.472.77 1.52 1.5 3.063 2.273 4.582.262.52.313.774-.426.746a58.648 58.648 0 0 0-3.707 0c-.5.016-.722-.191-.914-.625-.863-1.965-1.765-3.914-2.648-5.87-.485-1.075-1.254-1.731-2.461-1.9-.715-.097-.903.13-.89.837.042 2.238-.009 4.476.03 6.715.012.656-.16.886-.832.847-.941-.058-1.886-.035-2.828-.008-.5.012-.746-.101-.746-.675.02-6.454.012-12.903.016-19.356 0-.281-.074-.644.39-.629 3.145.102 6.313-.332 9.426.367 4.277.961 4.817 4.575 4.047 7.247-.504 1.753-1.86 2.71-3.645 3.25zm-5.84-4.711v2.207c0 .242-.008.492.34.492 1.203.012 2.421.097 3.539-.496 1.011-.54 1.43-1.426 1.28-2.664-.12-1.012-.679-1.641-1.804-1.895a9.13 9.13 0 0 0-1.926-.223c-1.77-.02-1.386-.164-1.43 1.344-.011.41 0 .824 0 1.235zm13.015 4.148c0-3.125.02-6.246-.015-9.371-.008-.703.136-.984.91-.95 2.5.102 5.012-.156 7.504.15 4.734.581 7.175 3.054 7.707 7.85.261 2.329.176 4.653-.66 6.891-1.317 3.512-4.067 5.13-7.602 5.618-2.398.328-4.824.117-7.242.171-.649.016-.602-.386-.602-.812v-9.547zm4.348-.016v4.766c0 2.04 0 2.04 2.078 1.953 2.578-.11 4.223-1.433 4.832-3.953.488-2.008.438-4.031-.062-6.027-.5-1.985-1.813-3.094-3.864-3.325-.726-.082-1.468-.054-2.199-.12-.621-.06-.809.18-.797.796.035 1.969.012 3.942.012 5.91zm-25.84 10.375c-2.367 0-2.367 0-3.004-2.238-.508-1.781-.508-1.781-2.363-1.781-1.477 0-2.95.027-4.422-.012-.547-.015-.777.168-.906.692-.223.914-.563 1.8-.785 2.714-.125.508-.383.649-.871.633a40.27 40.27 0 0 0-2.915 0c-.66.028-.722-.183-.542-.77 1.472-4.75 2.917-9.507 4.37-14.265.5-1.629 1.024-3.254 1.493-4.894.148-.528.351-.774.949-.754 1.504.046 3.008.03 4.508.007.46-.007.664.141.8.594a5006.596 5006.596 0 0 0 5.93 19.324c.176.57.09.813-.562.758-.555-.047-1.117-.008-1.68-.008zm-6.867-15.66-.184.012c-.777 2.672-1.558 5.34-2.336 8.012.137.039.192.07.25.07.942.008 1.883.016 2.825.016 1.804.004 1.808 0 1.312-1.7-.621-2.136-1.246-4.277-1.867-6.41zm46.445 2.684c0-2.328.012-4.656-.011-6.988-.004-.516.12-.739.683-.711.973.043 1.95.05 2.918-.004.652-.035.777.23.773.816-.019 3.922-.011 7.844-.003 11.766 0 .676.02 1.355.09 2.027.187 1.848 1.28 2.781 3.288 2.84 2.012.062 3.149-.809 3.422-2.672a14.01 14.01 0 0 0 .141-2.023c.016-3.922.023-7.844-.012-11.762-.004-.738.125-1.07.953-.996.907.082 1.829.039 2.739.012.48-.016.683.113.68.632-.032 4.48.046 8.965-.083 13.442-.109 3.89-2.644 6.41-6.543 6.844-1.664.187-3.3.093-4.89-.434-2.551-.852-4.008-2.902-4.106-5.895-.07-2.296-.011-4.597-.011-6.894zm25.895-7.688c2.035 0 4.066.02 6.101-.015.575-.008.785.16.746.746a17.403 17.403 0 0 0 0 2.117c.036.563-.191.707-.714.691-1.063-.035-2.122.008-3.184-.02-.496-.015-.734.083-.734.665.023 4.066.02 8.133.004 12.2-.004.542.167.726.707.706 1.058-.027 2.12.024 3.18-.02.6-.019.769.212.741.774-.039.734-.03 1.473-.004 2.207.02.473-.175.61-.62.61-4.126-.012-8.25-.012-12.38 0-.492.003-.69-.153-.671-.657a27.82 27.82 0 0 0-.004-2.21c-.024-.532.152-.735.703-.72 1.09.032 2.18-.007 3.27.012.5.012.66-.175.656-.672-.012-4.093-.012-8.191 0-12.289 0-.46-.164-.613-.618-.605-1.09.023-2.183-.024-3.27.02-.597.023-.788-.196-.737-.762.086-.899-.375-2.043.199-2.633.5-.512 1.625-.129 2.476-.145 1.38-.015 2.77 0 4.153 0zm41.883-61.8c-.133.199-.18.265-.223.332-.242.363-.055 1.097-.664 1.086-.54-.012-.403-.684-.594-1.051-.05-.098-.11-.188-.277-.461 0 .504.008.789 0 1.078-.008.195.035.441-.274.457-.312.016-.293-.234-.297-.43-.007-.68-.007-1.355-.003-2.031 0-.23-.036-.496.324-.504.27-.004.504-.015.617.336.144.43.195.91.527 1.324.317-.402.371-.867.492-1.293.102-.347.317-.37.598-.37.356.003.34.253.344.488.004.68.004 1.355-.004 2.035-.004.191.023.445-.281.449-.305 0-.282-.242-.285-.442-.008-.289 0-.574 0-1.003zm-3.712-1.532c.087 0 .18-.015.262 0 .325.063.828-.187.934.2.144.543-.426.27-.668.386-.242.117-.195.332-.2.528-.011.468-.007.937-.007 1.406 0 .258-.05.473-.383.46-.305-.01-.293-.234-.293-.437a36.975 36.975 0 0 1-.004-1.316c.012-.375.016-.727-.523-.676-.188.016-.352-.039-.352-.277 0-.328.254-.262.442-.27.265-.012.527-.004.793-.004zm0 0"/><path style="stroke:none;fill-rule:evenodd;fill-opacity:1" d="M31.977 47.543c3.238 0 6.48.023 9.718-.02.758-.011.953.223.907.942a19.358 19.358 0 0 0 0 2.734c.054.758-.149 1.004-.954.996-4.3-.043-8.601-.023-12.898-.023-2.18 0-4.36-.031-6.535.02-.762.019-.957-.235-.914-.95.058-.937.05-1.887 0-2.828-.035-.676.16-.898.87-.89 3.267.042 6.54.019 9.806.019zm63.039-6.414c.765 0 1.535.023 2.3-.008.5-.02.66.156.653.66-.028 1.414.02 2.828-.024 4.242-.023.641.133.875.82.848 1.383-.055 2.77.004 4.153-.023.535-.012.812.093.797.715a112.75 112.75 0 0 0-.004 4.597c.012.555-.2.7-.727.692-1.414-.032-2.828.015-4.242-.024-.601-.02-.82.133-.8.774.046 1.414-.008 2.828.027 4.242.015.593-.13.836-.774.816a91.282 91.282 0 0 0-4.507-.004c-.583.016-.762-.172-.747-.754.04-1.472-.007-2.945.024-4.418.008-.5-.145-.664-.649-.652-1.414.027-2.832-.031-4.242.027-.726.028-.894-.234-.879-.906.043-1.383.067-2.77-.004-4.152-.043-.817.262-.992 1.012-.961 1.356.058 2.711-.008 4.067.027.539.016.71-.148.695-.699-.035-1.41.015-2.828-.024-4.242-.015-.598.133-.852.774-.809.765.051 1.531.012 2.3.012zm0 0"/></g></svg>

```

2021-04-09 23:05 UTC, Panquesito7 commented on icons/arduino/arduino-original.svg
> +</svg>
The SVG can be optimized using the [SVG Viewer](https://www.svgviewer.dev/).
By the way: this icon is missing the `TM` on the corner.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128"><g fill="#00979c"><path style="fill-rule:evenodd;stroke:none;fill-opacity:1" d="M.3 66.5v-9.6c.2-.1.2-.3.2-.5 3-13.1 11.2-21 24.2-24.1 1.1-.3 2.3-.2 3.4-.6h6.4c.1.2.4.1.6.1 6.4.7 12.2 3 17.3 7 4.4 3.3 7.8 7.5 10.9 12 .4.6.6.6 1 0 1.8-2.6 3.7-5.1 5.9-7.4 5.3-5.7 11.7-9.7 19.5-11.1 1.1-.3 2.4-.2 3.5-.6h6.2c.1.2.3.1.5.1 1.9.2 3.7.6 5.5 1.1 13.4 3.9 22.9 16.2 22.1 30.1-.6 11.7-6.5 20.1-16.8 25.4-5.1 2.8-10.7 3.5-16.5 3.4-7.6-.1-14.2-2.7-19.9-7.7-4-3.5-7.1-7.7-10-12.1-.4-.6-.6-.5-1 .1-1.8 2.7-3.7 5.4-5.9 8-3.9 4.4-8.4 8-14 9.9-6.9 2.4-13.9 2.5-20.9.6-10.1-2.9-17-9.3-20.8-19.1-.6-1.6-.9-3.4-1.4-5zm31.8 14.7c5.7.2 10.6-1.7 14.8-5.6 4.3-4 7.4-9 10.5-13.9.1-.3.1-.5-.1-.8-2.6-4.1-5.3-8.2-8.9-11.6-6.9-6.6-15-8.8-24.1-5.9-7.5 2.5-12.3 7.8-13.4 15.8-1.1 7.5 1.8 13.5 7.8 18 4 2.9 8.5 4.1 13.4 4zm63.4 0c2.2 0 4.4-.1 6.5-.7 7.9-2.4 13.1-7.3 14.6-15.5 1.5-8.1-1.6-14.6-8.4-19.2-7.5-5.2-18.4-4.7-26 1-5.1 3.8-8.5 8.9-11.9 14.2-.2.3-.1.5 0 .8 2.7 4.3 5.4 8.6 8.9 12.3 4.4 4.7 9.7 7.4 16.3 7.1zm0 0"/><path style="fill-rule:evenodd;stroke:none;fill-opacity:1" d="M32 58.5c3.2 0 6.5.1 9.7 0 .8 0 .9.2.9 1-.1.9-.1 1.8 0 2.7.1.8-.1 1-1 1H28.8c-2.2 0-4.4-.1-6.6 0-.7 0-.9-.2-.9-1 .1-.9.1-1.8 0-2.8 0-.7.2-.9.9-.9 3.2.1 6.5 0 9.8 0zm63-6.4c.8 0 1.6.1 2.3 0 .5 0 .7.2.7.7-.1 1.4 0 2.8-.1 4.2 0 .7.2.9.9.9 1.3-.1 2.7 0 4.1-.1.6 0 .8.1.8.8v4.6c0 .5-.2.7-.7.7-1.4-.1-2.8 0-4.3-.1-.6 0-.8.2-.8.8.1 1.4 0 2.8.1 4.2 0 .6-.2.9-.8.9-1.5-.1-3-.1-4.5 0-.6 0-.8-.2-.8-.8.1-1.5 0-2.9.1-4.4 0-.5-.2-.7-.7-.7-1.4.1-2.8 0-4.2.1-.8 0-.9-.3-.9-.9 0-1.4.1-2.8 0-4.2-.1-.8.3-1 1-1 1.4.1 2.7 0 4.1.1.5 0 .7-.2.7-.7-.1-1.4 0-2.9-.1-4.3 0-.6.2-.8.8-.8.8.1 1.5 0 2.3 0zm0 0"/></g></svg>

```

2021-04-09 23:05 UTC, Panquesito7 commented on icons/arduino/arduino-plain-wordmark.svg
> +</svg>
The SVG can be optimized using the [SVG Viewer](https://www.svgviewer.dev/).
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128"><path style="stroke:none;fill-rule:evenodd;fill-opacity:1" d="M.316 55.504v-9.555c.223-.125.164-.355.207-.547C3.531 32.316 11.734 24.45 24.668 21.31c1.133-.274 2.32-.247 3.422-.653h6.37c.145.274.415.164.63.188 6.422.687 12.203 2.957 17.316 6.914 4.364 3.37 7.84 7.547 10.938 12.058.383.559.566.575.953.004 1.773-2.61 3.707-5.097 5.86-7.41 5.35-5.738 11.706-9.695 19.511-11.144 1.172-.22 2.383-.207 3.52-.61h6.19c.13.23.36.157.556.18 1.843.207 3.664.547 5.453 1.062 13.449 3.864 22.933 16.184 22.136 30.133-.668 11.645-6.562 20.032-16.78 25.418-5.157 2.719-10.75 3.489-16.524 3.375-7.625-.148-14.254-2.77-19.969-7.773-3.965-3.469-7.082-7.64-9.945-12.016-.426-.652-.59-.57-.973.02-1.812 2.789-3.758 5.492-5.96 8-3.868 4.406-8.337 8-13.93 9.96-6.915 2.422-13.965 2.516-20.954.54C12.414 76.707 5.468 70.3 1.723 60.48c-.618-1.617-.875-3.335-1.407-4.976zm31.79 14.684c5.734.238 10.62-1.688 14.765-5.543 4.324-4.024 7.383-9.004 10.488-13.946.188-.297.13-.531-.05-.808-2.645-4.121-5.356-8.203-8.934-11.602-6.883-6.543-14.992-8.742-24.04-5.852C16.778 34.855 12 40.234 10.884 48.22c-1.043 7.445 1.855 13.457 7.812 17.941 3.965 2.988 8.532 4.164 13.41 4.028zm63.347 0c2.246.058 4.457-.09 6.59-.731 7.82-2.332 13.105-7.293 14.578-15.43 1.469-8.105-1.668-14.593-8.39-19.226-7.493-5.168-18.415-4.66-26.055 1.023-5.074 3.774-8.524 8.91-11.875 14.133-.196.3-.145.531.027.805 2.688 4.3 5.379 8.597 8.863 12.324 4.407 4.715 9.704 7.394 16.262 7.102zm32.227 29.007c-.297.942-.535 1.903-.895 2.82-2.234 5.68-10.222 7.204-14.055 2.684-1.304-1.539-1.878-3.386-2.097-5.347-.305-2.743-.297-5.465.734-8.098 1.457-3.695 4.61-5.613 8.754-5.3 3.777.284 6.29 2.538 7.188 6.433.117.5.058 1.047.37 1.5zm-12.618-2.61c.004 1.509.086 3.009.622 4.438.406 1.106 1.086 1.942 2.293 2.254 2.156.559 3.925-.328 4.582-2.472.843-2.77.804-5.59.007-8.364-.515-1.808-1.605-2.601-3.316-2.632-1.828-.036-2.96.746-3.617 2.507-.512 1.38-.563 2.825-.57 4.27zm-17.753-3.14v12.278c0 1.21 0 1.21-1.254 1.21-.618 0-1.239-.042-1.856.012-.691.063-.906-.18-.898-.882.031-3.626.015-7.25.015-10.876 0-2.71.02-5.421-.011-8.132-.008-.618.168-.817.789-.793 1.207.047 2.418.05 3.625-.004.601-.024.883.191 1.125.719 1.886 4.09 3.8 8.164 5.71 12.242.048.097.114.191.31.515V98.68c0-3.86.015-7.72-.016-11.578-.004-.649.144-.891.824-.84.851.062 1.707.035 2.562.008.48-.02.672.117.672.636a4570.62 4570.62 0 0 0 0 19.364c0 .488-.144.68-.652.671a90.154 90.154 0 0 0-3.98.004c-.544.016-.684-.316-.864-.703a3437.438 3437.438 0 0 0-5.64-12.176c-.094-.199-.106-.464-.461-.62zm-65.496 3.7c1.515 1.218 2.117 2.906 2.914 4.472.77 1.52 1.5 3.063 2.273 4.582.262.52.313.774-.426.746a58.648 58.648 0 0 0-3.707 0c-.5.016-.722-.191-.914-.625-.863-1.965-1.765-3.914-2.648-5.87-.485-1.075-1.254-1.731-2.461-1.9-.715-.097-.903.13-.89.837.042 2.238-.009 4.476.03 6.715.012.656-.16.886-.832.847-.941-.058-1.886-.035-2.828-.008-.5.012-.746-.101-.746-.675.02-6.454.012-12.903.016-19.356 0-.281-.074-.644.39-.629 3.145.102 6.313-.332 9.426.367 4.277.961 4.817 4.575 4.047 7.247-.504 1.753-1.86 2.71-3.645 3.25zm-5.84-4.711v2.207c0 .242-.008.492.34.492 1.203.012 2.421.097 3.539-.496 1.011-.54 1.43-1.426 1.28-2.664-.12-1.012-.679-1.641-1.804-1.895a9.13 9.13 0 0 0-1.926-.223c-1.77-.02-1.386-.164-1.43 1.344-.011.41 0 .824 0 1.235zm13.015 4.148c0-3.125.02-6.246-.015-9.371-.008-.703.136-.984.91-.95 2.5.102 5.012-.156 7.504.15 4.734.581 7.175 3.054 7.707 7.85.261 2.329.176 4.653-.66 6.891-1.317 3.512-4.067 5.13-7.602 5.618-2.398.328-4.824.117-7.242.171-.649.016-.602-.386-.602-.812v-9.547zm4.348-.016v4.766c0 2.04 0 2.04 2.078 1.953 2.578-.11 4.223-1.433 4.832-3.953.488-2.008.438-4.031-.062-6.027-.5-1.985-1.813-3.094-3.864-3.325-.726-.082-1.468-.054-2.199-.12-.621-.06-.809.18-.797.796.035 1.969.012 3.942.012 5.91zm-25.84 10.375c-2.367 0-2.367 0-3.004-2.238-.508-1.781-.508-1.781-2.363-1.781-1.477 0-2.95.027-4.422-.012-.547-.015-.777.168-.906.692-.223.914-.563 1.8-.785 2.714-.125.508-.383.649-.871.633a40.27 40.27 0 0 0-2.915 0c-.66.028-.722-.183-.542-.77 1.472-4.75 2.917-9.507 4.37-14.265.5-1.629 1.024-3.254 1.493-4.894.148-.528.351-.774.949-.754 1.504.046 3.008.03 4.508.007.46-.007.664.141.8.594a5006.596 5006.596 0 0 0 5.93 19.324c.176.57.09.813-.562.758-.555-.047-1.117-.008-1.68-.008zm-6.867-15.66-.184.012c-.777 2.672-1.558 5.34-2.336 8.012.137.039.192.07.25.07.942.008 1.883.016 2.825.016 1.804.004 1.808 0 1.312-1.7-.621-2.136-1.246-4.277-1.867-6.41zm46.445 2.684c0-2.328.012-4.656-.011-6.988-.004-.516.12-.739.683-.711.973.043 1.95.05 2.918-.004.652-.035.777.23.773.816-.019 3.922-.011 7.844-.003 11.766 0 .676.02 1.355.09 2.027.187 1.848 1.28 2.781 3.288 2.84 2.012.062 3.149-.809 3.422-2.672a14.01 14.01 0 0 0 .141-2.023c.016-3.922.023-7.844-.012-11.762-.004-.738.125-1.07.953-.996.907.082 1.829.039 2.739.012.48-.016.683.113.68.632-.032 4.48.046 8.965-.083 13.442-.109 3.89-2.644 6.41-6.543 6.844-1.664.187-3.3.093-4.89-.434-2.551-.852-4.008-2.902-4.106-5.895-.07-2.296-.011-4.597-.011-6.894zm25.895-7.688c2.035 0 4.066.02 6.101-.015.575-.008.785.16.746.746a17.403 17.403 0 0 0 0 2.117c.036.563-.191.707-.714.691-1.063-.035-2.122.008-3.184-.02-.496-.015-.734.083-.734.665.023 4.066.02 8.133.004 12.2-.004.542.167.726.707.706 1.058-.027 2.12.024 3.18-.02.6-.019.769.212.741.774-.039.734-.03 1.473-.004 2.207.02.473-.175.61-.62.61-4.126-.012-8.25-.012-12.38 0-.492.003-.69-.153-.671-.657a27.82 27.82 0 0 0-.004-2.21c-.024-.532.152-.735.703-.72 1.09.032 2.18-.007 3.27.012.5.012.66-.175.656-.672-.012-4.093-.012-8.191 0-12.289 0-.46-.164-.613-.618-.605-1.09.023-2.183-.024-3.27.02-.597.023-.788-.196-.737-.762.086-.899-.375-2.043.199-2.633.5-.512 1.625-.129 2.476-.145 1.38-.015 2.77 0 4.153 0zm41.883-61.8c-.133.199-.18.265-.223.332-.242.363-.055 1.097-.664 1.086-.54-.012-.403-.684-.594-1.051-.05-.098-.11-.188-.277-.461 0 .504.008.789 0 1.078-.008.195.035.441-.274.457-.312.016-.293-.234-.297-.43-.007-.68-.007-1.355-.003-2.031 0-.23-.036-.496.324-.504.27-.004.504-.015.617.336.144.43.195.91.527 1.324.317-.402.371-.867.492-1.293.102-.347.317-.37.598-.37.356.003.34.253.344.488.004.68.004 1.355-.004 2.035-.004.191.023.445-.281.449-.305 0-.282-.242-.285-.442-.008-.289 0-.574 0-1.003zm-3.712-1.532c.087 0 .18-.015.262 0 .325.063.828-.187.934.2.144.543-.426.27-.668.386-.242.117-.195.332-.2.528-.011.468-.007.937-.007 1.406 0 .258-.05.473-.383.46-.305-.01-.293-.234-.293-.437a36.975 36.975 0 0 1-.004-1.316c.012-.375.016-.727-.523-.676-.188.016-.352-.039-.352-.277 0-.328.254-.262.442-.27.265-.012.527-.004.793-.004zm0 0"/><path style="stroke:none;fill-rule:evenodd;fill-opacity:1" d="M31.977 47.543c3.238 0 6.48.023 9.718-.02.758-.011.953.223.907.942a19.358 19.358 0 0 0 0 2.734c.054.758-.149 1.004-.954.996-4.3-.043-8.601-.023-12.898-.023-2.18 0-4.36-.031-6.535.02-.762.019-.957-.235-.914-.95.058-.937.05-1.887 0-2.828-.035-.676.16-.898.87-.89 3.267.042 6.54.019 9.806.019zm63.039-6.414c.765 0 1.535.023 2.3-.008.5-.02.66.156.653.66-.028 1.414.02 2.828-.024 4.242-.023.641.133.875.82.848 1.383-.055 2.77.004 4.153-.023.535-.012.812.093.797.715a112.75 112.75 0 0 0-.004 4.597c.012.555-.2.7-.727.692-1.414-.032-2.828.015-4.242-.024-.601-.02-.82.133-.8.774.046 1.414-.008 2.828.027 4.242.015.593-.13.836-.774.816a91.282 91.282 0 0 0-4.507-.004c-.583.016-.762-.172-.747-.754.04-1.472-.007-2.945.024-4.418.008-.5-.145-.664-.649-.652-1.414.027-2.832-.031-4.242.027-.726.028-.894-.234-.879-.906.043-1.383.067-2.77-.004-4.152-.043-.817.262-.992 1.012-.961 1.356.058 2.711-.008 4.067.027.539.016.71-.148.695-.699-.035-1.41.015-2.828-.024-4.242-.015-.598.133-.852.774-.809.765.051 1.531.012 2.3.012zm0 0"/></svg>

```

2021-04-09 23:05 UTC, Panquesito7 commented on icons/arduino/arduino-plain.svg
> +</svg>
The SVG can be optimized using the [SVG Viewer](https://www.svgviewer.dev/).
By the way: this icon is missing the `TM` on the corner.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128"><path style="fill-rule:evenodd;stroke:none;fill-opacity:1" d="M.3 66.5v-9.6c.2-.1.2-.3.2-.5 3-13.1 11.2-21 24.2-24.1 1.1-.3 2.3-.2 3.4-.6h6.4c.1.2.4.1.6.1 6.4.7 12.2 3 17.3 7 4.4 3.3 7.8 7.5 10.9 12 .4.6.6.6 1 0 1.8-2.6 3.7-5.1 5.9-7.4 5.3-5.7 11.7-9.7 19.5-11.1 1.1-.3 2.4-.2 3.5-.6h6.2c.1.2.3.1.5.1 1.9.2 3.7.6 5.5 1.1 13.4 3.9 22.9 16.2 22.1 30.1-.6 11.7-6.5 20.1-16.8 25.4-5.1 2.8-10.7 3.5-16.5 3.4-7.6-.1-14.2-2.7-19.9-7.7-4-3.5-7.1-7.7-10-12.1-.4-.6-.6-.5-1 .1-1.8 2.7-3.7 5.4-5.9 8-3.9 4.4-8.4 8-14 9.9-6.9 2.4-13.9 2.5-20.9.6-10.1-2.9-17-9.3-20.8-19.1-.6-1.6-.9-3.4-1.4-5zm31.8 14.7c5.7.2 10.6-1.7 14.8-5.6 4.3-4 7.4-9 10.5-13.9.1-.3.1-.5-.1-.8-2.6-4.1-5.3-8.2-8.9-11.6-6.9-6.6-15-8.8-24.1-5.9-7.5 2.5-12.3 7.8-13.4 15.8-1.1 7.5 1.8 13.5 7.8 18 4 2.9 8.5 4.1 13.4 4zm63.4 0c2.2 0 4.4-.1 6.5-.7 7.9-2.4 13.1-7.3 14.6-15.5 1.5-8.1-1.6-14.6-8.4-19.2-7.5-5.2-18.4-4.7-26 1-5.1 3.8-8.5 8.9-11.9 14.2-.2.3-.1.5 0 .8 2.7 4.3 5.4 8.6 8.9 12.3 4.4 4.7 9.7 7.4 16.3 7.1zm0 0"/><path style="fill-rule:evenodd;stroke:none;fill-opacity:1" d="M32 58.5c3.2 0 6.5.1 9.7 0 .8 0 .9.2.9 1-.1.9-.1 1.8 0 2.7.1.8-.1 1-1 1H28.8c-2.2 0-4.4-.1-6.6 0-.7 0-.9-.2-.9-1 .1-.9.1-1.8 0-2.8 0-.7.2-.9.9-.9 3.2.1 6.5 0 9.8 0zm63-6.4c.8 0 1.6.1 2.3 0 .5 0 .7.2.7.7-.1 1.4 0 2.8-.1 4.2 0 .7.2.9.9.9 1.3-.1 2.7 0 4.1-.1.6 0 .8.1.8.8v4.6c0 .5-.2.7-.7.7-1.4-.1-2.8 0-4.3-.1-.6 0-.8.2-.8.8.1 1.4 0 2.8.1 4.2 0 .6-.2.9-.8.9-1.5-.1-3-.1-4.5 0-.6 0-.8-.2-.8-.8.1-1.5 0-2.9.1-4.4 0-.5-.2-.7-.7-.7-1.4.1-2.8 0-4.2.1-.8 0-.9-.3-.9-.9 0-1.4.1-2.8 0-4.2-.1-.8.3-1 1-1 1.4.1 2.7 0 4.1.1.5 0 .7-.2.7-.7-.1-1.4 0-2.9-.1-4.3 0-.6.2-.8.8-.8.8.1 1.5 0 2.3 0zm0 0"/></svg>

```

2021-04-25 19:30 UTC, Thomas-Boi commented
Update: I've emailed Icomoon regarding the issue seen [here](https://github.com/devicons/devicon/pull/532#issuecomment-817044536). 

I've also take a look at the created SVG and compared them. One of the path element changed and I do not know what's causing it. The original SVG uses fill, not stroke, so I couldn't find the error. We'll wait and see what Icomoon says about this.

2021-04-26 22:21 UTC, Thomas-Boi commented
Hi all, 

The Icomoon team has quickly responded. Here is their response: 
> Hi,

> This issue seems to be caused by a bug in the SVG path parser in the current version of IcoMoon app. The new version which we have been working on for a couple of years now doesn’t have this issue.

> The new version of IcoMoon app won’t be ready anytime soon. In the meanwhile, you can use the attached SVG instead of your own. It’s basically the same SVG with separate paths.

> Best Regards,
> IcoMoon team

I have the updated svg and I will commit it to this PR soon. Until then, there is nothing we can do about this.

2021-04-27 00:42 UTC, Thomas-Boi commented
Alright, everything looks good! I'll merge the PR now

2021-04-27 00:45 UTC, Thomas-Boi approved these changes
All the files are minified and are built properly. This can be merged.

2021-04-27 00:45 UTC, merged