Missing icons from Font Mfizz added
devicons/devicon pull request #720
Opened 2021-07-07 05:02 UTC by soham4abc

Fixes #683

2021-07-07 05:10 UTC, theblobscp commented
Looks fine, but isn't blackberry a company?

2021-07-07 05:11 UTC, soham4abc commented
> Looks fine, but isn't blackberry a company?

I had the same question in my mind... I think we do not need it. Am I right?

2021-07-07 05:16 UTC, theblobscp commented
Yeah probably not

2021-07-07 05:17 UTC, soham4abc commented
> Yeah probably not

removing it

2021-07-07 05:17 UTC, theblobscp commented
Well other than that the pr is good

2021-07-07 05:21 UTC, theblobscp approved these changes
I said I approved before, just using the github feature to do it

2021-07-07 05:22 UTC, soham4abc commented
> I said I approved before, just using the github feature to do it

Thank you!

2021-07-08 07:01 UTC, soham4abc commented
@Panquesito7  Please do review!

2021-07-08 20:36 UTC, theblobscp commented
oof

2021-07-08 20:44 UTC, Panquesito7 requested changes

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +    },
```suggestion
    },
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            }
        ]
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +                "plain"
```suggestion
                "original"
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +                "plain"
```suggestion
                "original"
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            }
        ]
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +                "plain"
```suggestion
                "original"
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            }
        ]
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +                "plain"
```suggestion
                "original"
```

2021-07-08 20:44 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            }
        ]
```

2021-07-08 20:46 UTC, theblobscp commented
No idea what you did but looks cool

2021-07-09 05:01 UTC, soham4abc commented
@Panquesito7  All the requested changes have been merged. If anything else is required in this PR pls do let me know! Thanks for the support!

2021-07-09 05:25 UTC, theblobscp commented
Thats a lot of changes

2021-07-09 06:41 UTC, Thomas-Boi commented
Hi @soham4abc,

Thank you very much for your work! Overall, the icons look great. However, in order for our `peek-bot` to work, I'll need you to make each icon into a separate PR. So `alpinelinux` should be a new PR, `azure` should be another one, etc.  Please refer to step 4 and 5 [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview). 

If you are not sure how to achieve this with git, there's a few ways to do this:
- Checkout a new branch from `develop` and cherry-pick commits specific to an icon. Ex: create a `soham4abc:alpinelinux` branch, cherry pick the `alpinelinux`-related commits from this branch then push.
- Mixed reset everything so this PR branch is the same as `develop`. Then, create a commit for each icon added and checkout a new branch after the commit. Make sure the `devicon.json` only contains the changes for that specific icon. 
- Same as step 1 but rather than cherry-pick, copy and paste the files.

I'll close this PR for now. I hope to see your new icons soon 😃

2021-07-09 06:41 UTC, closed without merging

2021-07-09 10:55 UTC, soham4abc commented
> Hi @soham4abc,
> 
> Thank you very much for your work! Overall, the icons look great. However, in order for our `peek-bot` to work, I'll need you to make each icon into a separate PR. So `alpinelinux` should be a new PR, `azure` should be another one, etc. Please refer to step 4 and 5 [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview).
> 
> If you are not sure how to achieve this with git, there's a few ways to do this:
> 
> * Checkout a new branch from `develop` and cherry-pick commits specific to an icon. Ex: create a `soham4abc:alpinelinux` branch, cherry pick the `alpinelinux`-related commits from this branch then push.
> * Mixed reset everything so this PR branch is the same as `develop`. Then, create a commit for each icon added and checkout a new branch after the commit. Make sure the `devicon.json` only contains the changes for that specific icon.
> * Same as step 1 but rather than cherry-pick, copy and paste the files.
> 
> I'll close this PR for now. I hope to see your new icons soon 😃

Done the same... will give more PRs for each icon respectively. For 3dPrints #740 has been already opened! Please do have a look!