new icon: filezilla (original)
devicons/devicon pull request #725
Opened 2021-07-07 18:01 UTC by MichielPater

2021-07-07 19:02 UTC, Panquesito7 submitted a review, later dismissed
I checked out their website, and it seems you're missing an `original-wordmark` version. Please add it here in SVG format, too.

![image](https://user-images.githubusercontent.com/51391473/124814681-ee53f700-df2b-11eb-83e9-2b90648434b9.png)

2021-07-07 19:25 UTC, MichielPater commented
@Panquesito7 Thank you for your changes!

I've seen the wordmark logo, but I'm not sure how to convert it to SVG format without losing precision. Do you have any suggestions?

2021-07-09 06:28 UTC, Thomas-Boi requested changes
We're very close. This need to solve one final hiccup. As you can see in the bot's images, the `original` version is black. This is because we strip colors from the logo. In the image, I can see that the `f` is white => remove the colors and its black, same as the red background.

Suggestion:
If you have Inkscape, you can click on the SVG object -> decompose it into smaller objects -> click on the white `f` -> delete it. Then, replace the `original` entry in `font` with `plain`.

This *should* leave the red background and a transparent `f`. Then, save it as `filezilla-plain.svg` and resubmit. If the `f` is not clean (ex. jagged edges when removed), we might have to find another way. Props to you if you can do the same thing to `original-wordmark` and make it `plain-wordmark`.

2021-07-09 09:29 UTC, MichielPater commented
@Thomas-Boi Updated the icons :)

2021-07-09 18:40 UTC, Thomas-Boi commented on devicon.json
> +                "plain"
This looks great now! I also notice that you changes the `wordmark` version as well, which will make it font-friendly. I think we can add this in too.
```suggestion
                "plain",
                "plain-wordmark"
```

2021-07-09 19:04 UTC, Thomas-Boi approved these changes
@MichielPater fantastic work! `Filezilla` looks great now. Thank you for your time and welcome to the repo!

2021-07-09 19:05 UTC, merged