new icon: msdos (original)
devicons/devicon pull request #726
Opened 2021-07-07 18:09 UTC by MichielPater

And re-sorted icons starting with 'm' alphabetically.

2021-07-07 19:05 UTC, Panquesito7 requested changes

2021-07-07 19:05 UTC, Panquesito7 commented on icons/msdos/msdos-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" xmlns:v="https://vecta.io/nano"><path d="M80.426 114.348v3.414h20.48v-3.414h-20.48m-3.414-6.828h-3.41v3.414h3.41v-3.414m3.414 6.828v-3
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><path d="M80.426 114.348v3.414h20.48v-3.414h-20.48m-3.414-6.828h-3.41v3.414h3.41v-3.414m3.414 6.828v-3.414h-3.414v3.414h3.414m-6.824-10.242h-3.414v3.414h3.414v-3.414m6.824-13.652v3.414h3.414v-3.414h-3.414m10.242 3.414v-3.414h-3.414v3.414H83.84v3.414h13.652v-3.414h-6.824m6.824-3.414v3.414h3.414v-3.414h-3.414m10.242 20.48h3.414v-3.414h-3.414v3.414m0 3.414v-3.414h-6.828v3.414h6.828m-40.961 0H53.121v3.414h23.891v-3.414H66.773m-20.48 3.414v-3.414H15.574v3.414h30.719m10.242-13.656v-3.414h-6.828v10.242h-3.414v3.414h6.828v-10.242h3.414M32.641 46.078h3.414v-6.824h-3.414v6.824m6.824 27.309v-6.828h-3.41v3.414H25.813v27.309h20.48v-3.414h-3.414v-3.414h-3.414v3.414H29.227v-20.48h6.828v17.066h3.41V73.387m10.242-3.414v17.066h-3.414v6.828h3.414v-3.414h3.414V66.559h-3.414v3.414m0-13.652v-3.414h-3.414v3.414h3.414m-6.828 0v3.414h3.414V56.32h-3.414m0 6.828v-3.414h-3.414v6.824h3.414v-3.41M29.227 11.945v6.828h3.414v-6.828h-3.414m-10.238 0h10.238v-3.41H15.574v40.957H12.16v64.855h3.414V52.906h30.719v-6.828h-3.414v3.414h-3.414v-3.414h-3.41v3.414h-6.828V39.254h3.414v-6.828h-3.414v-3.414h-3.414v20.48h-6.824V11.945m17.066 13.656v-6.828h-3.414v6.828h3.414m6.824 6.824h3.414v-6.824h-3.414v6.824m6.828 6.828h-3.414v6.824h3.414v-6.824m-10.242-6.828v6.828h3.414v-6.828h-3.414m-3.41-6.824v6.824h3.41v-6.824h-3.41m13.652-6.828h-3.414v6.828h3.414v-6.828m3.414 0v-6.828h-3.414v6.828h3.414m61.438 64.852h-3.41v23.895h3.41V83.625m-6.824-3.41v3.41h3.414v-3.41h-3.414m0-20.48h3.414V56.32h-3.414v3.414m3.414 0v10.238h3.41V59.734h-3.41m-10.242 17.066v3.414h6.828v-3.414h-6.828m-3.414-6.828h3.414v-3.414h-3.414v3.414m3.414 0v3.414h10.242v-3.414h-10.242m-30.719 6.828V59.734h-3.414v10.238h-3.414v-6.824H53.121v3.41h6.824v27.309h-3.41v6.824h3.41v-3.41h6.828v6.824h3.414V90.453h-3.414v3.414h-3.414v-20.48h3.414v3.414h3.414m3.414 3.414v-3.414h-3.414v3.414h3.414m6.824-13.656h10.242v23.895h6.824v-3.414h-3.414V76.801h6.828v-3.414h-6.828v-6.828h3.414v-3.41H80.426v3.41m0 6.828v-6.828h-3.414v13.656h-3.41v3.41h3.41v3.414h-6.824v3.414h10.238V73.387m-10.238-20.48h3.414v-3.414h-6.828V8.535H53.121v3.41h10.238v37.547h-6.824v-20.48h-3.414v3.414h-3.414v6.828h3.414v10.238h-3.414v3.414h20.48m3.414 3.414h-3.414v3.414h3.414V56.32m0 0h3.41v-3.414h-3.41v3.414m3.41-10.242h-3.41v3.414h3.41v-3.414m23.895 6.828v3.414h6.828v-3.414h-6.828m0-3.414H77.012v3.414h23.895v-3.414m0-3.414v3.414h3.414v-3.414h-3.414m-3.414-6.824h-3.414v3.414h3.414v-3.414m0-6.828h3.414v-3.414h-6.828v3.414h3.414m-6.824 6.828h3.41V35.84h-3.41v3.414m-10.242 0V35.84H70.188v10.238h3.414v-6.824h6.824m3.414 0h-3.414v6.824h13.652v-3.41H83.84v-3.414m-3.414-6.828v3.414h10.242v-3.414H80.426m-3.414-3.414h-3.41v3.414h6.824v-3.414h-3.414m6.828-3.41v3.41h10.238v-3.41H83.84m0-6.828h-3.414v6.828h3.414v-6.828m-10.238-3.414h-3.414v13.652h3.414V15.359m0-3.414v3.414h6.824v-3.414h-6.824m20.477 0h3.414v-3.41H80.426v3.41h13.652m0 6.828v-3.414H83.84v3.414h10.238M104.32 35.84v-3.414h-3.414v3.414h3.414m3.414 0h-3.414v10.238h3.414V35.84m-3.414-20.48v-3.414h-6.828v3.414h6.828m3.414 0h-3.414v6.828h-6.828v-3.414h-3.414v6.828h13.656zm0 0" fill="rgb(0%,0%,0%)"/><path d="M70.188 107.52v3.414h3.414v-3.414h-3.414m3.414 6.828h3.41v-3.414h-3.41v3.414m6.824-23.895h3.414v-3.414h-3.414v3.414m-27.305 20.48v3.414h3.414v-3.414h-3.414m6.824-3.414h-3.41v3.414h3.41v-3.414m3.414 3.414h3.414v-3.414h-3.414v3.414m3.414 0v3.414h3.414v-3.414h-3.414m-3.414 3.414v-3.414h-3.414v3.414h3.414m0-44.375h3.414v-3.414h-3.414v3.414M46.293 80.215h3.414v-3.414h-3.414v3.414m3.414 3.41h-3.414v3.414h3.414v-3.414m-3.414-13.652v3.414h3.414v-3.414h-3.414m34.133 10.242v3.41h3.414v-3.41h-3.414m0-10.242h3.414v-3.414h-3.414v3.414m3.414 3.414h-3.414v3.414h3.414v-3.414M70.188 59.734V56.32h-3.414v3.414h3.414m3.414-3.414v-3.414h-3.414v3.414zm0 0" fill="rgb(0%,0%,50.196078%)"/><path d="M70.188 110.934v3.414h3.414v-3.414h-3.414m-17.066-3.414v3.414h3.414v-3.414h-3.414m3.414 6.828h3.41v-3.414h-3.41v3.414m10.238-6.828v3.414h3.414v-3.414h-3.414m-3.414 3.414v-3.414h-3.414v3.414h3.414m0 0v3.414h3.414v-3.414h-3.414M49.707 66.559h3.414v-3.41h-3.414v3.41m-3.414 13.656v3.41h3.414v-3.41h-3.414m0-10.242h3.414v-3.414h-3.414v3.414m3.414 3.414h-3.414v3.414h3.414v-3.414m17.066-10.238h-3.414v3.41h3.414v-3.41m13.652 17.066h3.414v-3.414h-3.414v3.414m3.414 3.41h-3.414v3.414h3.414v-3.414m-3.414-13.652v3.414h3.414v-3.414zm0 0" fill="rgb(50.196078%,0%,50.196078%)"/><path d="M87.254 90.453v-3.414H83.84v3.414h3.414m-44.375-3.414h-3.414v3.414h3.414v-3.414m3.414 6.828v-3.414h-3.414v3.414h3.414m17.066 6.824h3.414v-3.41h-3.414v3.41m3.414 3.414h-3.414v3.414h3.414v-3.414m-6.828-3.414v3.414h3.414v-3.414h-3.414m0 3.414h-3.41v3.414h3.41v-3.414m-13.652-20.48h-3.414v3.414h3.414v-3.414m-3.414-6.824v3.414h3.414v-3.414h-3.414m-3.414 6.824h3.414v-3.41h-3.414v3.41m3.414-10.238h-3.414v3.414h3.414v-3.414m0-6.828h-3.414v3.414h3.414v-3.414m3.414 6.828v-3.414h-3.414v3.414h3.414m0-10.238h-3.414v3.41h3.414v-3.41m0-3.414v3.414h3.414v-3.414h-3.414m20.48-3.414h-3.414v3.414h3.414V56.32m-13.652 3.414V56.32h-3.414v3.414h3.414m6.824 0v3.414h3.414v-3.414h-3.414m-6.824 0v3.414h3.414v-3.414h-3.414m3.414-3.414v-3.414h-3.414v3.414h3.414m3.41-3.414v3.414h3.414v-3.414h-3.414m0 3.414h-3.41v3.414h3.41V56.32m30.723 27.305h-3.414v3.414h3.414v-3.414m0-6.824h-3.414v3.414h3.414v-3.414m-3.414-3.414h3.414v-3.414h-3.414v3.414m-3.414 0v3.414h3.414v-3.414H83.84m0 6.828v3.41h3.414v-3.41H83.84m0-13.656v3.414h3.414v-3.414H83.84M70.188 56.32v-3.414h-3.414v3.414zm0 0" fill="rgb(100%,0%,100%)"/><path d="M87.254 93.867v-3.414H83.84v3.414h3.414m3.414-6.828h-3.414v3.414h3.414v-3.414m-23.895 17.066v3.414h3.414v-3.414h-3.414m-20.48-13.652v-3.414h-3.414v3.414h3.414m17.066 13.652h-3.414v3.414h3.414v-3.414m0-3.414v3.414h3.414v-3.414h-3.414m-3.414-3.41v3.41h3.414v-3.41h-3.414m-3.41 6.824h-3.414v3.414h3.414v-3.414m0 0h3.41v-3.414h-3.41v3.414M42.879 76.801h3.414v-3.414h-3.414v3.414m0 3.414v3.41h3.414v-3.41h-3.414m0 3.41h-3.414v3.414h3.414v-3.414m0-6.824h-3.414v3.414h3.414v-3.414m-3.414-3.414h3.414v-3.414h-3.414v3.414m6.828-3.414v-3.414h-3.414v3.414h3.414m3.414-6.824h-3.414v3.41h3.414v-3.41m0-6.828h-3.414v3.414h3.414V56.32m-6.828 3.414v3.414h3.414v-3.414h-3.414m20.48 0v3.414h3.414v-3.414h-3.414m3.414-3.414v-3.414h-3.414v3.414h3.414m-6.828 0v3.414h3.414V56.32h-3.414m-3.41 3.414V56.32h-3.414v3.414h3.414m0 0v3.414h3.41v-3.414h-3.41m-3.414 3.414v-3.414h-3.414v3.414h3.414m0-6.828v-3.414h-3.414v3.414h3.414m3.414 0h3.41v-3.414h-3.41v3.414m30.719 27.305H83.84v3.414h3.414v-3.414m0 0h3.414v-3.41h-3.414v3.41m3.414-10.238h-3.414v3.414h3.414v-3.414m0-6.828h-3.414v3.414h3.414v-3.414M83.84 76.801v3.414h3.414v-3.414H83.84m0-6.828v3.414h3.414v-3.414zm0 0" fill="rgb(0%,0%,100%)"/><path d="M97.492 90.453h3.414v-3.414h-3.414v3.414m6.828 10.238v3.414h-3.414v3.414H83.84v-3.414h-6.828v-3.414h-3.41v-6.824h-3.414v10.238h3.414v3.414h3.41v3.414h3.414v3.414h20.48v-3.414h6.828v-3.414h3.414V97.281h-3.414v3.41h-3.414m-6.828-17.066h-3.414v3.414h3.414v-3.414m3.414-17.066v3.414h10.242v-6.824h-3.414v3.41h-6.828M77.012 76.801h-3.41v3.414h3.41v-3.414m-3.41-3.414h-3.414v3.414h3.414v-3.414m27.305-10.238h-3.414v3.41h3.414zm0 0" fill="rgb(50.196078%,50.196078%,0%)"/><path d="M49.707 104.105h-3.414v3.414H18.988v3.414h-3.414v3.414h30.719v-3.414h3.414v-6.828m6.828-10.238h-3.414v6.824h3.414v-6.824m0 0h3.41v-3.414h-3.41v3.414M42.879 52.906v3.414h3.414v-3.414h-3.414m0 3.414h-3.414v3.414h3.414V56.32m-17.066 6.828v6.824h10.242v-3.414h3.41v-3.41zm0 0" fill="rgb(50.196078%,0%,0%)"/><path d="M25.813 69.973v-6.824h13.652V56.32h3.414v-3.414H15.574v58.027h3.414v-3.414h27.305v-3.414h3.414v-3.414h3.414v-6.824h3.414v-3.414h3.41V66.559h-6.824v23.895h-3.414v3.414h-3.414v3.414h-20.48zm0 0" fill="rgb(100%,0%,0%)"/><path d="M29.227 29.012v-3.41h-3.414v-3.414h-3.414v27.305h3.414v-20.48h3.414m3.414-10.238h-3.414v3.414h3.414v-3.414m-6.828-6.828v3.414h3.414v-3.414h-3.414m30.723 17.066v-3.41h-3.414v3.41h3.414M42.879 39.254h-3.414v3.414h3.414v-3.414m-3.414-3.414v-3.414h- [...]

2021-07-07 19:05 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            }
        ]
```

2021-07-09 06:21 UTC, Thomas-Boi requested changes

2021-07-09 06:21 UTC, Thomas-Boi commented on devicon.json
> +            "os",
Please remove the `,`
```suggestion
            "os"
```

2021-07-09 06:21 UTC, Thomas-Boi commented on devicon.json
> +                "original",
Please remove the `,`
```suggestion
                "original"
```

2021-07-09 19:11 UTC, Thomas-Boi commented
Seems like the `original` version is not icon friendly (see `peek-bot`'s image). I'm not sure on the best way to approach this... Can you try stripping the colors manually and upload it as a `plain` version? Still keep the `original` but has a `plain` version that's already simplified and stripped of colors. I'll run the bot again and we'll see how it goes.

2021-07-22 02:53 UTC, Thomas-Boi requested changes
Overall, the SVGs looks good. There are just a few things I'd like to see changed:
- Add the `line` version to the `devicon.json`'s `font` attribute. This should be font-friendly.
- Simplify the `plain` version a bit more. Currently, it has more than one color. There should only be one color in the whole SVG for the `plain` version. Pick the primary color and change all the other colors to that.

2021-07-22 20:12 UTC, Panquesito7 requested changes

2021-07-22 20:12 UTC, Panquesito7 commented on icons/msdos/msdos-line.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><path d="M80.426 114.348v3.414h20.48v-3.414h-20.48m-3.414-6.828h-3.41v3.414h3.41
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><path d="M80.426 114.348v3.414h20.48v-3.414h-20.48m-3.414-6.828h-3.41v3.414h3.41v-3.414m3.414 6.828v-3.414h-3.414v3.414h3.414m-6.824-10.242h-3.414v3.414h3.414v-3.414m6.824-13.652v3.414h3.414v-3.414h-3.414m10.242 3.414v-3.414h-3.414v3.414H83.84v3.414h13.652v-3.414h-6.824m6.824-3.414v3.414h3.414v-3.414h-3.414m10.242 20.48h3.414v-3.414h-3.414v3.414m0 3.414v-3.414h-6.828v3.414h6.828m-40.961 0H53.121v3.414h23.891v-3.414H66.773m-20.48 3.414v-3.414H15.574v3.414h30.719m10.242-13.656v-3.414h-6.828v10.242h-3.414v3.414h6.828v-10.242h3.414M32.641 46.078h3.414v-6.824h-3.414v6.824m6.824 27.309v-6.828h-3.41v3.414H25.813v27.309h20.48v-3.414h-3.414v-3.414h-3.414v3.414H29.227v-20.48h6.828v17.066h3.41V73.387m10.242-3.414v17.066h-3.414v6.828h3.414v-3.414h3.414V66.559h-3.414v3.414m0-13.652v-3.414h-3.414v3.414h3.414m-6.828 0v3.414h3.414V56.32h-3.414m0 6.828v-3.414h-3.414v6.824h3.414v-3.41M29.227 11.945v6.828h3.414v-6.828h-3.414m-10.238 0h10.238v-3.41H15.574v40.957H12.16v64.855h3.414V52.906h30.719v-6.828h-3.414v3.414h-3.414v-3.414h-3.41v3.414h-6.828V39.254h3.414v-6.828h-3.414v-3.414h-3.414v20.48h-6.824V11.945m17.066 13.656v-6.828h-3.414v6.828h3.414m6.824 6.824h3.414v-6.824h-3.414v6.824m6.828 6.828h-3.414v6.824h3.414v-6.824m-10.242-6.828v6.828h3.414v-6.828h-3.414m-3.41-6.824v6.824h3.41v-6.824h-3.41m13.652-6.828h-3.414v6.828h3.414v-6.828m3.414 0v-6.828h-3.414v6.828h3.414m61.438 64.852h-3.41v23.895h3.41V83.625m-6.824-3.41v3.41h3.414v-3.41h-3.414m0-20.48h3.414V56.32h-3.414v3.414m3.414 0v10.238h3.41V59.734h-3.41M100.907 76.8v3.414h6.828V76.8h-6.828m-3.414-6.828h3.414v-3.414h-3.414v3.414m3.414 0v3.414h10.242v-3.414h-10.242M70.188 76.8V59.734h-3.414v10.238H63.36v-6.824H53.121v3.41h6.824v27.309h-3.41v6.824h3.41v-3.41h6.828v6.824h3.414V90.453h-3.414v3.414h-3.414v-20.48h3.414v3.414h3.414m3.414 3.414v-3.414h-3.414v3.414h3.414m6.824-13.656h10.242v23.895h6.824V87.04h-3.414V76.801h6.828v-3.414h-6.828v-6.828h3.414v-3.41H80.426v3.41m0 6.828v-6.828h-3.414v13.656h-3.41v3.41h3.41v3.414h-6.824v3.414h10.238V73.387m-10.238-20.48h3.414v-3.414h-6.828V8.535H53.121v3.41h10.238v37.547h-6.824v-20.48h-3.414v3.414h-3.414v6.828h3.414v10.238h-3.414v3.414h20.48m3.414 3.414h-3.414v3.414h3.414V56.32m0 0h3.41v-3.414h-3.41v3.414m3.41-10.242h-3.41v3.414h3.41v-3.414m23.895 6.828v3.414h6.828v-3.414h-6.828m0-3.414H77.012v3.414h23.895v-3.414m0-3.414v3.414h3.414v-3.414h-3.414m-3.414-6.824h-3.414v3.414h3.414v-3.414m0-6.828h3.414v-3.414h-6.828v3.414h3.414m-6.824 6.828h3.41V35.84h-3.41v3.414m-10.242 0V35.84H70.188v10.238h3.414v-6.824h6.824m3.414 0h-3.414v6.824h13.652v-3.41H83.84v-3.414m-3.414-6.828v3.414h10.242v-3.414H80.426m-3.414-3.414h-3.41v3.414h6.824v-3.414h-3.414m6.828-3.41v3.41h10.238v-3.41H83.84m0-6.828h-3.414v6.828h3.414v-6.828M73.602 15.36h-3.414v13.652h3.414V15.359m0-3.414v3.414h6.824v-3.414h-6.824m20.477 0h3.414v-3.41H80.426v3.41h13.652m0 6.828v-3.414H83.84v3.414h10.238M104.32 35.84v-3.414h-3.414v3.414h3.414m3.414 0h-3.414v10.238h3.414V35.84m-3.414-20.48v-3.414h-6.828v3.414h6.828m3.414 0h-3.414v6.828h-6.828v-3.414h-3.414v6.828h13.656zm0 0" fill="rgb(0%,0%,0%)"/></svg>

```

2021-07-22 20:12 UTC, Panquesito7 commented on icons/msdos/msdos-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><path d="M80.426 114.348v3.414h20.48v-3.414h-20.48m-3.414-6.828h-3.41v3.414h3.41
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><path d="M80.426 114.348v3.414h20.48v-3.414h-20.48m-3.414-6.828h-3.41v3.414h3.41v-3.414m3.414 6.828v-3.414h-3.414v3.414h3.414m-6.824-10.242h-3.414v3.414h3.414v-3.414m6.824-13.652v3.414h3.414v-3.414h-3.414m10.242 3.414v-3.414h-3.414v3.414H83.84v3.414h13.652v-3.414h-6.824m6.824-3.414v3.414h3.414v-3.414h-3.414m10.242 20.48h3.414v-3.414h-3.414v3.414m0 3.414v-3.414h-6.828v3.414h6.828m-40.961 0H53.121v3.414h23.891v-3.414H66.773m-20.48 3.414v-3.414H15.574v3.414h30.719m10.242-13.656v-3.414h-6.828v10.242h-3.414v3.414h6.828v-10.242h3.414M32.641 46.078h3.414v-6.824h-3.414v6.824m6.824 27.309v-6.828h-3.41v3.414H25.813v27.309h20.48v-3.414h-3.414v-3.414h-3.414v3.414H29.227v-20.48h6.828v17.066h3.41V73.387m10.242-3.414v17.066h-3.414v6.828h3.414v-3.414h3.414V66.559h-3.414v3.414m0-13.652v-3.414h-3.414v3.414h3.414m-6.828 0v3.414h3.414V56.32h-3.414m0 6.828v-3.414h-3.414v6.824h3.414v-3.41M29.227 11.945v6.828h3.414v-6.828h-3.414m-10.238 0h10.238v-3.41H15.574v40.957H12.16v64.855h3.414V52.906h30.719v-6.828h-3.414v3.414h-3.414v-3.414h-3.41v3.414h-6.828V39.254h3.414v-6.828h-3.414v-3.414h-3.414v20.48h-6.824V11.945m17.066 13.656v-6.828h-3.414v6.828h3.414m6.824 6.824h3.414v-6.824h-3.414v6.824m6.828 6.828h-3.414v6.824h3.414v-6.824m-10.242-6.828v6.828h3.414v-6.828h-3.414m-3.41-6.824v6.824h3.41v-6.824h-3.41m13.652-6.828h-3.414v6.828h3.414v-6.828m3.414 0v-6.828h-3.414v6.828h3.414m61.438 64.852h-3.41v23.895h3.41V83.625m-6.824-3.41v3.41h3.414v-3.41h-3.414m0-20.48h3.414V56.32h-3.414v3.414m3.414 0v10.238h3.41V59.734h-3.41M100.907 76.8v3.414h6.828V76.8h-6.828m-3.414-6.828h3.414v-3.414h-3.414v3.414m3.414 0v3.414h10.242v-3.414h-10.242M70.188 76.8V59.734h-3.414v10.238H63.36v-6.824H53.121v3.41h6.824v27.309h-3.41v6.824h3.41v-3.41h6.828v6.824h3.414V90.453h-3.414v3.414h-3.414v-20.48h3.414v3.414h3.414m3.414 3.414v-3.414h-3.414v3.414h3.414m6.824-13.656h10.242v23.895h6.824V87.04h-3.414V76.801h6.828v-3.414h-6.828v-6.828h3.414v-3.41H80.426v3.41m0 6.828v-6.828h-3.414v13.656h-3.41v3.41h3.41v3.414h-6.824v3.414h10.238V73.387m-10.238-20.48h3.414v-3.414h-6.828V8.535H53.121v3.41h10.238v37.547h-6.824v-20.48h-3.414v3.414h-3.414v6.828h3.414v10.238h-3.414v3.414h20.48m3.414 3.414h-3.414v3.414h3.414V56.32m0 0h3.41v-3.414h-3.41v3.414m3.41-10.242h-3.41v3.414h3.41v-3.414m23.895 6.828v3.414h6.828v-3.414h-6.828m0-3.414H77.012v3.414h23.895v-3.414m0-3.414v3.414h3.414v-3.414h-3.414m-3.414-6.824h-3.414v3.414h3.414v-3.414m0-6.828h3.414v-3.414h-6.828v3.414h3.414m-6.824 6.828h3.41V35.84h-3.41v3.414m-10.242 0V35.84H70.188v10.238h3.414v-6.824h6.824m3.414 0h-3.414v6.824h13.652v-3.41H83.84v-3.414m-3.414-6.828v3.414h10.242v-3.414H80.426m-3.414-3.414h-3.41v3.414h6.824v-3.414h-3.414m6.828-3.41v3.41h10.238v-3.41H83.84m0-6.828h-3.414v6.828h3.414v-6.828M73.602 15.36h-3.414v13.652h3.414V15.359m0-3.414v3.414h6.824v-3.414h-6.824m20.477 0h3.414v-3.41H80.426v3.41h13.652m0 6.828v-3.414H83.84v3.414h10.238M104.32 35.84v-3.414h-3.414v3.414h3.414m3.414 0h-3.414v10.238h3.414V35.84m-3.414-20.48v-3.414h-6.828v3.414h6.828m3.414 0h-3.414v6.828h-6.828v-3.414h-3.414v6.828h13.656zm0 0" fill="rgb(0%,0%,0%)"/><path d="M73.616 78.424v-1.655h-1.655-1.655v-8.512-8.512h1.655 1.655V58.09v-1.655h1.734 1.734V54.7v-1.734h11.901 11.901V54.7v1.734h3.389 3.389v1.655 1.655h1.734 1.734v5.044 5.044h-5.044-5.044v-1.655-1.655H99.31h-1.734v-1.734-1.734h-8.591-8.591v1.734 1.734H78.66h-1.734V73.3v6.778h-1.655-1.655zm6.936 34.128v-1.734h-1.734-1.734v-1.655-1.655H75.35h-1.734v-1.734-1.734h-1.655-1.655v-6.778-6.778h5.044 5.044v1.734 1.734h1.655 1.655v1.734 1.734h6.936 6.936v-1.734-1.734h1.734 1.734v-1.813-1.813H99.31h-1.734V88.67v-1.655h-1.734-1.734V81.97v-5.044h3.389 3.389v1.655 1.655h3.389 3.389v1.734 1.734h1.734 1.734v11.901 11.901h-1.734-1.734v1.655 1.655h-3.389-3.389v1.734 1.734H90.719 80.552zm3.31-20.493v-1.734h-1.655-1.655V78.502 66.68h5.044 5.044v11.823 11.823h-1.734-1.734v1.734 1.734h-1.655-1.655zm-30.739 17.182v-5.044h1.734 1.734v-1.734-1.734h1.734 1.734v-1.655-1.655h3.31 3.31v3.389 3.389h1.734 1.734v1.734 1.734h1.655 1.655v1.655 1.655h1.734 1.734v1.655 1.655h-11.9-11.902zM15.606 83.626v-30.66h15.291 15.291v1.655 1.655h-1.655-1.655v1.655 1.655h-1.734-1.734v3.468 3.468h-1.734-1.734v1.655 1.655h-5.123-5.123v13.793 13.793H36.02h10.325v-1.734-1.734h1.734 1.734v-1.734-1.734h1.655 1.655V78.581 66.68h3.389 3.389v13.557 13.557h-1.734-1.734v3.389 3.389h-3.389-3.389v5.123 5.123h-1.734-1.734v1.734 1.734h-15.29-15.291zM43 92.099l-.045-1.695-1.695-.045-1.695-.045V78.502 66.69l1.695-.045 1.695-.045.042-3.429.042-3.429h1.652 1.652v-1.655-1.655h1.734 1.734V54.7v-1.734h11.823 11.823v1.655 1.655h-1.655-1.655v1.655 1.655h-1.734-1.734v5.123 5.123h-1.655-1.655v-3.391-3.391l-5.163.042-5.163.042L53 64.828l-.045 1.695h-1.65-1.65v10.246 10.246h-1.734-1.734v3.389 3.389h-1.571-1.571zM19.074 30.66V11.98h5.044 5.044v3.468 3.468h1.734 1.734v3.389 3.389h1.655 1.655v3.389 3.389h1.734 1.734v3.389 3.389h1.813 1.813v-3.389-3.389h1.655 1.655v-3.389-3.389h1.734 1.734v-3.389-3.389h1.655 1.655v-3.468-3.468h5.044 5.044v18.68 18.68H59.9h-3.31V39.172 29.005h-1.813-1.813v1.655 1.655H51.31h-1.655v3.468 3.468h-1.734-1.734v3.389 3.389h-1.655-1.655v1.655 1.655h-1.655-1.655v-1.655-1.655h-1.734-1.734V42.64v-3.389h-1.655-1.655v-3.468-3.468h-1.734-1.734V30.66v-1.655h-1.813-1.813v10.167V49.34h-3.31-3.31zm58.01 17.025V46.03H75.35h-1.734v-3.39-3.389h3.389 3.389v3.468 3.468h6.857 6.857v-1.734-1.734h1.734 1.734v-1.734-1.734h-1.734-1.734v-1.734-1.734h-1.655-1.655v-1.734-1.734h-5.123-5.123V30.66v-1.655h-3.468-3.468v-6.778-6.778h3.468 3.468v-1.734-1.734h8.433 8.433v1.734 1.734h3.389 3.389v3.31 3.31h-3.31-3.31v-1.655-1.655h-1.734-1.734v-1.734-1.734h-5.202-5.202v1.734 1.734h-1.655-1.655v3.468 3.468h1.655 1.655v1.734 1.734h5.123 5.123v1.655 1.655h3.468 3.468v1.734 1.734h1.655 1.655v5.044 5.044h-1.655-1.655v1.655 1.655H88.985 77.084z" fill="#ccc"/></svg>

```

2021-07-22 20:12 UTC, Panquesito7 commented on devicon.json
> +				"line"
Please fix the wrong indentation here.

2021-07-22 20:12 UTC, Panquesito7 commented on devicon.json
> +				"line"
Same here as above.

2021-07-25 18:54 UTC, Panquesito7 requested changes
Hmm, the `version` version looks good, but the `plain` version doesn't look so good. @Thomas-Boi, what do you think we should do? 🤔

2021-07-27 00:22 UTC, Panquesito7 commented on icons/msdos/msdos-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="170.667" height="170.667" viewBox="0 0 128 128" fill="#8c8f8f" fill-rule="evenodd" xmlns:v="https://vecta.io/nano"><path d="M79.435 38.806v3.016h3.109v2
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" fill="#8c8f8f" fill-rule="evenodd" xmlns:v="https://vecta.io/nano"><path d="M79.435 38.806v3.016h3.109v2.922h8.953v-2.547h-3.016v-3.391zm12.063-9.707v-5.656h-8.949v5.656zm0 0"/><path d="M94.611 14.017H79.435v3.02h-6.316v3.297h-3.016v12.063h3.016v3.016h6.316v3.016h9.426v3.395h3.016v3.297h-9.707v-2.922H79.06v-3.391h-8.953v9.047h3.016v3.203h3.297v3.109h21.395v-3.109h3.109v-3.203h3.301v-9.047h-3.301V35.79h-3.109v-3.016h-6.316v-3.301h-9.328v-6.406h9.707v6.031h12.348v-8.766h-3.301v-3.297h-6.312zm0 0"/><path d="M79.248 13.548h15.738v3.109h6.316v3.297h3.297v9.52H91.876v2.922h6.41v3.016h3.016v3.016h3.297v9.801h-3.297v3.301h-3.016v3.016H76.044V51.53h-3.297v-3.301h-3.016v-9.801h9.328V35.79h-6.312v-3.016h-3.016V19.958h3.016v-3.301h6.313v-3.109zm-59.469 0h12.629v3.109h3.301v6.41h3.109v6.031h3.016v6.313h2.828v-6.313h3.297v-6.031h3.016v-6.41h3.016v-3.109h13.102v40.996H53.99V42.197h-2.637v6.031h-3.016v6.316h-9.992v-6.316H35.33v-6.031h-2.922v12.348H19.591V13.548zm0 0"/><path d="M38.345 73.298h-5.937V94.88h9.047v-6.031h-3.109zm28.273 0h-2.828v18.379h2.828V88.47h3.109v-3.109h6.316v-2.637h-3.301v-3.016h-3.016v-3.016h-3.109zm27.992 15.551h-5.75v2.828h5.75zM16.763 51.056h31.574v3.109h2.637v-3.109h22.148v3.109h2.922v-3.109h22.238v3.109h6.316v3.016h3.016v3.488h3.109v9.613h-3.109v3.016h-9.332v2.922h6.316v3.109h3.016v3.016h3.109v22.148h-3.109v3.109h-3.016v3.109h-6.316v3.109H79.06v-3.109h-2.641v3.109H53.99v-3.109h-5.652v3.109H16.482V51.056zm81.051 21.863v-2.637h-3.203v-3.395h-2.734v6.031zm0 0"/><path d="M60.587 16.845h3.016v34.398h-3.016zm-6.41 12.441h3.113v3.297h-3.113zM29.205 16.845h3.016v3.301h-3.016zm3.016 6.41h3.297v2.922H32.22zm3.297 6.031h3.113v3.297h-3.113zm3.113 6.313h3.016v3.016H38.63zm3.016 6.41h3.203v2.922h-3.203zM26.189 26.177v25.066h3.016v-18.66h3.016v-3.297h-3.016v-3.109zm0 0"/></svg>

```

2021-07-27 18:57 UTC, Panquesito7 requested changes
The `line` version looks good, but the `plain` doesn't. Could you please fix it?

2021-07-27 20:45 UTC, MichielPater commented
> The `line` version looks good, but the `plain` doesn't. Could you please fix it?

Why doesn't it look good?

2021-07-28 00:50 UTC, Panquesito7 commented
> > The `line` version looks good, but the `plain` doesn't. Could you please fix it?
> 
> Why doesn't it look good?

I already know what does it say, but for other users, it would be kind of hard to understand, as it looks all black and the letters are very much together. The `line` version looks very good though. Hope I get to understand, thanks. 🙂

2021-07-30 00:00 UTC, Panquesito7 approved these changes
Actually, never mind. Now that I think about it well, it looks great! I love it. Great work, @MichielPater! Thank you for your patience, dedication, and contributions to our community! 😄👍🎉

2021-08-07 05:08 UTC, Thomas-Boi approved these changes
Sorry @MichielPater for the late response.

I think the icons and SVGs all look good. I'll merge your changes in. Thank you for your dedication in seeing this through 😃, we really appreciate it.

2021-08-07 05:13 UTC, merged