new icon: opengl (original)
devicons/devicon pull request #727
Opened 2021-07-07 18:17 UTC by MichielPater

And re-sorted icons starting with 'o' alphabetically

2021-07-07 19:10 UTC, Panquesito7 requested changes

2021-07-07 19:10 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            }
        ]
```

2021-07-07 19:10 UTC, Panquesito7 commented on icons/opengl/opengl-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" fill-rule="evenodd" xmlns:v="https://vecta.io/nano"><path d="M27.363 76.605c-6.078 0-9.094-3.645-10.277-7.453 1.32 6.195 8.449 12.23 3
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" fill-rule="evenodd" xmlns:v="https://vecta.io/nano"><path d="M27.363 76.605c-6.078 0-9.094-3.645-10.277-7.453 1.32 6.195 8.449 12.23 30.945 14.91 21.258 2.551 35.09-3.848 39.77-6.824 0 0 3.156-1.367 1.266.742 0 0-13.398 12.129-39.609 12.285-26.262.129-47.09-12.863-46.984-26.043-.125-13.125 20.723-26.145 46.984-26.039 26.262.125 39.609 12.281 39.609 12.281 1.895 2.105-1.266.75-1.266.75-4.668-2.969-18.457-8.82-39.77-6.824-20.934 1.98-27.77 8.977-30.086 13.648-.871 1.813-1.27 3.523-1.367 5.242.566-4.496 3.414-9.766 10.766-9.766 8.34 0 10.871 6.824 10.871 11.496 0 4.727-2.547 11.551-10.871 11.551zm84.496-4.539h11.086v3.961h-15.77V54.137h4.66v17.902zm-17.113-7.828h9.309v11.816h-3.105l-.465-2.746c-1.18 1.344-2.891 3.324-6.941 3.324-5.371 0-10.227-3.777-10.227-11.445 0-5.984 3.387-11.605 10.926-11.605 6.832 0 9.523 4.359 9.793 7.352h-4.66c0-.852-1.582-3.598-4.875-3.598-3.32 0-6.406 2.258-6.406 7.875 0 5.988 3.32 7.512 6.512 7.512 1.023 0 4.441-.395 5.383-4.816h-5.187v-3.687zm-67.273-8.031c-4.844 0-7.75 3.746-7.75 8.926 0 5.152 2.918 8.926 7.75 8.926 4.844 0 7.75-3.75 7.75-8.926 0-5.152-2.918-8.926-7.75-8.926zm12.539 5.832h2.262v1.977h.055c.57-.805 1.66-2.387 4.25-2.387 3.789 0 6.512 3.152 6.512 7.09 0 3.348-1.965 7.719-6.836 7.719-1.91 0-3.164-.883-3.785-1.875h-.055v7.035h-2.402zm6.082 12.387c2.617 0 4.391-2.227 4.391-5.301 0-1.797-.738-5.355-4.445-5.355-3.461 0-3.844 3.664-3.844 5.934 0 3.715 2.375 4.711 3.898 4.711zm21.527-2.754c-.082.664-.738 2.652-2.535 3.824-.656.43-1.582.969-3.871.969-4.008 0-6.402-2.973-6.402-7.035 0-4.34 2.125-7.773 6.836-7.773 4.117 0 6.133 3.215 6.133 8.191H57.34c0 2.922 1.391 4.605 4.145 4.605 2.262 0 3.602-1.711 3.684-2.758h2.398zm-2.539-3.719c-.137-2.168-1.066-4.176-3.984-4.176-2.207 0-3.949 2.008-3.949 4.176zm15.984 8.086h-2.402v-8.613c0-2.43-.711-3.664-3.051-3.664-1.363 0-3.762.859-3.762 4.656v7.613h-2.402V62.016h2.266v1.977h.055c.52-.75 1.852-2.383 4.305-2.383 2.207 0 4.992.883 4.992 4.875v9.555" fill="rgb(70.196078%,70.196078%,70.196078%)"/><path d="M26.289 75.031c-6.137 0-9.203-3.645-10.387-7.453 1.336 6.191 8.555 12.23 31.27 14.91 21.473 2.543 35.465-3.848 40.199-6.828 0 0 3.191-1.363 1.277.746 0 0-13.508 12.129-40.094 12.285C22.02 88.816.926 75.828 1.086 62.648.957 49.523 22.02 36.504 48.555 36.609c26.531.125 40.094 12.281 40.094 12.281 1.914 2.105-1.277.75-1.277.75-4.719-2.969-18.676-8.82-40.199-6.828-21.207 1.984-28.094 8.98-30.41 13.652a13.44 13.44 0 0 0-1.383 5.242c.57-4.496 3.449-9.77 10.871-9.77 8.398 0 10.98 6.828 10.98 11.551s-2.574 11.5-10.98 11.5zm85.57-4.543h11.195v3.965h-15.93V52.555h4.707v17.91zm-17.277-7.824H104v11.813h-3.137l-.469-2.738c-1.195 1.34-2.926 3.324-7.051 3.324-5.437 0-10.387-3.777-10.387-11.445 0-5.984 3.422-11.605 11.031-11.605 6.891 0 9.633 4.359 9.902 7.352h-4.707c0-.852-1.605-3.598-4.93-3.598-3.359 0-6.461 2.258-6.461 7.875 0 5.988 3.359 7.512 6.566 7.512 1.035 0 4.488-.395 5.438-4.816h-5.242v-3.687zm-68.348-8.031c-4.898 0-7.855 3.746-7.855 8.926 0 5.148 2.949 8.926 7.855 8.926 4.898 0 7.859-3.75 7.859-8.926 0-5.152-2.949-8.926-7.859-8.926zm12.703 5.828h2.285v1.98h.055c.582-.805 1.68-2.387 4.301-2.387 3.832 0 6.566 3.152 6.566 7.09 0 3.344-1.988 7.719-6.891 7.719-1.93 0-3.195-.883-3.832-1.875h-.055v7.035h-2.426V60.488zm6.133 12.395c2.648 0 4.441-2.23 4.441-5.305 0-1.801-.75-5.359-4.496-5.359-3.496 0-3.883 3.668-3.883 5.938 0 3.715 2.398 4.711 3.938 4.711zm21.742-2.762c-.082.672-.742 2.652-2.562 3.828-.66.43-1.598.969-3.91.969-4.055 0-6.457-2.973-6.457-7.039 0-4.336 2.152-7.77 6.941-7.77 4.16 0 6.188 3.215 6.188 8.191H56.465c0 2.922 1.402 4.602 4.191 4.602 2.289 0 3.637-1.707 3.719-2.754h2.43zm-2.57-3.715c-.141-2.172-1.078-4.176-4.027-4.176-2.234 0-4 2.004-4 4.176zm16.145 8.082h-2.426v-8.609c0-2.434-.719-3.664-3.09-3.664-1.379 0-3.805.855-3.805 4.656v7.613h-2.43V60.441h2.289v1.977h.055c.523-.75 1.871-2.383 4.355-2.383 2.23 0 5.043.883 5.043 4.875v9.504" fill="rgb(33.333333%,52.54902%,64.313725%)"/><path d="M127.754 74.242c0 .363-.094.703-.277 1.016s-.437.559-.758.742-.664.27-1.035.27-.711-.09-1.031-.27a2.06 2.06 0 0 1-.758-.742c-.184-.312-.277-.652-.277-1.016a1.98 1.98 0 0 1 .277-1.012c.188-.316.438-.562.758-.742s.664-.27 1.031-.27.719.09 1.035.27.574.426.758.742a1.98 1.98 0 0 1 .277 1.012zm-.398 0c0-.449-.164-.836-.492-1.152a1.62 1.62 0 0 0-1.176-.484 1.62 1.62 0 0 0-1.18.484 1.54 1.54 0 0 0-.488 1.152 1.55 1.55 0 0 0 .488 1.156c.328.32.719.48 1.18.48a1.61 1.61 0 0 0 1.176-.48c.328-.32.492-.703.492-1.156zm-2.605-1.082h.988c.277 0 .484.055.609.168s.188.258.188.441a.54.54 0 0 1-.145.379c-.094.105-.246.184-.453.23.086.031.148.063.188.098.059.051.117.125.176.227.004.004.125.215.359.621h-.652l-.426-.738c-.07-.082-.145-.121-.215-.121-.02 0-.039 0-.07.008v.852h-.551zm.551.918h.238c.156 0 .27-.023.336-.074s.098-.113.098-.195-.031-.148-.094-.195-.168-.078-.32-.078h-.258zm0 0" fill="rgb(60%,60%,60%)"/><path d="M127.754 73.719a1.95 1.95 0 0 1-.277 1.012c-.184.316-.437.563-.758.742a2.07 2.07 0 0 1-1.035.273c-.367 0-.711-.094-1.031-.273s-.57-.426-.758-.742a1.95 1.95 0 0 1-.277-1.012c0-.359.094-.699.277-1.016a2.02 2.02 0 0 1 .758-.738c.32-.18.664-.27 1.031-.27s.719.09 1.035.27.574.426.758.738.277.656.277 1.016zm-.398 0a1.53 1.53 0 0 0-.492-1.152c-.324-.324-.719-.484-1.176-.484s-.855.16-1.18.484a1.54 1.54 0 0 0-.488 1.152 1.55 1.55 0 0 0 .488 1.156 1.62 1.62 0 0 0 1.18.477c.461 0 .852-.156 1.176-.477s.492-.703.492-1.156zm-2.605-1.086h.988c.277 0 .484.059.609.168s.188.262.188.445c0 .145-.047.27-.145.379-.094.102-.246.18-.453.23.086.031.148.063.188.098a.92.92 0 0 1 .176.223c.004.004.125.215.359.625h-.652l-.426-.738c-.07-.082-.145-.125-.215-.125-.02 0-.039.004-.07.008v.855h-.551zm.551.922h.238c.156 0 .27-.027.336-.078a.24.24 0 0 0 .098-.195.23.23 0 0 0-.094-.191c-.062-.051-.168-.078-.32-.078h-.258zm0 0" fill="rgb(33.333333%,52.54902%,64.313725%)"/></svg>

```

2021-07-09 06:31 UTC, Thomas-Boi requested changes

2021-07-09 06:31 UTC, Thomas-Boi commented on devicon.json
> +                "original",
Pesky commas 😄
```suggestion
                "original"
```

2021-07-09 19:07 UTC, Thomas-Boi commented
The icon looks good 👍. The edges are a bit blurry but that's due to the shadow in the original. 

Would you be interested in making a `plain` version that's the same as the `original` but without the shadows? We'll keep the original but the no-shadow one will be the `plain` version. If you're too busy, I can merge this branch as is into the repo as well.

2021-07-22 00:11 UTC, Panquesito7 commented on icons/opengl/opengl-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" fill-rule="evenodd" xmlns:v="https://vecta.io/nano"><path d="M27.363 76.605c-6.078 0-9.094-3.645-10.277-7.453 1.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" fill-rule="evenodd" xmlns:v="https://vecta.io/nano"><path d="M27.363 76.605c-6.078 0-9.094-3.645-10.277-7.453 1.32 6.195 8.449 12.23 30.945 14.91 21.258 2.551 35.09-3.848 39.77-6.824 0 0 3.156-1.367 1.266.742 0 0-13.398 12.129-39.609 12.285-26.262.129-47.09-12.863-46.984-26.043-.125-13.125 20.723-26.145 46.984-26.039 26.262.125 39.609 12.281 39.609 12.281 1.895 2.105-1.266.75-1.266.75-4.668-2.969-18.457-8.82-39.77-6.824-20.934 1.98-27.77 8.977-30.086 13.648-.871 1.813-1.27 3.523-1.367 5.242.566-4.496 3.414-9.766 10.766-9.766 8.34 0 10.871 6.824 10.871 11.496 0 4.727-2.547 11.551-10.871 11.551zm84.496-4.539h11.086v3.961h-15.77V54.137h4.66v17.902zm-17.113-7.828h9.309v11.816h-3.105l-.465-2.746c-1.18 1.344-2.891 3.324-6.941 3.324-5.371 0-10.227-3.777-10.227-11.445 0-5.984 3.387-11.605 10.926-11.605 6.832 0 9.523 4.359 9.793 7.352h-4.66c0-.852-1.582-3.598-4.875-3.598-3.32 0-6.406 2.258-6.406 7.875 0 5.988 3.32 7.512 6.512 7.512 1.023 0 4.441-.395 5.383-4.816h-5.187v-3.687zm-67.273-8.031c-4.844 0-7.75 3.746-7.75 8.926 0 5.152 2.918 8.926 7.75 8.926 4.844 0 7.75-3.75 7.75-8.926 0-5.152-2.918-8.926-7.75-8.926zm12.539 5.832h2.262v1.977h.055c.57-.805 1.66-2.387 4.25-2.387 3.789 0 6.512 3.152 6.512 7.09 0 3.348-1.965 7.719-6.836 7.719-1.91 0-3.164-.883-3.785-1.875h-.055v7.035h-2.402zm6.082 12.387c2.617 0 4.391-2.227 4.391-5.301 0-1.797-.738-5.355-4.445-5.355-3.461 0-3.844 3.664-3.844 5.934 0 3.715 2.375 4.711 3.898 4.711zm21.527-2.754c-.082.664-.738 2.652-2.535 3.824-.656.43-1.582.969-3.871.969-4.008 0-6.402-2.973-6.402-7.035 0-4.34 2.125-7.773 6.836-7.773 4.117 0 6.133 3.215 6.133 8.191H57.34c0 2.922 1.391 4.605 4.145 4.605 2.262 0 3.602-1.711 3.684-2.758h2.398zm-2.539-3.719c-.137-2.168-1.066-4.176-3.984-4.176-2.207 0-3.949 2.008-3.949 4.176zm15.984 8.086h-2.402v-8.613c0-2.43-.711-3.664-3.051-3.664-1.363 0-3.762.859-3.762 4.656v7.613h-2.402V62.016h2.266v1.977h.055c.52-.75 1.852-2.383 4.305-2.383 2.207 0 4.992.883 4.992 4.875v9.555" fill="rgb(70.196078%,70.196078%,70.196078%)"/><path d="M26.289 75.031c-6.137 0-9.203-3.645-10.387-7.453 1.336 6.191 8.555 12.23 31.27 14.91 21.473 2.543 35.465-3.848 40.199-6.828 0 0 3.191-1.363 1.277.746 0 0-13.508 12.129-40.094 12.285C22.02 88.816.926 75.828 1.086 62.648.957 49.523 22.02 36.504 48.555 36.609c26.531.125 40.094 12.281 40.094 12.281 1.914 2.105-1.277.75-1.277.75-4.719-2.969-18.676-8.82-40.199-6.828-21.207 1.984-28.094 8.98-30.41 13.652a13.44 13.44 0 0 0-1.383 5.242c.57-4.496 3.449-9.77 10.871-9.77 8.398 0 10.98 6.828 10.98 11.551s-2.574 11.5-10.98 11.5zm85.57-4.543h11.195v3.965h-15.93V52.555h4.707v17.91zm-17.277-7.824H104v11.813h-3.137l-.469-2.738c-1.195 1.34-2.926 3.324-7.051 3.324-5.437 0-10.387-3.777-10.387-11.445 0-5.984 3.422-11.605 11.031-11.605 6.891 0 9.633 4.359 9.902 7.352h-4.707c0-.852-1.605-3.598-4.93-3.598-3.359 0-6.461 2.258-6.461 7.875 0 5.988 3.359 7.512 6.566 7.512 1.035 0 4.488-.395 5.438-4.816h-5.242v-3.687zm-68.348-8.031c-4.898 0-7.855 3.746-7.855 8.926 0 5.148 2.949 8.926 7.855 8.926 4.898 0 7.859-3.75 7.859-8.926 0-5.152-2.949-8.926-7.859-8.926zm12.703 5.828h2.285v1.98h.055c.582-.805 1.68-2.387 4.301-2.387 3.832 0 6.566 3.152 6.566 7.09 0 3.344-1.988 7.719-6.891 7.719-1.93 0-3.195-.883-3.832-1.875h-.055v7.035h-2.426V60.488zm6.133 12.395c2.648 0 4.441-2.23 4.441-5.305 0-1.801-.75-5.359-4.496-5.359-3.496 0-3.883 3.668-3.883 5.938 0 3.715 2.398 4.711 3.938 4.711zm21.742-2.762c-.082.672-.742 2.652-2.562 3.828-.66.43-1.598.969-3.91.969-4.055 0-6.457-2.973-6.457-7.039 0-4.336 2.152-7.77 6.941-7.77 4.16 0 6.188 3.215 6.188 8.191H56.465c0 2.922 1.402 4.602 4.191 4.602 2.289 0 3.637-1.707 3.719-2.754h2.43zm-2.57-3.715c-.141-2.172-1.078-4.176-4.027-4.176-2.234 0-4 2.004-4 4.176zm16.145 8.082h-2.426v-8.609c0-2.434-.719-3.664-3.09-3.664-1.379 0-3.805.855-3.805 4.656v7.613h-2.43V60.441h2.289v1.977h.055c.523-.75 1.871-2.383 4.355-2.383 2.23 0 5.043.883 5.043 4.875v9.504" fill="rgb(33.333333%,52.54902%,64.313725%)"/><path d="M127.754 74.242c0 .363-.094.703-.277 1.016s-.437.559-.758.742-.664.27-1.035.27-.711-.09-1.031-.27a2.06 2.06 0 0 1-.758-.742c-.184-.312-.277-.652-.277-1.016a1.98 1.98 0 0 1 .277-1.012c.188-.316.438-.562.758-.742s.664-.27 1.031-.27.719.09 1.035.27.574.426.758.742a1.98 1.98 0 0 1 .277 1.012zm-.398 0c0-.449-.164-.836-.492-1.152a1.62 1.62 0 0 0-1.176-.484 1.62 1.62 0 0 0-1.18.484 1.54 1.54 0 0 0-.488 1.152 1.55 1.55 0 0 0 .488 1.156c.328.32.719.48 1.18.48a1.61 1.61 0 0 0 1.176-.48c.328-.32.492-.703.492-1.156zm-2.605-1.082h.988c.277 0 .484.055.609.168s.188.258.188.441a.54.54 0 0 1-.145.379c-.094.105-.246.184-.453.23.086.031.148.063.188.098.059.051.117.125.176.227.004.004.125.215.359.621h-.652l-.426-.738c-.07-.082-.145-.121-.215-.121-.02 0-.039 0-.07.008v.852h-.551zm.551.918h.238c.156 0 .27-.023.336-.074s.098-.113.098-.195-.031-.148-.094-.195-.168-.078-.32-.078h-.258zm0 0" fill="rgb(60%,60%,60%)"/><path d="M127.754 73.719a1.95 1.95 0 0 1-.277 1.012c-.184.316-.437.563-.758.742a2.07 2.07 0 0 1-1.035.273c-.367 0-.711-.094-1.031-.273s-.57-.426-.758-.742a1.95 1.95 0 0 1-.277-1.012c0-.359.094-.699.277-1.016a2.02 2.02 0 0 1 .758-.738c.32-.18.664-.27 1.031-.27s.719.09 1.035.27.574.426.758.738.277.656.277 1.016zm-.398 0a1.53 1.53 0 0 0-.492-1.152c-.324-.324-.719-.484-1.176-.484s-.855.16-1.18.484a1.54 1.54 0 0 0-.488 1.152 1.55 1.55 0 0 0 .488 1.156 1.62 1.62 0 0 0 1.18.477c.461 0 .852-.156 1.176-.477s.492-.703.492-1.156zm-2.605-1.086h.988c.277 0 .484.059.609.168s.188.262.188.445c0 .145-.047.27-.145.379-.094.102-.246.18-.453.23.086.031.148.063.188.098a.92.92 0 0 1 .176.223c.004.004.125.215.359.625h-.652l-.426-.738c-.07-.082-.145-.125-.215-.125-.02 0-.039.004-.07.008v.855h-.551zm.551.922h.238c.156 0 .27-.027.336-.078a.24.24 0 0 0 .098-.195.23.23 0 0 0-.094-.191c-.062-.051-.168-.078-.32-.078h-.258zm0 0" fill="rgb(33.333333%,52.54902%,64.313725%)"/></svg>

```

2021-07-22 00:11 UTC, Panquesito7 commented on icons/opengl/opengl-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" fill-rule="evenodd" fill="rgb(33.333333%,52.54902%,64.313725%)" xmlns:v="https://vecta.io/nano"><path d="M26.289
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128" fill-rule="evenodd" fill="rgb(33.333333%,52.54902%,64.313725%)" xmlns:v="https://vecta.io/nano"><path d="M26.289 75.031c-6.137 0-9.203-3.645-10.387-7.453 1.336 6.191 8.555 12.23 31.27 14.91 21.473 2.543 35.465-3.848 40.199-6.828 0 0 3.191-1.363 1.277.746 0 0-13.508 12.129-40.094 12.285C22.02 88.816.926 75.828 1.086 62.648.957 49.523 22.02 36.504 48.555 36.609c26.531.125 40.094 12.281 40.094 12.281 1.914 2.105-1.277.75-1.277.75-4.719-2.969-18.676-8.82-40.199-6.828-21.207 1.984-28.094 8.98-30.41 13.652a13.44 13.44 0 0 0-1.383 5.242c.57-4.496 3.449-9.77 10.871-9.77 8.398 0 10.98 6.828 10.98 11.551s-2.574 11.5-10.98 11.5zm85.57-4.543h11.195v3.965h-15.93V52.555h4.707v17.91zm-17.277-7.824H104v11.813h-3.137l-.469-2.738c-1.195 1.34-2.926 3.324-7.051 3.324-5.437 0-10.387-3.777-10.387-11.445 0-5.984 3.422-11.605 11.031-11.605 6.891 0 9.633 4.359 9.902 7.352h-4.707c0-.852-1.605-3.598-4.93-3.598-3.359 0-6.461 2.258-6.461 7.875 0 5.988 3.359 7.512 6.566 7.512 1.035 0 4.488-.395 5.438-4.816h-5.242v-3.687zm-68.348-8.031c-4.898 0-7.855 3.746-7.855 8.926 0 5.148 2.949 8.926 7.855 8.926 4.898 0 7.859-3.75 7.859-8.926 0-5.152-2.949-8.926-7.859-8.926zm12.703 5.828h2.285v1.98h.055c.582-.805 1.68-2.387 4.301-2.387 3.832 0 6.566 3.152 6.566 7.09 0 3.344-1.988 7.719-6.891 7.719-1.93 0-3.195-.883-3.832-1.875h-.055v7.035H38.94V60.488zm6.133 12.395c2.648 0 4.441-2.23 4.441-5.305 0-1.801-.75-5.359-4.496-5.359-3.496 0-3.883 3.668-3.883 5.938 0 3.715 2.398 4.711 3.938 4.711zm21.742-2.762c-.082.672-.742 2.652-2.562 3.828-.66.43-1.598.969-3.91.969-4.055 0-6.457-2.973-6.457-7.039 0-4.336 2.152-7.77 6.941-7.77 4.16 0 6.188 3.215 6.188 8.191H56.465c0 2.922 1.402 4.602 4.191 4.602 2.289 0 3.637-1.707 3.719-2.754h2.43zm-2.57-3.715c-.141-2.172-1.078-4.176-4.027-4.176-2.234 0-4 2.004-4 4.176zm16.145 8.082h-2.426v-8.609c0-2.434-.719-3.664-3.09-3.664-1.379 0-3.805.855-3.805 4.656v7.613h-2.43V60.441h2.289v1.977h.055c.523-.75 1.871-2.383 4.355-2.383 2.23 0 5.043.883 5.043 4.875v9.504m47.376-.695a1.95 1.95 0 0 1-.277 1.012 1.97 1.97 0 0 1-.758.742 2.07 2.07 0 0 1-1.035.273c-.367 0-.711-.094-1.031-.273s-.57-.426-.758-.742a1.95 1.95 0 0 1-.277-1.012c0-.359.094-.699.277-1.016a2.02 2.02 0 0 1 .758-.738 2.07 2.07 0 0 1 1.031-.27c.367 0 .719.09 1.035.27s.574.426.758.738a1.98 1.98 0 0 1 .277 1.016zm-.398 0a1.53 1.53 0 0 0-.492-1.152c-.324-.324-.719-.484-1.176-.484s-.855.16-1.18.484a1.54 1.54 0 0 0-.488 1.152 1.55 1.55 0 0 0 .488 1.156 1.62 1.62 0 0 0 1.18.477c.461 0 .852-.156 1.176-.477a1.57 1.57 0 0 0 .492-1.156zm-2.605-1.086h.988c.277 0 .484.059.609.168s.188.262.188.445c0 .145-.047.27-.145.379-.094.102-.246.18-.453.23.086.031.148.063.188.098a.92.92 0 0 1 .176.223 47.6 47.6 0 0 1 .359.625h-.652l-.426-.738c-.07-.082-.145-.125-.215-.125-.02 0-.039.004-.07.008v.855h-.551zm.551.922h.238c.156 0 .27-.027.336-.078a.24.24 0 0 0 .098-.195.23.23 0 0 0-.094-.191c-.062-.051-.168-.078-.32-.078h-.258zm0 0"/></svg>

```

2021-07-22 19:08 UTC, Panquesito7 approved these changes
LGTM. Thank you for your contribution! 👍 🎉

2021-07-24 22:57 UTC, Thomas-Boi approved these changes

2021-07-24 23:01 UTC, Thomas-Boi commented
Sorry for the late review. Everything looks great now!

2021-07-24 23:01 UTC, merged