new icon: towergit (original, original-wordmark)
devicons/devicon pull request #733
Opened 2021-07-07 18:41 UTC by MichielPater

2021-07-09 06:31 UTC, Thomas-Boi commented
Hey @MichielPater,

Please hold off fixing the `fill` issue reported by the bot. I'm trying to find a way to fix this issue permanently using our SVG-optimizer bot.

2021-07-27 19:20 UTC, Panquesito7 requested changes
Yes, please fix the `fill` issue mentioned by the bot (use `fill` instead of `class`).

2021-07-27 19:20 UTC, Panquesito7 commented on devicon.json
> +                "original"
```suggestion
                "original",
                "original-wordmark"
```

2021-07-27 19:20 UTC, Panquesito7 commented on devicon.json
> +        "aliases": []
```suggestion
        "aliases": [
            {
                "base": "original",
                "alias": "plain"
            },
            {
                "base": "original-wordmark",
                "alias": "plain-wordmark"
            }
        ]
```

2021-07-27 19:20 UTC, Panquesito7 commented on icons/towergit/towergit-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{filter:url(#A)}.C{stroke:none}.D{fill-ru
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{filter:url(#A)}.C{stroke:none}.D{fill-rule:nonzero}.E{fill-opacity:1}.F{fill:rgb(100%,100%,100%)}.G{fill:rgb(5.098039%,18.039216%,30.980392%)}.H{fill:rgb(0%,29.019608%,44.705882%)}.I{fill:rgb(100%,78.039216%,3.529412%)}.J{fill:rgb(69.803922%,49.411765%,30.980392%)}.K{fill:rgb(17.647059%,76.862745%,92.941176%)}]]></style><defs><filter id="A" x="0%" y="0%" width="100%" height="100%"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><image id="B" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAqUlEQVR4nO3WsQ0CMRAEwDUP9VAJIf1QBh1QGiVAADINIP3rJP6RPBPvnR1scAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALC2tiTUMy3KfX/g3auz/N5+LtAztbzO19L2frvn0C6lWVax2/oDbEsBBqcAg1OAwc0egUmSfnzW1p8etTkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4Mx/NhAx7BcWa9AAAAABJRU5ErkJggg=="/><mask id="C"><g class="B"><use xlink:href="#B"/></g></mask><linearGradient id="D" x1="8.937" y1="51.936" x2="23.922" y2="51.936" xlink:href="#An"><stop offset=".41" stop-color="rgb(100%,100%,100%)" stop-opacity="0"/><stop offset=".51" stop-color="rgb(100%,100%,100%)" stop-opacity=".149"/><stop offset=".74" stop-color="rgb(100%,100%,100%)" stop-opacity=".529"/><stop offset="1" stop-color="rgb(100%,100%,100%)"/></linearGradient><clipPath id="E"><path d="M0 0h128v128H0z"/></clipPath><g id="F" clip-path="url(#E)"><path d="M8.934 48.922H23.91v6.047H8.934zm0 0" fill="url(#D)" class="C D"/></g><image id="G" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAmklEQVR4nO3SQQqCYBSF0UcYBIE4iRxEq3CbgXtwbY2DCkfaaweN/JXgnAV83MGNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+Vj5eTY7XS76Hdust/LYrUj30dVT3c+yPpyJ9FlPmAPmcI7pPxG0q0gcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC1fQHvOg9HP8ukHAAAAABJRU5ErkJggg=="/><mask id="H"><g class="B"><use xlink:href="#G"/></g></mask><clipPath id="I"><path d="M0 0h128v128H0z"/></clipPath><g id="J" clip-path="url(#I)"><path d="M21.242 54.969h2.688v-2.707zm0 0" class="C D E F"/></g><linearGradient id="K" x1="23.826" y1="48.901" x2="23.826" y2="49.093" xlink:href="#An"><stop offset=".28" stop-color="rgb(100%,100%,100%)" stop-opacity="0"/><stop offset=".39" stop-color="rgb(100%,100%,100%)" stop-opacity=".012"/><stop offset=".48" stop-color="rgb(100%,100%,100%)" stop-opacity=".059"/><stop offset=".57" stop-color="rgb(100%,100%,100%)" stop-opacity=".129"/><stop offset=".65" stop-color="rgb(100%,100%,100%)" stop-opacity=".22"/><stop offset=".73" stop-color="rgb(100%,100%,100%)" stop-opacity=".349"/><stop offset=".81" stop-color="rgb(100%,100%,100%)" stop-opacity=".51"/><stop offset=".89" stop-color="rgb(100%,100%,100%)" stop-opacity=".69"/><stop offset=".97" stop-color="rgb(100%,100%,100%)" stop-opacity=".902"/><stop offset="1" stop-color="rgb(100%,100%,100%)"/></linearGradient><image id="L" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAArklEQVR4nO3XsQ3CMBAF0AtJdkDKLCkyD2NRsgdDsAItUlIATklrN46E36v/fVnyNRcBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU1uUGU/TZ2V/5J5XOUFfWp6bX9RzjtBS338dbt8zv4jmqOR39AI5lARpnARpnARo3ZKXS+o3+shW3Px+uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7DDuquEC2aAngFAAAAAElFTkSuQmCC"/><mask id="M"><g class="B"><use xlink:href="#L"/></g></mask><clipPath id="N"><path d="M0 0h128v128H0z"/></clipPath><g id="O" clip-path="url(#N)"><path d="M9.48 54.949h7.758l5.965-6.047h-7.734zm0 0" class="C D E F"/></g><image id="P" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAkUlEQVR4nO3Sqw2AMBQF0PIR7MMUnYBFWYcdajCEFBwa05aEc9R9yRVXvBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoqntTuo5hfo4cUzetW7FFVNW3HkBbHuDnxletHNOTz2UPYS21BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC+5gZzIws9NYC5KgAAAABJRU5ErkJggg=="/><mask id="Q"><g class="B"><use xlink:href="#P"/></g></mask><clipPath id="R"><path d="M0 0h128v128H0z"/></clipPath><g id="S" clip-path="url(#R)"><path d="M12.82 48.902H8.934v3.926zm0 0" class="C D E F"/></g><image id="T" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAg0lEQVR4nO3NMQ5AUBBF0RFavX3Y/z7sQSfR4duAYjIJmnPq+2YiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAr3WZqEWf6p4fnK265X1DqtrnqXT92o4Yl7W0BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+NUN2XwJAiNL2E4AAAAASUVORK5CYII="/><mask id="U"><g class="B"><use xlink:href="#T"/></g></mask><clipPath id="V"><path d="M0 0h128v128H0z"/></clipPath><g id="W" clip-path="url(#V)"><path d="M8.934 48.902H23.91v.648H8.934zm0 0" class="C D E H"/></g><linearGradient id="X" x1="13.178" y1="54.456" x2="13.178" y2="49.093" xlink:href="#An"><stop offset=".1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity="0"/><stop offset=".23" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".012"/><stop offset=".34" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".059"/><stop offset=".45" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".129"/><stop offset=".55" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".239"/><stop offset=".6" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset=".8" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".102"/></linearGradient><linearGradient id="Y" x1="19.669" y1="54.456" x2="19.669" y2="49.093" xlink:href="#An"><stop offset=".1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity="0"/><stop offset=".23" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".012"/><stop offset=".34" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".059"/><stop offset=".45" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".129"/><stop offset=".55" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".239"/><stop offset=".6" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset=".8" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".102"/></linearGradient><image id="Z" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAcUlEQVR4nO3SwQkAIAwEwaiNCxauJfgRImSmgoW7CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP63Y7TsBhLtuXp2A28YsjgHKM4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK4OQ3YDDl4kZoEAAAAASUVORK5CYII="/><mask id="a"><g class="B"><use xlink:href="#Z"/></g></mask><clipPath id="b"><path d="M0 0h128v128H0z"/></clipPath><g id="c" clip-path="url(#b)"><path d="M13.547 49.098h.137v5.359h-.137zm0 0" class="C D E H"/></g><image id="d" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAcUlEQVR4nO3SwQkAIAwEwaiNCxauJYivIJmpYOEuAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgH/tGC27gUR7rp7dwBuDFecAxTkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwNUB+r8DDkxFxjAAAAAASUVORK5CYII="/><mask id="e"><g class="B"><use xlink:href="#d"/></g></mask><clipPath id="f"><path d="M0 0h128v128H0z"/></clipPath><g id="g" clip-path="url(#f)"><path d="M19.18 49.098h.137v5.359h-.137zm0 0" class="C D E H"/></g><image id="h" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAjklEQVR4nO3SwQmAMAwF0NSKgzifILiMm3oRqRtYpJRe3rsm/J9DIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgL5SbaFEru7US57SmkEf89ewRE5x70dTQ9muWNazKYNuptEHMJYHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD45QXkYwkJZMet4wAAAABJRU5ErkJggg=="/><mask id="i"><g class="B"><use xlink:href="#h"/></g></mask><linearGradient id="j" x1="7.9 [...]

2021-07-27 19:20 UTC, Panquesito7 commented on icons/towergit/towergit-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{stroke:none}.C{filter:url(#A)}.D{fill:rg
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{stroke:none}.C{filter:url(#A)}.D{fill:rgb(0%,0%,0%)}.E{fill-rule:nonzero}.F{fill-opacity:1}.G{fill-opacity:.4}.H{fill:rgb(0%,17.647059%,30.980392%)}.I{fill:rgb(0%,28.627451%,44.705882%)}.J{fill-opacity:.2}.K{fill:rgb(100%,100%,100%)}.L{fill:rgb(100%,77.647059%,0%)}.M{fill-opacity:.349}.N{fill-opacity:.302}.O{fill:rgb(80.392157%,49.803922%,12.156863%)}.P{fill:rgb(100%,100%,0%)}.Q{fill:rgb(85.882353%,60%,15.294118%)}]]></style><defs><filter id="A" x="0%" y="0%" width="100%" height="100%"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><mask id="B"><g class="C"><path d="M0 0h128v128H0z" fill-opacity=".6" class="B D"/></g></mask><linearGradient id="C" x1="44.579" y1="37.314" x2="83.607" y2="37.314" xlink:href="#AN"><stop offset=".408" stop-color="rgb(100%,100%,100%)" stop-opacity="0"/><stop offset=".999" stop-color="rgb(100%,100%,100%)"/></linearGradient><clipPath id="D"><path d="M0 0h128v128H0z"/></clipPath><g id="E" clip-path="url(#D)"><path d="M44.574 29.512h39.039v15.602H44.574zm0 0" fill="url(#C)" class="B E"/></g><mask id="F"><g class="C"><path d="M0 0h128v128H0z" class="B D J"/></g></mask><clipPath id="G"><path d="M0 0h128v128H0z"/></clipPath><g id="H" clip-path="url(#G)"><path d="M77.961 43.813h5.652v-5.648zm0 0" class="B E F K"/></g><mask id="I"><g class="C"><path d="M0 0h128v128H0z" class="B D M"/></g></mask><clipPath id="J"><path d="M0 0h128v128H0z"/></clipPath><g id="K" clip-path="url(#J)"><path d="M67.477 43.813l14.297-14.301H61.477L47.176 43.813zm0 0" class="B E F K"/></g><mask id="L"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="M"><path d="M0 0h128v128H0z"/></clipPath><g id="N" clip-path="url(#M)"><path d="M44.574 29.512h39.027v1.563H44.574zm0 0" class="B E F I"/></g><mask id="O"><g class="C"><path d="M0 0h128v128H0z" class="B D J"/></g></mask><clipPath id="P"><path d="M0 0h128v128H0z"/></clipPath><g id="Q" clip-path="url(#P)"><path d="M54.688 29.512H44.574v10.102zm0 0" class="B E F K"/></g><linearGradient id="R" x1="55.637" y1="43.812" x2="55.637" y2="30.032" xlink:href="#AN"><stop offset=".096" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity="0"/><stop offset=".568" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".282"/><stop offset=".6" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset=".797" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".102"/></linearGradient><linearGradient id="S" x1="72.548" y1="43.812" x2="72.548" y2="30.032" xlink:href="#AN"><stop offset=".096" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity="0"/><stop offset=".568" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".282"/><stop offset=".6" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset=".797" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".102"/></linearGradient><mask id="T"><g class="C"><path d="M0 0h128v128H0z" class="B D N"/></g></mask><clipPath id="U"><path d="M0 0h128v128H0z"/></clipPath><g id="V" clip-path="url(#U)"><path d="M56.574 30.039h.352v13.773h-.352zm0 0" class="B E F I"/></g><mask id="W"><g class="C"><path d="M0 0h128v128H0z" class="B D N"/></g></mask><clipPath id="X"><path d="M0 0h128v128H0z"/></clipPath><g id="Y" clip-path="url(#X)"><path d="M71.25 30.039h.352v13.773h-.352zm0 0" class="B E F I"/></g><linearGradient id="Z" x1="35.114" y1="52.737" x2="93.071" y2="52.737" xlink:href="#AN"><stop offset=".096" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity="0"/><stop offset=".568" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".282"/><stop offset=".6" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset=".797" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".102"/></linearGradient><linearGradient id="a" x1="64.078" y1="80.597" x2="64.078" y2="107.541" xlink:href="#AN"><stop offset="0" stop-color="rgb(0%,37.254902%,55.686275%)"/><stop offset=".724" stop-color="rgb(0%,28.627451%,44.705882%)"/></linearGradient><linearGradient id="b" x1="37.714" y1="19.119" x2="90.502" y2="19.119" xlink:href="#AN"><stop offset=".204" stop-color="rgb(100%,84.705882%,7.45098%)" stop-opacity="0"/><stop offset=".782" stop-color="rgb(100%,84.705882%,7.45098%)"/></linearGradient><mask id="c"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="d"><path d="M0 0h128v128H0z"/></clipPath><g id="e" clip-path="url(#d)"><path d="M37.711 20.625H90.5l-.199-.773H37.887zm0 0" fill="rgb(70.588235%,49.019608%,30.980392%)" class="B E F"/></g><linearGradient id="f" x1="42.679" y1="47.019" x2="85.507" y2="47.019" xlink:href="#AN"><stop offset=".204" stop-color="rgb(100%,84.705882%,7.45098%)" stop-opacity="0"/><stop offset=".782" stop-color="rgb(100%,84.705882%,7.45098%)"/></linearGradient><mask id="g"><g class="C"><path d="M0 0h128v128H0z" class="B D M"/></g></mask><clipPath id="h"><path d="M0 0h128v128H0z"/></clipPath><g id="i" clip-path="url(#h)"><path d="M93.074 56.676l-.324-1.824H35.438l-.324 1.824zm0 0" class="B E F H"/></g><mask id="j"><g class="C"><path d="M0 0h128v128H0z" class="B D J"/></g></mask><clipPath id="k"><path d="M0 0h128v128H0z"/></clipPath><g id="l" clip-path="url(#k)"><path d="M47.688 107.539h32.488v.523H47.688zm0 0" class="B E F I"/></g><mask id="m"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="n"><path d="M0 0h128v128H0z"/></clipPath><g id="o" clip-path="url(#n)"><path d="M54.887 80.602h-9.473v26.063a.87.87 0 0 0 .875.875h8.586V80.602zm0 0" class="B E F H"/></g><linearGradient id="p" x1="78" y1="80.597" x2="78" y2="107.541" xlink:href="#AN"><stop offset="0" stop-color="rgb(0%,55.294118%,76.862745%)"/><stop offset=".541" stop-color="rgb(0%,44.705882%,65.490196%)"/></linearGradient><mask id="q"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><linearGradient id="r" x1="50.251" y1="85.46" x2="74.121" y2="44.116" xlink:href="#AN"><stop offset=".204" stop-color="rgb(100%,84.705882%,7.45098%)" stop-opacity="0"/><stop offset=".782" stop-color="rgb(100%,84.705882%,7.45098%)"/></linearGradient><clipPath id="s"><path d="M0 0h128v128H0z"/></clipPath><g id="t" clip-path="url(#s)"><path d="M97.836 63.125l-1.461-5.898c-.074-.328-.375-.551-.699-.551H32.477a.71.71 0 0 0-.703.551l-1.449 5.898c-.023.102-.012.199.051.289l11.086 16.887a.68.68 0 0 0 .563.301h44.141a.68.68 0 0 0 .563-.301l11.086-16.887c.023-.09.051-.187.023-.289zm0 0" fill="url(#r)" class="B E"/></g><mask id="u"><g class="C"><path d="M0 0h128v128H0z" fill-opacity=".42" class="B D"/></g></mask><clipPath id="v"><path d="M0 0h128v128H0z"/></clipPath><g id="w" clip-path="url(#v)"><path d="M45.426 80.602h37.313v2.16H45.426zm0 0" class="B E F H"/></g><mask id="x"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="y"><path d="M0 0h128v128H0z"/></clipPath><g id="z" clip-path="url(#y)"><path d="M43.512 63.074l1.527-6.176a.36.36 0 0 1 .348-.273H32.648a.71.71 0 0 0-.699.551L30.5 63.074zm0 0" class="B E F O"/></g><mask id="AA"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="AB"><path d="M0 0h128v128H0z"/></clipPath><g id="AC" clip-path="url(#AB)"><path d="M73.711 80.262l11.164-16.949h12.988c-.012.051-.027.086-.051.137L86.727 80.336a.68.68 0 0 1-.562.301H73.086a.76.76 0 0 0 .625-.375zm0 0" fill="rgb(100%,90.588235%,0%)" class="B E F"/></g><mask id="AD"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="AE"><path d="M0 0h128v128H0z"/></clipPath><g id="AF" clip-path="url(#AE)"><path d="M84.824 63.125l-1.523-6.176c-.039-.16-.187-.273-.35 [...]

2021-07-28 00:45 UTC, Panquesito7 requested changes

2021-07-28 00:45 UTC, Panquesito7 commented on icons/towergit/towergit-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{filter:url(#A)}.C{stroke:none}.D{fill-ru
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{filter:url(#A)}.C{stroke:none}.D{fill-rule:nonzero}.E{fill-opacity:1}.F{fill:rgb(100%,100%,100%)}.G{fill:rgb(5.098039%,18.039216%,30.980392%)}.H{fill:rgb(0%,29.019608%,44.705882%)}.I{fill:rgb(100%,78.039216%,3.529412%)}.J{fill:rgb(69.803922%,49.411765%,30.980392%)}.K{fill:rgb(17.647059%,76.862745%,92.941176%)}]]></style><defs><filter id="A" x="0%" y="0%" width="100%" height="100%"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><image id="B" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAqUlEQVR4nO3WsQ0CMRAEwDUP9VAJIf1QBh1QGiVAADINIP3rJP6RPBPvnR1scAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALC2tiTUMy3KfX/g3auz/N5+LtAztbzO19L2frvn0C6lWVax2/oDbEsBBqcAg1OAwc0egUmSfnzW1p8etTkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4Mx/NhAx7BcWa9AAAAABJRU5ErkJggg=="/><mask id="C"><g class="B"><use xlink:href="#B"/></g></mask><linearGradient id="D" x1="8.937" y1="51.936" x2="23.922" y2="51.936" xlink:href="#An"><stop offset=".41" stop-color="rgb(100%,100%,100%)" stop-opacity="0"/><stop offset=".51" stop-color="rgb(100%,100%,100%)" stop-opacity=".149"/><stop offset=".74" stop-color="rgb(100%,100%,100%)" stop-opacity=".529"/><stop offset="1" stop-color="rgb(100%,100%,100%)"/></linearGradient><clipPath id="E"><path d="M0 0h128v128H0z"/></clipPath><g id="F" clip-path="url(#E)"><path d="M8.934 48.922H23.91v6.047H8.934zm0 0" fill="url(#D)" class="C D"/></g><image id="G" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAmklEQVR4nO3SQQqCYBSF0UcYBIE4iRxEq3CbgXtwbY2DCkfaaweN/JXgnAV83MGNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+Vj5eTY7XS76Hdust/LYrUj30dVT3c+yPpyJ9FlPmAPmcI7pPxG0q0gcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC1fQHvOg9HP8ukHAAAAABJRU5ErkJggg=="/><mask id="H"><g class="B"><use xlink:href="#G"/></g></mask><clipPath id="I"><path d="M0 0h128v128H0z"/></clipPath><g id="J" clip-path="url(#I)"><path d="M21.242 54.969h2.688v-2.707zm0 0" class="C D E F"/></g><linearGradient id="K" x1="23.826" y1="48.901" x2="23.826" y2="49.093" xlink:href="#An"><stop offset=".28" stop-color="rgb(100%,100%,100%)" stop-opacity="0"/><stop offset=".39" stop-color="rgb(100%,100%,100%)" stop-opacity=".012"/><stop offset=".48" stop-color="rgb(100%,100%,100%)" stop-opacity=".059"/><stop offset=".57" stop-color="rgb(100%,100%,100%)" stop-opacity=".129"/><stop offset=".65" stop-color="rgb(100%,100%,100%)" stop-opacity=".22"/><stop offset=".73" stop-color="rgb(100%,100%,100%)" stop-opacity=".349"/><stop offset=".81" stop-color="rgb(100%,100%,100%)" stop-opacity=".51"/><stop offset=".89" stop-color="rgb(100%,100%,100%)" stop-opacity=".69"/><stop offset=".97" stop-color="rgb(100%,100%,100%)" stop-opacity=".902"/><stop offset="1" stop-color="rgb(100%,100%,100%)"/></linearGradient><image id="L" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAArklEQVR4nO3XsQ3CMBAF0AtJdkDKLCkyD2NRsgdDsAItUlIATklrN46E36v/fVnyNRcBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADU1uUGU/TZ2V/5J5XOUFfWp6bX9RzjtBS338dbt8zv4jmqOR39AI5lARpnARpnARo3ZKXS+o3+shW3Px+uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7DDuquEC2aAngFAAAAAElFTkSuQmCC"/><mask id="M"><g class="B"><use xlink:href="#L"/></g></mask><clipPath id="N"><path d="M0 0h128v128H0z"/></clipPath><g id="O" clip-path="url(#N)"><path d="M9.48 54.949h7.758l5.965-6.047h-7.734zm0 0" class="C D E F"/></g><image id="P" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAkUlEQVR4nO3Sqw2AMBQF0PIR7MMUnYBFWYcdajCEFBwa05aEc9R9yRVXvBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoqntTuo5hfo4cUzetW7FFVNW3HkBbHuDnxletHNOTz2UPYS21BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC+5gZzIws9NYC5KgAAAABJRU5ErkJggg=="/><mask id="Q"><g class="B"><use xlink:href="#P"/></g></mask><clipPath id="R"><path d="M0 0h128v128H0z"/></clipPath><g id="S" clip-path="url(#R)"><path d="M12.82 48.902H8.934v3.926zm0 0" class="C D E F"/></g><image id="T" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAg0lEQVR4nO3NMQ5AUBBF0RFavX3Y/z7sQSfR4duAYjIJmnPq+2YiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAr3WZqEWf6p4fnK265X1DqtrnqXT92o4Yl7W0BQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+NUN2XwJAiNL2E4AAAAASUVORK5CYII="/><mask id="U"><g class="B"><use xlink:href="#T"/></g></mask><clipPath id="V"><path d="M0 0h128v128H0z"/></clipPath><g id="W" clip-path="url(#V)"><path d="M8.934 48.902H23.91v.648H8.934zm0 0" class="C D E H"/></g><linearGradient id="X" x1="13.178" y1="54.456" x2="13.178" y2="49.093" xlink:href="#An"><stop offset=".1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity="0"/><stop offset=".23" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".012"/><stop offset=".34" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".059"/><stop offset=".45" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".129"/><stop offset=".55" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".239"/><stop offset=".6" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset=".8" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".102"/></linearGradient><linearGradient id="Y" x1="19.669" y1="54.456" x2="19.669" y2="49.093" xlink:href="#An"><stop offset=".1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity="0"/><stop offset=".23" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".012"/><stop offset=".34" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".059"/><stop offset=".45" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".129"/><stop offset=".55" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".239"/><stop offset=".6" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset=".8" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(17.647059%,76.862745%,92.941176%)" stop-opacity=".102"/></linearGradient><image id="Z" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAcUlEQVR4nO3SwQkAIAwEwaiNCxauJfgRImSmgoW7CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP63Y7TsBhLtuXp2A28YsjgHKM4BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK4OQ3YDDl4kZoEAAAAASUVORK5CYII="/><mask id="a"><g class="B"><use xlink:href="#Z"/></g></mask><clipPath id="b"><path d="M0 0h128v128H0z"/></clipPath><g id="c" clip-path="url(#b)"><path d="M13.547 49.098h.137v5.359h-.137zm0 0" class="C D E H"/></g><image id="d" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAcUlEQVR4nO3SwQkAIAwEwaiNCxauJYivIJmpYOEuAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgH/tGC27gUR7rp7dwBuDFecAxTkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwNUB+r8DDkxFxjAAAAAASUVORK5CYII="/><mask id="e"><g class="B"><use xlink:href="#d"/></g></mask><clipPath id="f"><path d="M0 0h128v128H0z"/></clipPath><g id="g" clip-path="url(#f)"><path d="M19.18 49.098h.137v5.359h-.137zm0 0" class="C D E H"/></g><image id="h" width="128" height="128" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAAjklEQVR4nO3SwQmAMAwF0NSKgzifILiMm3oRqRtYpJRe3rsm/J9DIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgL5SbaFEru7US57SmkEf89ewRE5x70dTQ9muWNazKYNuptEHMJYHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD45QXkYwkJZMet4wAAAABJRU5ErkJggg=="/><mask id="i"><g class="B"><use xlink:href="#h"/></g></mask><linearG [...]

2021-07-28 00:45 UTC, Panquesito7 commented on icons/towergit/towergit-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{stroke:none}.C{filter:url(#A)}.D{fill:rg
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{stroke:none}.C{filter:url(#A)}.D{fill:rgb(0%,0%,0%)}.E{fill-rule:nonzero}.F{fill-opacity:1}.G{fill-opacity:.4}.H{fill:rgb(0%,17.647059%,30.980392%)}.I{fill:rgb(0%,28.627451%,44.705882%)}.J{fill-opacity:.2}.K{fill:rgb(100%,100%,100%)}.L{fill:rgb(100%,77.647059%,0%)}.M{fill-opacity:.349}.N{fill-opacity:.302}.O{fill:rgb(80.392157%,49.803922%,12.156863%)}.P{fill:rgb(100%,100%,0%)}.Q{fill:rgb(85.882353%,60%,15.294118%)}]]></style><defs><filter id="A" x="0%" y="0%" width="100%" height="100%"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><mask id="B"><g class="C"><path d="M0 0h128v128H0z" fill-opacity=".6" class="B D"/></g></mask><linearGradient id="C" x1="44.579" y1="37.314" x2="83.607" y2="37.314" xlink:href="#AN"><stop offset=".408" stop-color="rgb(100%,100%,100%)" stop-opacity="0"/><stop offset=".999" stop-color="rgb(100%,100%,100%)"/></linearGradient><clipPath id="D"><path d="M0 0h128v128H0z"/></clipPath><g id="E" clip-path="url(#D)"><path d="M44.574 29.512h39.039v15.602H44.574zm0 0" fill="url(#C)" class="B E"/></g><mask id="F"><g class="C"><path d="M0 0h128v128H0z" class="B D J"/></g></mask><clipPath id="G"><path d="M0 0h128v128H0z"/></clipPath><g id="H" clip-path="url(#G)"><path d="M77.961 43.813h5.652v-5.648zm0 0" class="B E F K"/></g><mask id="I"><g class="C"><path d="M0 0h128v128H0z" class="B D M"/></g></mask><clipPath id="J"><path d="M0 0h128v128H0z"/></clipPath><g id="K" clip-path="url(#J)"><path d="M67.477 43.813l14.297-14.301H61.477L47.176 43.813zm0 0" class="B E F K"/></g><mask id="L"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="M"><path d="M0 0h128v128H0z"/></clipPath><g id="N" clip-path="url(#M)"><path d="M44.574 29.512h39.027v1.563H44.574zm0 0" class="B E F I"/></g><mask id="O"><g class="C"><path d="M0 0h128v128H0z" class="B D J"/></g></mask><clipPath id="P"><path d="M0 0h128v128H0z"/></clipPath><g id="Q" clip-path="url(#P)"><path d="M54.688 29.512H44.574v10.102zm0 0" class="B E F K"/></g><linearGradient id="R" x1="55.637" y1="43.812" x2="55.637" y2="30.032" xlink:href="#AN"><stop offset=".096" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity="0"/><stop offset=".568" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".282"/><stop offset=".6" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset=".797" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".102"/></linearGradient><linearGradient id="S" x1="72.548" y1="43.812" x2="72.548" y2="30.032" xlink:href="#AN"><stop offset=".096" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity="0"/><stop offset=".568" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".282"/><stop offset=".6" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset=".797" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".102"/></linearGradient><mask id="T"><g class="C"><path d="M0 0h128v128H0z" class="B D N"/></g></mask><clipPath id="U"><path d="M0 0h128v128H0z"/></clipPath><g id="V" clip-path="url(#U)"><path d="M56.574 30.039h.352v13.773h-.352zm0 0" class="B E F I"/></g><mask id="W"><g class="C"><path d="M0 0h128v128H0z" class="B D N"/></g></mask><clipPath id="X"><path d="M0 0h128v128H0z"/></clipPath><g id="Y" clip-path="url(#X)"><path d="M71.25 30.039h.352v13.773h-.352zm0 0" class="B E F I"/></g><linearGradient id="Z" x1="35.114" y1="52.737" x2="93.071" y2="52.737" xlink:href="#AN"><stop offset=".096" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity="0"/><stop offset=".568" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".282"/><stop offset=".6" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset=".797" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".302"/><stop offset="1" stop-color="rgb(0%,79.215686%,95.686275%)" stop-opacity=".102"/></linearGradient><linearGradient id="a" x1="64.078" y1="80.597" x2="64.078" y2="107.541" xlink:href="#AN"><stop offset="0" stop-color="rgb(0%,37.254902%,55.686275%)"/><stop offset=".724" stop-color="rgb(0%,28.627451%,44.705882%)"/></linearGradient><linearGradient id="b" x1="37.714" y1="19.119" x2="90.502" y2="19.119" xlink:href="#AN"><stop offset=".204" stop-color="rgb(100%,84.705882%,7.45098%)" stop-opacity="0"/><stop offset=".782" stop-color="rgb(100%,84.705882%,7.45098%)"/></linearGradient><mask id="c"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="d"><path d="M0 0h128v128H0z"/></clipPath><g id="e" clip-path="url(#d)"><path d="M37.711 20.625H90.5l-.199-.773H37.887zm0 0" fill="rgb(70.588235%,49.019608%,30.980392%)" class="B E F"/></g><linearGradient id="f" x1="42.679" y1="47.019" x2="85.507" y2="47.019" xlink:href="#AN"><stop offset=".204" stop-color="rgb(100%,84.705882%,7.45098%)" stop-opacity="0"/><stop offset=".782" stop-color="rgb(100%,84.705882%,7.45098%)"/></linearGradient><mask id="g"><g class="C"><path d="M0 0h128v128H0z" class="B D M"/></g></mask><clipPath id="h"><path d="M0 0h128v128H0z"/></clipPath><g id="i" clip-path="url(#h)"><path d="M93.074 56.676l-.324-1.824H35.438l-.324 1.824zm0 0" class="B E F H"/></g><mask id="j"><g class="C"><path d="M0 0h128v128H0z" class="B D J"/></g></mask><clipPath id="k"><path d="M0 0h128v128H0z"/></clipPath><g id="l" clip-path="url(#k)"><path d="M47.688 107.539h32.488v.523H47.688zm0 0" class="B E F I"/></g><mask id="m"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="n"><path d="M0 0h128v128H0z"/></clipPath><g id="o" clip-path="url(#n)"><path d="M54.887 80.602h-9.473v26.063a.87.87 0 0 0 .875.875h8.586V80.602zm0 0" class="B E F H"/></g><linearGradient id="p" x1="78" y1="80.597" x2="78" y2="107.541" xlink:href="#AN"><stop offset="0" stop-color="rgb(0%,55.294118%,76.862745%)"/><stop offset=".541" stop-color="rgb(0%,44.705882%,65.490196%)"/></linearGradient><mask id="q"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><linearGradient id="r" x1="50.251" y1="85.46" x2="74.121" y2="44.116" xlink:href="#AN"><stop offset=".204" stop-color="rgb(100%,84.705882%,7.45098%)" stop-opacity="0"/><stop offset=".782" stop-color="rgb(100%,84.705882%,7.45098%)"/></linearGradient><clipPath id="s"><path d="M0 0h128v128H0z"/></clipPath><g id="t" clip-path="url(#s)"><path d="M97.836 63.125l-1.461-5.898c-.074-.328-.375-.551-.699-.551H32.477a.71.71 0 0 0-.703.551l-1.449 5.898c-.023.102-.012.199.051.289l11.086 16.887a.68.68 0 0 0 .563.301h44.141a.68.68 0 0 0 .563-.301l11.086-16.887c.023-.09.051-.187.023-.289zm0 0" fill="url(#r)" class="B E"/></g><mask id="u"><g class="C"><path d="M0 0h128v128H0z" fill-opacity=".42" class="B D"/></g></mask><clipPath id="v"><path d="M0 0h128v128H0z"/></clipPath><g id="w" clip-path="url(#v)"><path d="M45.426 80.602h37.313v2.16H45.426zm0 0" class="B E F H"/></g><mask id="x"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="y"><path d="M0 0h128v128H0z"/></clipPath><g id="z" clip-path="url(#y)"><path d="M43.512 63.074l1.527-6.176a.36.36 0 0 1 .348-.273H32.648a.71.71 0 0 0-.699.551L30.5 63.074zm0 0" class="B E F O"/></g><mask id="AA"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="AB"><path d="M0 0h128v128H0z"/></clipPath><g id="AC" clip-path="url(#AB)"><path d="M73.711 80.262l11.164-16.949h12.988c-.012.051-.027.086-.051.137L86.727 80.336a.68.68 0 0 1-.562.301H73.086a.76.76 0 0 0 .625-.375zm0 0" fill="rgb(100%,90.588235%,0%)" class="B E F"/></g><mask id="AD"><g class="C"><path d="M0 0h128v128H0z" class="B D G"/></g></mask><clipPath id="AE"><path d="M0 0h128v128H0z"/></clipPath><g id="AF" clip-path="url(#AE)"><path d="M84.824 63.125l-1.523-6.176c- [...]

2021-07-28 00:45 UTC, Panquesito7 commented on icons/towergit/towergit-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" xmlns:v="https://vecta.io/nano"><style><![CDATA[.B{filter:url(#A)}.C{stroke:none}.D{fill-ru
You're using PNG images in an SVG. Please use pure SVG format.

2021-07-28 19:08 UTC, Panquesito7 requested changes
Please replace the `class` attribute with `fill`. This PR won't be approved or merged if that's not fixed. If you need any help, let us know. You can also see [**my suggestion**](https://github.com/devicons/devicon/pull/729#discussion_r676203738) as a reference of how I did it. 🙂

2021-07-28 20:54 UTC, Panquesito7 reviewed
Sorry about your effort; although the icons look great, they do not meet our standards to be font icons. You may want to make a `line` version like in other PRs and improve the `plain` version to fulfill the font icon standards. If you need any more help, please let us know. Hope I get to understand. 🙂

2021-07-28 20:54 UTC, Panquesito7 commented on icons/towergit/towergit-original-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" version="1.1" viewBox="0 0 128 128"><defs><clipPath id="f"><path d="M0 0h128v50H0z"/></clip
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" version="1.1" viewBox="0 0 128 128"><defs><clipPath id="f"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="g"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="B"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="A"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="z"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="y"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="x"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="v"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="t"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="s"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="p"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="l"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="k"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="h"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="r"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="e"><path d="M0 0h128v50H0z"/></clipPath><clipPath id="c"><path d="M0 0h128v50H0z"/></clipPath><linearGradient id="C" x1="44.303" x2="116.064" y1="48.852" y2="48.852" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><linearGradient id="m" x1="45.74" x2="114.59" y1="81.723" y2="81.723" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><linearGradient id="b" x1="63.721" x2="92.078" y1="120.596" y2="71.481" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset=".204" stop-color="#ffd813" stop-opacity="0"/><stop offset=".781" stop-color="#ffd813" stop-opacity="1"/></linearGradient><linearGradient id="a" x1="56.983" x2="103.347" y1="63.4" y2="63.4" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset=".408" stop-color="#fff" stop-opacity="0"/><stop offset=".999" stop-color="#fff" stop-opacity="1"/></linearGradient><linearGradient id="d" x1="56.983" x2="103.347" y1="63.4" y2="63.4" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse" xlink:href="#a"/><linearGradient id="u" x1="96.686" x2="96.686" y1="114.82" y2="146.828" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#008dc4" stop-opacity="1"/><stop offset=".541" stop-color="#0072a7" stop-opacity="1"/></linearGradient><linearGradient id="n" x1="80.148" x2="80.148" y1="114.819" y2="146.828" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#005f8e" stop-opacity="1"/><stop offset=".724" stop-color="#004972" stop-opacity="1"/><stop offset=".74" stop-color="#004972" stop-opacity="1"/></linearGradient><linearGradient id="w" x1="63.721" x2="92.078" y1="120.596" y2="71.481" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse" xlink:href="#b"/><linearGradient id="o" x1="48.828" x2="111.539" y1="41.785" y2="41.785" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset=".204" stop-color="#ffd813" stop-opacity="0"/><stop offset=".781" stop-color="#ffd813" stop-opacity="1"/></linearGradient><linearGradient id="q" x1="54.726" x2="105.604" y1="74.93" y2="74.93" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset=".204" stop-color="#ffd813" stop-opacity="0"/><stop offset=".781" stop-color="#ffd813" stop-opacity="1"/></linearGradient><linearGradient id="i" x1="70.12" x2="70.12" y1="71.12" y2="54.75" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><linearGradient id="j" x1="-14909.275" x2="-14909.275" y1="71.12" y2="54.75" gradientTransform="matrix(-.26667 0 0 .26316 -3951.75 0)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient></defs><path d="m123.642 74.037-3.646-5.253c2.18-.792 3.677-2.534 3.677-5.274v-.061c0-3.51-2.45-5.603-6.487-5.603h-7.348a.532.532 0 0 0-.538.53v15.953c0 .294.24.53.538.53h2.717a.532.532 0 0 0 .538-.53v-4.923h2.99l3.523 5.217a.534.534 0 0 0 .452.236h3.134c.42 0 .687-.473.45-.822zm-3.795-10.321c0 1.444-1.045 2.385-2.897 2.385h-3.826v-4.863h3.765c1.851 0 2.99.823 2.99 2.416v.062zm-27.938-5.84h-2.841a.512.512 0 0 0-.508.382l-3.466 11.148L81.361 58.2a.521.521 0 0 0-.509-.355h-2.48c-.237 0-.418.148-.51.355L74.13 69.406l-3.466-11.15a.54.54 0 0 0-.507-.38h-2.898c-.359 0-.626.355-.509.679l5.529 16.068c.056.206.266.355.507.355h2.54a.547.547 0 0 0 .507-.355l3.765-10.763 3.768 10.763c.056.206.267.355.508.355h2.538c.236 0 .416-.149.508-.355l5.528-16.068c.056-.324-.18-.678-.538-.678zm14.82 13.652h-8.815v-3.567h7.59a.533.533 0 0 0 .537-.53v-2.27a.531.531 0 0 0-.538-.53h-7.589v-3.423h8.698a.533.533 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53H94.689a.532.532 0 0 0-.539.53v15.922c0 .294.24.53.538.53h12.041a.532.532 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53zm-49.092-13.95c-5.318 0-9.175 3.954-9.175 8.79v.056c0 4.837 3.826 8.733 9.113 8.733 5.318 0 9.174-3.953 9.174-8.789v-.056c0-4.812-3.794-8.733-9.112-8.733zm5.17 8.847c0 2.92-2.124 5.278-5.17 5.278-3.051 0-5.23-2.416-5.23-5.335v-.056c0-2.92 2.122-5.28 5.168-5.28 3.047 0 5.231 2.417 5.231 5.336zm-14.97-8.548h-13.21a.533.533 0 0 0-.539.53v2.389c0 .263.18.473.45.5h4.811v13.033c0 .294.237.53.538.53h2.72a.533.533 0 0 0 .537-.53V61.295h4.81a.527.527 0 0 0 .447-.5v-2.388c-.056-.294-.267-.53-.564-.53zm0 0" fill="#142e4a" fill-opacity="1" fill-rule="nonzero"/><path d="M10.396 81.644v.823c0 .061.056.118.118.118H21.78c.056 0 .118-.057.118-.118v-.823zm12.737-21.85H9.266v-5.458h13.867zm0 0" fill="#00caf3" fill-opacity="1" fill-rule="nonzero"/><g clip-path="url(#c)" transform="translate(-7.743 38.355) scale(1.12052)"><path d="M15.2 14.238h12.347v4.895H15.199zm0 0" fill="url(#d)" fill-rule="nonzero"/></g><g clip-path="url(#e)" transform="translate(-7.743 38.355) scale(1.12052)"><path d="M25.762 18.71h1.785v-1.76zm0 0" fill="#fff" fill-opacity="1" fill-rule="nonzero"/></g><g clip-path="url(#f)" transform="translate(-7.743 38.355) scale(1.12052)"><path d="m22.453 18.71 4.535-4.472h-6.43l-4.53 4.473zm0 0" fill="#fff" fill-opacity="1" fill-rule="nonzero"/></g><g clip-path="url(#g)" transform="translate(-7.743 38.355) scale(1.12052)"><path d="M15.2 14.238h12.374v.5H15.2zm0 0" fill="#004770" fill-opacity="1" fill-rule="nonzero"/></g><g clip-path="url(#h)" transform="translate(-7.743 38.355) scale(1.12052)"><path d="M18.398 14.238H15.2v3.157zm0 0" fill="#fff" fill-opacity="1" fill-rule="nonzero"/></g><path d="M23.133 59.829H9.266v-.499h13.867zm0 0" fill="#002b4c" fill-opacity="1" fill-rule="nonzero"/><path d="M18.883 54.515h.533v4.836h-.533zm-5.887 0h.537v4.836h-.537zm0 0" fill="#002b4c" fill-opacity="1" fill-rule="nonzero"/><path d="M18.508 14.422h.37v4.316h-.37zm0 0" fill="url(#i)" fill-rule="nonzero" transform="translate(-7.743 38.355) scale(1. [...]

2021-07-28 20:54 UTC, Panquesito7 commented on icons/towergit/towergit-original.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" version="1.1" viewBox="0 0 128 128"><defs><clipPath id="i"><path d="M0 0h128v128H0z"/></cli
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" version="1.1" viewBox="0 0 128 128"><defs><clipPath id="i"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="h"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="s"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="o"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="l"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="k"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="r"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="f"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="c"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="d"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="q"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="t"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="b"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="p"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="g"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="j"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="m"><path d="M0 0h128v128H0z"/></clipPath><mask id="Q"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".349" stroke="none"/></g></mask><mask id="S"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".2" stroke="none"/></g></mask><mask id="u"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".6" stroke="none"/></g></mask><mask id="U"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="N"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="X"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="I"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".302" stroke="none"/></g></mask><mask id="Z"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".42" stroke="none"/></g></mask><mask id="w"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".2" stroke="none"/></g></mask><mask id="ab"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="C"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".2" stroke="none"/></g></mask><mask id="ad"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="A"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="af"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="y"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".349" stroke="none"/></g></mask><mask id="ah"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".4" stroke="none"/></g></mask><mask id="G"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".302" stroke="none"/></g></mask><g id="O" clip-path="url(#b)"><path d="M37.71 20.625H90.5l-.2-.773H37.888zm0 0" fill="#b47d4f" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="ag" clip-path="url(#c)"><path d="m84.824 63.125-1.523-6.176a.364.364 0 0 0-.352-.273h12.739c.335 0 .624.222.699.55l1.449 5.9zm0 0" fill="#ff0" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="Y" clip-path="url(#d)"><path d="m97.836 63.125-1.46-5.898a.718.718 0 0 0-.7-.55h-63.2a.712.712 0 0 0-.703.55l-1.449 5.9a.348.348 0 0 0 .05.287L41.461 80.3c.125.187.34.3.562.3h44.14a.681.681 0 0 0 .564-.3l11.085-16.887c.024-.09.05-.187.024-.29zm0 0" fill="url(#e)" fill-rule="nonzero" stroke="none"/></g><g id="x" clip-path="url(#f)"><path d="M77.96 43.813h5.653v-5.649zm0 0" fill="#fff" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="ai" clip-path="url(#g)"><path d="M30.29 63.273h67.585l-.164-.636H30.438zm0 0" fill="#ff0" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="aa" clip-path="url(#h)"><path d="M45.426 80.602h37.312v2.16H45.426zm0 0" fill="#002d4f" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="H" clip-path="url(#i)"><path d="M56.574 30.04h.352v13.773h-.352zm0 0" fill="#004972" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="R" clip-path="url(#j)"><path d="m93.074 56.676-.324-1.824H35.437l-.324 1.824zm0 0" fill="#002d4f" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="ac" clip-path="url(#k)"><path d="m43.512 63.074 1.527-6.176a.36.36 0 0 1 .348-.273H32.648a.712.712 0 0 0-.699.55l-1.45 5.9zm0 0" fill="#cd7f1f" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="B" clip-path="url(#l)"><path d="M44.574 29.512h39.028v1.562H44.574zm0 0" fill="#004972" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="v" clip-path="url(#m)"><path d="M44.574 29.512h39.04v15.601h-39.04zm0 0" fill="url(#n)" fill-rule="nonzero" stroke="none"/></g><g id="ae" clip-path="url(#o)"><path d="m73.71 80.262 11.165-16.95h12.988a.647.647 0 0 1-.05.137L86.727 80.336a.681.681 0 0 1-.563.3H73.086a.76.76 0 0 0 .625-.374zm0 0" fill="#ffe700" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="T" clip-path="url(#p)"><path d="M47.688 107.54h32.488v.522h-32.49zm0 0" fill="#004972" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="J" clip-path="url(#q)"><path d="M71.25 30.04h.352v13.773h-.352zm0 0" fill="#004972" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="D" clip-path="url(#r)"><path d="M54.688 29.512H44.573v10.101zm0 0" fill="#fff" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="z" clip-path="url(#s)"><path d="m67.477 43.813 14.296-14.301H61.477l-14.301 14.3zm0 0" fill="#fff" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><g id="V" clip-path="url(#t)"><path d="M54.887 80.602h-9.473v26.062c0 .484.387.875.875.875h8.586V80.602zm0 0" fill="#002d4f" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><linearGradient id="e" x1="402.006" x2="592.967" y1="683.678" y2="352.925" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".204" stop-color="#ffd813" stop-opacity="0"/><stop offset=".781" stop-color="#ffd813" stop-opacity="1"/></linearGradient><linearGradient id="n" x1="356.628" x2="668.854" y1="298.508" y2="298.508" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".408" stop-color="#fff" stop-opacity="0"/><stop offset=".999" stop-color="#fff" stop-opacity="1"/></linearGradient><linearGradient id="E" x1="445.097" x2="445.097" y1="350.498" y2="240.257" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><linearGradient id="F" x1="-13963.451" x2="-13963.451" y1="350.498" y2="240.257" gradientTransform="matrix(-.125 0 0 .125 -1672.883 0)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><linearGradient id="aj" x1="271.237" x2="754.495" y1="200.537" y2="200.537" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><linearGradient id="P" x1="341.428" x2="684.054" y1="376.1 [...]

2021-07-28 23:22 UTC, Panquesito7 commented on devicon.json
> +				"line"
```suggestion
                "original",
                "original-wordmark",
                "plain",
                "line"
```

2021-07-28 23:22 UTC, Panquesito7 commented on devicon.json
> +				"line"
```suggestion
                "plain",
                "line"
```

2021-07-29 18:42 UTC, Panquesito7 reviewed
I'm not sure why the `line` version looks like that. Hopefully, optimizing it will fix it with the suggestion below.

2021-07-29 18:42 UTC, Panquesito7 commented on icons/towergit/towergit-line.svg
> +</svg>
```suggestion
<svg width="128" height="128" viewBox="0 0 128 128" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><defs><clipPath id="i"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="h"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="s"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="o"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="l"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="k"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="r"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="f"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="c"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="d"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="q"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="t"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="b"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="p"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="g"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="j"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="m"><path d="M0 0h128v128H0z"/></clipPath><linearGradient id="e" x1="402.006" x2="592.967" y1="683.678" y2="352.925" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".204" stop-color="#ffd813" stop-opacity="0"/><stop offset=".781" stop-color="#ffd813"/></linearGradient><linearGradient id="n" x1="356.628" x2="668.854" y1="298.508" y2="298.508" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".408" stop-color="#fff" stop-opacity="0"/><stop offset=".999" stop-color="#fff"/></linearGradient><filter id="a" width="1" height="1" x="0" y="0" filterUnits="objectBoundingBox"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><mask id="u"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill-opacity=".2"/></g></mask><g id="v" clip-path="url(#p)"><path d="M47.688 107.54h32.488v.522h-32.49zm0 0" fill="#004972"/></g></defs><path style="stroke:#000;stroke-opacity:1;fill:none" d="M55.051 30.04h1.523v13.773h-1.523zM44.585 30.037h1.523V43.81h-1.523zM71.613 30.04h1.524v13.773h-1.524zM82.085 30.037h1.523V43.81h-1.523z"/><path d="M83.61 45.23H44.585v-1.42h39.023z" fill="#002d4f" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="m85.512 48.8-.586-3.277a.353.353 0 0 0-.352-.296h-40.96a.353.353 0 0 0-.352.296l-.586 3.278zm0 0" fill="#ffc600" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="m93.074 56.676-1.363-7.574a.346.346 0 0 0-.348-.3H36.824a.346.346 0 0 0-.347.301l-1.364 7.574zm0 0" fill="#002d4f" style="stroke:#000;stroke-opacity:1;fill:none"/><path style="stroke:#000;stroke-opacity:1;fill:none" d="M45.426 80.602v26.062a.87.87 0 0 0 .875.875h35.55c.485 0 .876-.39.876-.875V80.602z"/><path d="M36.824 48.8a.346.346 0 0 0-.347.302l-.016.074h55.266l-.016-.074a.346.346 0 0 0-.348-.301zm0 0" fill="#002d4f" style="stroke:#000;stroke-opacity:1"/><path d="M37.71 20.625H90.5l-.727-2.7a.411.411 0 0 0-.398-.3H38.727a.43.43 0 0 0-.403.313zm0 0" fill="#ffc600" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="M35.563 30.04h57.085c.141 0 .25-.102.278-.227l1.398-9.188H33.898l1.391 9.188a.28.28 0 0 0 .273.226zm0 0" fill="#002d4f" style="stroke:#000;stroke-opacity:1;fill:none"/><use mask="url(#u)" xlink:href="#v" style="stroke:#000;stroke-opacity:1"/><path d="m97.836 63.125-1.46-5.898a.718.718 0 0 0-.7-.55h-63.2a.712.712 0 0 0-.703.55l-1.449 5.9a.348.348 0 0 0 .05.287L41.461 80.3c.125.187.34.3.562.3h44.14a.681.681 0 0 0 .564-.3l11.085-16.887c.024-.09.05-.187.024-.29zm0 0" fill="#ffc600" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="M43.613 45.238a.353.353 0 0 0-.351.301l-.024.125h41.7l-.024-.125a.353.353 0 0 0-.352-.3zm0 0" fill="#fff203" style="stroke:#000;stroke-opacity:1"/></svg>
```

2021-07-29 18:42 UTC, Panquesito7 commented on icons/towergit/towergit-line.svg
> +</svg>
```suggestion
<svg width="128" height="128" viewBox="0 0 128 128" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><defs><clipPath id="i"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="h"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="s"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="o"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="l"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="k"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="r"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="f"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="c"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="d"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="q"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="t"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="b"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="p"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="g"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="j"><path d="M0 0h128v128H0z"/></clipPath><clipPath id="m"><path d="M0 0h128v128H0z"/></clipPath><linearGradient id="e" x1="402.006" x2="592.967" y1="683.678" y2="352.925" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".204" stop-color="#ffd813" stop-opacity="0"/><stop offset=".781" stop-color="#ffd813"/></linearGradient><linearGradient id="n" x1="356.628" x2="668.854" y1="298.508" y2="298.508" gradientTransform="scale(.125)" gradientUnits="userSpaceOnUse"><stop offset=".408" stop-color="#fff" stop-opacity="0"/><stop offset=".999" stop-color="#fff"/></linearGradient><filter id="a" width="1" height="1" x="0" y="0" filterUnits="objectBoundingBox"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><mask id="u"><g filter="url(#a)"><path d="M0 0h128v128H0z" fill-opacity=".2"/></g></mask><g id="v" clip-path="url(#p)"><path d="M47.688 107.54h32.488v.522h-32.49zm0 0" fill="#004972"/></g></defs><path style="stroke:#000;stroke-opacity:1;fill:none" d="M55.051 30.04h1.523v13.773h-1.523zM44.585 30.037h1.523V43.81h-1.523zM71.613 30.04h1.524v13.773h-1.524zM82.085 30.037h1.523V43.81h-1.523z"/><path d="M83.61 45.23H44.585v-1.42h39.023z" fill="#002d4f" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="m85.512 48.8-.586-3.277a.353.353 0 0 0-.352-.296h-40.96a.353.353 0 0 0-.352.296l-.586 3.278zm0 0" fill="#ffc600" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="m93.074 56.676-1.363-7.574a.346.346 0 0 0-.348-.3H36.824a.346.346 0 0 0-.347.301l-1.364 7.574zm0 0" fill="#002d4f" style="stroke:#000;stroke-opacity:1;fill:none"/><path style="stroke:#000;stroke-opacity:1;fill:none" d="M45.426 80.602v26.062a.87.87 0 0 0 .875.875h35.55c.485 0 .876-.39.876-.875V80.602z"/><path d="M36.824 48.8a.346.346 0 0 0-.347.302l-.016.074h55.266l-.016-.074a.346.346 0 0 0-.348-.301zm0 0" fill="#002d4f" style="stroke:#000;stroke-opacity:1"/><path d="M37.71 20.625H90.5l-.727-2.7a.411.411 0 0 0-.398-.3H38.727a.43.43 0 0 0-.403.313zm0 0" fill="#ffc600" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="M35.563 30.04h57.085c.141 0 .25-.102.278-.227l1.398-9.188H33.898l1.391 9.188a.28.28 0 0 0 .273.226zm0 0" fill="#002d4f" style="stroke:#000;stroke-opacity:1;fill:none"/><use mask="url(#u)" xlink:href="#v" style="stroke:#000;stroke-opacity:1"/><path d="m97.836 63.125-1.46-5.898a.718.718 0 0 0-.7-.55h-63.2a.712.712 0 0 0-.703.55l-1.449 5.9a.348.348 0 0 0 .05.287L41.461 80.3c.125.187.34.3.562.3h44.14a.681.681 0 0 0 .564-.3l11.085-16.887c.024-.09.05-.187.024-.29zm0 0" fill="#ffc600" style="stroke:#000;stroke-opacity:1;fill:none"/><path d="M43.613 45.238a.353.353 0 0 0-.351.301l-.024.125h41.7l-.024-.125a.353.353 0 0 0-.352-.3zm0 0" fill="#fff203" style="stroke:#000;stroke-opacity:1"/></svg>
```

2021-07-29 18:42 UTC, Panquesito7 commented on icons/towergit/towergit-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><defs><clipPath ><path d="M0 0h128v12
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><defs><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath id="H"><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><clipPath ><path d="M0 0h128v128H0z"/></clipPath><mask id="R"><g filter="url(#T)"><path d="M0 0h128v128H0z" fill="#000" fill-opacity=".2" stroke="none"/></g></mask><g id="S" clip-path="url(#H)"><path d="M77.96 43.813h5.653v-5.649zm0 0" fill="#fff" fill-opacity="1" fill-rule="nonzero" stroke="none"/></g><filter id="T" width="1" height="1" x="0" y="0"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><path id="U" d="m85.512 48.8-.586-3.277a.353.353 0 0 0-.352-.296h-40.96a.353.353 0 0 0-.352.296l-.586 3.278zm0 0"/><path id="V" d="M37.71 20.625H90.5l-.727-2.7a.411.411 0 0 0-.398-.3H38.727a.43.43 0 0 0-.403.313zm0 0"/></defs><use mask="url(#R)" xlink:href="#S"/><g fill="#ffc600"><path d="M83.61 45.23H44.585v-1.42h39.023zM71.613 30.04h1.524v13.773h-1.524zm-16.562 0h1.523v13.773h-1.523zm0 0"/><path d="M82.09 30.04h1.523v13.773H82.09zm-37.505-.003h1.524V43.81h-1.524z"/><use xlink:href="#U"/><use xlink:href="#V"/></g><g fill="#ffd813"><use xlink:href="#V" fill-opacity="0"/><use xlink:href="#U" fill-opacity="0"/></g><path d="M97.836 63.125l-1.46-5.898a.718.718 0 0 0-.7-.55h-63.2a.712.712 0 0 0-.703.55l-1.449 5.9a.348.348 0 0 0 .05.287L41.461 80.3a.68.68 0 0 0 .562.3h44.14a.681.681 0 0 0 .564-.3l11.085-16.887c.024-.09.05-.187.024-.29zm-61.999-7.361c.108-.434 1.049-5.667 1.05-5.833 0-.065 12.237-.118 27.192-.118l27.192.05c0 .028.247 1.393.55 3.034L92.372 56c.001.065-12.739.118-28.311.118H35.749zm-.054-26.426c0-.077-.248-1.757-.552-3.733l-.552-3.722c0-.071 13.251-.129 29.446-.129h29.446l-.59 3.823-.599 3.862c-.028.119-56.601.018-56.601-.101zm10.124 77.924l-.35-.245V93.863 80.709h18.522 18.522v13.154 13.154l-.35.245c-.312.219-2.297.245-18.172.245s-17.86-.027-18.172-.245zm1.962 2.821c-.058-.058-.106-.555-.106-1.104v-.998h16.165 16.165l-.047 1.064-.047 1.064-16.012.04c-8.807.022-16.06-.007-16.118-.066z" fill="#ffc600"/></svg>

```

2021-07-29 23:59 UTC, Panquesito7 commented on icons/towergit/towergit-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><defs><clipPath ><path d="M0 0h128v12
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="128" height="128" viewBox="0 0 128 128" xmlns:v="https://vecta.io/nano"><defs><clipPath ><path d="M0 0h128v128H0z"/></clipPath><filter  width="1" height="1" x="0" y="0"><feColorMatrix in="SourceGraphic" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><path id="C" d="m85.512 48.8-.586-3.277a.353.353 0 0 0-.352-.296h-40.96a.353.353 0 0 0-.352.296l-.586 3.278zm0 0"/><path id="D" d="M37.71 20.625H90.5l-.727-2.7a.411.411 0 0 0-.398-.3H38.727a.43.43 0 0 0-.403.313zm0 0"/></defs><g fill="#ffc600"><path d="M83.61 45.23H44.585v-1.42h39.023zM71.613 30.04h1.524v13.773h-1.524zm-16.562 0h1.523v13.773h-1.523zm0 0"/><path d="M82.09 30.04h1.523v13.773H82.09zm-37.505-.003h1.524V43.81h-1.524z"/><use xlink:href="#C"/><use xlink:href="#D"/></g><g fill="#ffd813"><use xlink:href="#D" fill-opacity="0"/><use xlink:href="#C" fill-opacity="0"/></g><path d="M97.836 63.125l-1.46-5.898a.718.718 0 0 0-.7-.55h-63.2a.712.712 0 0 0-.703.55l-1.449 5.9a.348.348 0 0 0 .05.287L41.461 80.3a.68.68 0 0 0 .562.3h44.14a.681.681 0 0 0 .564-.3l11.085-16.887c.024-.09.05-.187.024-.29zm-61.999-7.361c.108-.434 1.049-5.667 1.05-5.833 0-.065 12.237-.118 27.192-.118l27.192.05c0 .028.247 1.393.55 3.034L92.372 56c.001.065-12.739.118-28.311.118H35.749zm-.054-26.426c0-.077-.248-1.757-.552-3.733l-.552-3.722c0-.071 13.251-.129 29.446-.129h29.446l-.59 3.823-.599 3.862c-.028.119-56.601.018-56.601-.101zm10.124 77.924l-.35-.245V93.863 80.709h18.522 18.522v13.154 13.154l-.35.245c-.312.219-2.297.245-18.172.245s-17.86-.027-18.172-.245zm1.962 2.821c-.058-.058-.106-.555-.106-1.104v-.998h16.165 16.165l-.047 1.064-.047 1.064-16.012.04c-8.807.022-16.06-.007-16.118-.066z" fill="#ffc600"/></svg>

```

2021-07-30 18:30 UTC, Panquesito7 requested changes
Please fix the `line` version looking like that. I don't really know why does it look like that, though. @Thomas-Boi, thoughts? 🤔

2021-08-01 00:33 UTC, Thomas-Boi commented
@MichielPater and @Panquesito7 I honestly have no clue why the line looks strange like that. I uploaded it manually to Icomoon and the same thing happened. There was no error message either.

I think the `plain` version alone should be fine. Can you remove the `line` version and update the `devicon.json` so it's proper? I think we'll accept your PR once that is done.

2021-08-05 17:51 UTC, Panquesito7 requested changes
Please make a `plain-wordmark` version. Like the `plain` version, but with the text. 🙂

2021-08-07 05:22 UTC, Thomas-Boi commented
Hi @MichielPater,

The `plain` version looks great now! If possible, can you add a `plain-wordmark` version as well since it's feasible? If you don't want to, that's fine and we can merge the PR as is 😄.

2021-08-08 00:40 UTC, Thomas-Boi commented on devicon.json
> +                "plain"
```suggestion
                "plain",
                "plain-wordmark"
```

2021-08-08 00:41 UTC, Panquesito7 requested changes

2021-08-08 00:41 UTC, Panquesito7 commented on devicon.json
> +                "plain"
```suggestion
                "plain",
                "plain-wordmark"
```

2021-08-08 00:41 UTC, Panquesito7 commented on icons/towergit/towergit-plain-wordmark.svg
> +</svg>
```suggestion
<svg width="128" height="128" viewBox="0 128 128" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="b" x1="80.148" x2="80.148" y1="114.819" y2="146.828" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#005f8e"/><stop offset=".724" stop-color="#004972"/><stop offset=".74" stop-color="#004972"/></linearGradient><linearGradient id="a" x1="-14909.275" x2="-14909.275" y1="71.12" y2="54.75" gradientTransform="matrix(-.26667 0 0 .26316 -3951.75 0)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><clipPath id="c"><path d="M0 0h128v50H0z"/></clipPath></defs><path d="m123.642 74.037-3.646-5.253c2.18-.792 3.677-2.534 3.677-5.274v-.061c0-3.51-2.45-5.603-6.487-5.603h-7.348a.532.532 0 0 0-.538.53v15.953c0 .294.24.53.538.53h2.717a.532.532 0 0 0 .538-.53v-4.923h2.99l3.523 5.217a.534.534 0 0 0 .452.236h3.134c.42 0 .687-.473.45-.822zm-3.795-10.321c0 1.444-1.045 2.385-2.897 2.385h-3.826v-4.863h3.765c1.851 0 2.99.823 2.99 2.416v.062zm-27.938-5.84h-2.841a.512.512 0 0 0-.508.382l-3.466 11.148L81.361 58.2a.521.521 0 0 0-.509-.355h-2.48c-.237 0-.418.148-.51.355L74.13 69.406l-3.466-11.15a.54.54 0 0 0-.507-.38h-2.898c-.359 0-.626.355-.509.679l5.529 16.068c.056.206.266.355.507.355h2.54a.547.547 0 0 0 .507-.355l3.765-10.763 3.768 10.763c.056.206.267.355.508.355h2.538c.236 0 .416-.149.508-.355l5.528-16.068c.056-.324-.18-.678-.538-.678zm14.82 13.652h-8.815v-3.567h7.59a.533.533 0 0 0 .537-.53v-2.27a.531.531 0 0 0-.538-.53h-7.589v-3.423h8.698a.533.533 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53H94.689a.532.532 0 0 0-.539.53v15.922c0 .294.24.53.538.53h12.041a.532.532 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53zm-49.092-13.95c-5.318 0-9.175 3.954-9.175 8.79v.056c0 4.837 3.826 8.733 9.113 8.733 5.318 0 9.174-3.953 9.174-8.789v-.056c0-4.812-3.794-8.733-9.112-8.733zm5.17 8.847c0 2.92-2.124 5.278-5.17 5.278-3.051 0-5.23-2.416-5.23-5.335v-.056c0-2.92 2.122-5.28 5.168-5.28 3.047 0 5.231 2.417 5.231 5.336zm-14.97-8.548h-13.21a.533.533 0 0 0-.539.53v2.389c0 .263.18.473.45.5h4.811v13.033c0 .294.237.53.538.53h2.72a.533.533 0 0 0 .537-.53V61.295h4.81a.527.527 0 0 0 .447-.5v-2.388c-.056-.294-.267-.53-.564-.53zm0 0" fill="#142e4a" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M10.396 81.644v.823c0 .061.056.118.118.118H21.78c.056 0 .118-.057.118-.118v-.823z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M23.133 59.829H9.266v-.499h13.867zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M12.996 54.515h.537v4.836h-.537zm5.887 0h.533v4.836h-.533zm3.717-.021h.533v4.836H22.6z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M23.867 14.422h.371v4.316h-.37zm0 0" fill="url(#a)" transform="translate(-7.743 38.355) scale(1.12052)" style="fill:#ffc600;fill-opacity:1;stroke:none"/><path d="m23.81 61.059-.209-1.147c0-.06-.057-.092-.118-.092H8.93c-.056 0-.118.031-.118.092l-.21 1.147zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="m26.499 63.833-.477-2.655c0-.059-.062-.089-.12-.089H6.54c-.062 0-.119.03-.119.088l-.477 2.656zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M15.465 30.21v8.157c0 .16.137.266.27.266h11.253c.16 0 .266-.133.266-.266v-8.156zm0 0" fill="url(#b)" transform="translate(-7.743 38.355) scale(1.12052)" style="stroke:none;stroke-opacity:1;fill:#ffc600;fill-opacity:1"/><path d="M6.837 51.21h18.738l-.272-.94c-.03-.062-.056-.12-.149-.12H7.196c-.056 0-.118.058-.15.12zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><g clip-path="url(#c)" transform="translate(-7.743 38.355) scale(1.12052)" style="stroke:none;fill:#ffc600;fill-opacity:1"><path d="M13.012 11.473h16.722l-.054-.235H13.066zm0 0" fill="#b37d4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/></g><path d="M6.093 54.515H26.35c.06 0 .092-.03.092-.087l.507-3.217H5.494L6 54.427c0 .027.03.088.092.088zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="m28.201 66.101-.508-2.061c-.025-.12-.117-.207-.235-.207H4.984c-.118 0-.21.088-.235.207l-.514 2.06c0 .03 0 .06.032.092L8.21 72.12c.03.056.122.117.21.117h15.655c.092 0 .154-.03.211-.117l3.944-5.928c-.031-.03-.031-.06-.031-.09zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M9.266 54.494h.533v4.836h-.533z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0200612;stroke-opacity:1" d="M6.028 54.457a57.5 57.5 0 0 1-.27-1.64l-.252-1.595 10.708-.005c5.89-.003 10.712-.002 10.716.002.01.01-.5 3.239-.516 3.264-.009.014-3.165.02-10.19.019l-10.176-.001-.02-.044zm.836-3.309.024-.118.013-.074h18.611l.013.074c.006.04.017.093.024.118l.012.044H6.853zm15.737 5.778v-2.404h.532v4.808h-.532zm-3.704.01v-2.414h.512v4.828h-.512zm-5.892 0v-2.414h.512v4.828h-.512zm-3.725-.02v-2.414h.513v4.828h-.512z"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0200612;stroke-opacity:1" d="M9.28 59.567v-.237h1.852c1.213 0 1.855.007 1.863.02.016.026.542.026.542 0 0-.028 5.333-.028 5.35 0 .016.026.516.026.532 0 .008-.013.65-.02 1.863-.02h1.851v.473H9.281zm-3.316 4.211.242-1.342c.155-.866.242-1.303.26-1.315.015-.01 4.288-.017 9.763-.017 7.849 0 9.74.004 9.757.024.016.019.497 2.619.497 2.683 0 .007-4.619.012-10.264.012H5.956z"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0283709;stroke-opacity:1" d="M9.716 81.563a.359.359 0 0 1-.101-.16c-.02-.069-.029-1.612-.029-4.624v-4.522h13.209v4.522c0 3.012-.01 4.555-.03 4.624a.359.359 0 0 1-.1.16l-.073.057H9.789zm.741.987c-.026-.011-.035-.13-.035-.458v-.444h11.453v.427c0 .294-.01.436-.033.46-.026.025-1.326.032-5.692.03a585.332 585.332 0 0 1-5.693-.016z"/></svg>

```

2021-08-08 00:41 UTC, Panquesito7 commented on icons/towergit/towergit-plain-wordmark.svg
> +</svg>
```suggestion
<svg width="128" height="128" viewBox="0 128 128" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="b" x1="80.148" x2="80.148" y1="114.819" y2="146.828" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#005f8e"/><stop offset=".724" stop-color="#004972"/><stop offset=".74" stop-color="#004972"/></linearGradient><linearGradient id="a" x1="-14909.275" x2="-14909.275" y1="71.12" y2="54.75" gradientTransform="matrix(-.26667 0 0 .26316 -3951.75 0)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><clipPath id="c"><path d="M0 0h128v50H0z"/></clipPath></defs><path d="m123.642 74.037-3.646-5.253c2.18-.792 3.677-2.534 3.677-5.274v-.061c0-3.51-2.45-5.603-6.487-5.603h-7.348a.532.532 0 0 0-.538.53v15.953c0 .294.24.53.538.53h2.717a.532.532 0 0 0 .538-.53v-4.923h2.99l3.523 5.217a.534.534 0 0 0 .452.236h3.134c.42 0 .687-.473.45-.822zm-3.795-10.321c0 1.444-1.045 2.385-2.897 2.385h-3.826v-4.863h3.765c1.851 0 2.99.823 2.99 2.416v.062zm-27.938-5.84h-2.841a.512.512 0 0 0-.508.382l-3.466 11.148L81.361 58.2a.521.521 0 0 0-.509-.355h-2.48c-.237 0-.418.148-.51.355L74.13 69.406l-3.466-11.15a.54.54 0 0 0-.507-.38h-2.898c-.359 0-.626.355-.509.679l5.529 16.068c.056.206.266.355.507.355h2.54a.547.547 0 0 0 .507-.355l3.765-10.763 3.768 10.763c.056.206.267.355.508.355h2.538c.236 0 .416-.149.508-.355l5.528-16.068c.056-.324-.18-.678-.538-.678zm14.82 13.652h-8.815v-3.567h7.59a.533.533 0 0 0 .537-.53v-2.27a.531.531 0 0 0-.538-.53h-7.589v-3.423h8.698a.533.533 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53H94.689a.532.532 0 0 0-.539.53v15.922c0 .294.24.53.538.53h12.041a.532.532 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53zm-49.092-13.95c-5.318 0-9.175 3.954-9.175 8.79v.056c0 4.837 3.826 8.733 9.113 8.733 5.318 0 9.174-3.953 9.174-8.789v-.056c0-4.812-3.794-8.733-9.112-8.733zm5.17 8.847c0 2.92-2.124 5.278-5.17 5.278-3.051 0-5.23-2.416-5.23-5.335v-.056c0-2.92 2.122-5.28 5.168-5.28 3.047 0 5.231 2.417 5.231 5.336zm-14.97-8.548h-13.21a.533.533 0 0 0-.539.53v2.389c0 .263.18.473.45.5h4.811v13.033c0 .294.237.53.538.53h2.72a.533.533 0 0 0 .537-.53V61.295h4.81a.527.527 0 0 0 .447-.5v-2.388c-.056-.294-.267-.53-.564-.53zm0 0" fill="#142e4a" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M10.396 81.644v.823c0 .061.056.118.118.118H21.78c.056 0 .118-.057.118-.118v-.823z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M23.133 59.829H9.266v-.499h13.867zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M12.996 54.515h.537v4.836h-.537zm5.887 0h.533v4.836h-.533zm3.717-.021h.533v4.836H22.6z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M23.867 14.422h.371v4.316h-.37zm0 0" fill="url(#a)" transform="translate(-7.743 38.355) scale(1.12052)" style="fill:#ffc600;fill-opacity:1;stroke:none"/><path d="m23.81 61.059-.209-1.147c0-.06-.057-.092-.118-.092H8.93c-.056 0-.118.031-.118.092l-.21 1.147zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="m26.499 63.833-.477-2.655c0-.059-.062-.089-.12-.089H6.54c-.062 0-.119.03-.119.088l-.477 2.656zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M15.465 30.21v8.157c0 .16.137.266.27.266h11.253c.16 0 .266-.133.266-.266v-8.156zm0 0" fill="url(#b)" transform="translate(-7.743 38.355) scale(1.12052)" style="stroke:none;stroke-opacity:1;fill:#ffc600;fill-opacity:1"/><path d="M6.837 51.21h18.738l-.272-.94c-.03-.062-.056-.12-.149-.12H7.196c-.056 0-.118.058-.15.12zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><g clip-path="url(#c)" transform="translate(-7.743 38.355) scale(1.12052)" style="stroke:none;fill:#ffc600;fill-opacity:1"><path d="M13.012 11.473h16.722l-.054-.235H13.066zm0 0" fill="#b37d4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/></g><path d="M6.093 54.515H26.35c.06 0 .092-.03.092-.087l.507-3.217H5.494L6 54.427c0 .027.03.088.092.088zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="m28.201 66.101-.508-2.061c-.025-.12-.117-.207-.235-.207H4.984c-.118 0-.21.088-.235.207l-.514 2.06c0 .03 0 .06.032.092L8.21 72.12c.03.056.122.117.21.117h15.655c.092 0 .154-.03.211-.117l3.944-5.928c-.031-.03-.031-.06-.031-.09zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M9.266 54.494h.533v4.836h-.533z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0200612;stroke-opacity:1" d="M6.028 54.457a57.5 57.5 0 0 1-.27-1.64l-.252-1.595 10.708-.005c5.89-.003 10.712-.002 10.716.002.01.01-.5 3.239-.516 3.264-.009.014-3.165.02-10.19.019l-10.176-.001-.02-.044zm.836-3.309.024-.118.013-.074h18.611l.013.074c.006.04.017.093.024.118l.012.044H6.853zm15.737 5.778v-2.404h.532v4.808h-.532zm-3.704.01v-2.414h.512v4.828h-.512zm-5.892 0v-2.414h.512v4.828h-.512zm-3.725-.02v-2.414h.513v4.828h-.512z"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0200612;stroke-opacity:1" d="M9.28 59.567v-.237h1.852c1.213 0 1.855.007 1.863.02.016.026.542.026.542 0 0-.028 5.333-.028 5.35 0 .016.026.516.026.532 0 .008-.013.65-.02 1.863-.02h1.851v.473H9.281zm-3.316 4.211.242-1.342c.155-.866.242-1.303.26-1.315.015-.01 4.288-.017 9.763-.017 7.849 0 9.74.004 9.757.024.016.019.497 2.619.497 2.683 0 .007-4.619.012-10.264.012H5.956z"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0283709;stroke-opacity:1" d="M9.716 81.563a.359.359 0 0 1-.101-.16c-.02-.069-.029-1.612-.029-4.624v-4.522h13.209v4.522c0 3.012-.01 4.555-.03 4.624a.359.359 0 0 1-.1.16l-.073.057H9.789zm.741.987c-.026-.011-.035-.13-.035-.458v-.444h11.453v.427c0 .294-.01.436-.033.46-.026.025-1.326.032-5.692.03a585.332 585.332 0 0 1-5.693-.016z"/></svg>

```

2021-08-08 00:41 UTC, Panquesito7 commented on icons/towergit/towergit-plain-wordmark.svg
> +</svg>
```suggestion
<svg width="128" height="128" viewBox="0 128 128" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="b" x1="80.148" x2="80.148" y1="114.819" y2="146.828" gradientTransform="scale(.26667 .26316)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#005f8e"/><stop offset=".724" stop-color="#004972"/><stop offset=".74" stop-color="#004972"/></linearGradient><linearGradient id="a" x1="-14909.275" x2="-14909.275" y1="71.12" y2="54.75" gradientTransform="matrix(-.26667 0 0 .26316 -3951.75 0)" gradientUnits="userSpaceOnUse"><stop offset=".096" stop-color="#00caf4" stop-opacity="0"/><stop offset=".568" stop-color="#00caf4" stop-opacity=".282"/><stop offset=".6" stop-color="#00caf4" stop-opacity=".302"/><stop offset=".797" stop-color="#00caf4" stop-opacity=".302"/><stop offset="1" stop-color="#00caf4" stop-opacity=".102"/></linearGradient><clipPath id="c"><path d="M0 0h128v50H0z"/></clipPath></defs><path d="m123.642 74.037-3.646-5.253c2.18-.792 3.677-2.534 3.677-5.274v-.061c0-3.51-2.45-5.603-6.487-5.603h-7.348a.532.532 0 0 0-.538.53v15.953c0 .294.24.53.538.53h2.717a.532.532 0 0 0 .538-.53v-4.923h2.99l3.523 5.217a.534.534 0 0 0 .452.236h3.134c.42 0 .687-.473.45-.822zm-3.795-10.321c0 1.444-1.045 2.385-2.897 2.385h-3.826v-4.863h3.765c1.851 0 2.99.823 2.99 2.416v.062zm-27.938-5.84h-2.841a.512.512 0 0 0-.508.382l-3.466 11.148L81.361 58.2a.521.521 0 0 0-.509-.355h-2.48c-.237 0-.418.148-.51.355L74.13 69.406l-3.466-11.15a.54.54 0 0 0-.507-.38h-2.898c-.359 0-.626.355-.509.679l5.529 16.068c.056.206.266.355.507.355h2.54a.547.547 0 0 0 .507-.355l3.765-10.763 3.768 10.763c.056.206.267.355.508.355h2.538c.236 0 .416-.149.508-.355l5.528-16.068c.056-.324-.18-.678-.538-.678zm14.82 13.652h-8.815v-3.567h7.59a.533.533 0 0 0 .537-.53v-2.27a.531.531 0 0 0-.538-.53h-7.589v-3.423h8.698a.533.533 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53H94.689a.532.532 0 0 0-.539.53v15.922c0 .294.24.53.538.53h12.041a.532.532 0 0 0 .538-.53v-2.271a.533.533 0 0 0-.538-.53zm-49.092-13.95c-5.318 0-9.175 3.954-9.175 8.79v.056c0 4.837 3.826 8.733 9.113 8.733 5.318 0 9.174-3.953 9.174-8.789v-.056c0-4.812-3.794-8.733-9.112-8.733zm5.17 8.847c0 2.92-2.124 5.278-5.17 5.278-3.051 0-5.23-2.416-5.23-5.335v-.056c0-2.92 2.122-5.28 5.168-5.28 3.047 0 5.231 2.417 5.231 5.336zm-14.97-8.548h-13.21a.533.533 0 0 0-.539.53v2.389c0 .263.18.473.45.5h4.811v13.033c0 .294.237.53.538.53h2.72a.533.533 0 0 0 .537-.53V61.295h4.81a.527.527 0 0 0 .447-.5v-2.388c-.056-.294-.267-.53-.564-.53zm0 0" fill="#142e4a" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M10.396 81.644v.823c0 .061.056.118.118.118H21.78c.056 0 .118-.057.118-.118v-.823z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M23.133 59.829H9.266v-.499h13.867zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M12.996 54.515h.537v4.836h-.537zm5.887 0h.533v4.836h-.533zm3.717-.021h.533v4.836H22.6z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M23.867 14.422h.371v4.316h-.37zm0 0" fill="url(#a)" transform="translate(-7.743 38.355) scale(1.12052)" style="fill:#ffc600;fill-opacity:1;stroke:none"/><path d="m23.81 61.059-.209-1.147c0-.06-.057-.092-.118-.092H8.93c-.056 0-.118.031-.118.092l-.21 1.147zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="m26.499 63.833-.477-2.655c0-.059-.062-.089-.12-.089H6.54c-.062 0-.119.03-.119.088l-.477 2.656zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M15.465 30.21v8.157c0 .16.137.266.27.266h11.253c.16 0 .266-.133.266-.266v-8.156zm0 0" fill="url(#b)" transform="translate(-7.743 38.355) scale(1.12052)" style="stroke:none;stroke-opacity:1;fill:#ffc600;fill-opacity:1"/><path d="M6.837 51.21h18.738l-.272-.94c-.03-.062-.056-.12-.149-.12H7.196c-.056 0-.118.058-.15.12zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><g clip-path="url(#c)" transform="translate(-7.743 38.355) scale(1.12052)" style="stroke:none;fill:#ffc600;fill-opacity:1"><path d="M13.012 11.473h16.722l-.054-.235H13.066zm0 0" fill="#b37d4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/></g><path d="M6.093 54.515H26.35c.06 0 .092-.03.092-.087l.507-3.217H5.494L6 54.427c0 .027.03.088.092.088zm0 0" fill="#002b4c" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="m28.201 66.101-.508-2.061c-.025-.12-.117-.207-.235-.207H4.984c-.118 0-.21.088-.235.207l-.514 2.06c0 .03 0 .06.032.092L8.21 72.12c.03.056.122.117.21.117h15.655c.092 0 .154-.03.211-.117l3.944-5.928c-.031-.03-.031-.06-.031-.09zm0 0" fill="#ffc500" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path d="M9.266 54.494h.533v4.836h-.533z" style="stroke:none;fill:#ffc600;fill-opacity:1"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0200612;stroke-opacity:1" d="M6.028 54.457a57.5 57.5 0 0 1-.27-1.64l-.252-1.595 10.708-.005c5.89-.003 10.712-.002 10.716.002.01.01-.5 3.239-.516 3.264-.009.014-3.165.02-10.19.019l-10.176-.001-.02-.044zm.836-3.309.024-.118.013-.074h18.611l.013.074c.006.04.017.093.024.118l.012.044H6.853zm15.737 5.778v-2.404h.532v4.808h-.532zm-3.704.01v-2.414h.512v4.828h-.512zm-5.892 0v-2.414h.512v4.828h-.512zm-3.725-.02v-2.414h.513v4.828h-.512z"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0200612;stroke-opacity:1" d="M9.28 59.567v-.237h1.852c1.213 0 1.855.007 1.863.02.016.026.542.026.542 0 0-.028 5.333-.028 5.35 0 .016.026.516.026.532 0 .008-.013.65-.02 1.863-.02h1.851v.473H9.281zm-3.316 4.211.242-1.342c.155-.866.242-1.303.26-1.315.015-.01 4.288-.017 9.763-.017 7.849 0 9.74.004 9.757.024.016.019.497 2.619.497 2.683 0 .007-4.619.012-10.264.012H5.956z"/><path style="fill:#ffc600;fill-opacity:1;stroke:none;stroke-width:.0283709;stroke-opacity:1" d="M9.716 81.563a.359.359 0 0 1-.101-.16c-.02-.069-.029-1.612-.029-4.624v-4.522h13.209v4.522c0 3.012-.01 4.555-.03 4.624a.359.359 0 0 1-.1.16l-.073.057H9.789zm.741.987c-.026-.011-.035-.13-.035-.458v-.444h11.453v.427c0 .294-.01.436-.033.46-.026.025-1.326.032-5.692.03a585.332 585.332 0 0 1-5.693-.016z"/></svg>

```

2021-08-08 00:50 UTC, Panquesito7 approved these changes
LGTM. Amazing work, @MichielPater; thank you for your contribution! 😄👍🎉

2021-08-08 00:52 UTC, merged