Add newer verison of bootstrap icon
devicons/devicon pull request #739
Opened 2021-07-09 05:30 UTC by theblobscp

Just adds the newer icon. Tell me if I forgot to add something, which I probbably did

2021-07-09 06:07 UTC, Thomas-Boi commented
This looks good @theblobscp. Thank you for updating the icon.

@amacado @Panquesito7 should we remove the plain icons? If we do, should someone make a plain version to replace them? The original doesn't look icon friendly

2021-07-09 07:01 UTC, theblobscp commented
Thanks! I'll try to fix it asap

2021-07-09 07:08 UTC, theblobscp commented
I did it but now it looks terrible

2021-07-09 18:35 UTC, Thomas-Boi commented
> I did it but now it looks terrible

Unfortunately, adding a `viewBox` attribute is not enough. You'd have to use the software specified by the bot or scale the elements manually down to fit the `viewBox` using an SVG editor.

2021-07-09 20:07 UTC, theblobscp commented
@Thomas-Boi Does this work? If not, what do I need to do? I resized it using the thing from the bot

2021-07-09 20:54 UTC, Panquesito7 requested changes
You may need to make some changes to the icon itself. Also, remember to make the SVG pure SVG format, not using external images or so (that's why the `B` looks blurry).

2021-07-09 20:54 UTC, Panquesito7 commented on icons/bootstrap/bootstrap-original.svg
> +<image id="image13" width="256" height="204" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAADMCAYAAACcL30dAAAABmJLR0QA/wD/AP+gvaeTAAAbJElEQVR4nO2de3Qc1X3Hv3dmdyXZsiXLsmUbAg7YBszT4KaF
This is where you shouldn't use images. The file should be in pure SVG format.

2021-07-09 22:26 UTC, Thomas-Boi commented
If you resize the SVG using the web app, just specify the width and height to be 128 in the box specified.

![image](https://user-images.githubusercontent.com/43018778/125141456-f2b61680-e0c9-11eb-8a7c-960e7c910c13.png)

You might have to uncheck the `Maintain Aspect Ratio` box if the SVG is not a square. Any further changes will need an SVG editor

2021-07-10 15:57 UTC, theblobscp commented
> If you resize the SVG using the web app, just specify the width and height to be 128 in the box specified.
> 
> ![image](https://user-images.githubusercontent.com/43018778/125141456-f2b61680-e0c9-11eb-8a7c-960e7c910c13.png)
> 
> You might have to uncheck the `Maintain Aspect Ratio` box if the SVG is not a square. Any further changes will need an SVG editor

Ok

2021-07-16 20:15 UTC, theblobscp commented
I'm gonna redo this pr, I kinda messed it up

2021-07-16 20:15 UTC, closed without merging