Build preparation for release v2.13.1
devicons/devicon pull request #840
Opened 2021-09-07 03:52 UTC by Thomas-Boi

A huge thanks to all our maintainers and contributors for making this release possible!

 **4 New Icons**
- [update icon: msdos (original, plain, line)](https://github.com/devicons/devicon/pull/827) by @MichielPater, @Thomas-Boi, @Panquesito7.
- [update icon: devicon (original, original-wordmark, plain, plain-wordmark, line, line-wordmark)](https://github.com/devicons/devicon/pull/823) by @Panquesito7, @Thomas-Boi.
- [update icon: go (original-wordmark)](https://github.com/devicons/devicon/pull/821) by @Thomas-Boi.
- [new icon: azure (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/816) by @ThomasMoran.
- [new icon: pandas (original, original-wordmark)](https://github.com/devicons/devicon/pull/796) by @kimjiwook0129
- [new icon: storybook (original, original-wordmark, plain, plain-wordmark)](https://github.com/devicons/devicon/pull/799) by @jonlima2018

 **6 New Features**
- [New Feature: webpage now displays <img> of SVG](https://github.com/devicons/devicon/pull/834) by @Thomas-Boi.
- [New Feature: Updated geckodriver](https://github.com/devicons/devicon/pull/830) by @Thomas-Boi.
- [New Feature: Fixed `capture.canvas` issue as seen in #822](https://github.com/devicons/devicon/pull/829) by @amacado, @Thomas-Boi.
- [New Feature: Update the docs for CONTRIBUTING.md](https://github.com/devicons/devicon/pull/824) by @Panquesito7, @Thomas-Boi.
- [Fix syntax with the issue templates](https://github.com/devicons/devicon/pull/815) by @Panquesito7.
- [Feature/website cache busting](https://github.com/devicons/devicon/pull/813) by @MichielPater, @Thomas-Boi.

2021-09-07 10:32 UTC, amacado requested changes
Since we introduce new icons in this release I propose to create a minor release, resulting in v2.14.0. According to our [contribution guidelines](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#conventions)
>The version naming follows the rules of Semantic Versioning. Given a version number MAJOR.MINOR.PATCH, increment the:
>MAJOR version when you make incompatible API changes,
>**MINOR version when you add functionality (like a new icon)** in a backwards compatible manner, and
>PATCH version when you make backwards compatible bug fixes.

2021-09-07 17:26 UTC, Thomas-Boi commented
That sounds good. I'll change the version then

2021-09-07 20:04 UTC, Panquesito7 submitted a review, later dismissed
LGTM once the version is changed. Thanks for preparing this small release, @Thomas-Boi. 😄👍

2021-09-08 03:36 UTC, Panquesito7 approved these changes

2021-09-08 07:50 UTC, amacado approved these changes

2021-09-08 20:52 UTC, merged