new icon: pytest (original, original-wordmark, plain, plain-wordmark)
devicons/devicon pull request #871
Opened 2021-10-04 11:08 UTC by weh

# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date

https://github.com/pytest-dev/pytest/

## This PR adds/fixes

- Closes #861

## Notes

Can you please add the label 'hacktoberfest-accepted' to this. I plan to contribute some more icons, to fulfill (at least) the 4 required Pullrequests.

2021-10-04 11:10 UTC, weh commented
i think the rebase failed. i will do it again and force push..

2021-10-05 00:20 UTC, Panquesito7 requested changes
Also please change the view boxes to `0 0 128 128`. If it doesn't work manually, use a tool like [`iloveimg`](https://www.iloveimg.com/resize-image/resize-svg). **Let us know if you need any help here or in our [Discord server](https://discord.gg/hScy8KWACQ).** 🙂

2021-10-05 00:20 UTC, Panquesito7 commented on icons/pytest/pytest-original-wordmark.svg
> +<svg width="128" height="128" viewBox="0 0 1500 1500" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.
Missing an endline.
```suggestion
<svg width="128" height="128" viewBox="0 0 1500 1500" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.125-9.458-21.125-21.125s9.458-21.125 21.125-21.125z" fill="#696969"/><path d="M525.33 171h86.667v20H525.33z" fill="#009fe3"/><path d="M638.67 171h86.666v20H638.67z" fill="#c7d302"/><path d="M750.5 171h86.667v20H750.5z" fill="#f07e16"/><path d="M861.86 171h86.667v20H861.86zm0 107h86.667v146.5H861.86z" fill="#df2815"/><path d="M750.5 278h86.828v238H750.5z" fill="#f07e16"/><path d="M638.67 278h86.661v356.5H638.67z" fill="#c7d302"/><path d="M525.33 278h86.667v434.5H525.33z" fill="#009fe3"/><path d="M252.96 1173.8q-12.82 0-23.249-2.825-10.43-2.825-18.796-7.496-8.365-4.672-14.775-10.973-6.41-6.302-11.407-13.255h-2.608q.652 7.388 1.304 14.124.434 5.649.869 11.625.435 5.975.435 9.452v101.91h-39.546v-345.48h32.158l5.649 32.158h1.739q4.997-7.605 11.298-14.232 6.302-6.627 14.667-11.516 8.366-4.889 18.795-7.822 10.43-2.934 23.467-2.934 20.425 0 37.156 7.822 16.731 7.823 28.573 23.359t18.36 38.568q6.519 23.032 6.519 53.452 0 30.637-6.519 53.778-6.518 23.141-18.36 38.785-11.842 15.645-28.573 23.576t-37.156 7.931zm-7.605-214.46q-16.514 0-27.921 4.998-11.408 4.997-18.469 15.21-7.062 10.212-10.43 25.422t-3.802 35.852v8.909q0 21.946 2.933 39.003 2.933 17.056 9.995 28.681t18.795 17.6q11.734 5.976 29.334 5.976 29.333 0 43.131-23.684 13.797-23.685 13.797-68.011 0-45.195-13.797-67.575-13.798-22.381-43.566-22.381zm124.935-28.42h41.067l46.716 133.2q3.042 8.691 6.193 18.252 3.151 9.56 5.867 19.121 2.716 9.56 4.671 18.469 1.956 8.909 2.825 16.514h1.304q1.086-5.432 3.476-14.776 2.39-9.343 5.324-19.881 2.933-10.539 6.084-20.751 3.15-10.212 5.54-17.383l43.24-132.76h40.85l-94.302 269.65q-6.084 17.6-13.146 31.615-7.061 14.015-16.405 23.792-9.343 9.778-21.946 15.102-12.602 5.323-29.985 5.323-11.299 0-19.556-1.195-8.256-1.195-14.123-2.499v-31.506q4.563 1.087 11.516 1.847 6.953.761 14.558.761 10.43 0 18.035-2.499t13.254-7.279q5.65-4.781 9.669-11.734 4.02-6.953 7.279-15.862l12.386-34.765z" fill="#696969"/><path d="M695.57 1141.5q3.911 0 8.8-.434 4.889-.435 9.452-1.087t8.366-1.521q3.802-.869 5.758-1.521v29.986q-2.825 1.303-7.171 2.607-4.345 1.304-9.56 2.281-5.215.978-10.864 1.521-5.65.544-11.082.544-13.472 0-24.988-3.477-11.516-3.476-19.881-11.951-8.366-8.474-13.146-22.923-4.78-14.45-4.78-36.395V960.72h-33.68v-17.6l33.68-16.948 16.948-49.976h22.815v54.756h59.971v29.768h-59.971v138.41q0 21.076 6.844 31.723 6.845 10.647 22.489 10.647zm172.96 32.3q-23.901 0-43.674-8.04-19.773-8.039-34.005-23.467-14.232-15.427-22.055-38.242-7.822-22.815-7.822-52.148 0-29.551 7.171-52.801 7.17-23.249 20.207-39.437t31.18-24.662q18.144-8.474 40.09-8.474 21.511 0 38.676 7.714 17.166 7.713 29.117 21.728 11.95 14.015 18.36 33.68 6.41 19.664 6.41 43.565v24.553h-150.36q1.086 41.936 17.708 61.709 16.623 19.773 49.433 19.773 11.081 0 20.533-1.086t18.252-3.151q8.8-2.064 17.057-5.215 8.257-3.15 16.731-7.061v35.2q-8.691 4.128-17.057 7.17-8.365 3.042-17.165 4.998-8.8 1.955-18.252 2.825-9.452.869-20.534.869zm-9.778-214.46q-24.77 0-39.22 16.948-14.449 16.949-16.839 49.324h106.9q0-14.775-2.933-27.052-2.934-12.276-9.126-20.968-6.193-8.691-15.753-13.471-9.561-4.781-23.033-4.781zM1155.1 1104.1q0 17.383-6.301 30.42t-18.143 21.837-28.573 13.146-37.591 4.346q-23.684 0-40.632-3.803-16.948-3.802-29.768-11.19v-36.069q6.736 3.476 14.993 6.844t17.383 5.976q9.126 2.607 18.795 4.237 9.669 1.629 19.229 1.629 14.124 0 24.01-2.39 9.887-2.39 16.08-6.844 6.192-4.455 9.017-10.865t2.825-14.232q0-6.736-2.173-12.168t-7.931-10.755q-5.758-5.324-15.753-10.756t-25.64-12.168-28.138-13.254q-12.494-6.519-21.186-14.559-8.691-8.039-13.363-18.577-4.671-10.539-4.671-25.097 0-15.21 5.975-27.052t16.84-19.881q10.864-8.04 26.074-12.168 15.21-4.129 33.896-4.129 21.077 0 38.568 4.563 17.492 4.563 33.136 11.951l-13.689 31.941q-14.123-6.301-29.007-10.973t-30.311-4.672q-22.164 0-32.811 7.279-10.646 7.279-10.646 20.751 0 7.605 2.498 13.254 2.499 5.65 8.583 10.647 6.084 4.998 16.296 10.104 10.213 5.106 25.423 11.408 15.644 6.518 27.921 13.037 12.277 6.518 20.968 14.666 8.691 8.149 13.254 18.578 4.563 10.43 4.563 24.988zm130.2 37.4q3.911 0 8.8-.434 4.889-.435 9.452-1.087t8.366-1.521q3.802-.869 5.758-1.521v29.986q-2.825 1.303-7.171 2.607-4.345 1.304-9.56 2.281-5.215.978-10.865 1.521-5.649.544-11.081.544-13.472 0-24.988-3.477-11.516-3.476-19.882-11.951-8.365-8.474-13.145-22.923-4.781-14.45-4.781-36.395V960.72h-33.679v-17.6l33.679-16.948 16.949-49.976h22.815v54.756h59.97v29.768h-59.97v138.41q0 21.076 6.844 31.723 6.845 10.647 22.489 10.647z" fill="#009fe3"/></svg>

```

2021-10-05 00:20 UTC, Panquesito7 commented on icons/pytest/pytest-original.svg
> +<svg width="128" height="128" viewBox="300 0 900 900" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.
Missing an endline.
```suggestion
<svg width="128" height="128" viewBox="300 0 900 900" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.125-9.458-21.125-21.125s9.458-21.125 21.125-21.125z" fill="#696969"/><path d="M525.33 171h86.667v20H525.33z" fill="#009fe3"/><path d="M638.67 171h86.666v20H638.67z" fill="#c7d302"/><path d="M750.5 171h86.667v20H750.5z" fill="#f07e16"/><path d="M861.86 171h86.667v20H861.86zm0 107h86.667v146.5H861.86z" fill="#df2815"/><path d="M750.5 278h86.828v238H750.5z" fill="#f07e16"/><path d="M638.67 278h86.661v356.5H638.67z" fill="#c7d302"/><path d="M525.33 278h86.667v434.5H525.33z" fill="#009fe3"/></svg>

```

2021-10-05 00:20 UTC, Panquesito7 commented on icons/pytest/pytest-plain-wordmark.svg
> +<svg width="128" height="128" viewBox="0 0 1500 1500" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.
Missing an endline.
```suggestion
<svg width="128" height="128" viewBox="0 0 1500 1500" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.125-9.458-21.125-21.125s9.458-21.125 21.125-21.125zm3.75-42.75h86.667v20H525.33zm113.34 0h86.666v20H638.67zm111.83 0h86.667v20H750.5zm111.36 0h86.667v20H861.86zm0 107h86.667v146.5H861.86zm-111.36 0h86.828v238H750.5zm-111.83 0h86.661v356.5H638.67zm-113.34 0h86.667v434.5H525.33zm-272.37 895.8q-12.82 0-23.249-2.825-10.43-2.825-18.796-7.496-8.365-4.672-14.775-10.973-6.41-6.302-11.407-13.255h-2.608q.652 7.388 1.304 14.124.434 5.649.869 11.625.435 5.975.435 9.452v101.91h-39.546v-345.48h32.158l5.649 32.158h1.739q4.997-7.605 11.298-14.232 6.302-6.627 14.667-11.516 8.366-4.889 18.795-7.822 10.43-2.934 23.467-2.934 20.425 0 37.156 7.822 16.731 7.823 28.573 23.359t18.36 38.568q6.519 23.032 6.519 53.452 0 30.637-6.519 53.778-6.518 23.141-18.36 38.785-11.842 15.645-28.573 23.576t-37.156 7.931zm-7.605-214.46q-16.514 0-27.921 4.998-11.408 4.997-18.469 15.21-7.062 10.212-10.43 25.422t-3.802 35.852v8.909q0 21.946 2.933 39.003 2.933 17.056 9.995 28.681t18.795 17.6q11.734 5.976 29.334 5.976 29.333 0 43.131-23.684 13.797-23.685 13.797-68.011 0-45.195-13.797-67.575-13.798-22.381-43.566-22.381zm124.935-28.42h41.067l46.716 133.2q3.042 8.691 6.193 18.252 3.151 9.56 5.867 19.121 2.716 9.56 4.671 18.469 1.956 8.909 2.825 16.514h1.304q1.086-5.432 3.476-14.776 2.39-9.343 5.324-19.881 2.933-10.539 6.084-20.751 3.15-10.212 5.54-17.383l43.24-132.76h40.85l-94.302 269.65q-6.084 17.6-13.146 31.615-7.061 14.015-16.405 23.792-9.343 9.778-21.946 15.102-12.602 5.323-29.985 5.323-11.299 0-19.556-1.195-8.256-1.195-14.123-2.499v-31.506q4.563 1.087 11.516 1.847 6.953.761 14.558.761 10.43 0 18.035-2.499t13.254-7.279q5.65-4.781 9.669-11.734 4.02-6.953 7.279-15.862l12.386-34.765zm325.28 210.58q3.911 0 8.8-.434 4.889-.435 9.452-1.087t8.366-1.521q3.802-.869 5.758-1.521v29.986q-2.825 1.303-7.171 2.607-4.345 1.304-9.56 2.281-5.215.978-10.864 1.521-5.65.544-11.082.544-13.472 0-24.988-3.477-11.516-3.476-19.881-11.951-8.366-8.474-13.146-22.923-4.78-14.45-4.78-36.395V960.72h-33.68v-17.6l33.68-16.948 16.948-49.976h22.815v54.756h59.971v29.768h-59.971v138.41q0 21.076 6.844 31.723 6.845 10.647 22.489 10.647zm172.96 32.3q-23.901 0-43.674-8.04-19.773-8.039-34.005-23.467-14.232-15.427-22.055-38.242-7.822-22.815-7.822-52.148 0-29.551 7.171-52.801 7.17-23.249 20.207-39.437t31.18-24.662q18.144-8.474 40.09-8.474 21.511 0 38.676 7.714 17.166 7.713 29.117 21.728 11.95 14.015 18.36 33.68 6.41 19.664 6.41 43.565v24.553h-150.36q1.086 41.936 17.708 61.709 16.623 19.773 49.433 19.773 11.081 0 20.533-1.086t18.252-3.151q8.8-2.064 17.057-5.215 8.257-3.15 16.731-7.061v35.2q-8.691 4.128-17.057 7.17-8.365 3.042-17.165 4.998-8.8 1.955-18.252 2.825-9.452.869-20.534.869zm-9.778-214.46q-24.77 0-39.22 16.948-14.449 16.949-16.839 49.324h106.9q0-14.775-2.933-27.052-2.934-12.276-9.126-20.968-6.193-8.691-15.753-13.471-9.561-4.781-23.033-4.781zM1155.1 1104.1q0 17.383-6.301 30.42t-18.143 21.837-28.573 13.146-37.591 4.346q-23.684 0-40.632-3.803-16.948-3.802-29.768-11.19v-36.069q6.736 3.476 14.993 6.844t17.383 5.976q9.126 2.607 18.795 4.237 9.669 1.629 19.229 1.629 14.124 0 24.01-2.39 9.887-2.39 16.08-6.844 6.192-4.455 9.017-10.865t2.825-14.232q0-6.736-2.173-12.168t-7.931-10.755q-5.758-5.324-15.753-10.756t-25.64-12.168-28.138-13.254q-12.494-6.519-21.186-14.559-8.691-8.039-13.363-18.577-4.671-10.539-4.671-25.097 0-15.21 5.975-27.052t16.84-19.881q10.864-8.04 26.074-12.168 15.21-4.129 33.896-4.129 21.077 0 38.568 4.563 17.492 4.563 33.136 11.951l-13.689 31.941q-14.123-6.301-29.007-10.973t-30.311-4.672q-22.164 0-32.811 7.279-10.646 7.279-10.646 20.751 0 7.605 2.498 13.254 2.499 5.65 8.583 10.647 6.084 4.998 16.296 10.104 10.213 5.106 25.423 11.408 15.644 6.518 27.921 13.037 12.277 6.518 20.968 14.666 8.691 8.149 13.254 18.578 4.563 10.43 4.563 24.988zm130.2 37.4q3.911 0 8.8-.434 4.889-.435 9.452-1.087t8.366-1.521q3.802-.869 5.758-1.521v29.986q-2.825 1.303-7.171 2.607-4.345 1.304-9.56 2.281-5.215.978-10.865 1.521-5.649.544-11.081.544-13.472 0-24.988-3.477-11.516-3.476-19.882-11.951-8.365-8.474-13.145-22.923-4.781-14.45-4.781-36.395V960.72h-33.679v-17.6l33.679-16.948 16.949-49.976h22.815v54.756h59.97v29.768h-59.97v138.41q0 21.076 6.844 31.723 6.845 10.647 22.489 10.647z" fill="#386f9f"/></svg>

```

2021-10-05 00:20 UTC, Panquesito7 commented on icons/pytest/pytest-plain.svg
> +<svg width="128" height="128" viewBox="300 0 900 900" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.
Missing an endline.
```suggestion
<svg width="128" height="128" viewBox="300 0 900 900" xmlns="http://www.w3.org/2000/svg"><path d="M521.58 213.75h431.04c11.667 0 21.125 9.458 21.125 21.125S964.287 256 952.62 256H521.58c-11.667 0-21.125-9.458-21.125-21.125s9.458-21.125 21.125-21.125zM525.33 171h86.667v20H525.33zM638.67 171h86.666v20H638.67zM750.5 171h86.667v20H750.5zM861.86 171h86.667v20H861.86zm0 107h86.667v146.5H861.86zM750.5 278h86.828v238H750.5zM638.67 278h86.661v356.5H638.67zM525.33 278h86.667v434.5H525.33z" fill="#386f9f"/></svg>

```

2021-10-05 00:20 UTC, Panquesito7 commented on devicon.json
> +        "color": "#386f9f",
I recommend more this color `#009fe3`
```suggestion
        "color": "#009fe3",
```

2021-10-05 11:19 UTC, weh commented on devicon.json
> +        "color": "#386f9f",
yes, i realized i picked the wrong one

2021-10-05 23:35 UTC, Panquesito7 approved these changes
Looks awesome! Thank you for your contribution! 🚀

2021-10-06 08:23 UTC, amacado approved these changes
Thanks @weh!

2021-10-06 08:23 UTC, merged