new icon: podman (original, original-wordmark)
devicons/devicon pull request #916
Opened 2021-11-17 10:18 UTC by weh

# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date

https://github.com/containers/podman/blob/main/logo/podman-logo-source.svg

2021-11-18 08:40 UTC, weh commented
Ooops :laughing: i think this needs a bit more svg love.

2021-11-18 12:38 UTC, weh commented
after removing the background i am still not happy. i think i need to also fix the septagon and other colors. Maybe add separate version for the rendered font.

2021-11-18 12:39 UTC, weh commented
after removing the background i am still not happy. i think i need to also fix the heptagon and some of the colors. Maybe add separate version for the rendered font.

2021-11-18 14:37 UTC, Panquesito7 commented
> after removing the background i am still not happy. i think i need to also fix the heptagon and some of the colors. Maybe add separate version for the rendered font.

We can use the current one as original and another one as a font (only one color). 🙂

2021-11-18 14:44 UTC, Panquesito7 requested changes
Still not looking good 😅 could you please update it to fit to be a font icon? Let us know if you need any help here or in our [**Discord server**](https://discord.gg/hScy8KWACQ). 🙂

2021-11-19 09:23 UTC, weh commented
yes, i will add two separate files for font, and try to optimize the svg with icomoon.

2021-11-23 17:25 UTC, Panquesito7 commented on icons/podman/podman-plain-wordmark.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><defs><clipPath id="a"><path d="M7 64h9v5.32H7Zm0 0"/></clipPath><clipPath id="b"><path d="M4.855 63.39h12.102v5
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><defs><clipPath id="a"><path d="M7 64h9v5.32H7Zm0 0"/></clipPath><clipPath id="b"><path d="M4.855 63.39h12.102v5.93H4.855Zm0 0"/></clipPath><clipPath id="c"><path d="M13 69h2v.32h-2Zm0 0"/></clipPath><clipPath id="d"><path d="M8 69h2v.32H8Zm0 0"/></clipPath><clipPath id="e"><path d="M6 67h7v2.32H6Zm0 0"/></clipPath><clipPath id="f"><path d="M11 67h5.957v2.32H11Zm0 0"/></clipPath><clipPath id="g"><path d="M10 67h4v2.32h-4Zm0 0"/></clipPath><clipPath id="h"><path d="M7 65h9v4.32H7Zm0 0"/></clipPath><clipPath id="i"><path d="M10 64h6.957v5.32H10Zm0 0"/></clipPath><clipPath id="j"><path d="M10 63.39h6.957v5.93H10Zm0 0"/></clipPath><clipPath id="k"><path d="M8 66h8v3.32H8Zm0 0"/></clipPath><clipPath id="l"><path d="M10 68h3v1.32h-3Zm0 0"/></clipPath><clipPath id="m"><path d="M8 66h7v3.32H8Zm0 0"/></clipPath><clipPath id="n"><path d="M6 64h7v5.32H6Zm0 0"/></clipPath><clipPath id="o"><path d="M6 63.39h7v5.93H6Zm0 0"/></clipPath></defs><path style="stroke:none;fill-rule:nonzero;fill:#000;fill-opacity:1" d="M44.18 59.203c-1.735 0-3.075.711-3.887 2.008v-1.926h-2.406V74.47h2.406v-5.98c.812 1.296 2.152 2.007 3.93 2.007 3.18 0 5.27-2.281 5.27-5.605 0-3.387-2.157-5.688-5.313-5.688Zm-.5 9.242c-1.989 0-3.387-1.484-3.387-3.636 0-2.094 1.398-3.598 3.387-3.598 1.984 0 3.386 1.527 3.386 3.598 0 2.132-1.402 3.636-3.386 3.636Zm13.082-9.242c-3.45 0-5.813 2.281-5.813 5.649 0 3.343 2.364 5.644 5.813 5.644 3.43 0 5.789-2.3 5.789-5.644 0-3.368-2.36-5.649-5.79-5.649Zm0 2.07c1.984 0 3.386 1.465 3.386 3.598 0 2.152-1.402 3.617-3.386 3.617-2.008 0-3.41-1.465-3.41-3.617 0-2.133 1.402-3.598 3.41-3.598Zm16.496-6.378v6.316c-.817-1.297-2.153-2.027-3.953-2.027-3.137 0-5.29 2.277-5.29 5.625 0 3.386 2.133 5.707 5.333 5.707 1.777 0 3.113-.711 3.91-2.008v1.902h2.406V54.895Zm-3.406 13.613c-2.032 0-3.41-1.504-3.43-3.617.02-2.133 1.422-3.66 3.43-3.66 2.003 0 3.406 1.507 3.406 3.66 0 2.113-1.403 3.617-3.406 3.617ZM93.824 59.203c-2.027 0-3.511.817-4.222 2.676-.524-1.691-1.883-2.676-3.868-2.676-1.843 0-3.261.668-4.039 2.238v-2.156h-2.382v11.13h2.382v-5.5c0-1.946 1.172-3.411 3.098-3.474 1.629 0 2.613 1.024 2.613 2.72v6.25h2.403v-5.497c0-1.945 1.152-3.41 3.054-3.473 1.63 0 2.633 1.024 2.633 2.72v6.25h2.406v-6.923c0-2.652-1.527-4.285-4.078-4.285Zm16.328 11.207-.02-7.297c-.023-2.445-1.632-3.91-4.495-3.91-2.114 0-3.242.48-4.79 1.402l.985 1.672c1.11-.754 2.215-1.129 3.281-1.129 1.758 0 2.657.836 2.657 2.239v.332h-3.368c-2.675.023-4.203 1.32-4.203 3.347 0 1.965 1.508 3.45 3.91 3.45 1.61 0 2.887-.48 3.68-1.461v1.355Zm-5.539-1.797c-1.34 0-2.156-.648-2.156-1.652 0-1.066.734-1.484 2.3-1.484h3.013V66.5c-.125 1.215-1.442 2.113-3.157 2.113Zm15.262-9.41c-1.883 0-3.305.668-4.098 2.219v-2.137h-2.406v11.13h2.406v-5.923c.168-1.734 1.317-3.008 3.157-3.031 1.671 0 2.675 1.027 2.675 2.7v6.253h2.407v-6.926c0-2.652-1.547-4.285-4.141-4.285Zm0 0"/><path style="fill:none;stroke-width:1.058333;stroke-linecap:butt;stroke-linejoin:miter;stroke:#000;stroke-opacity:1;stroke-miterlimit:4" d="M963.979-1.267h12.726M966.1 1.381h12.719" transform="matrix(.5562 0 0 .5563 -518.393 64.869)"/><path style="color:#000;font-style:normal;font-variant:normal;font-weight:400;font-stretch:normal;font-size:medium;line-height:normal;font-family:sans-serif;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration:none;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;letter-spacing:normal;word-spacing:normal;text-transform:none;writing-mode:lr-tb;direction:ltr;text-orientation:mixed;dominant-baseline:auto;baseline-shift:baseline;text-anchor:start;white-space:normal;shape-padding:0;clip-rule:nonzero;display:inline;overflow:visible;visibility:visible;opacity:1;isolation:auto;mix-blend-mode:normal;color-interpolation:sRGB;color-interpolation-filters:linearRGB;solid-color:#000;solid-opacity:1;vector-effect:none;fill:#000;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:.44151932;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;color-rendering:auto;image-rendering:auto;shape-rendering:auto;text-rendering:auto;enable-background:accumulate" d="M15.988 54.353c-1.065 0-2.101.115-2.768.379-1.767.65-3.102 2.398-3.498 4.5l-.002.005c-.35 1.666-.442 3.079-.63 4.355-.187 1.278-.466 2.418-1.184 3.582l.377.231c.758-1.23 1.053-2.446 1.244-3.749.191-1.303.283-2.698.627-4.333v-.005c.37-1.971 1.627-3.588 3.223-4.173l.003-.002h.002c.557-.22 1.575-.347 2.606-.347s2.088.124 2.736.35c1.595.586 2.846 2.202 3.22 4.173l.001.001v.003c.344 1.635.435 3.03.626 4.333.191 1.303.487 2.519 1.245 3.75l.377-.232c-.718-1.164-.997-2.304-1.185-3.582-.187-1.278-.28-2.691-.63-4.36v.005c-.4-2.106-1.734-3.858-3.505-4.508h-.002c-.739-.257-1.818-.376-2.883-.376Z"/><path style="stroke:none;fill-rule:nonzero;fill:#e6e6e8;fill-opacity:1" d="M20.535 62.484c0-.418-.316-.754-.71-.754-.395 0-.716.336-.716.754 0 .414.32.75.715.75.395 0 .711-.336.711-.75Zm-7.211 0c0-.418-.32-.754-.715-.754-.394 0-.714.336-.714.754 0 .414.32.75.714.75.395 0 .715-.336.715-.75Zm0 0"/><path style="color:#000;font-style:normal;font-variant:normal;font-weight:400;font-stretch:normal;font-size:medium;line-height:normal;font-family:sans-serif;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration:none;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;letter-spacing:normal;word-spacing:normal;text-transform:none;writing-mode:lr-tb;direction:ltr;text-orientation:mixed;dominant-baseline:auto;baseline-shift:baseline;text-anchor:start;white-space:normal;shape-padding:0;clip-rule:nonzero;display:inline;overflow:visible;visibility:visible;opacity:1;isolation:auto;mix-blend-mode:normal;color-interpolation:sRGB;color-interpolation-filters:linearRGB;solid-color:#000;solid-opacity:1;vector-effect:none;fill:#000;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:.29434481;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;color-rendering:auto;image-rendering:auto;shape-rendering:auto;text-rendering:auto;enable-background:accumulate" d="m13.814 61.928-2.652.71.075.285 2.652-.71zm.265.429-2.668 1.538.148.256 2.668-1.54zm.193.511-2.703 2.707.207.21 2.704-2.708zm.09.668-1.383 2.398.255.148 1.382-2.399zM18.83 61.928l2.652.71-.075.285-2.652-.71zm-.265.429 2.668 1.538-.148.256-2.668-1.54zm-.196.511 2.706 2.707-.207.21-2.707-2.708zm-.087.668 1.38 2.398-.255.147-1.379-2.399z"/><path style="color:#000;font-style:normal;font-variant:normal;font-weight:400;font-stretch:normal;font-size:medium;line-height:normal;font-family:sans-serif;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration:none;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;letter-spacing:normal;word-spacing:normal;text-transform:none;writing-mode:lr-tb;direction:ltr;text-orientation:mixed;dominant-baseline:auto;baseline-shift:baseline;text-anchor:start;white-space:normal;shape-padding:0;clip-rule:nonzero;display:inline;overflow:visible;visibility:visible;opacity:1;isolation:auto;mix-blend-mode:normal;color-interpolation:sRGB;color-interpolation-filters:linearRGB;solid-color:#000;solid-opacity:1;vector-effect:none;fill:#000;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:.44151932;stroke-linecap:square;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;color-rendering:auto;image-rendering:auto;sh [...]

2021-11-23 17:25 UTC, Panquesito7 commented on icons/podman/podman-plain.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><defs><clipPath id="a"><path d="M19 61h42v22.336H19Zm0 0"/></clipPath><clipPath id="b"><path d="M8.96 55.742h56.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><defs><clipPath id="a"><path d="M19 61h42v22.336H19Zm0 0"/></clipPath><clipPath id="b"><path d="M8.96 55.742h56.58v27.594H8.96Zm0 0"/></clipPath><clipPath id="c"><path d="M49 82h5v1.336h-5Zm0 0"/></clipPath><clipPath id="d"><path d="M27 82h5v1.336h-5Zm0 0"/></clipPath><clipPath id="e"><path d="M17 76h25v7.336H17Zm0 0"/></clipPath><clipPath id="f"><path d="M18 77h25v6.336H18Zm0 0"/></clipPath><clipPath id="g"><path d="M19 78h24v5.336H19Zm0 0"/></clipPath><clipPath id="h"><path d="M23 80h21v3.336H23Zm0 0"/></clipPath><clipPath id="i"><path d="M40 76h24v7.336H40Zm0 0"/></clipPath><clipPath id="j"><path d="M39 77h24v6.336H39Zm0 0"/></clipPath><clipPath id="k"><path d="M38 78h25v5.336H38Zm0 0"/></clipPath><clipPath id="l"><path d="M38 80h21v3.336H38Zm0 0"/></clipPath><clipPath id="m"><path d="M33 77h15v6.336H33Zm0 0"/></clipPath><clipPath id="n"><path d="M22 65h38v18.336H22Zm0 0"/></clipPath><clipPath id="o"><path d="M36 62h29.54v21.336H36Zm0 0"/></clipPath><clipPath id="p"><path d="M36 57h29.54v26H36Zm0 0"/></clipPath><clipPath id="q"><path d="M28 70h29v13.336H28Zm0 0"/></clipPath><clipPath id="r"><path d="M24 70h29v13.336H24Zm0 0"/></clipPath><clipPath id="s"><path d="M37 80h7v3.336h-7Zm0 0"/></clipPath><clipPath id="t"><path d="M26 68h30v15.336H26Zm0 0"/></clipPath><clipPath id="u"><path d="M14 62h31v21.336H14Zm0 0"/></clipPath></defs><path style="fill:none;stroke-width:1.058333;stroke-linecap:butt;stroke-linejoin:miter;stroke:#000;stroke-opacity:1;stroke-miterlimit:4" d="M963.983-1.265h12.722M966.1 1.38h12.721" transform="matrix(2.60096 0 0 2.58929 -2437.947 62.618)"/><path style="color:#000;font-style:normal;font-variant:normal;font-weight:400;font-stretch:normal;font-size:medium;line-height:normal;font-family:sans-serif;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration:none;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;letter-spacing:normal;word-spacing:normal;text-transform:none;writing-mode:lr-tb;direction:ltr;text-orientation:mixed;dominant-baseline:auto;baseline-shift:baseline;text-anchor:start;white-space:normal;shape-padding:0;clip-rule:nonzero;display:inline;overflow:visible;visibility:visible;opacity:1;isolation:auto;mix-blend-mode:normal;color-interpolation:sRGB;color-interpolation-filters:linearRGB;solid-color:#000;solid-opacity:1;vector-effect:none;fill:#000;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:2.05987883;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;color-rendering:auto;image-rendering:auto;shape-rendering:auto;text-rendering:auto;enable-background:accumulate" d="M61.002 13.672c-4.976 0-9.816.538-12.935 1.77-.003 0-.009-.002-.012 0-8.26 3.025-14.49 11.161-16.346 20.943v.006c-.002.006-.005.011-.006.017-1.644 7.754-2.076 14.323-2.95 20.263-.876 5.947-2.177 11.25-5.533 16.671l1.758 1.077c3.548-5.731 4.926-11.381 5.82-17.445.892-6.064 1.317-12.557 2.932-20.164v-.023c1.736-9.18 7.597-16.704 15.061-19.425l.012-.005.017-.006c2.601-1.029 7.36-1.619 12.182-1.618 4.816 0 9.755.58 12.794 1.635h.012c7.458 2.726 13.31 10.246 15.038 19.419v.011l.006.012c1.616 7.607 2.039 14.1 2.932 20.164.894 6.064 2.274 11.72 5.825 17.45l1.759-1.082c-3.36-5.421-4.663-10.724-5.539-16.671-.875-5.94-1.31-12.508-2.956-20.263l-.006-.017c-1.852-9.796-8.084-17.944-16.364-20.961H74.485c-3.458-1.203-8.503-1.758-13.483-1.758Z"/><path style="stroke:none;fill-rule:nonzero;fill:#e7e8e9;fill-opacity:1" d="M82.258 51.516c0-1.934-1.492-3.5-3.336-3.5-1.844 0-3.34 1.566-3.34 3.5 0 1.933 1.496 3.5 3.34 3.5 1.844 0 3.336-1.567 3.336-3.5Zm-33.727 0c0-1.934-1.496-3.5-3.34-3.5-1.843 0-3.336 1.566-3.336 3.5 0 1.933 1.493 3.5 3.336 3.5 1.844 0 3.34-1.567 3.34-3.5Zm0 0"/><path style="color:#000;font-style:normal;font-variant:normal;font-weight:400;font-stretch:normal;font-size:medium;line-height:normal;font-family:sans-serif;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration:none;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;letter-spacing:normal;word-spacing:normal;text-transform:none;writing-mode:lr-tb;direction:ltr;text-orientation:mixed;dominant-baseline:auto;baseline-shift:baseline;text-anchor:start;white-space:normal;shape-padding:0;clip-rule:nonzero;display:inline;overflow:visible;visibility:visible;opacity:1;isolation:auto;mix-blend-mode:normal;color-interpolation:sRGB;color-interpolation-filters:linearRGB;solid-color:#000;solid-opacity:1;vector-effect:none;fill:#000;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:1.37324953;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;color-rendering:auto;image-rendering:auto;shape-rendering:auto;text-rendering:auto;enable-background:accumulate" d="M50.801 48.93 38.398 52.24l.358 1.323 12.403-3.308zm1.24 1.99L39.57 58.1l.684 1.183 12.476-7.174zm.913 2.383L40.307 65.914l.97.967L53.924 54.27zm.42 3.117-6.469 11.158 1.194.688 6.463-11.159zM74.297 48.93 86.7 52.24l-.353 1.323-12.408-3.308zm-1.24 1.99 12.47 7.18-.684 1.183-12.476-7.174zm-.913 2.383 12.647 12.611-.97.967L71.174 54.27Zm-.42 3.117 6.469 11.158-1.194.688-6.463-11.159z"/><path style="color:#000;font-style:normal;font-variant:normal;font-weight:400;font-stretch:normal;font-size:medium;line-height:normal;font-family:sans-serif;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration:none;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;letter-spacing:normal;word-spacing:normal;text-transform:none;writing-mode:lr-tb;direction:ltr;text-orientation:mixed;dominant-baseline:auto;baseline-shift:baseline;text-anchor:start;white-space:normal;shape-padding:0;clip-rule:nonzero;display:inline;overflow:visible;visibility:visible;opacity:1;isolation:auto;mix-blend-mode:normal;color-interpolation:sRGB;color-interpolation-filters:linearRGB;solid-color:#000;solid-opacity:1;vector-effect:none;fill:#60605b;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:2.05987883;stroke-linecap:square;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;color-rendering:auto;image-rendering:auto;shape-rendering:auto;text-rendering:auto;enable-background:accumulate" d="M62.41 37.887c-6.447 0-11.75 4.983-11.75 11.176 0 6.19 5.303 11.176 11.75 11.176 6.452 0 11.748-4.986 11.748-11.176 0-6.193-5.296-11.176-11.748-11.176zm0 2.055c5.393 0 9.686 4.096 9.686 9.121 0 5.022-4.293 9.121-9.686 9.121-5.387 0-9.687-4.1-9.687-9.12 0-5.026 4.3-9.122 9.687-9.122z"/><path style="fill-rule:nonzero;fill:#000;fill-opacity:1;stroke-width:.689901;stroke-linecap:square;stroke-linejoin:miter;stroke:#000;stroke-opacity:1;stroke-miterlimit:4" d="M-964.802-7.841c0-.977-.773-1.768-1.725-1.768-.953 0-1.725.791-1.725 1.768 0 .978.772 1.77 1.725 1.77.952 0 1.725-.792 1.725-1.77Zm0 0" transform="matrix(-2.99123 0 0 2.9803 -2812.291 63.755)"/><path style="color:#000;font-style:normal;font-variant:normal;font-weight:400;font-stretch:normal;font-size:medium;line-height:normal;font-family:sans-serif;font-variant-ligatures:normal;font-variant-position:normal;font-variant-caps:normal;font-variant-numeric:normal;font-variant-alternates:normal;font-feature-settings:normal;text-indent:0;text-align:start;text-decoration:none;text-decoration-line:none;text-decoration-style:solid;text-decoration-color:#000;letter-spacing:normal;word-spacing:normal; [...]

2021-11-23 17:31 UTC, Panquesito7 commented
Any idea why it's failing, @Thomas-Boi? 😅

2021-11-24 06:33 UTC, Thomas-Boi approved these changes
This looks fantastic @weh!

2021-11-24 20:30 UTC, Panquesito7 approved these changes
Woah 👀 awesome! 🚀 Thank you for your contribution! 😄👍

2021-11-25 06:44 UTC, Thomas-Boi approved these changes

2021-11-25 06:44 UTC, merged