new icon: networkx (original)
devicons/devicon pull request #917
Opened 2021-11-17 16:06 UTC by ozanuslan

## original
![networkx-original](https://user-images.githubusercontent.com/54141068/142236499-3c741ae9-a30a-42e9-afde-ef7a95d26de3.png)

## Double check these details before you open a PR

- [ ] PR does not match another non-stale PR currently opened
- [ ] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [ ] The PR's base is the `develop` branch.
- [ ] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [ ] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [ ] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date
+ <a href="https://networkx.org/">Official Networkx Page</a>

## This PR adds/fixes
Addresses #898

2021-11-17 16:26 UTC, Panquesito7 commented on icons/networkx/networkx-original.svg
> +
```suggestion
```

2021-11-17 16:30 UTC, Panquesito7 submitted a review, later dismissed
LGTM 🚀 Thank you for your contribution! 😄👍

2021-11-17 16:39 UTC, amino19 submitted a review, later dismissed
I checked for `plain-original`, it wouldn't exist at `networkx` artwork even.

BTW, Thanks for your contribution @ozanuslan, LGTM! :tada:

2021-11-24 06:52 UTC, Thomas-Boi requested changes
Hi @ozanuslan,

The bot detected that your icon contains strokes in them. Icomoon (the icon maker) would ignore these when converting them to font. This cause the font to miss some details:
![image](https://user-images.githubusercontent.com/43018778/143189213-9479e795-62c9-4bf3-abd4-57265b60eaac.png)

Can you please [convert these strokes to fills](https://icomoon.io/#docs/stroke-to-fill) please? That will ensure the lines show up in the font version.

2021-11-24 21:36 UTC, Panquesito7 approved these changes

2021-11-24 21:45 UTC, amino19 approved these changes

2021-11-25 06:33 UTC, Thomas-Boi commented
> Pardon the commit message, strokes have been converted to fills as requested. If strokes are not allowed perhaps a check can be added to the actions? 🤔

We actually do have a check. It's in the `peek-bot` message at the top. However, we can add it in `check-bot` as well.

2021-11-25 06:33 UTC, Thomas-Boi approved these changes

2021-11-25 06:33 UTC, merged