new icon: sqlite (original, original-wordmark, plain)
devicons/devicon pull request #926
Opened 2021-12-04 01:57 UTC by Snailedlt

This is my first venture into the world of SVGs so probably a lot of things that need fixing or improving here. Anyways, leave some feedback, and let me know what I can do better! :)

fixing #437

# **New icon section**

## Double check these details before you open a PR

- [x] PR does not match another non-stale PR currently opened
- [x] PR name matches the format *new icon: <i>Icon name</i> (<i>versions separated by comma</i>)*. More details [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#overview)
- [x] The PR's base is the `develop` branch.
- [x] Your icons are inside a folder as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#organizational-guidelines)
- [x] SVG matches the standards laid out [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#svgStandards)
- [x] A new object is added in the `devicon.json` file as seen [here](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#-updating-the-deviconjson-)

## Link to prove your SVG is correct and up-to-date

https://www.sqlite.org/index.html

2021-12-05 15:21 UTC, Panquesito7 requested changes
Great work! 🚀
Could you please create a  `plain-wordmark` version? Should be the same as `original-wordmark` but black. Thanks. 🙂

2021-12-05 15:21 UTC, Panquesito7 commented on icons/sqlite/sqlite-plain.svg
> +</svg>
Missing an endline.
```suggestion
</svg>

```

2021-12-06 18:29 UTC, Snailedlt commented
> Great work! 🚀 Could you please create a `plain-wordmark` version? Should be the same as `original-wordmark` but black. Thanks. 🙂

I'll add this. But shouldn't that ideally just be generated automatically once the PR is merged? I mean if the only difference is the color :)

2021-12-06 19:51 UTC, Snailedlt commented
@Panquesito7 
Can you take a look again now?
See two latest commits for the updates I did.

2021-12-06 19:54 UTC, Panquesito7 requested changes

2021-12-06 19:54 UTC, Panquesito7 commented on icons/sqlite/sqlite-plain.svg
> +   width="180"
I think the width, height, and viewbox should be `128`? 🤔
If you're having trouble with resizing, try to use [**this tool**](https://www.iloveimg.com/resize-image/resize-svg).

2021-12-06 20:24 UTC, Panquesito7 submitted a review, later dismissed
LGTM 🚀 Thank you for your contribution! 😄👍

2021-12-06 20:32 UTC, Snailedlt commented
> LGTM 🚀 Thank you for your contribution! 😄👍

Thanks for helping! 🙇‍♂️

2021-12-06 20:43 UTC, Panquesito7 commented on devicon.json
> +        "color": "#0f80cc"
```suggestion
        "color": "#0f80cc",
        "aliases": []
```

2021-12-06 20:47 UTC, Panquesito7 commented on devicon.json
> +            ]
```suggestion
            ],
          "font": [
              "plain",
              "plain-wordmark"
          ]
```

2021-12-06 23:12 UTC, Panquesito7 commented
Any reasons why it's failing, @Thomas-Boi? 👀

2021-12-11 23:07 UTC, Thomas-Boi commented
Due to the bugs related to `peek-bot` and `upload-artifact`, this PR will need longer than usual to be merged. Hopefully, it'll be merged within the next 2 weeks. Until then, thank you for your patience and understanding.

2021-12-21 20:48 UTC, Thomas-Boi approved these changes
The icon looks wonderful! Congratulations on getting your first icon into the repo. Also thank you very much for your patience while we fix the bug.

2021-12-21 20:48 UTC, merged

2021-12-22 11:19 UTC, Snailedlt commented
> The icon looks wonderful! Congratulations on getting your first icon into the repo. Also thank you very much for your patience while we fix the bug.

Thanks, happy to help! 💯

2021-12-22 18:32 UTC, Panquesito7 reviewed
Awesome! 🚀