Update contributing md with devicon line logos
devicons/devicon pull request #941
Opened 2021-12-08 19:38 UTC by Snailedlt

updated CONTRIBUTING.md to show devicon line logos instead of apache line logos.

ref: https://www.script-tutorials.com/line-icons/#:~:text=Line%20icons%20is%20a%20shape%20vector%20of%20a%20symbolic%20glyph%20outline%20only%20which%20basically%20consist%20of%20fonts%20styled%20in%20css%20%7Bresize%2C%20colors%20and%20moved%7D

2021-12-08 20:11 UTC, Panquesito7 requested changes
Great work! 🚀

2021-12-08 20:11 UTC, Panquesito7 commented on CONTRIBUTING.md
>            <h4>apache-line.svg</h4>
```suggestion
          <h4>devicon-line.svg</h4>
```

2021-12-08 20:11 UTC, Panquesito7 commented on CONTRIBUTING.md
>            <h4>apache-line-wordmark.svg</h4>
```suggestion
          <h4>devicon-line-wordmark.svg</h4>
```

2021-12-08 20:14 UTC, Snailedlt commented
> Great work! 🚀

Thanks @Panquesito7 😄 
I accepted your commits too :P

2021-12-08 20:21 UTC, amacado requested changes
I think the href to https://www.script-tutorials.com/line-icons/ is not necessary. Would you please remove it? The updated icon version is great!

2021-12-08 20:29 UTC, Snailedlt commented
> I think the href to https://www.script-tutorials.com/line-icons/ is not necessary. Would you please remove it? The updated icon version is great!

Done!

2021-12-08 20:29 UTC, Panquesito7 submitted a review, later dismissed

2021-12-08 22:34 UTC, amacado commented
> > I think the href to https://www.script-tutorials.com/line-icons/ is not necessary. Would you please remove it? The updated icon version is great!
> 
> Done!

Nope, still there.. I'm unable to approve this :)

2021-12-08 22:48 UTC, Snailedlt commented on CONTRIBUTING.md
> +          <p><b>line</b>: a one-color, <a href="https://www.script-tutorials.com/line-icons/#:~:text=Line%20icons%20is%20a%20shape%20vector%20of%20a%20symbolic%20glyph%20outline%20only%20which%20basi
```suggestion
          <p><b>line</b>: a one-color, line version of the original logo. Note that the icon version will be stripped of all colors so you don't have to strip beforehand. </p>      
```

2021-12-08 22:50 UTC, Snailedlt commented
> > > I think the href to https://www.script-tutorials.com/line-icons/ is not necessary. Would you please remove it? The updated icon version is great!
> > 
> > 
> > Done!
> 
> Nope, still there.. I'm unable to approve this :)

You're right! Odd, I swear I removed it.

Oh well, I managed to remove it now at least 😄

2021-12-09 00:18 UTC, Panquesito7 approved these changes

2021-12-11 20:38 UTC, Thomas-Boi approved these changes
This looks good to me 👍. Thank you for working on it, it was on my TODO list.

2021-12-12 01:24 UTC, merged